      MODULE CTRIG

      USE PRECISION
      USE PARMMOD

      IMPLICIT NONE

      PRIVATE

      PUBLIC :: ALLOC_CTRIG, DEALLOC_CTRIG, INIT_CTRIG,
     P          TRI_ELEM, TRI_LISTE

      REAL(DP), PUBLIC, ALLOCATABLE, SAVE ::
     R XTRIAN(:),  YTRIAN(:),
     R VTRIX(:,:), VTRIY(:,:), PTRIX(:,:), PTRIY(:,:)

      INTEGER, PUBLIC, ALLOCATABLE, SAVE ::
     I NECKE(:,:), NCHBAR(:,:), NSEITE(:,:), 
     I INMTI(:,:), INSPAT(:,:), IXTRI(:), IYTRI(:)

      INTEGER, PUBLIC, SAVE ::
     I NRKNOT, NTRII, NCTRIG, MCTRIG


      TYPE :: TRI_ELEM
        INTEGER :: NOTRI
        TYPE(TRI_ELEM), POINTER :: NEXT_TRI
      END TYPE TRI_ELEM

      TYPE :: TRI_LISTE
        TYPE(TRI_ELEM), POINTER :: PTRI
      END TYPE TRI_LISTE
        
      TYPE(TRI_LISTE), ALLOCATABLE, SAVE, PUBLIC :: COORTRI(:)


      CONTAINS


      SUBROUTINE ALLOC_CTRIG

      IF (ALLOCATED(XTRIAN)) RETURN

      NCTRIG = 2*NKNOTS+4*3*NTRIS
      MCTRIG = (5*3+2)*NTRIS+2

      ALLOCATE (XTRIAN(NKNOTS))
      ALLOCATE (YTRIAN(NKNOTS))
      ALLOCATE (VTRIX(3,NTRIS))
      ALLOCATE (VTRIY(3,NTRIS))
      ALLOCATE (PTRIX(3,NTRIS))
      ALLOCATE (PTRIY(3,NTRIS))

      ALLOCATE (NECKE(3,NTRIS))
      ALLOCATE (NCHBAR(3,NTRIS))
      ALLOCATE (NSEITE(3,NTRIS))
      ALLOCATE (INMTI(3,NTRIS))
      ALLOCATE (INSPAT(3,NTRIS))
      ALLOCATE (IXTRI(NTRIS))
      ALLOCATE (IYTRI(NTRIS))

      WRITE (55,'(A,T25,I15)')
     .       ' CTRIG ',NCTRIG*8+MCTRIG*4

      CALL INIT_CTRIG

      RETURN
      END SUBROUTINE ALLOC_CTRIG


      SUBROUTINE DEALLOC_CTRIG

      IF (.NOT.ALLOCATED(XTRIAN)) RETURN

      DEALLOCATE (XTRIAN)
      DEALLOCATE (YTRIAN)
      DEALLOCATE (VTRIX)
      DEALLOCATE (VTRIY)
      DEALLOCATE (PTRIX)
      DEALLOCATE (PTRIY)

      DEALLOCATE (NECKE)
      DEALLOCATE (NCHBAR)
      DEALLOCATE (NSEITE)
      DEALLOCATE (INMTI)
      DEALLOCATE (INSPAT)
      DEALLOCATE (IXTRI)
      DEALLOCATE (IYTRI)

      RETURN
      END SUBROUTINE DEALLOC_CTRIG


      SUBROUTINE INIT_CTRIG

      XTRIAN = 0._DP
      YTRIAN = 0._DP
      VTRIX  = 0._DP
      VTRIY  = 0._DP
      PTRIX  = 0._DP
      PTRIY  = 0._DP

      NECKE  = 0
      NCHBAR = 0
      NSEITE = 0
      INMTI  = 0
      INSPAT = 0
      IXTRI = 0
      IYTRI = 0

      RETURN
      END SUBROUTINE INIT_CTRIG

      END MODULE CTRIG






