

      FUNCTION FEHVPI1 (IRPI,K)

      USE PRECISION
      USE PARMMOD
      USE COMUSR
      USE CCONA
      USE COMXS

      IMPLICIT NONE

      INTEGER, INTENT(IN) :: IRPI, K
      REAL(DP) :: FEHVPI1, EHVPI, FTABPI3, RATE_COEFF
      INTEGER :: II, KK

      FEHVPI1=0.D0
      KK=NRHVPI(IRPI)

      IF (KK == -1) THEN
! TAKE EHEAVY FROM INPUT FILE
         FEHVPI1=EHVPI1(IRPI,1)

      ELSE IF (KK > 0) THEN
        EHVPI = RATE_COEFF(KK,TEINL(K),0._DP,.FALSE.,0)
        EHVPI=EXP(MAX(-100._DP,EHVPI+FACREA(KK,2)))
        FEHVPI1=EHVPI*DEIN(K)/(FTABPI3(IRPI,K)+EPS60)
      END IF

      RETURN
      END
