C
C
      FUNCTION EIRENE_EXTRAP(ELAB,IFLAG,FP1,FP2,FP3)
C
C  NOTE:
C  INPUT:  ELAB IS LOG OF RELATIVE ENERGY, OR LOG OF TEMP
C  OUTPUT: EXTRAP IS NOT LOG, BUT THE TRUE VALUE
C
C  FUNCTION FOR EXTRAPOLATING SINGLE PARAMETER FITS BEYOND THEIR
C  RANGE OF VALIDITY
C  TYPE  IFLAG=1--4: JANEV ET AL. , SPRINGER, 1987, P13
C  TYPE  IFLAG=5  BACHMANN ET AL., IPP-REPORT, .....ELASTIC
C
      USE EIRMOD_PRECISION
      USE EIRMOD_COMPRT, ONLY: IUNOUT
 
      IMPLICIT NONE
 
      REAL(DP), INTENT(IN) :: ELAB, FP1, FP2, FP3
      INTEGER, INTENT(IN) :: IFLAG
      REAL(DP) :: X, EL, EIRENE_EXTRAP
 
      IF (IFLAG.EQ.1) THEN
C  NON ZERO THRESHOLD
        EIRENE_EXTRAP=0.
      ELSEIF (IFLAG.EQ.2) THEN
C  EXTRAPOLATION AT HIGH ENERGY END FOR REACTIONS WITH NON ZERO THRESHOLD
C  FP1 SHOULD BE = E_THRESHOLD (EV)
        EL=EXP(ELAB)
        X=EL/FP1
        EIRENE_EXTRAP=FP2*X**FP3*LOG(X)
      ELSEIF (IFLAG.EQ.3) THEN
        EIRENE_EXTRAP=EXP(FP1+FP2*ELAB)
      ELSEIF (IFLAG.EQ.4) THEN
C
C  OUT
C       EIRENE_EXTRAP=EXP((FP1+FP2*ELAB)**2)
C
      ELSEIF (IFLAG.EQ.5) THEN
C  LINEAR OR QUADRATIC EXTRAPOLATION IN LN(SIGMA)
        EIRENE_EXTRAP=EXP(FP1+FP2*ELAB+FP3*ELAB**2)
      ELSE
        GOTO 999
      ENDIF
      RETURN
999   CONTINUE
      WRITE (iunout,*) 'ERROR IN EXTRAP. EXIT CALLED EIRENE_'
      CALL EIRENE_EXIT_OWN(1)
      END
