 
 
      FUNCTION EIRENE_FEPLOT3 (IROT,K)
 
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      USE EIRMOD_COMUSR
      USE EIRMOD_CCONA
      USE EIRMOD_COMPRT
      USE EIRMOD_COMXS
      USE EIRMOD_PHOTON
 
      IMPLICIT NONE
 
      INTEGER, INTENT(IN) :: IROT, K
      REAL(DP) :: PLS, ADD, ELCX, EIRENE_FEPLOT3
      INTEGER :: II, KK, IPLSTI
 
      EIRENE_FEPLOT3=0.D0
      KK=NELROT(IROT)
      IPLSTI=MPLSTI(IPLS)
      SELECT CASE (KK)
      CASE (-2)
         EIRENE_FEPLOT3=EPLOT3(IROT,1,1)+EDRIFT(IPLS,K)
      CASE (-3)
         EIRENE_FEPLOT3=1.5*TIIN(IPLSTI,K)+EDRIFT(IPLS,K)
      CASE DEFAULT
        WRITE (iunout,*) ' FEPLOT3 NOT READY '
        WRITE (iunout,*) ' CALCULATION ABANDONNED '
        CALL EIRENE_EXIT_OWN(1)
      END SELECT
 
      RETURN
      END
