C
C
      FUNCTION ELLU (X)
      USE CLMSUR
      IMPLICIT NONE
      REAL(DP), INTENT(IN) :: X
      REAL(DP) :: ELLU
      ELLU=-BHALB*SQRT(MAX(0.D0,1.D0-X*X/(AHALB*AHALB)))
      RETURN
      END
