C  sept. 05:  5 tallies added to step functions.  see also: CSTEP.f
C  nov.  05:  add eltot and ve to step function data.
C
C  same as  WRPLAM.f, RPLAM.f, but for XDR format
C
      SUBROUTINE WRPLAM_XDR(TRCFLE,IFLG)
      USE PRECISION
      USE PARMMOD
      USE COMUSR
      USE COMPRT, ONLY: IUNOUT
      USE CZT1
      USE COMSOU
      USE CSTEP
      USE COMXS
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: IFLG
      LOGICAL TRCFLE, LHELP(1)
      REAL(DP), ALLOCATABLE :: RDUM(:)
      REAL(DP) :: RHELP(1)
      INTEGER, ALLOCATABLE :: IDUM(:)
      LOGICAL, ALLOCATABLE :: LDUM(:)
      INTEGER :: NRDUM, NIDUM, NLDUM,IHELP(1)
      INTEGER :: IUN, ISPZ
C
      CALL FXDROPN ('fort13','ENCODE',iun)

      CALL FXDRDBL (IUN,TEIN,NRAD)
      CALL FXDRDBL (IUN,TIIN,NPLSTI*NRAD)
      CALL FXDRDBL (IUN,DEIN,NRAD)
      CALL FXDRDBL (IUN,DIIN,NPLS*NRAD)
      CALL FXDRDBL (IUN,VXIN,NPLSV*NRAD)
      CALL FXDRDBL (IUN,VYIN,NPLSV*NRAD)
      CALL FXDRDBL (IUN,VZIN,NPLSV*NRAD)
      CALL FXDRDBL (IUN,BXIN,NRAD)
      CALL FXDRDBL (IUN,BYIN,NRAD)
      CALL FXDRDBL (IUN,BZIN,NRAD)
      CALL FXDRDBL (IUN,BFIN,NRAD)
      CALL FXDRDBL (IUN,ADIN,NAIN*NRAD)
      CALL FXDRDBL (IUN,EDRIFT,NPLS*NRAD)
      CALL FXDRDBL (IUN,VOL,NRAD)
      CALL FXDRDBL (IUN,WGHT,NSPZMC*NRAD)
      CALL FXDRDBL (IUN,BXPERP,NRAD)
      CALL FXDRDBL (IUN,BYPERP,NRAD)
      CALL FXDRDBL (IUN,FLXOUT,NLMPGS)
      CALL FXDRDBL (IUN,SAREA,NLMPGS)
      CALL FXDRDBL (IUN,TEINL,NRAD)
      CALL FXDRDBL (IUN,TIINL,NPLSTI*NRAD)
      CALL FXDRDBL (IUN,DEINL,NRAD)
      CALL FXDRDBL (IUN,DIINL,NPLS*NRAD)
      CALL FXDRDBL (IUN,BVIN,NPLSV*NRAD)
      CALL FXDRDBL (IUN,PARMOM,NPLS*NRAD)
      CALL FXDRDBL (IUN,RMASSI,NION)
      CALL FXDRDBL (IUN,RMASSA,NATM)
      CALL FXDRDBL (IUN,RMASSM,NMOL)
      CALL FXDRDBL (IUN,RMASSP,NPLS)
      CALL FXDRDBL (IUN,DIOD,NION)
      CALL FXDRDBL (IUN,DATD,NATM)
      CALL FXDRDBL (IUN,DMLD,NMOL)
      CALL FXDRDBL (IUN,DPLD,NPLS)
      CALL FXDRDBL (IUN,DPHD,NPHOT)
      CALL FXDRDBL (IUN,DION,NION)
      CALL FXDRDBL (IUN,DATM,NATM)
      CALL FXDRDBL (IUN,DMOL,NMOL)
      CALL FXDRDBL (IUN,DPLS,NPLS)
      CALL FXDRDBL (IUN,DPHOT,NPHOT)
      RHELP(1) = TVAC
      CALL FXDRDBL (IUN,RHELP,1)
      RHELP(1) = DVAC
      CALL FXDRDBL (IUN,RHELP,1)
      RHELP(1) = VVAC
      CALL FXDRDBL (IUN,RHELP,1)
      RHELP(1) = ALLOC
      CALL FXDRDBL (IUN,RHELP,1)

      DO ISPZ=1,NSPZ
        CALL FXDRCHR (IUN,TEXTS(ISPZ))
      END DO

      IHELP(1) = NSPH
      CALL FXDRINT (IUN,IHELP,1)
      IHELP(1) = NPHOTI
      CALL FXDRINT (IUN,IHELP,1)
      IHELP(1) = NPHOTIM
      CALL FXDRINT (IUN,IHELP,1)
      CALL FXDRINT (IUN,NFOLPH,NPHOT)
      CALL FXDRINT (IUN,NGENPH,NPHOT)
      IHELP(1) = NSPA
      CALL FXDRINT (IUN,IHELP,1)
      IHELP(1) = NATMI
      CALL FXDRINT (IUN,IHELP,1)
      IHELP(1) = NATMIM
      CALL FXDRINT (IUN,IHELP,1)
      CALL FXDRINT (IUN,NMASSA,NATM)
      CALL FXDRINT (IUN,NCHARA,NATM)
      CALL FXDRINT (IUN,NFOLA,NATM)
      CALL FXDRINT (IUN,NGENA,NATM)
      IHELP(1) = NSPAM
      CALL FXDRINT (IUN,IHELP,1)
      IHELP(1) = NMOLI
      CALL FXDRINT (IUN,IHELP,1)
      IHELP(1) = NMOLIM
      CALL FXDRINT (IUN,IHELP,1)
      CALL FXDRINT (IUN,NMASSM,NMOL)
      CALL FXDRINT (IUN,NCHARM,NMOL)
      CALL FXDRINT (IUN,NFOLM,NMOL)
      CALL FXDRINT (IUN,NGENM,NMOL)
      IHELP(1) = NSPAMI
      CALL FXDRINT (IUN,IHELP,1)
      IHELP(1) = NIONI
      CALL FXDRINT (IUN,IHELP,1)
      IHELP(1) = NIONIM
      CALL FXDRINT (IUN,IHELP,1)
      CALL FXDRINT (IUN,NMASSI,NION)
      CALL FXDRINT (IUN,NCHARI,NION)
      CALL FXDRINT (IUN,NCHRGI,NION)
      CALL FXDRINT (IUN,NFOLI,NION)
      CALL FXDRINT (IUN,NGENI,NION)
      IHELP(1) = NSPTOT
      CALL FXDRINT (IUN,IHELP,1)
      IHELP(1) = NPLSI
      CALL FXDRINT (IUN,IHELP,1)
      IHELP(1) = NPLSIM
      CALL FXDRINT (IUN,IHELP,1)
      CALL FXDRINT (IUN,NMASSP,NPLS)
      CALL FXDRINT (IUN,NCHARP,NPLS)
      CALL FXDRINT (IUN,NCHRGP,NPLS)
      IHELP(1) = NBITS
      CALL FXDRINT (IUN,IHELP,1)
      IHELP(1) = NSNVI
      CALL FXDRINT (IUN,IHELP,1)
      IHELP(1) = NCPVI
      CALL FXDRINT (IUN,IHELP,1)
      IHELP(1) = NADVI
      CALL FXDRINT (IUN,IHELP,1)
      IHELP(1) = NBGVI
      CALL FXDRINT (IUN,IHELP,1)
      IHELP(1) = NALVI
      CALL FXDRINT (IUN,IHELP,1)
      IHELP(1) = NCLVI
      CALL FXDRINT (IUN,IHELP,1)
      IHELP(1) = NADSI
      CALL FXDRINT (IUN,IHELP,1)
      IHELP(1) = NALSI
      CALL FXDRINT (IUN,IHELP,1)
      IHELP(1) = NAINI
      CALL FXDRINT (IUN,IHELP,1)
      CALL FXDRINT (IUN,NPRT,NSPZ)
      CALL FXDRINT (IUN,ISPEZ,6*(NPHOT+2)*(NATM+2)*(NMOL+2)*(NION+2)*
     .              (NPLS+2))
      CALL FXDRINT (IUN,ISPEZI,6*NSPZ)
      CALL FXDRINT (IUN,MPLSTI,NPLS)
      CALL FXDRINT (IUN,MPLSV,NPLS)

      CALL FXDRLOG (IUN,LGVAC,(NPLS+2)*NRAD)
      CALL FXDRLOG (IUN,LGDFT,NRAD)

      IF (TRCFLE) WRITE (iunout,*) 'WRITE 13: module COMUSR.f '

      CALL CMDTA_XDR (IUN)
      IF (TRCFLE) WRITE (iunout,*) 'WRITE 13: RCMDTA,ICMDTA'

      CALL CMAMF_XDR (IUN,0)
      IF (TRCFLE) WRITE (iunout,*) 'WRITE 13: RCMAMF,ICMAMF'

      CALL FXDRDBL (IUN,RCZT1,NZT1)
      CALL FXDRDBL (IUN,RCZT2,NZT2)
      CALL FXDRDBL (IUN,ZT1,NPLS*NRAD)
      CALL FXDRDBL (IUN,ZRG,NPLS*NRAD)
      IF (TRCFLE) WRITE (iunout,*) 'WRITE 13: RCZT1,RCZT2,ZT1,ZRG'

      CALL FXDRDBL (IUN,RCMSOU,(12+11*NSRFS)*NSTRA)
      CALL FXDRDBL (IUN,SREC,(NPLS+1)*(NREC+1))
      CALL FXDRDBL (IUN,EIO,(NPLS+1)*(NREC+1))
      CALL FXDRDBL (IUN,EEL,(NPLS+1)*(NREC+1))
      CALL FXDRINT (IUN,ICMSOU,(14+9*NSRFS)*NSTRA)
      CALL FXDRINT (IUN,INGRDA,NSRFS*NSTRA*3)
      CALL FXDRINT (IUN,INGRDE,NSRFS*NSTRA*3)
      IHELP(1) = NSTRAI
      CALL FXDRINT (IUN,IHELP,1)
      CALL FXDRLOG (IUN,LCMSOU,13*NSTRA)
      CALL FXDRLOG (IUN,NLSYMP,NSTRA+1)
      CALL FXDRLOG (IUN,NLSYMT,NSTRA+1)
      IF (TRCFLE) WRITE (iunout,*) 'WRITE 13: RCMSOU,ICMSOU,LCMSOU'

      IF (ALLOCATED(FLSTEP)) THEN
        CALL FXDRDBL (IUN,FLSTEP,(NSPZ+1)*NSTEP*NGITT)
        CALL FXDRDBL (IUN,ELSTEP,(NSPZ+1)*NSTEP*NGITT)
        CALL FXDRDBL (IUN,FLTOT,(NSPZ+1)*NSTEP)
        CALL FXDRDBL (IUN,ELTOT,(NSPZ+1)*NSTEP)
        CALL FXDRDBL (IUN,VF,(NSPZ+1)*NSTEP*NGITT)
        CALL FXDRDBL (IUN,VE,(NSPZ+1)*NSTEP*NGITT)
        CALL FXDRDBL (IUN,QUOT,(NSPZ+1)*NSTEP*NGITT)
        CALL FXDRDBL (IUN,ADD,(NSPZ+1)*NSTEP*NGITT)
        CALL FXDRDBL (IUN,QUOTI,(NSPZ+1)*NSTEP*NGITT)
        CALL FXDRDBL (IUN,ADDIV,(NSPZ+1)*NSTEP*NGITT)
        CALL FXDRDBL (IUN,TESTEP,NSTEP*NGITT)
        CALL FXDRDBL (IUN,TISTEP,NPLSTI*NSTEP*NGITT)
        CALL FXDRDBL (IUN,RRSTEP,NSTEP*NGITT)
        CALL FXDRDBL (IUN,VXSTEP,NPLSV*NSTEP*NGITT)
        CALL FXDRDBL (IUN,VYSTEP,NPLSV*NSTEP*NGITT)
        CALL FXDRDBL (IUN,VZSTEP,NPLSV*NSTEP*NGITT)
        CALL FXDRDBL (IUN,DISTEP,NPLS*NSTEP*NGITT)

c  next five tallies added in sept. 05, !dr
        CALL FXDRDBL (IUN,FESTEP,NSTEP*NGITT)
        CALL FXDRDBL (IUN,FISTEP,NPLS*NSTEP*NGITT)
        CALL FXDRDBL (IUN,SHSTEP,NSTEP*NGITT)
        CALL FXDRDBL (IUN,VPSTEP,NPLSV*NSTEP*NGITT)
        CALL FXDRDBL (IUN,MCSTEP,NPLSV*NSTEP*NGITT)

        CALL FXDRINT (IUN,IRSTEP,NSTEP*NGITT)
        CALL FXDRINT (IUN,IPSTEP,NSTEP*NGITT)
        CALL FXDRINT (IUN,ITSTEP,NSTEP*NGITT)
        CALL FXDRINT (IUN,IASTEP,NSTEP*NGITT)
        CALL FXDRINT (IUN,IBSTEP,NSTEP*NGITT)
        CALL FXDRINT (IUN,IGSTEP,NSTEP*NGITT)
        CALL FXDRINT (IUN,ISTUF,NSTEP)
        CALL FXDRINT (IUN,NSMAX,NSTEP)
        CALL FXDRINT (IUN,NSPSTI,NSTEP)
        CALL FXDRINT (IUN,NSPSTE,NSTEP)
        IF (TRCFLE) WRITE (iunout,*) 'WRITE 13: module CSTEP.f'
      END IF

      CALL FXDRCLS (IUN)
      RETURN
C
C
C
      ENTRY RPLAM_XDR(TRCFLE,IFLG)
C
      CALL FXDROPN ('fort13','DECODE',iun)

      CALL FXDRDBL (IUN,TEIN,NRAD)
      CALL FXDRDBL (IUN,TIIN,NPLSTI*NRAD)
      CALL FXDRDBL (IUN,DEIN,NRAD)
      CALL FXDRDBL (IUN,DIIN,NPLS*NRAD)
      CALL FXDRDBL (IUN,VXIN,NPLSTI*NRAD)
      CALL FXDRDBL (IUN,VYIN,NPLSTI*NRAD)
      CALL FXDRDBL (IUN,VZIN,NPLSTI*NRAD)
      CALL FXDRDBL (IUN,BXIN,NRAD)
      CALL FXDRDBL (IUN,BYIN,NRAD)
      CALL FXDRDBL (IUN,BZIN,NRAD)
      CALL FXDRDBL (IUN,BFIN,NRAD)
      CALL FXDRDBL (IUN,ADIN,NAIN*NRAD)
      CALL FXDRDBL (IUN,EDRIFT,NPLS*NRAD)
      CALL FXDRDBL (IUN,VOL,NRAD)
      CALL FXDRDBL (IUN,WGHT,NSPZMC*NRAD)
      CALL FXDRDBL (IUN,BXPERP,NRAD)
      CALL FXDRDBL (IUN,BYPERP,NRAD)
      CALL FXDRDBL (IUN,FLXOUT,NLMPGS)
      CALL FXDRDBL (IUN,SAREA,NLMPGS)
      CALL FXDRDBL (IUN,TEINL,NRAD)
      CALL FXDRDBL (IUN,TIINL,NPLSTI*NRAD)
      CALL FXDRDBL (IUN,DEINL,NRAD)
      CALL FXDRDBL (IUN,DIINL,NPLS*NRAD)
      CALL FXDRDBL (IUN,BVIN,NPLSV*NRAD)
      CALL FXDRDBL (IUN,PARMOM,NPLS*NRAD)
      CALL FXDRDBL (IUN,RMASSI,NION)
      CALL FXDRDBL (IUN,RMASSA,NATM)
      CALL FXDRDBL (IUN,RMASSM,NMOL)
      CALL FXDRDBL (IUN,RMASSP,NPLS)
      CALL FXDRDBL (IUN,DIOD,NION)
      CALL FXDRDBL (IUN,DATD,NATM)
      CALL FXDRDBL (IUN,DMLD,NMOL)
      CALL FXDRDBL (IUN,DPLD,NPLS)
      CALL FXDRDBL (IUN,DPHD,NPHOT)
      CALL FXDRDBL (IUN,DION,NION)
      CALL FXDRDBL (IUN,DATM,NATM)
      CALL FXDRDBL (IUN,DMOL,NMOL)
      CALL FXDRDBL (IUN,DPLS,NPLS)
      CALL FXDRDBL (IUN,DPHOT,NPHOT)
      CALL FXDRDBL (IUN,RHELP,1)
      TVAC = RHELP(1)
      CALL FXDRDBL (IUN,RHELP,1)
      DVAC = RHELP(1)
      CALL FXDRDBL (IUN,RHELP,1)
      VVAC = RHELP(1)
      CALL FXDRDBL (IUN,RHELP,1)
      ALLOC = RHELP(1)

      DO ISPZ=1,NSPZ
        CALL FXDRCHR (IUN,TEXTS(ISPZ))
      END DO

      CALL FXDRINT (IUN,IHELP,1)
      NSPH = IHELP(1)
      CALL FXDRINT (IUN,IHELP,1)
      NPHOTI = IHELP(1)
      CALL FXDRINT (IUN,IHELP,1)
      NPHOTIM = IHELP(1)
      CALL FXDRINT (IUN,NFOLPH,NPHOT)
      CALL FXDRINT (IUN,NGENPH,NPHOT)
      CALL FXDRINT (IUN,IHELP,1)
      NSPA = IHELP(1)
      CALL FXDRINT (IUN,IHELP,1)
      NATMI = IHELP(1)
      CALL FXDRINT (IUN,IHELP,1)
      NATMIM = IHELP(1)
      CALL FXDRINT (IUN,NMASSA,NATM)
      CALL FXDRINT (IUN,NCHARA,NATM)
      CALL FXDRINT (IUN,NFOLA,NATM)
      CALL FXDRINT (IUN,NGENA,NATM)
      CALL FXDRINT (IUN,IHELP,1)
      NSPAM = IHELP(1)
      CALL FXDRINT (IUN,IHELP,1)
      NMOLI = IHELP(1)
      CALL FXDRINT (IUN,IHELP,1)
      NMOLIM = IHELP(1)
      CALL FXDRINT (IUN,NMASSM,NMOL)
      CALL FXDRINT (IUN,NCHARM,NMOL)
      CALL FXDRINT (IUN,NFOLM,NMOL)
      CALL FXDRINT (IUN,NGENM,NMOL)
      CALL FXDRINT (IUN,IHELP,1)
      NSPAMI = IHELP(1)
      CALL FXDRINT (IUN,IHELP,1)
      NIONI = IHELP(1)
      CALL FXDRINT (IUN,IHELP,1)
      NIONIM = IHELP(1)
      CALL FXDRINT (IUN,NMASSI,NION)
      CALL FXDRINT (IUN,NCHARI,NION)
      CALL FXDRINT (IUN,NCHRGI,NION)
      CALL FXDRINT (IUN,NFOLI,NION)
      CALL FXDRINT (IUN,NGENI,NION)
      CALL FXDRINT (IUN,IHELP,1)
      NSPTOT = IHELP(1)
      CALL FXDRINT (IUN,IHELP,1)
      NPLSI = IHELP(1)
      CALL FXDRINT (IUN,IHELP,1)
      NPLSIM = IHELP(1)
      CALL FXDRINT (IUN,NMASSP,NPLS)
      CALL FXDRINT (IUN,NCHARP,NPLS)
      CALL FXDRINT (IUN,NCHRGP,NPLS)
      CALL FXDRINT (IUN,IHELP,1)
      NBITS = IHELP(1)
      CALL FXDRINT (IUN,IHELP,1)
      NSNVI = IHELP(1)
      CALL FXDRINT (IUN,IHELP,1)
      NCPVI = IHELP(1)
      CALL FXDRINT (IUN,IHELP,1)
      NADVI = IHELP(1)
      CALL FXDRINT (IUN,IHELP,1)
      NBGVI = IHELP(1)
      CALL FXDRINT (IUN,IHELP,1)
      NALVI = IHELP(1)
      CALL FXDRINT (IUN,IHELP,1)
      NCLVI = IHELP(1)
      CALL FXDRINT (IUN,IHELP,1)
      NADSI = IHELP(1)
      CALL FXDRINT (IUN,IHELP,1)
      NALSI = IHELP(1)
      CALL FXDRINT (IUN,IHELP,1)
      NAINI = IHELP(1)
      CALL FXDRINT (IUN,NPRT,NSPZ)
      CALL FXDRINT (IUN,ISPEZ,6*(NPHOT+2)*(NATM+2)*(NMOL+2)*(NION+2)*
     .              (NPLS+2))
      CALL FXDRINT (IUN,ISPEZI,6*NSPZ)
      CALL FXDRINT (IUN,MPLSTI,NPLS)
      CALL FXDRINT (IUN,MPLSV,NPLS)

      CALL FXDRLOG (IUN,LGVAC,(NPLS+2)*NRAD)
      CALL FXDRLOG (IUN,LGDFT,NRAD)

      IF (TRCFLE) WRITE (iunout,*) 'READ 13: module COMUSR.f '

      CALL CMDTA_XDR (IUN)
      IF (TRCFLE) WRITE (iunout,*) 'READ 13: RCMDTA,ICMDTA'

      CALL CMAMF_XDR (IUN,1)
      IF (TRCFLE) WRITE (iunout,*) 'READ 13: RCMAMF,ICMAMF'

      CALL FXDRDBL (IUN,RCZT1,NZT1)
      CALL FXDRDBL (IUN,RCZT2,NZT2)
      CALL FXDRDBL (IUN,ZT1,NPLS*NRAD)
      CALL FXDRDBL (IUN,ZRG,NPLS*NRAD)
      IF (TRCFLE) WRITE (iunout,*) 'READ 13: RCZT1,RCZT2,ZT1,ZRG'

      IF (IFLG == 0) THEN
        CALL FXDRDBL (IUN,RCMSOU,(12+11*NSRFS)*NSTRA)
        CALL FXDRDBL (IUN,SREC,(NPLS+1)*(NREC+1))
        CALL FXDRDBL (IUN,EIO,(NPLS+1)*(NREC+1))
        CALL FXDRDBL (IUN,EEL,(NPLS+1)*(NREC+1))
        CALL FXDRINT (IUN,ICMSOU,(14+9*NSRFS)*NSTRA)
        CALL FXDRINT (IUN,INGRDA,NSRFS*NSTRA*3)
        CALL FXDRINT (IUN,INGRDE,NSRFS*NSTRA*3)
        CALL FXDRINT (IUN,IHELP,1)
        NSTRAI = IHELP(1)
        CALL FXDRLOG (IUN,LCMSOU,13*NSTRA)
        CALL FXDRLOG (IUN,NLSYMP,NSTRA+1)
        CALL FXDRLOG (IUN,NLSYMT,NSTRA+1)
        IF (TRCFLE) WRITE (iunout,*) 'READ 13: RCMSOU,ICMSOU,LCMSOU'
      ELSE
        NRDUM = MAX(SIZE(RCMSOU), SIZE(SREC), SIZE(EIO), SIZE(EEL))
        NIDUM = MAX(SIZE(ICMSOU), SIZE(INGRDA), SIZE(INGRDE))
        NLDUM = MAX(SIZE(LCMSOU), SIZE(NLSYMP), SIZE(NLSYMT))
        ALLOCATE (RDUM(NRDUM))
        ALLOCATE (IDUM(NIDUM))
        ALLOCATE (LDUM(NLDUM))
        LDUM = .FALSE.
        CALL FXDRDBL (IUN,RDUM,(12+11*NSRFS)*NSTRA)
        CALL FXDRDBL (IUN,RDUM,(NPLS+1)*(NREC+1))
        CALL FXDRDBL (IUN,RDUM,(NPLS+1)*(NREC+1))
        CALL FXDRDBL (IUN,RDUM,(NPLS+1)*(NREC+1))
        CALL FXDRINT (IUN,IDUM,(14+9*NSRFS)*NSTRA)
        CALL FXDRINT (IUN,IDUM,NSRFS*NSTRA*3)
        CALL FXDRINT (IUN,IDUM,NSRFS*NSTRA*3)
        CALL FXDRINT (IUN,IDUM,1)
        CALL FXDRLOG (IUN,LDUM,13*NSTRA)
        CALL FXDRLOG (IUN,LDUM,NSTRA+1)
        CALL FXDRLOG (IUN,LDUM,NSTRA+1)
        DEALLOCATE (RDUM)
        DEALLOCATE (IDUM)
        DEALLOCATE (LDUM)
      END IF

      IF (ALLOCATED(FLSTEP)) THEN
        CALL FXDRDBL (IUN,FLSTEP,(NSPZ+1)*NSTEP*NGITT)
        CALL FXDRDBL (IUN,ELSTEP,(NSPZ+1)*NSTEP*NGITT)
        CALL FXDRDBL (IUN,FLTOT,(NSPZ+1)*NSTEP)
        CALL FXDRDBL (IUN,ELTOT,(NSPZ+1)*NSTEP)
        CALL FXDRDBL (IUN,VF,(NSPZ+1)*NSTEP*NGITT)
        CALL FXDRDBL (IUN,VE,(NSPZ+1)*NSTEP*NGITT)
        CALL FXDRDBL (IUN,QUOT,(NSPZ+1)*NSTEP*NGITT)
        CALL FXDRDBL (IUN,ADD,(NSPZ+1)*NSTEP*NGITT)
        CALL FXDRDBL (IUN,QUOTI,(NSPZ+1)*NSTEP*NGITT)
        CALL FXDRDBL (IUN,ADDIV,(NSPZ+1)*NSTEP*NGITT)
        CALL FXDRDBL (IUN,TESTEP,NSTEP*NGITT)
        CALL FXDRDBL (IUN,TISTEP,NPLSTI*NSTEP*NGITT)
        CALL FXDRDBL (IUN,RRSTEP,NSTEP*NGITT)
        CALL FXDRDBL (IUN,VXSTEP,NPLSV*NSTEP*NGITT)
        CALL FXDRDBL (IUN,VYSTEP,NPLSV*NSTEP*NGITT)
        CALL FXDRDBL (IUN,VZSTEP,NPLSV*NSTEP*NGITT)
        CALL FXDRDBL (IUN,DISTEP,NPLS*NSTEP*NGITT)

c  next five tallies added in sept. 05, !dr
        CALL FXDRDBL (IUN,FESTEP,NSTEP*NGITT)
        CALL FXDRDBL (IUN,FISTEP,NPLS*NSTEP*NGITT)
        CALL FXDRDBL (IUN,SHSTEP,NSTEP*NGITT)
        CALL FXDRDBL (IUN,VPSTEP,NPLSV*NSTEP*NGITT)
        CALL FXDRDBL (IUN,MCSTEP,NPLSV*NSTEP*NGITT)

        CALL FXDRINT (IUN,IRSTEP,NSTEP*NGITT)
        CALL FXDRINT (IUN,IPSTEP,NSTEP*NGITT)
        CALL FXDRINT (IUN,ITSTEP,NSTEP*NGITT)
        CALL FXDRINT (IUN,IASTEP,NSTEP*NGITT)
        CALL FXDRINT (IUN,IBSTEP,NSTEP*NGITT)
        CALL FXDRINT (IUN,IGSTEP,NSTEP*NGITT)
        CALL FXDRINT (IUN,ISTUF,NSTEP)
        CALL FXDRINT (IUN,NSMAX,NSTEP)
        CALL FXDRINT (IUN,NSPSTI,NSTEP)
        CALL FXDRINT (IUN,NSPSTE,NSTEP)
        IF (TRCFLE) WRITE (iunout,*) 'READ 13: module CSTEP.f'
      END IF

      CALL FXDRCLS (IUN)
      RETURN
      END
