      MODULE COMPRT

      USE PRECISION
      USE PARMMOD

      IMPLICIT NONE

      PRIVATE

      PUBLIC :: ALLOC_COMPRT, DEALLOC_COMPRT, INIT_COMPRT

!pb      INTEGER, PUBLIC, PARAMETER ::
!pb     P         NPARTC=13, NPARTT=13,
!pb     P         MPARTC=14, MPARTT=9

      REAL(DP), PUBLIC, TARGET, ALLOCATABLE, SAVE :: RPST(:)

      REAL(DP), PUBLIC, POINTER, SAVE :: RPSTT(:)

C NPARTT PARTICLE COORDINATES FOR CENSUS ARRAY
C NPARTC PARTICLE COORDINATES, REAL, (E.G.: SPLITTING)
      REAL(DP), PUBLIC, POINTER, SAVE ::
     R X0,     Y0,     Z0,     
     R VEL,    VELX,   VELY,   VELZ,
     R E0,     WEIGHT, TIME,   PHI,
     R XGENER, XNUE

      REAL(DP), PUBLIC, ALLOCATABLE, SAVE ::
     R TIMINT(:), TIMPOL(:,:)

      REAL(DP), PUBLIC, SAVE ::
     R TL,     TT,     TS,     ZT,     ZDT1,
     R CRTX,   CRTY,   CRTZ,   SCOS,   WGHTSP, WGHTSC

      REAL(DP), PUBLIC, SAVE ::
     R VEL_MEAN, VELX_MEAN, VELY_MEAN, VELZ_MEAN, E0_MEAN

      INTEGER, PUBLIC, TARGET, ALLOCATABLE, SAVE :: IPSTD(:)

      INTEGER, PUBLIC, POINTER, SAVE :: IPST(:), IPSTT(:)

C MPARTT PARTICLE COORDINATES FOR CENSUS ARRAY
C MPARTC PARTICLE COORDINATES, INTEGER, (E.G.: SPLITTING)
      INTEGER, PUBLIC, POINTER, SAVE ::
     I NPANU,
     I IPOLG,  IPERID, NCELL,
     I ITIME,  IFPATH, IUPDTE,
     I ISTRA,
     I ISPZ,
     I MRSURF, MPSURF, MTSURF, MASURF, MSURF,
     I MSURFG

      INTEGER, PUBLIC, ALLOCATABLE, SAVE ::
     I NTIM(:), IIMPOL(:,:)

      INTEGER, PUBLIC, SAVE ::
     I NRCELL, NPCELL, NTCELL, NACELL, NBLOCK, NBLCKA, 
     I ITYP,   IATM,   IMOL,   IION,   IPLS, IPHOT,
     I ICOL,   IPOLGN, NINCX,  NINCY,  NINCZ,  NINCA,  NJUMP,
     I IUNIN,  IUNOUT

      LOGICAL, PUBLIC, SAVE ::
     L LGPART, LGLAST, LGTIME,
     L NLSRFX, NLSRFY, NLSRFZ, NLSRFA,
     L NLTRC,  NLSTOR


      CONTAINS


      SUBROUTINE ALLOC_COMPRT

      IF (ALLOCATED(RPST)) RETURN

      ALLOCATE (RPST(NPARTC))
      ALLOCATE (IPSTD(MPARTC+1))

      ALLOCATE (TIMINT(NRADS))
      ALLOCATE (TIMPOL(N1STS,N2NDPLG))
      ALLOCATE (NTIM(NRADS))
      ALLOCATE (IIMPOL(N1STS,N2NDPLG))

      WRITE (55,*) ' COMPRT ',(NPARTC+NRADS+N1STS*N2NDPLG)*8 +
     .                       (MPARTC+1+NRADS+N1STS*N2NDPLG)*4

      RPSTT => RPST

      X0     => RPST( 1)
      Y0     => RPST( 2)
      Z0     => RPST( 3)
      VEL    => RPST( 4)
      VELX   => RPST( 5)
      VELY   => RPST( 6)
      VELZ   => RPST( 7)
      E0     => RPST( 8)
      WEIGHT => RPST( 9)
      TIME   => RPST(10)
      PHI    => RPST(11)
      XGENER => RPST(12)
      XNUE   => RPST(13)

      IPST  => IPSTD(2:MPARTC+1)
      IPSTT => IPSTD(1:MPARTT)

      NPANU  => IPSTD( 1)
      IPOLG  => IPSTD( 2)
      IPERID => IPSTD( 3)
      NCELL  => IPSTD( 4)
      ITIME  => IPSTD( 5)
      IFPATH => IPSTD( 6)
      IUPDTE => IPSTD( 7)
      ISTRA  => IPSTD( 8)
      ISPZ   => IPSTD( 9)
      MRSURF => IPSTD(10)
      MPSURF => IPSTD(11)
      MTSURF => IPSTD(12)
      MASURF => IPSTD(13)
      MSURF  => IPSTD(14)
      MSURFG => IPSTD(15)

      CALL INIT_COMPRT

      RETURN
      END SUBROUTINE ALLOC_COMPRT


      SUBROUTINE DEALLOC_COMPRT

      IF (.NOT.ALLOCATED(RPST)) RETURN

      DEALLOCATE (RPST)
      DEALLOCATE (IPSTD)

      DEALLOCATE (TIMINT)
      DEALLOCATE (TIMPOL)
      DEALLOCATE (NTIM)
      DEALLOCATE (IIMPOL)

      RETURN
      END SUBROUTINE DEALLOC_COMPRT


      SUBROUTINE INIT_COMPRT

      RPST   = 0._DP
      IPSTD  = 0._DP

      TIMINT = 0._DP
      TIMPOL = 0._DP
      NTIM   = 0._DP
      IIMPOL = 0._DP

      RETURN
      END SUBROUTINE INIT_COMPRT

      END MODULE COMPRT
