# 
#  Copyright @ 1984 - 1995   Josef Heinen
# 
#  Permission to use, copy, and distribute this software and its
#  documentation for any purpose with or without fee is hereby granted,
#  provided that the above copyright notice appear in all copies and
#  that both that copyright notice and this permission notice appear
#  in supporting documentation.
# 
#  Permission to modify the software is granted, but not the right to
#  distribute the modified code.  Modifications are to be distributed
#  as patches to released version.
# 
#  This software is provided "as is" without express or implied warranty.
# 
#  Send your comments or suggestions to
#   J.Heinen@kfa-juelich.de.
# 

FOR = FL
FFLAGS = /FPi /AH /Gt /nologo
AR = LIB /NOL
LINK = LINK
RM = DEL
CP = COPY
MKDIR = MKDIR
#
LIBCE = D:\C600\LIB\LLIBCE.LIB
DEV = D:

.SUFFIXES: .obj .for

.for.obj:
	$(FOR) /c $(FFLAGS) $*.for

all: libgks.lib demo.exe

#INT86.OBJ:
#	$(AR) $(LIBCE) *INT86;

libgks.lib: gksio.obj gks.obj gksinq.obj gkserror.obj gksroot.obj \
	    gksmisc.obj gksdidd.obj gksdps.obj gksdhpgl.obj \
	    gksdpbm.obj gksdwiss.obj gkswiss.obj gksddos.obj \
	    gksuns.obj gksafm.obj INT86.OBJ
	-$(RM) $@
	$(AR) $@ +gksio.obj +gks.obj +gksinq.obj +gkserror.obj +gksroot.obj;
	$(AR) $@ +gksmisc.obj +gksdidd.obj +gksdps.obj +gksdhpgl.obj;
	$(AR) $@ +gksdpbm.obj +gksdwiss.obj +gkswiss.obj +gksddos.obj;
	$(AR) $@ +gksuns.obj +gksafm.obj +INT86.OBJ;

clean:
	-$(RM) *.exe
	-$(RM) *.map
	-$(RM) libgks.*
	-$(RM) *.obj

demo.exe: demo.obj libgks.lib
	$(LINK) demo.obj,,,libgks+GRAPHICS+LLIBFORE;

install: all
	-$(MKDIR) $(DEV)\gks
	$(CP) gksfont.dat $(DEV)\gks
	$(CP) libgks.lib $(DEV)\gks
