      MODULE CTRCEI

      USE PRECISION
      USE PARMMOD

      IMPLICIT NONE

      PRIVATE

      PUBLIC :: ALLOC_CTRCEI, DEALLOC_CTRCEI, INIT_CTRCEI

      LOGICAL, PUBLIC, TARGET, ALLOCATABLE, SAVE :: LTRCEI(:)

      LOGICAL, PUBLIC, POINTER, SAVE ::
     L TRCPLT, TRCHST, TRCNAL, TRCMOD, TRCSIG,
     L TRCGRD, TRCSUR, TRCREF, TRCFLE, TRCAMD,
     L TRCINT, TRCLST, TRCSOU, TRCREC, TRCTIM,
     L TRCBLA, TRCBLP, TRCBLE, TRCBLM, TRCBLI

      LOGICAL, PUBLIC, ALLOCATABLE, SAVE :: TRCSRC(:)

      INTEGER, PUBLIC, TARGET, ALLOCATABLE, SAVE :: ITRCEI(:)

      INTEGER, PUBLIC, POINTER, SAVE ::
     I NPRTLV(:), NPRTLS(:), NPRSRF(:),
     I NVOLPR,    NFLAGV(:), NTLVFL(:),
     I NSURPR,    NFLAGS(:),
     I I1TRC,     I2TRC

      INTEGER, PUBLIC, ALLOCATABLE, SAVE ::
     I NSPEZV(:,:), NSPEZS(:,:)

      INTEGER, PUBLIC, SAVE :: MCTRC, LCTRC

      CONTAINS


      SUBROUTINE ALLOC_CTRCEI

      IF (ALLOCATED(LTRCEI)) RETURN

      MCTRC=4+500+NLIMPS
      LCTRC=20

      ALLOCATE (LTRCEI(LCTRC))
      ALLOCATE (ITRCEI(MCTRC))
      ALLOCATE (TRCSRC(0:NSTRA))
      ALLOCATE (NSPEZV(100,2))
      ALLOCATE (NSPEZS(NLIMPS,2))

      WRITE (55,*) ' CTRCEI ',(LCTRC+(NSTRA+1))*4
      WRITE (55,*) ' CTRCEI ',(MCTRC+200+2*NLIMPS)*4

      TRCPLT => LTRCEI( 1)
      TRCHST => LTRCEI( 2)
      TRCNAL => LTRCEI( 3)
      TRCMOD => LTRCEI( 4)
      TRCSIG => LTRCEI( 5)
      TRCGRD => LTRCEI( 6)
      TRCSUR => LTRCEI( 7)
      TRCREF => LTRCEI( 8)
      TRCFLE => LTRCEI( 9)
      TRCAMD => LTRCEI(10)
      TRCINT => LTRCEI(11)
      TRCLST => LTRCEI(12)
      TRCSOU => LTRCEI(13)
      TRCREC => LTRCEI(14)
      TRCTIM => LTRCEI(15)
      TRCBLA => LTRCEI(16)
      TRCBLP => LTRCEI(17)
      TRCBLE => LTRCEI(18)
      TRCBLM => LTRCEI(19)
      TRCBLI => LTRCEI(20)

      NPRTLV => ITRCEI(  1 : 100)
      NPRTLS => ITRCEI(101 : 200)
      NPRSRF => ITRCEI(201 : 300)
      NFLAGV => ITRCEI(301 : 400)
      NTLVFL => ITRCEI(401 : 500)
      NFLAGS => ITRCEI(501 : 500+NLIMPS)
      NVOLPR => ITRCEI(501+NLIMPS)
      NSURPR => ITRCEI(502+NLIMPS)
      I1TRC  => ITRCEI(503+NLIMPS)
      I2TRC  => ITRCEI(504+NLIMPS)

      CALL INIT_CTRCEI

      RETURN
      END SUBROUTINE ALLOC_CTRCEI


      SUBROUTINE DEALLOC_CTRCEI

      IF (.NOT.ALLOCATED(LTRCEI)) RETURN

      DEALLOCATE (LTRCEI)
      DEALLOCATE (ITRCEI)
      DEALLOCATE (TRCSRC)
      DEALLOCATE (NSPEZV)
      DEALLOCATE (NSPEZS)

      RETURN
      END SUBROUTINE DEALLOC_CTRCEI


      SUBROUTINE INIT_CTRCEI
      LTRCEI = .FALSE.
      ITRCEI = 0
      TRCSRC = .FALSE.
      NSPEZV = 0
      NSPEZS = 0
      NFLAGV = 1

      RETURN
      END SUBROUTINE INIT_CTRCEI

      END MODULE CTRCEI
