C
C
      SUBROUTINE PLTUSR(PLABLE,J)
      USE PRECISION
      USE PARMMOD
      USE COMUSR
      USE CADGEO
      USE CCONA
      USE CLGIN
      IMPLICIT NONE
      LOGICAL, INTENT(INOUT) :: PLABLE
      INTEGER, INTENT(IN) :: J
      INTEGER :: IB, MERK, IER
      REAL(DP) :: XS, YS, ZX0, ZY0, ZZ0, CX, CY, CZ, RZYLB, B0B, B1B,
     .          B2B, B3B, F0B, F1B, F2B, F3B, X0, Y0, B0, B1, B2, Z1, Z2
      INTEGER :: IN
      RETURN
      END
