      MODULE CLAST

      USE PRECISION
      USE PARMMOD

      IMPLICIT NONE

      PRIVATE

      PUBLIC :: ALLOC_CLAST, DEALLOC_CLAST, INIT_CLAST

      REAL(DP), PUBLIC, ALLOCATABLE, SAVE ::
     R          XCMEAN(:), SGCVMX(:),
     R          XEMEAN(:), SGEVMX(:)

      INTEGER, PUBLIC, ALLOCATABLE, SAVE ::
     I         NCMEAN(:),IFLRCX(:),
     I         NEMEAN(:),IFLREL(:)


      CONTAINS


      SUBROUTINE ALLOC_CLAST

      IF (ALLOCATED(XCMEAN)) RETURN

      ALLOCATE (XCMEAN(NRCX))
      ALLOCATE (SGCVMX(NRCX))
      ALLOCATE (XEMEAN(NREL))
      ALLOCATE (SGEVMX(NREL))

      ALLOCATE (NCMEAN(NRCX))
      ALLOCATE (IFLRCX(NRCX))
      ALLOCATE (NEMEAN(NREL))
      ALLOCATE (IFLREL(NREL))

      WRITE (55,*) ' CLAST ',(2*NRCX*2*NREL)*(8+4)

      CALL INIT_CLAST

      RETURN
      END SUBROUTINE ALLOC_CLAST


      SUBROUTINE DEALLOC_CLAST

      IF (.NOT.ALLOCATED(XCMEAN)) RETURN

      DEALLOCATE (XCMEAN)
      DEALLOCATE (SGCVMX)
      DEALLOCATE (XEMEAN)
      DEALLOCATE (SGEVMX)

      DEALLOCATE (NCMEAN)
      DEALLOCATE (IFLRCX)
      DEALLOCATE (NEMEAN)
      DEALLOCATE (IFLREL)

      RETURN
      END SUBROUTINE DEALLOC_CLAST


      SUBROUTINE INIT_CLAST

      XCMEAN = 0._DP
      SGCVMX = 0._DP
      XEMEAN = 0._DP
      SGEVMX = 0._DP

      NCMEAN = 0
      IFLRCX = 0
      NEMEAN = 0
      IFLREL = 0

      RETURN
      END SUBROUTINE INIT_CLAST

      END MODULE CLAST
