'195   LOG (Zi N)  against S for  ir =   8   '   99
'195   LOG (Zi N)  against S for  ir =  11   '   99
'196   LOG (Zi N)  against P for  ir =  11   '   99
'196   LOG (Zi N)  against P for  ir =  11   '   99
'196   LOG (Zi N)  against P for  ir =  11   '   99
'197   LOG (Zi Pow)  over  S for  ir =   8   '   99
'197   LOG (Zi Pow)  over  S for  ir =  12   '   99
'198   LOG (Zi Pow)  over  P for  ir =  11   '   99
