C
C
      SUBROUTINE SGNAL(ICHORI,IISTR,IAT)
C
C  THIS SUBROUTINE CALCULATES LINE INTEGRATED SIGNALS, USING THE EIRENE
C  VOLUME AVERAGED TALLIES AND THE PLASMA BACKGROUND DATA.
C
      USE PRECISION
      USE PARMMOD
      USE COMUSR
      USE CESTIM
      USE CCONA
      USE CLOGAU
      USE CPLOT
      USE COMSIG
      USE CGRID
      USE CTRCEI
      USE CSDVI
      USE CSDVI_COP
      USE CSDVI_BGK
      USE COMPRT
      USE COMSOU
      USE COUTAU
      USE COMXS
      USE CSPEI

      IMPLICIT NONE
C
      INTEGER, INTENT(IN) :: ICHORI, IISTR, IAT
      REAL(DP) :: C1(3),C2(3),PSIG(0:NSPZ+2),
     .          BUFFER(NCHOR,NCHEN),ESTART(NCHOR),ENDFIT(NCHOR)
C     REAL(DP) :: RECADD(0:NATM,NRAD)
      REAL(DP) :: ZE1, ZE2, ZSCALE, ZZ, SLOPE, STEIG, PMI, PMA, XMA, 
     .            XMI, XMAX, XMIN, ZSI, TIMAX, ZE
      INTEGER :: I1, I2, IN, I, NAC2, NBC2, ICHRD, IPVOT, NCHNI, ISK,
     .           JSK, IFIRST, JEN, ISP, NSPI, ISTR
      LOGICAL :: NLVL
C
      ISTRA=IISTR
      NCHNI=IABS(NCHENI)
C     CALL ZEROA2(RECADD,NATM,NRAD)
C
      IF (ISTRA.EQ.IESTR) THEN
C  NOTHING TO BE DONE
      ELSEIF (NFILEN.EQ.1.OR.NFILEN.EQ.2) THEN
        IESTR=ISTRA
        CALL RSTRT(ISTRA,NSTRAI,NESTM1,NESTM2,NADSPC,
     .             ESTIMV,ESTIMS,ESTIML,
     .             NSDVI1,SDVI1,NSDVI2,SDVI2,
     .             NSDVC1,SIGMAC,NSDVC2,SGMCS,
     .             NSBGK,SIGMA_BGK,NBGV_STAT,SGMS_BGK,
     .             NSCOP,SIGMA_COP,NCPV_STAT,SGMS_COP,
     .             NSIGI_SPC,TRCFLE)
        IF (NLSYMP(ISTRA).OR.NLSYMT(ISTRA)) THEN
          CALL SYMET(ESTIMV,NTALV,NRAD,NR1ST,NP2ND,NT3RD,
     .               NADDV,NFIRST,NLSYMP(ISTRA),NLSYMT(ISTRA))
        ENDIF
      ELSEIF ((NFILEN.EQ.6.OR.NFILEN.EQ.7).AND.ISTRA.EQ.0) THEN
        IESTR=ISTRA
        CALL RSTRT(ISTRA,NSTRAI,NESTM1,NESTM2,NADSPC,
     .             ESTIMV,ESTIMS,ESTIML,
     .             NSDVI1,SDVI1,NSDVI2,SDVI2,
     .             NSDVC1,SIGMAC,NSDVC2,SGMCS,
     .             NSBGK,SIGMA_BGK,NBGV_STAT,SGMS_BGK,
     .             NSCOP,SIGMA_COP,NCPV_STAT,SGMS_COP,
     .             NSIGI_SPC,TRCFLE)
        IF (NLSYMP(ISTRA).OR.NLSYMT(ISTRA)) THEN
          CALL SYMET(ESTIMV,NTALV,NRAD,NR1ST,NP2ND,NT3RD,
     .               NADDV,NFIRST,NLSYMP(ISTRA),NLSYMT(ISTRA))
        ENDIF
      ELSE
        WRITE (6,*) 'ERROR IN DIAGNO: DATA FOR STRATUM ISTRA= ',ISTRA
        WRITE (6,*) 'ARE NOT AVAILABLE. LINE INTEGRATION ABANDONNED'
        RETURN
      ENDIF
C
      IF (ISTRA.EQ.0) THEN
        NLVL=.FALSE.
        DO 10 ISTR=1,NSTRAI
          NLVL=NLVL.OR.NLVOL(ISTR)
10      CONTINUE
      ELSE
        NLVL=NLVOL(ISTRA)
      ENDIF
      IF (NLVL) THEN
        WRITE (6,*) 'WARNING:'
        WRITE (6,*) 'VOLUME RECOMBINATION CONTRIBUTION TO CX SIGNAL:'
        WRITE (6,*) 'FIRST GENERATION CONTRIBUTION: TO BE WRITTEN'
C  RECADD: #/S/CM**3
C  RECADD*ELCHA*VOL: AMP/CELL
C       DO 100 IPLS=1,NPLSI
C         DO 100 KREC=1,NPRCI(IPLS)
C           IATM=NATPRC(KREC)
C           IF (IATM.LE.0.OR.IATM.GT.NATMI) GOTO 100
C           DO 101 IR=1,NSBOX
C             RECADD(IATM,IR)=RECADD(IATM,IR)+
C    .                        TABRC1(KREC,IR)*DIIN(IPLS,IR)*ELCHA
101         CONTINUE
100     CONTINUE
      ENDIF
C
C     CALCULATE SIGNAL STRENGTHS
C
      IPVOT=IPIVOT(ICHORI)
      C1(1)=XPIVOT(ICHORI)
      C1(2)=YPIVOT(ICHORI)
      C1(3)=ZPIVOT(ICHORI)
C
      ICHRD=ICHORD(ICHORI)
      C2(1)=XCHORD(ICHORI)
      C2(2)=YCHORD(ICHORI)
      C2(3)=ZCHORD(ICHORI)
C
      NBC2=NSPBLC(ICHORI)
      NAC2=NSPADD(ICHORI)
C
C  ENERGY LOOP (IF ANY)
C
      PMA=-1.E30
      PMI=1.E30
      XMA=-1.E30
      XMI=1.E30
      IF (NCHTAL(ICHORI).EQ.1) NSPI=NATMI
      IF (NCHTAL(ICHORI).EQ.2) NSPI=6
      IF (NCHTAL(ICHORI).EQ.3) NSPI=NSPZ
      IFIRST=0
      DO 231 JEN=1,NCHNI
        ZE=ENERGY(JEN)
        CALL LININT (IFIRST,ICHORI,C1,C2,ICHRD,IPVOT,NBC2,NAC2,ZE,
     .               PSIG,TIMAX,PMI,PMA,XMI,XMA)
        IFIRST=1
        IF (IAT.GT.0.AND.IAT.LE.NSPI) THEN
C  SINGLE SPECIES INDEX ISP=IAT
          BUFFER(ICHORI,JEN)=PSIG(IAT)
        ELSEIF (IAT.EQ.0) THEN
C  SUM OVER SPECIES INDEX
          ZSI=0.
          DO 239 ISP=1,NSPI
            ZSI=ZSI+PSIG(ISP)
239       CONTINUE
          BUFFER(ICHORI,JEN)=ZSI
          WRITE (80,'(I6,3ES12.4)') ICHORI,C2
          WRITE (80,'(6ES12.4)') PSIG(0:NSPI)
        ELSE
          WRITE (6,*) 'ERROR IN SUBR. SGNAL: IAT= ',IAT
          CALL EXIT_OWN(1)
        ENDIF
C
C  PROCESS DATA FROM LINE INTEGRAL ROUTINES INTO REQUESTED DATA & UNITS
C
        IF (NCHTAL(ICHORI).EQ.1) THEN
C  LINE INTEGRAL: CX ATOMS/SEC/CM**2/EV/STERAD
C  THE NUMERICAL FACTOR 1./11.137 ARISES FROM A TRANSFORMATION
C  OF A MAXWELLIAN VELOCITY DISTRIBUTION TO A MAXW. ENERGY DISTR.
C  1./11.137=0.5*(1./PI)**1.5
          FUFFER(ICHORI,JEN)=BUFFER(ICHORI,JEN)*SQRT(ZE)/11.137
        ELSEIF (NCHTAL(ICHORI).EQ.2) THEN
C  LINE INTEGRAL: PHOTONS/SEC/CM**2/STERAD
          FUFFER(ICHORI,JEN)=BUFFER(ICHORI,JEN)/(4.*PIA)
        ELSEIF (NCHTAL(ICHORI).EQ.3) THEN
          FUFFER(ICHORI,JEN)=BUFFER(ICHORI,JEN)
        ENDIF
231   CONTINUE
C
C  ENERGY LOOP FINISHED
C
C  PLOT ENERGY SPECTRUM, IF AVAILABLE AND IF REQUESTED
C
      IF (NCHNI.LE.1) RETURN
C
      IF (PLSPEC) THEN
        CALL GRNXTB(2)
        IF (NSPSCL(ICHORI).EQ.0) THEN
          ISK=101
          JSK=101
        ELSEIF (NSPSCL(ICHORI).EQ.1) THEN
          ISK=101
          JSK=-101
        ELSEIF (NSPSCL(ICHORI).EQ.2) THEN
          ISK=-101
          JSK=101
        ELSEIF (NSPSCL(ICHORI).EQ.3) THEN
          ISK=-101
          JSK=-101
        ENDIF
        CALL GRBLD(33.,24.,ISK,JSK,REAL(XMI,KIND(1.E0)),
     .             REAL(XMA,KIND(1.E0)),REAL(PMI,KIND(1.E0)),
     .             REAL(PMA,KIND(1.E0)),NCHNI)
      ENDIF
C
C  FIT A STRAIGHT LINE TO SPECTRUM, BETWEEN ESTART AND ENDFIT
C
      ESTART(ICHORI)=NSPINI(ICHORI)*TIMAX
      ENDFIT(ICHORI)=NSPEND(ICHORI)*TIMAX
      TINP(ICHORI)=TIMAX
      IF (TRCSIG) THEN
        WRITE (6,*) 'FITTING RANGE: E1--E2, TIMAX'
        WRITE (6,*) ESTART(ICHORI),'--',ENDFIT(ICHORI),'  ',TIMAX
      ENDIF
C
C  FIND MAX. VALUE OF SIGNAL
      CALL MAXMN2(BUFFER,NCHOR,ICHORI,ICHORI,1,NCHNI,XMIN,XMAX)
C  SCALE RESULT
      IF (XMAX.GT.0.) GOTO 235
      CALL MASAGE ('NO SLOPE IN SIGNAL, BECAUSE MAX(BUFFER).LE.0   ')
      PLSPEC=.FALSE.
      RETURN
235   ZSCALE=1./XMAX
      DO 233 I=1,NCHNI
        BUFFER(ICHORI,I)=BUFFER(ICHORI,I)*ZSCALE
        ZZ=MAX(1.E-10_DP,BUFFER(ICHORI,I))
233     BUFFER(ICHORI,I)=LOG(ZZ)
C
C  CURVE FITTING
C
C  MIN. ENERGY FOR FIT
      ZE1=ESTART(ICHORI)
C  MAX. ENERGY
      ZE2=ENDFIT(ICHORI)
C
C  FIND ELEMENTS
      DO 241 JEN=2,NCHNI
        I1=JEN
        IF (ENERGY(I1).GE.ZE1) GO TO 242
241   CONTINUE
242   CONTINUE
C
      DO 243 JEN=I1,NCHNI
        I2=JEN
        IF (ENERGY(I2).GE.ZE2) GO TO 244
243   CONTINUE
244   CONTINUE
C
C   NUMBER OF POINTS FOR FITTING
      IN=I2-I1+1
      IF (IN.LT.2) THEN
        CALL MASAGE ('WRONG ENERGY RANGE FOR CURVE FITTING IN SIGNAL ')
        CALL MASJ1 ('CHORD.NO. I=           ',ICHORI)
        WRITE (6,*) 'I1,I2,IN ',I1,I2,IN
        TILINE(ICHORI)=0.
      ELSE
C  FITTED RESULT
        STEIG=SLOPE(IN,ICHORI,I1,ENERGY,BUFFER,NCHOR,NCHNI)
        IF (STEIG.GE.0.) THEN
          TILINE(ICHORI)=0.
        ELSE
          TILINE(ICHORI)=-1./STEIG
        ENDIF
      ENDIF
C
      IF (TRCSIG) THEN
        WRITE (6,*) 'ICHORI,TILINE(ICHORI) ',ICHORI,TILINE(ICHORI)
      ENDIF
C
      RETURN
      END
