C
C           *********************************
C           * ASSISTANT ROUTINES FOR EIRENE *
C           *********************************
C
C
C
C      SUBROUTINE MASJ1 (A,I)
C      SUBROUTINE MASJ2 (A,I,J)
C      SUBROUTINE MASJ3 (A,I,J,K)
C      SUBROUTINE MASJ4 (A,I,J,K,L)
C      SUBROUTINE MASJ5 (A,I,J,K,L,M)
C      SUBROUTINE MASJ6 (A,I,J,K,L,M,N)
C      SUBROUTINE MASR1 (A,B)
C      SUBROUTINE MASR2 (A,B,C)
C      SUBROUTINE MASR3 (A,B,C,D)
C      SUBROUTINE MASR4 (A,B,C,D,E)
C      SUBROUTINE MASR5 (A,B,C,D,E,F)
C      SUBROUTINE MASR6 (A,B,C,D,E,F,G)
C      SUBROUTINE MASJ1R (A,I,C)
C      SUBROUTINE MASJ2R (A,I,J,C)
C      SUBROUTINE MASL1 (A,B)
C      SUBROUTINE MASL2 (A,B,C)
C      SUBROUTINE MASL3 (A,B,C,D)
C      SUBROUTINE MASL4 (A,B,C,D,E)
C      SUBROUTINE MASL5 (A,B,C,D,E,F)
C      SUBROUTINE MASL6 (A,B,C,D,E,F,G)
C      SUBROUTINE MASLR2 (A,B,N,M,K)
C      SUBROUTINE MASIR2 (A,B,N,M,K)
C      SUBROUTINE MASRR1 (A,B,N,IN)
C      SUBROUTINE MASRR2 (A,B,C,N)
C      SUBROUTINE MASRR3 (A,B,C,D,N)
C      SUBROUTINE MASRR4 (A,B,C,D,E,N)
C      SUBROUTINE PRTTAL (T1,T2,T3,PROF,NR,NP,NT,NB,NTT,IFLAG,IFILE)
C      SUBROUTINE PRTVOL (T1,T2,T3,PROF,NR,NP,NT,NB,NTT,IFLAG,IFILE)
C      SUBROUTINE READTL (T1,T2,T3,PROF,NR,NP,NT,NB,NTT,IFLAG,IFILE)
C      SUBROUTINE READVL (T1,T2,T3,PROF,NR,NP,NT,NB,NTT,IFLAG,IFILE)
C      SUBROUTINE MASAJ1 (A,M,N)
C      SUBROUTINE MASAL1 (A,NL,N)
C      SUBROUTINE MASXR1 (A,B,KI,KE,KST,TX)
C      SUBROUTINE MASXR2 (A,B,C,KI,KE,KST,N,M,TX)
C      SUBROUTINE MASXR3 (A,B,C,D,KI,KE,KST,N,M,TX)
C      SUBROUTINE MASXR4 (A,B,C,D,KI,KE,KST,N,M,TX)
C      SUBROUTINE MASYR1 (A,B,NL,I1,N,TX)
C      SUBROUTINE MASPRM (A,NA,MA,B,NB,MA)
C      SUBROUTINE MASAGE (A)
C      SUBROUTINE MASBOX (A)
C      SUBROUTINE PAGE
C      SUBROUTINE LEER (N)
C      SUBROUTINE HEADNG (A,N)
C      SUBROUTINE MAXMN2
C      SUBROUTINE INTTAL
C      SUBROUTINE INTVOL
C      SUBROUTINE INDTAL
C      FUNCTION   LEARCA
C      FUNCTION   LEAPOL
C      SUBROUTINE NCELLN(NCELL,NR,NP,NT,NA,NB,NR1,NP2,NT3,NBM,LR,LP,LT)
C      FUNCTION   IDEZ
C      FUNCTION   DETER
C      SUBROUTINE ROTATE
C      SUBROUTINE SETROT
C      SUBROUTINE SETREF
C      SUBROUTINE XCORDF
C      SUBROUTINE SYMET
C      SUBROUTINE SPOINT
C      SUBROUTINE WRSTRT
C           ENTRY RDSTRT
C      SUBROUTINE FTCRI
C      SUBROUTINE FTCRE
C      FUNCTION   ARTRIA(X1,Y1,X2,Y2,X3,Y3)
C      FUNCTION   ARQUAD(X1,Y1,X2,Y2,X3,Y3,X4,Y4)
C      SUBROUTINE ARPOLY
C      SUBROUTINE ARELLP
C      SUBROUTINE BPROJ
C      SUBROUTINE BPROJI
C
C*DK MASJ1
      SUBROUTINE MASJ1 (A,I)
      IMPLICIT NONE
      CHARACTER(8), INTENT(IN) :: A
      INTEGER, INTENT(IN) :: I
      WRITE (6,60) A,I
60    FORMAT (1X,A8,3X,I6)
      RETURN
      END
