

      FUNCTION FEPLCX3 (IRCX,K)

      USE PRECISION
      USE PARMMOD
      USE COMUSR
      USE CCONA
      USE COMPRT
      USE COMXS

      IMPLICIT NONE

      INTEGER, INTENT(IN) :: IRCX, K
      REAL(DP) :: PLS, ADD, ELCX, FEPLCX3
      INTEGER :: II, KK, IPLSTI

      FEPLCX3=0.D0
      KK=NELRCX(IRCX)
      IPLSTI=MPLSTI(IPLS)
      IF (KK < 0) THEN
        SELECT CASE (KK)
C  DEFAULT CX MODEL
        CASE (-1)
            FEPLCX3=1.5*TIIN(IPLSTI,K)+EDRIFT(IPLS,K)
        CASE (-2)
C  MEAN ENERGY FROM DRIFTING MONOENERGETIC
            FEPLCX3=EPLCX3(IRCX,1,1)+EDRIFT(IPLS,K)
        CASE (-3)
C  MEAN ENERGY FROM DRIFTING MAXWELLIAN
            FEPLCX3=1.5*TIIN(IPLSTI,K)+EDRIFT(IPLS,K)
        END SELECT
      ELSE
C  MEAN ENERGY FROM SINGLE PARAMETER FIT KK
        ELCX = CREAC(9,1,KK)
        PLS=TIINL(IPLSTI,K)+ADDCX(IRCX,IPLS)
        DO II=8,1,-1
          ELCX = ELCX*PLS + CREAC(II,1,KK)
        END DO
        ADD=EPLCX3(IRCX,1,1)
        FEPLCX3=ELCX*DIIN(IPLS,K)*ADD
      END IF

      RETURN
      END
