C
C
C*DK RESETP
      SUBROUTINE RESETP (CRV,DEN,JC,ISEP,M1,N)
      USE PRECISION
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: JC, ISEP, M1,N
      REAL(DP), INTENT(OUT) :: CRV(M1,N)
      REAL(DP), INTENT(IN) :: DEN(N)
      INTEGER :: J
      DO 5 J=ISEP,N
5        CRV(JC,J-ISEP+1)=DEN(J)
      RETURN
      END
