      SUBROUTINE EIRENE_SCAL_SURF_TALLIES (ISTR)
 
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      USE EIRMOD_CESTIM
      USE EIRMOD_COUTAU
 
      IMPLICIT NONE
 
      INTEGER, INTENT(IN) :: ISTR
      INTEGER :: IATM, IMOL, IION, IPHOT, IPLS, ISPC
 
      ESTIMS=ESTIMS*FLXFAC(ISTR)
C
      ETOTA(ISTR)=ETOTA(ISTR)*FLXFAC(ISTR)
      ETOTM(ISTR)=ETOTM(ISTR)*FLXFAC(ISTR)
      ETOTI(ISTR)=ETOTI(ISTR)*FLXFAC(ISTR)
      ETOTP(ISTR)=ETOTP(ISTR)*FLXFAC(ISTR)
      ETOTPH(ISTR)=ETOTPH(ISTR)*FLXFAC(ISTR)
      PTRASH(ISTR)=PTRASH(ISTR)*FLXFAC(ISTR)
      ETRASH(ISTR)=ETRASH(ISTR)*FLXFAC(ISTR)
      DO 610 IATM=0,NATM
        WTOTA(IATM,ISTR)=WTOTA(IATM,ISTR)*FLXFAC(ISTR)
610   CONTINUE
      DO 615 IMOL=0,NMOL
        WTOTM(IMOL,ISTR)=WTOTM(IMOL,ISTR)*FLXFAC(ISTR)
615   CONTINUE
      DO 620 IION=0,NION
        EELFI(IION,ISTR)=EELFI(IION,ISTR)*FLXFAC(ISTR)
        WTOTI(IION,ISTR)=WTOTI(IION,ISTR)*FLXFAC(ISTR)
620   CONTINUE
      DO 622 IPHOT=0,NPHOT
        WTOTPH(IPHOT,ISTR)=WTOTPH(IPHOT,ISTR)*FLXFAC(ISTR)
 622  CONTINUE
      DO 625 IPLS=0,NPLS
        WTOTP(IPLS,ISTR)=WTOTP(IPLS,ISTR)*FLXFAC(ISTR)
625   CONTINUE
      WTOTE(ISTR)=WTOTE(ISTR)*FLXFAC(ISTR)
 
C   SCALE AND INTEGRATE SPECTRA
 
      DO ISPC=1,NADSPC
        IF (ESTIML(ISPC)%PSPC%ISRFCLL == 0) THEN
          ESTIML(ISPC)%PSPC%SPC = ESTIML(ISPC)%PSPC%SPC * FLXFAC(ISTR) *
     .                            ESTIML(ISPC)%PSPC%SPCDELI
          ESTIML(ISPC)%PSPC%SPCINT = SUM(ESTIML(ISPC)%PSPC%SPC*
     .                                   ESTIML(ISPC)%PSPC%SPCDEL)
        END IF
      END DO
 
      RETURN
 
      END SUBROUTINE EIRENE_SCAL_SURF_TALLIES
