c  16.12.05  cleaned up
      SUBROUTINE EIRENE_STAT_SUMOSTRA
C
C    STATISTICS, SUM OVER STRATA
C
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      USE EIRMOD_CSDVI
      USE EIRMOD_CSDVI_BGK
      USE EIRMOD_CSDVI_COP
      USE EIRMOD_CGRID
      USE EIRMOD_CSPEI
      USE EIRMOD_CCONA
      USE EIRMOD_COMSOU
      USE EIRMOD_CESTIM
 
      IMPLICIT NONE
 
      REAL(DP) :: ST
      INTEGER :: K, I, ISPC, J, ISDV, ICELL, IB
 
      DO 1207 K=1,NSIGVI
        DO 1208 I=1,NSBOX_TAL
          ST=MAX(0._DP,STV(K,I))
          STV(K,I)=SQRT(ST)/(ABS(EE(K,I))+EPS60)
1208    CONTINUE
        ST=MAX(0._DP,STVS(K))
        STVS(K)=SQRT(ST)/(ABS(EES(K))+EPS60)
1207  CONTINUE
C
      IF (NSIGI_BGK.GT.0) THEN
        DO 1217 K=1,NBGVI_STAT
          DO 1218 I=1,NSBOX_TAL
            ST=MAX(0._DP,STV_BGK(K,I))
            STV_BGK(K,I)=SQRT(ST)/(ABS(EE_BGK(K,I))+EPS60)
1218      CONTINUE
          ST=MAX(0._DP,STVS_BGK(K))
          STVS_BGK(K)=SQRT(ST)/(ABS(EES_BGK(K))+EPS60)
1217    CONTINUE
      ENDIF
C
      IF (NSIGI_COP.GT.0) THEN
        DO K=1,NCPVI_STAT
          DO I=1,NSBOX_TAL
            ST=MAX(0._DP,STV_COP(K,I))
            STV_COP(K,I)=SQRT(ST)/(ABS(EE_COP(K,I))+EPS60)
          END DO
          ST=MAX(0._DP,STVS_COP(K))
          STVS_COP(K)=SQRT(ST)/(ABS(EES_COP(K))+EPS60)
        END DO
      ENDIF
C
      IF ((NSTRAI > 1) .AND. (NSMSTRA > 0)) THEN
        IF (NSIGI_SPC.GT.0) THEN
          DO ISPC=1,NADSPC
            DO I=0,SMESTL(ISPC)%PSPC%NSPC+1
              ST=MAX(0._DP,SMESTL(ISPC)%PSPC%SGM(I))
              SMESTL(ISPC)%PSPC%SGM(I)=SQRT(ST)/
     .                     (ABS(SMESTL(ISPC)%PSPC%SDV(I))+EPS60)
            END DO
            ST=MAX(0._DP,SMESTL(ISPC)%PSPC%STVS)
            SMESTL(ISPC)%PSPC%STVS=SQRT(ST)/
     .                             (ABS(SMESTL(ISPC)%PSPC%EES)+EPS60)
          END DO
        ENDIF
      ENDIF
C
      DO 1221 K=1,NSIGSI
        DO 1222 J=1,NLIMPS
          ST=MAX(0._DP,STVW(K,J))
          STVW(K,J)=SQRT(ST)/(ABS(FF(K,J))+EPS60)
1222    CONTINUE
        ST=MAX(0._DP,STVWS(K))
        STVWS(K)=SQRT(ST)/(ABS(FFS(K))+EPS60)
1221  CONTINUE
C
      DO 1240 ISDV=1,NSIGCI
        DO 1242 ICELL=1,NSBOX_TAL
          STVC(1,ISDV,ICELL)=SQRT(MAX(0._DP,STVC(1,ISDV,ICELL)))
          STVC(2,ISDV,ICELL)=SQRT(MAX(0._DP,STVC(2,ISDV,ICELL)))
1242    CONTINUE
        STVCS(1,ISDV)=SQRT(MAX(0._DP,STVCS(1,ISDV)))
        STVCS(2,ISDV)=SQRT(MAX(0._DP,STVCS(2,ISDV)))
1240  CONTINUE
C
C  CONVERT RELATIVE ERRORS TO %-ERRORS
C
      STV  = STV*100._DP
      STVS = STVS*100._DP
      STVW  = STVW*100._DP
      STVWS = STVWS*100._DP
C
      IF (NSIGI_BGK.GT.0) THEN
        DO 1251 IB=1,NBGVI_STAT
          STVS_BGK(IB)=STVS_BGK(IB)*100.D0
          DO 1252 J=1,NSBOX_TAL
            STV_BGK(IB,J)=STV_BGK(IB,J)*100.D0
1252      CONTINUE
1251    CONTINUE
      ENDIF
C
      IF (NSIGI_COP.GT.0) THEN
        DO IB=1,NCPVI_STAT
          STVS_COP(IB)=STVS_COP(IB)*100.D0
          DO J=1,NSBOX_TAL
            STV_COP(IB,J)=STV_COP(IB,J)*100.D0
          END DO
        END DO
      ENDIF
 
      IF ((NSTRAI > 1) .AND. (NSMSTRA > 0)) THEN
        IF (NSIGI_SPC.GT.0) THEN
          DO ISPC=1,NADSPC
            SMESTL(ISPC)%PSPC%STVS=SMESTL(ISPC)%PSPC%STVS*100.D0
            DO J=0,SMESTL(ISPC)%PSPC%NSPC+1
              SMESTL(ISPC)%PSPC%SGM(J)=SMESTL(ISPC)%PSPC%SGM(J)*100.D0
            END DO
          END DO
        ENDIF
      ENDIF
 
      RETURN
 
      END SUBROUTINE EIRENE_STAT_SUMOSTRA
