C
      SUBROUTINE WRGEOM(TRCFLE)
      USE PRECISION
      USE PARMMOD
      USE CADGEO
      USE COMPRT, ONLY: IUNOUT
      USE CPOLYG
      USE CGRID
      USE CGEOM
      USE CLGIN
      USE CTRIG
      IMPLICIT NONE
      LOGICAL TRCFLE
C
      OPEN (UNIT=12,ACCESS='SEQUENTIAL',FORM='UNFORMATTED')
      REWIND 12
      WRITE (12) RCGM1,RCGM2,NPOINT,NSTGRD,NGHPLS,NGHPOL,NCLTAL
      IF (TRCFLE) WRITE (iunout,*) 'WRITE 12: RCGM,ICGM '
      WRITE (12) RCGRID,ICGRID
      IF (TRCFLE) WRITE (iunout,*) 'WRITE 12: RCGRID,ICGRID'
      WRITE (12) RCPLYG,RCPLY2,ICPLYG
      IF (TRCFLE) WRITE (iunout,*) 'WRITE 12: RCPLYG,ICPLYG'
      IF (NRKNOT > 0) THEN
        WRITE (12) XTRIAN,YTRIAN,VTRIX,VTRIY,PTRIX,PTRIY,
     .             NECKE,NCHBAR,NSEITE,INMTI,NRKNOT,NTRII
        IF (TRCFLE) WRITE (iunout,*) 'WRITE 12: RCTRIG,ICTRIG'
      END IF
      WRITE (12)
     R RLWMN,RLWMX,EWALL,EWBIN,TRANSP,FSHEAT,
     R ZNML,ZNCL,
     R RECYCF,RECYCT,RECPRM,EXPPL,EXPEL,EXPIL,
     R RECYCS,RECYCC,SPTPRM,
     I ILSWCH,ILEQUI,ILTOR,ILSIDE,ILIIN,ILREF,
     I ILSPT,ILCOL,ILFIT,ILCELL,ILBOX,ILPLG,ISPUT,
     I NLIMII,NLIMIE,ISWICH,ILBLCK,ILACLL,JUMLIM,
     I NSTSI,INUMP,IRPTA,IRPTE,ISRF,ISRT,ISRS,ISRC,
     I INMP1I,INMP2I,INMP3I,
     I IGFIL,IGJUM0,IGJUM1,IGJUM2,IGJUM3
      IF (TRCFLE) WRITE (iunout,*) 'WRITE 12: RCLGN,ICLGN,LCLGN'
      WRITE (12) RADGEO,IADGEO,NLIMI
      IF (TRCFLE) WRITE (iunout,*) 'WRITE 12: RCADG,ICADG'
      CLOSE (UNIT=12)
      RETURN
C
      ENTRY RGEOM(TRCFLE)
      OPEN (UNIT=12,ACCESS='SEQUENTIAL',FORM='UNFORMATTED')
      REWIND 12
      READ (12) RCGM1,RCGM2,NPOINT,NSTGRD,NGHPLS,NGHPOL,NCLTAL
      IF (TRCFLE) WRITE (iunout,*) 'READ 12: RCGM,ICGM '
      READ (12) RCGRID,ICGRID
      IF (TRCFLE) WRITE (iunout,*) 'READ 12: RCGRID,ICGRID'
      READ (12) RCPLYG,RCPLY2,ICPLYG
      IF (TRCFLE) WRITE (iunout,*) 'READ 12: RCPLYG,ICPLYG'
      IF (NRKNOT > 0) THEN
        READ (12) XTRIAN,YTRIAN,VTRIX,VTRIY,PTRIX,PTRIY,
     .            NECKE,NCHBAR,NSEITE,INMTI,NRKNOT,NTRII
        IF (TRCFLE) WRITE (iunout,*) 'READ 12: RCTRIG,ICTRIG'
      END IF
      READ (12)
     R RLWMN,RLWMX,EWALL,EWBIN,TRANSP,FSHEAT,
     R ZNML,ZNCL,
     R RECYCF,RECYCT,RECPRM,EXPPL,EXPEL,EXPIL,
     R RECYCS,RECYCC,SPTPRM,
     I ILSWCH,ILEQUI,ILTOR,ILSIDE,ILIIN,ILREF,
     I ILSPT,ILCOL,ILFIT,ILCELL,ILBOX,ILPLG,ISPUT,
     I NLIMII,NLIMIE,ISWICH,ILBLCK,ILACLL,JUMLIM,
     I NSTSI,INUMP,IRPTA,IRPTE,ISRF,ISRT,ISRS,ISRC,
     I INMP1I,INMP2I,INMP3I,
     I IGFIL,IGJUM0,IGJUM1,IGJUM2,IGJUM3
      IF (TRCFLE) WRITE (iunout,*) 'READ 12: RCLGN,ICLGN,LCLGN'
      READ (12) RADGEO,IADGEO,NLIMI
      IF (TRCFLE) WRITE (iunout,*) 'READ 12: RCADG,ICADG'
      CLOSE (UNIT=12)
      RETURN
      END
