#!/bin/sh
if [ $# -lt 2 ]
then 
   echo "usage: $0 <input file> <output driver>"
   exit 1
fi
cd /u/progs/lim
mkdir $1
cd $1
cp /u/progs/lim/results/$1.raw fort.8
/u/progs/lim/outsrc/out3O < /u/progs/lim/data/limout/$2.dlo > $1.outo
cp fort.7 /u/progs/lim/results/$1.dago
cp fort.9 /u/progs/lim/results/$1.ingo
cp $1.outo /u/progs/lim/results/$1.outo
#
# To convert back to gnuplot - comment out the following line 
# and uncomment the rest.
#
mv POSTSCPT.LIS /u/progs/lim/results/$1.psgo
#mv fort.12 $1.grao 
#cp $1.grao /u/progs/lim/results
#/u/progs/lim/utils/cgpp $1.grao
#gnuplot $1.gnu
#mv $1.psg /u/progs/lim/results/$1.psgo
#a2ps -nn $1.inf > $1.psio
#mv $1.inf /u/progs/lim/results/$1.info
#mv $1.psio /u/progs/lim/results
#rm $1*
#rm fort.* 
cd /u/progs/lim
#rmdir $1
cd /u/progs/lim/results
#lp $1.psio
#lp $1.psgo
cd /u/progs/lim



