C
C
C*DK MASAGE
      SUBROUTINE MASAGE (A)
      USE PRECISION
      USE COMPRT, ONLY: IUNOUT
      IMPLICIT NONE
      CHARACTER(*), INTENT(IN) :: A
      WRITE (iunout,60) A
 60   FORMAT (1X,A)
      RETURN
      END
