C
C*DK MASJ1R
      SUBROUTINE MASJ1R (A,I,B)
      USE PRECISION
      USE COMPRT, ONLY: IUNOUT
      IMPLICIT NONE
      CHARACTER(16), INTENT(IN) :: A
      REAL(DP), INTENT(IN) :: B
      INTEGER, INTENT(IN) :: I
      WRITE (iunout,60) A,I,B
60    FORMAT (1X,A16,3X,I6,3X,1PE12.4)
      RETURN
      END
