C
C*DK MASL1
      SUBROUTINE MASL1 (A,B)
      USE PRECISION
      USE COMPRT, ONLY: IUNOUT
      IMPLICIT NONE
      CHARACTER(*), INTENT(IN) :: A
      LOGICAL, INTENT(IN) :: B
      WRITE (iunout,60) A,B
60    FORMAT (1X,A,5X,L3)
      RETURN
      END
