#!/bin/sh
if [ $# -lt 2 ]
then 
   echo "usage: $0 <input driver> <output driver>"
   exit 1
fi
cd /u/progs/lim
mkdir $1
cd $1
/u/progs/lim/limsrc/lim3O < /u/progs/lim/data/limin/$1.dli > /u/progs/lim/results/$1.lim
mv fort.7 $1.dat 
mv fort.78 $1.dbg
cp $1.dat /u/progs/lim/results
a2ps -nn $1.dat > $1.ps 
cp $1.ps /u/progs/lim/results
cp fort.9 /u/progs/lim/results/$1.inp
cp fort.8 /u/progs/lim/results/$1.raw
#
# slmod
#
cp fort.63 $1.pro
cp $1.pro ../profile
cp fort.59 $1.rpr
cp $1.bdg ../results
#
# slmod end
#
/u/progs/lim/outsrc/out3O < /u/progs/lim/data/limout/$2.dlo > $1.out
cp fort.7 /u/progs/lim/results/$1.dag
cp fort.9 /u/progs/lim/results/$1.ing
cp $1.out /u/progs/lim/results/$1.out
#
# To convert back to gnuplot - comment out the following line 
# and uncomment the rest.
#
mv POSTSCPT.LIS /u/progs/lim/results/$1.psg
#mv fort.12 $1.gra 
#cp $1.gra /u/progs/lim/results
#/u/progs/lim/utils/cgpp $1.gra
#gnuplot $1.gnu
#mv $1.psg /u/progs/lim/results
#a2ps -nn $1.inf > $1.psi
#mv $1.inf /u/progs/lim/results
#mv $1.psi /u/progs/lim/results
rm $1*
rm fort.* 
cd /u/progs/lim
rmdir $1
cd /u/progs/lim/results
#lp $1.ps
#lp $1.psi
#lp $1.psg
cd /u/progs/lim



