C
C
      LOGICAL FUNCTION EIRENE_BITGET(IBIT,N1LOW,N1UP,IROW,JCOL,NBITS)
 
      IMPLICIT NONE
 
      INTEGER, INTENT(IN) :: N1LOW, N1UP, IROW, JCOL, NBITS
      INTEGER, INTENT(INOUT) :: IBIT(N1LOW:N1UP,*)
      INTEGER :: JELEM, JB, ISET
 
      JELEM=JCOL/NBITS
      JB=MOD(JCOL,NBITS)
      IF (JB == 0) THEN
        JB=NBITS-1
      ELSE
        JELEM=JELEM+1
        JB=JB-1
      END IF
 
      EIRENE_BITGET = BTEST(IBIT(IROW,JELEM),JB)
 
      RETURN
      END
