C
C
      SUBROUTINE EIRENE_FTCRE (F,C)
      USE EIRMOD_PRECISION
      IMPLICIT NONE
      REAL(DP), INTENT(IN) :: F
      CHARACTER(10), INTENT(OUT) :: C
      WRITE(C,'(1P,E10.3)') F
      RETURN
      END
