C
C
C*DK LEARCA
      FUNCTION EIRENE_LEARCA (X,R,N1,N,NS,TEXT)
C
C   THIS FUNCTION COMPUTES THE INDEX OF THE SMALLER MESHPOINT OF THE
C   INTERVALL CONTAINING THE POINT X IN THE MESH R(NS,I),I=1,N
C   N1 IS THE LEADING DIMENSION OF THE FIELD R, AS SPECIFIED IN THE
C   CALLING PROGRAM AND NS IS A FIXED INDEX.
C
      USE EIRMOD_PRECISION
      USE EIRMOD_COMPRT, ONLY: IUNOUT
      IMPLICIT NONE
 
      CHARACTER(*), INTENT(IN) :: TEXT
      INTEGER, INTENT(IN) :: N1, N, NS
      REAL(DP), INTENT(IN) :: R(N1,*)
      REAL(DP), INTENT(IN) :: X
      INTEGER :: NNN, I, J, EIRENE_LEARCA
 
      NNN=1
      IF (X.LT.R(NS,1)-1.D-12) GOTO 20
13    DO 10 J=2,N
        I=J
        IF (X-R(NS,J).LE.0.0) GOTO 15
10    CONTINUE
      NNN=N
      IF (X.GT.R(NS,N)+1.D-12) GOTO 20
15    EIRENE_LEARCA=I-1
      RETURN
C
20    WRITE (iunout,*) 'X OUT OF RANGE IN LEARCA'
      WRITE (iunout,*)  X,NNN,R(NS,NNN)
      WRITE (iunout,*) 'LEARCA= ',NNN,' RETURNED TO SUBR. ',TEXT
      EIRENE_LEARCA=NNN
C
      RETURN
      END
