C
C*DK MASJ4
      SUBROUTINE EIRENE_MASJ4 (A,I,J,K,L)
      USE EIRMOD_PRECISION
      USE EIRMOD_COMPRT, ONLY: IUNOUT
      IMPLICIT NONE
      CHARACTER(32), INTENT(IN) :: A
      INTEGER, INTENT(IN) :: I, J, K, L
      WRITE (iunout,60) A,I,J,K,L
60    FORMAT (1X,A32/1X,4(I6,3X))
      RETURN
      END
