C
C*DK MASJR2
      SUBROUTINE EIRENE_MASJR2 (A,I,B,C)
      USE EIRMOD_PRECISION
      USE EIRMOD_COMPRT, ONLY: IUNOUT
      IMPLICIT NONE
      CHARACTER(24), INTENT(IN) :: A
      REAL(DP), INTENT(IN) :: B, C
      INTEGER, INTENT(IN) :: I
      WRITE (iunout,60) A,I,B,C
60    FORMAT (1X,A24,3X,I6,3X,2(1PE12.4,3X))
      RETURN
      END
