C
C*DK MASJ1
      SUBROUTINE EIRENE_MASJ1 (A,I)
      USE EIRMOD_PRECISION
      USE EIRMOD_COMPRT, ONLY: IUNOUT
      IMPLICIT NONE
      CHARACTER(8), INTENT(IN) :: A
      INTEGER, INTENT(IN) :: I
      REAL(DP) :: FI
      IF (I.LT.1000000) THEN
        WRITE (IUNOUT,60) A,I
      ELSEIF (I.LT.100000000) THEN
        WRITE (IUNOUT,70) A,I
      ELSE
        FI=I
        WRITE (IUNOUT,80) A,FI
      ENDIF
60    FORMAT (1X,A8,3X,I6)
70    FORMAT (1X,A8,3X,I8)
80    FORMAT (1X,A8,3X,1PE12.4)
      RETURN
      END
