C
C
C*DK MASL4
      SUBROUTINE EIRENE_MASL4 (A,B,C,D,E)
      USE EIRMOD_PRECISION
      USE EIRMOD_COMPRT, ONLY: IUNOUT
      IMPLICIT NONE
      CHARACTER(*), INTENT(IN) :: A
      LOGICAL, INTENT(IN) :: B, C, D, E
      WRITE (iunout,60) A,B,C,D,E
60    FORMAT (1X,A,5X,4L3)
      RETURN
      END
