C
C*DK MASR6
      SUBROUTINE EIRENE_MASR6 (A,B,C,D,E,F,G)
      USE EIRMOD_PRECISION
      USE EIRMOD_COMPRT, ONLY: IUNOUT
      IMPLICIT NONE
      CHARACTER(48), INTENT(IN) :: A
      REAL(DP), INTENT(IN) :: B, C, D, E, F, G
      WRITE (iunout,60) A,B,C,D,E,F,G
60    FORMAT (1X,A48/1X,6(1PE12.4,3X))
      RETURN
      END
