C
C
C*DK MASR1
      SUBROUTINE EIRENE_MASR1 (A,B)
      USE EIRMOD_PRECISION
      USE EIRMOD_COMPRT, ONLY: IUNOUT
      IMPLICIT NONE
      CHARACTER(8), INTENT(IN) :: A
      REAL(DP), INTENT(IN) :: B
      WRITE (iunout,60) A,B
60    FORMAT (1X,A8,3X,1PE12.4)
      RETURN
      END
