C
C*DK MASRR2
      SUBROUTINE EIRENE_MASRR2 (A,B,C,N)
      USE EIRMOD_PRECISION
      USE EIRMOD_COMPRT, ONLY: IUNOUT
      IMPLICIT NONE
      CHARACTER(22), INTENT(IN) :: A
      INTEGER, INTENT(IN) :: N
      REAL(DP), INTENT(IN) :: B(N), C(N)
      INTEGER :: J
      WRITE (iunout,60) A
60    FORMAT (1X,A22)
      DO 5 J=1,N
5        WRITE (iunout,61) J,B(J),C(J)
61    FORMAT (1X,I4,1X,2(1PE12.4,3X))
      RETURN
      END
