C
      SUBROUTINE PROFS(PRO,PRO0,PRO1,SEP,PROVAC)
C
C  CONSTANT PROFILE, PLUS SECOND VALUE BEYOND RHOSEP
C
      USE PRECISION
      USE PARMMOD
      USE CCONA
      USE CGRID

      IMPLICIT NONE

      REAL(DP), INTENT(IN) :: PRO0, PRO1, SEP, PROVAC
      REAL(DP), INTENT(OUT) :: PRO(*)
      REAL(DP) :: AREAA, ARCA, AR, ELLR, YR, EP1R, RHOSEP
      INTEGER :: LEARCA, J, NLOCAL, JM1

      RHOSEP=SEP
      IF (LEVGEO.LE.2) THEN
        IF (RRA.GT.RAA) THEN
          NLOCAL=NR1STM
          PRO(NR1STM)=PROVAC
        ELSE
          NLOCAL=NR1ST
        ENDIF
C
C FIND RADIAL SURFACE LABELING CO-ORDINATE AT "SEP"
C
        IF (LEVGEO.EQ.2) THEN
          JM1=LEARCA(SEP,RSURF,1,NLOCAL,1,'PROFS       ')
          AR=AREAA (SEP,JM1,ARCA,YR,EP1R,ELLR)
          RHOSEP=SQRT(AR*PIAI)
        ELSEIF (LEVGEO.EQ.1) THEN
          RHOSEP=SEP
        ENDIF
      ELSE
        WRITE (6,*) 'WARNING: PROFS CALLED WITH LEVGEO.GT.2 '
        WRITE (6,*) 'CONSTANT PLASMA PARAMETERS RETURNED'
        NLOCAL=NR1ST
        DO 25 J=1,NLOCAL-1
          PRO(J)=PRO0
25      CONTINUE
        PRO(NR1ST)=0.
        RETURN
      ENDIF
C
      DO 20 J=1,NLOCAL-1
        IF (RHOZNE(J).GT.RHOSEP) GOTO 15
        PRO(J)=PRO0
        GOTO 20
15      PRO(J)=PRO1
20    CONTINUE
      PRO(NR1ST)=0.
      RETURN
      END
