C
      SUBROUTINE SETCON
      USE PRECISION
      USE PARMMOD
      USE CCONA

      IMPLICIT NONE

      REAL(DP) :: AMUAKG

      CALL ALLOC_CCONA

C   CONSTANTS
C  ELECTRON CHARGE [EV]
      ELCHA=1.6022D-19
C  ENERGY CONVERSION
      EV_TO_J=ELCHA
      J_TO_EV=1.D0/EV_TO_J
      J_TO_ERG=1.0D7
      ERG_TO_J=1.D0/J_TO_ERG
      EV_TO_ERG=EV_TO_J*J_TO_ERG
      ERG_TO_EV=1.D0/EV_TO_ERG
      EVKEL=8.6173D-5
C  PLANCK CONSTANT, [ERG S]
      HPLANCK=6.6260755D-27
C  SPEED OF LIGHT, [CM/S]
      CSPEED=2.99792458D+10
C  ATOMIC MASS UNIT [G]
      AMUA=1.6606D-24
C  PROTON, ELECTRON MASS
      PMASSA=1.0073
      PMASSE=5.448D-4
C  NUMERICAL PRECISION PARAMETERS
      EPS60=1.D-60
      EPS30=1.D-30
      EPS12=1.D-12
      EPS10=1.D-10
      EPS6=1.D-6
      EPS5=1.D-5
C
      PIA=4._DP*ATAN(1._DP)
      PI2A=2._DP*PIA
      PIHA=PIA/2._DP
      PISQ=SQRT(PIA)
      PIAI=1._DP/PIA
C
      SQ2=SQRT(2._DP)
      SQ2I=1._DP/SQ2
      DEGRAD=PIA/180._DP
      RADDEG=180._DP/PIA
C  EIRENE UNITS CONVERSIONS
      AMUAKG=AMUA*1.D-3
C  V_THERMAL=CVEL2A*SQRT(T(EV)/RMASS(AMU)),  CVEL2A=0.98227E6
      CVEL2A=SQRT(1.D4*ELCHA/AMUAKG)
C  VEL(CM/S)=CVELAA*SQRT(E0(EV)/RMASS(AMU)), CVELAA=1.38912E6
      CVELAA=SQ2*CVEL2A
      CVELI2=1._DP/CVELAA/CVELAA
      EFACT=CVELI2*PMASSA
      EFCT23=EFACT*2._DP/3._DP
C
C  IONIZATION POTENTIAL OF NEUTRAL HYDROGEN ATOM
      EIONH=13.6_DP
C  IONIZATION POTENTIAL OF NEUTRAL HYDROGEN MOLECULE
      EIONH2=15.4_DP
C  IONIZATION POTENTIAL OF NEUTRAL HELIUM ATOM
      EIONHE=24.588_DP
C
      RETURN
C
      END
