C
C
C
C*DK MASR2
      SUBROUTINE MASR2 (A,B,C)
      USE PRECISION
      IMPLICIT NONE
      CHARACTER(16), INTENT(IN) :: A
      REAL(DP), INTENT(IN) :: B, C
      WRITE (6,60) A,B,C
60    FORMAT (1X,A16,2(3X,1PE12.4))
      RETURN
      END
