 
 
      FUNCTION EIRENE_LEAUSR(A,B,C)
      USE EIRMOD_PRECISION
      IMPLICIT NONE
      REAL(DP), INTENT(IN) :: A, B, C
      INTEGER :: EIRENE_LEAUSR
      EIRENE_LEAUSR=1
      RETURN
      END
