      MODULE CSPEZ

      USE PRECISION
      USE PARMMOD

      IMPLICIT NONE

      PRIVATE

      PUBLIC :: ALLOC_CSPEZ, DEALLOC_CSPEZ, INIT_CSPEZ

      LOGICAL, PUBLIC, ALLOCATABLE, SAVE ::
     L LOGATM(:,:), LOGION(:,:),
     L LOGMOL(:,:), LOGPLS(:,:), LOGPHOT(:,:)


      CONTAINS

      SUBROUTINE ALLOC_CSPEZ

      IF (ALLOCATED(LOGATM)) RETURN

      ALLOCATE (LOGATM(0:NATM,0:NSTRA))
      ALLOCATE (LOGION(0:NION,0:NSTRA))
      ALLOCATE (LOGMOL(0:NMOL,0:NSTRA))
      ALLOCATE (LOGPLS(0:NPLS,0:NSTRA))
      ALLOCATE (LOGPHOT(0:NPHOT,0:NSTRA))

      WRITE (55,'(A,T25,I15)')
     .      ' CSPEZ ', (NSTRA+1)*(NPHOT+NATM+NION+NMOL+NPLS+5)*4

      CALL INIT_CSPEZ

      RETURN
      END SUBROUTINE ALLOC_CSPEZ


      SUBROUTINE DEALLOC_CSPEZ

      IF (.NOT.ALLOCATED(LOGATM)) RETURN

      DEALLOCATE (LOGATM)
      DEALLOCATE (LOGION)
      DEALLOCATE (LOGMOL)
      DEALLOCATE (LOGPLS)
      DEALLOCATE (LOGPHOT)

      RETURN
      END SUBROUTINE DEALLOC_CSPEZ


      SUBROUTINE INIT_CSPEZ

      LOGATM  = .FALSE.
      LOGION  = .FALSE.
      LOGMOL  = .FALSE.
      LOGPLS  = .FALSE.
      LOGPHOT = .FALSE.

      RETURN
      END SUBROUTINE INIT_CSPEZ

      END MODULE CSPEZ
