C
C
      SUBROUTINE STATIS_SPC

      USE PRECISION
      USE PARMMOD
      USE COMUSR
      USE CESTIM
      USE CCONA
      USE CGRID
      USE CSDVI
      USE CSDVI_COP
      USE COUTAU
      USE COMSOU

      IMPLICIT NONE

      REAL(DP), INTENT(IN) :: XN, FSIG, ZFLUX
      INTEGER, INTENT(IN) :: NBIN, NRIN, NPIN, NTIN, NSIN
      LOGICAL, INTENT(IN) :: LP, LT

      REAL(DP), ALLOCATABLE :: SD(:)
      REAL(DP) :: XNM, DS, ZFLUXQ, D2S, SG,
     .            DSA, DD, D, SG2, DA, SD1, SD1S
      INTEGER :: NSB, NP2, NR1, NT3, I, ISPC
C
      SAVE
C
      ENTRY STATS0_SPC

      IF (NADSPC > 0) THEN
        DO ISPC=1,NADSPC
          ESTIML(ISPC)%PSPC%IMETSP = 0
        END DO
      END IF
C
      RETURN

C
      ENTRY STATS1_SPC(NBIN,NRIN,NPIN,NTIN,NSIN,LP,LT)
      NSB=NBIN
      NR1=NRIN
      NP2=NPIN
      NT3=NTIN
C
C
      IF (NADSPC.EQ.0) RETURN
C
C
C  STATISTICS FOR SPECTRA
      DO ISPC=1,NADSPC
C
        IF (ESTIML(ISPC)%PSPC%IMETSP > 0) THEN
          SD1S=0.
          ALLOCATE (SD(0:ESTIML(ISPC)%PSPC%NSPC+1))
          SD = 0.D0
          DO I = 0,ESTIML(ISPC)%PSPC%NSPC+1
            SD1=ESTIML(ISPC)%PSPC%SPC(I)-ESTIML(ISPC)%PSPC%SDV(I)
            SD1S=SD1S+SD1
            ESTIML(ISPC)%PSPC%SDV(I)=ESTIML(ISPC)%PSPC%SPC(I)
            SD(I) = SD1
          END DO

          DO I = 0,ESTIML(ISPC)%PSPC%NSPC+1
            SD1=SD(I)
            ESTIML(ISPC)%PSPC%SGM(I)=ESTIML(ISPC)%PSPC%SGM(I)+SD1*SD1
          END DO
          ESTIML(ISPC)%PSPC%SGMS=ESTIML(ISPC)%PSPC%SGMS+SD1S*SD1S
          DEALLOCATE (SD)
        END IF
      END DO
C
C
      RETURN
C
      ENTRY STATS2_SPC(XN,FSIG,ZFLUX)
C
C  1. FALL  ALLE BEITRAEGE GLEICHES VORZEICHEN: SIG ZWISCHEN 0 UND 1
C           (=1, FALLS NUR EIN BEITRAG UNGLEICH 0, ODER (KUENSTLICH
C            ERZWUNGEN) FALLS GAR KEIN BEITRAG UNGLEICH NULL)
C  2. FALL  NEGATIVE UND POSITIVE BEITRAGE KOMMEN VOR:
C           LT. FORMEL SIND AUCH WERTE GROESSER 1  MOEGLICH.
C
      XNM=XN-1.
      IF (XNM.LE.0.) RETURN
      ZFLUXQ=ZFLUX*ZFLUX
C
      IF (NADSPC.EQ.0) RETURN
C
C  STATISTICS FOR MOMENTUM SOURCES
      DO ISPC=1,NADSPC
C
        ALLOCATE (SD(0:ESTIML(ISPC)%PSPC%NSPC+1))

        SD=ESTIML(ISPC)%PSPC%SPC
        DS=SUM(SD)

        DO I=0,ESTIML(ISPC)%PSPC%NSPC+1
          D=SD(I)
          DD=D*D
          DA=ABS(D)
          SG2=MAX(0._DP,ESTIML(ISPC)%PSPC%SGM(I)-DD/XN)
C RELATIV STANDARD DEVIATION
          SG=SQRT(SG2)/(DA+EPS60)
          ESTIML(ISPC)%PSPC%SGM(I)=SG*FSIG
C CUMULATED VARIANCE FOR SUM OVER STRATA
! STV
          IF ((NSMSTRA > 0 ) .AND. (NSTRAI > 1)) THEN
            SMESTL(ISPC)%PSPC%SGM(I)=SMESTL(ISPC)%PSPC%SGM(I)+
     .                               SG2*ZFLUXQ/XNM/XN
! EE
            SMESTL(ISPC)%PSPC%SDV(I)=SMESTL(ISPC)%PSPC%SDV(I)+D*ZFLUX/XN
          END IF
        END DO
        D2S=DS*DS
        DSA=ABS(DS)
        SG2=MAX(0._DP,ESTIML(ISPC)%PSPC%SGMS-D2S/XN)
        SG=SQRT(SG2)/(DSA+EPS60)
        ESTIML(ISPC)%PSPC%SGMS=SG*FSIG
C
        IF ((NSMSTRA > 0 ) .AND. (NSTRAI > 1)) THEN
          SMESTL(ISPC)%PSPC%STVS=SMESTL(ISPC)%PSPC%STVS+
     .                           SG2*ZFLUXQ/XNM/XN
          SMESTL(ISPC)%PSPC%EES =SMESTL(ISPC)%PSPC%EES+DS*ZFLUX/XN
        END IF

        DEALLOCATE (SD)
      END DO
C
2200  CONTINUE
      RETURN
      END
