$
$    Dperp Xperp Extractor Options
$
'TN1303 Dperp Extractor - methods used - 0 1 2       '     2
'TN1310 Dperp Ext. 0=only to Xpoint 1=Full Field Line'     1 
'TN1310 Dperp Ext. Outer Ring Losses   0=off 1=on    '     1
'TN1309 Dperp Ext. Dperp  Convection   0=off 1=on    '     1
'TN1311 Dperp Ext. 1/2 Cell Flux Corr. 0=off 1=on    '     0
'TN1311 Dperp Ext. Calc. Average Dperp.0=off 1=on    '     1
'TN1311 Dperp Ext. Major Radius Corr.  0=off 1=on    '     0
