'      PIN Puffing Option - 0=off 1=on               '    0
'      PIN Puff Location switch - 0=main SOL 1=PP    '    0
'      PIN Puff fraction (opt 1)                     '   0.0
'      PIN Extra Flux Fraction (Puff opt 2)          '   0.0
'      PIN Fraction of Extra Flux to be Puffed       '   0.0
'      PIN Puff Injection temperature (eV)           '   0.5
'      PIN Puff location indices JHPUF1(1 and 2)'  -1000 -1000
'      PIN Puff location indices JHPUF2(1 and 2)'  -1    -1
