$
$    Parameters for SOL model 
$
'    Imposed mach number at the target               '    1.0
'    Delta mach number for initial iterative solution'    0.1
'    Maximum resolution in calculation of m0         ' 0.000001
$
$    Ionization source
$
'    Length of ionization source                     '    5.0
'    Decay length of ionization source               '    0.5
$
$    Radiation source
$
'    Length of radiation source                      '    5.0
'    Decay length of radiation  source               '    0.5
'    Source strength fraction (frr)                  '    1.0
$
$    Miscellaneous
$
'    Gamma correction factor in gammai               '    0.0
'    CX power coefficeint CEICF                      '    1.0
'    Initial number of stages for Runge Kutta steps  '    100
$
$    Switches
$
'    Switch: 5/2 nv * kT    : 0.0-off 1.0-on         '    1.0
'    Switch: 1/2 m v^3 * n  : 0.0-off 1.0-on         '    1.0
'    Switch: Prad           : 0.0-off 1.0-on         '    0.0
'    Switch: Phelpi         : 0.0-off 1.0-on         '    0.0
'    Switch: Pei            : 0.0-off 1.0-on         '    0.0 
'    Switch: Pcx            : 0.0-off 1.0-on         '    0.0
'    Switch: Visc 1 - N calc: 0.0-off 1.0-on         '    1.0
'    Switch: Momentum loss  : 0.0-off 1.0-on         '    0.0
'    Switch: Iterative Mach : 0.0-off 1.0-on         '    1.0
