      MODULE EIRMOD_CAI
 
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
 
      IMPLICIT NONE
 
      PRIVATE
 
      PUBLIC :: EIRENE_ALLOC_CAI, EIRENE_DEALLOC_CAI, EIRENE_INIT_CAI
 
      REAL(DP), PUBLIC, ALLOCATABLE, SAVE :: RATIO(:)
 
      INTEGER, PUBLIC, ALLOCATABLE, SAVE :: NRECOM(:)
 
      CONTAINS
 
 
      SUBROUTINE EIRENE_ALLOC_CAI
 
      IF (ALLOCATED(RATIO)) RETURN
 
      ALLOCATE (RATIO(NSTRA))
      ALLOCATE (NRECOM(NSTRA))
 
      WRITE (55,'(A,T25,I15)')
     .      ' CAI ',NSTRA*(8+4)
 
      CALL EIRENE_INIT_CAI
 
      RETURN
      END SUBROUTINE EIRENE_ALLOC_CAI
 
 
      SUBROUTINE EIRENE_DEALLOC_CAI
 
      IF (.NOT.ALLOCATED(RATIO)) RETURN
 
      DEALLOCATE (RATIO)
      DEALLOCATE (NRECOM)
 
      RETURN
      END SUBROUTINE EIRENE_DEALLOC_CAI
 
 
      SUBROUTINE EIRENE_INIT_CAI
 
      RATIO  = 0.D0
      NRECOM = 0
 
      RETURN
      END SUBROUTINE EIRENE_INIT_CAI
 
      END MODULE EIRMOD_CAI
