      MODULE EIRMOD_CTSURF
 
      USE EIRMOD_PRECISION
 
      IMPLICIT NONE
 
      PRIVATE
 
      INTEGER, ALLOCATABLE, PUBLIC :: IDROB(:,:), ISEEOB(:,:)
      INTEGER, PUBLIC :: NTETSUR
 
      REAL(DP), ALLOCATABLE, PUBLIC :: RTETMIN(:,:)
 
      END MODULE EIRMOD_CTSURF
