      MODULE EIRMOD_PRECISION
 
      PUBLIC :: DP, SP
 
      INTEGER, PARAMETER :: DP = SELECTED_REAL_KIND(15,307)
      INTEGER, PARAMETER :: SP = SELECTED_REAL_KIND(6)
 
      END MODULE EIRMOD_PRECISION
