      SUBROUTINE CLEAR_STRATUM
C
C  CLEAR WORK AREA FOR THIS STRATUM
C
      USE PRECISION
      USE PARMMOD
      USE CSPEI
      USE CESTIM
      USE CSDVI
      USE CSDVI_BGK
      USE CSDVI_COP

      IMPLICIT NONE

      INTEGER :: ISPC

      IESTR=-1
      ESTIMV=0.
      ESTIMS=0.
      SDVI1=0.
      SDVI2=0.
      SIGMAC=0.
      SGMCS=0.
C  ARRAYS SDVIA,SDVIAW,SDVIAC
      SDVIA  = 0.D0
      SDVIAW = 0.D0
      SDVIAC = 0.D0
C  BGK-ARRAYS
      SGMS_BGK=0.D0
      SIGMA_BGK=0.D0
      SDVIA_BGK=0.D0
C  COP-ARRAYS
      SGMS_COP=0.D0
      SIGMA_COP=0.D0
      SDVIA_COP=0.D0
C  SPECTRA
      DO ISPC=1,NADSPC
        ESTIML(ISPC)%PSPC%SPC = 0._DP
        ESTIML(ISPC)%PSPC%SPCINT = 0._DP
        IF (NSIGI_SPC > 0) THEN
          ESTIML(ISPC)%PSPC%SGMS = 0._DP
          ESTIML(ISPC)%PSPC%SGM = 0._DP
          ESTIML(ISPC)%PSPC%SDV = 0._DP
        END IF
      END DO

      RETURN

      END SUBROUTINE CLEAR_STRATUM
