C
C
      SUBROUTINE FZRTRI(X0,Z0,NNEW,XOLD,PH,NOLD)
C
C  CALCULATE THE LOCAL CO-ORDINATES X0,Z0 IN ZONE NNEW
C
C  FROM THE CELL NUMBER NOLD,
C       THE X CO-ORDINATE XOLD (=X+RMTOR) IN THAT CELL
C       THE TOROIDAL ANGLE PH
C
C  INPUT : XOLD,PH,NOLD, NNEW
C  OUTPUT: X0,Z0
C
C
      USE PRECISION
      USE PARMMOD
      USE CCONA
      USE CGRID

      IMPLICIT NONE

      REAL(DP), INTENT(IN) :: XOLD, PH
      REAL(DP), INTENT(OUT) :: X0, Z0
      INTEGER, INTENT(IN) :: NOLD, NNEW
      REAL(DP) :: WLOC1, WLOC2, WTH, Z1, RR, XNEW

      Z1=ZSURF(1)
      WTH=MOD(PH+PI2A-Z1,PI2A)+Z1
      WLOC1=WTH-ZZONE(NOLD)
      RR=XOLD/COS(WLOC1)
C
      WLOC2=WTH-ZZONE(NNEW)
      XNEW=RR*COS(WLOC2)
      X0=XNEW-RMTOR
      Z0=TAN(WLOC2)*XNEW
      RETURN
      END
