C
C
      SUBROUTINE EIRENE_STATIS_COP
      USE EIRMOD_PRECISION
      IMPLICIT NONE
      REAL(DP), INTENT(IN) :: X1, X2, X3
      INTEGER, INTENT(IN) :: N1, N2, N3, N4, N5
      LOGICAL, INTENT(IN) :: L1, L2
      ENTRY EIRENE_STATS0_COP
      ENTRY EIRENE_STATS1_COP(N1,N2,N3,N4,N5,L1,L2)
      ENTRY EIRENE_STATS2_COP(X1,X2,X3)
      END
