subroutine styx_deallocate_eirene_modules
  USE EIRMOD_PRECISION
  USE EIRMOD_PARMMOD
  USE EIRMOD_COMUSR
!pb      USE EIRMOD_CREFMOD
  USE EIRMOD_CREF
  USE EIRMOD_CESTIM
  USE EIRMOD_CRECH
  USE EIRMOD_CADGEO
  USE EIRMOD_cai
  USE EIRMOD_CCONA
  USE EIRMOD_CGRPTL
  USE EIRMOD_CLOGAU
  USE EIRMOD_CPL3D
  USE EIRMOD_CPLOT
  USE EIRMOD_CINIT
  USE EIRMOD_CUPD
  USE EIRMOD_COMSIG
  USE EIRMOD_CPOLYG
  USE EIRMOD_CGRID
  USE EIRMOD_CSPEZ
  USE EIRMOD_CZT1
  USE EIRMOD_CTRCEI
  USE EIRMOD_CCOUPL
  USE EIRMOD_CGEOM
  USE EIRMOD_CSDVI
  USE EIRMOD_CSDVI_COP
  USE EIRMOD_CSDVI_BGK
  USE EIRMOD_CTETRA
  USE EIRMOD_COMPRT
  USE EIRMOD_CPES
  USE EIRMOD_COMNNL
  USE EIRMOD_COMSOU
  USE EIRMOD_CSTEP
  USE EIRMOD_COMSPL
  USE EIRMOD_CTEXT
  USE EIRMOD_CLGIN
  USE EIRMOD_COUTAU
  USE EIRMOD_COMXS
  USE EIRMOD_CSPEI
  USE EIRMOD_CTRIG
  USE EIRMOD_CLAST
  use EIRMOD_cfplk
  implicit none

  write(*,*) 'Deallocating EIRENE modules ...'

  CALL EIRENE_DEALLOC_COMUSR
!pb         CALL EIRENE_DEALLOC_CREFMOD
  CALL EIRENE_DEALLOC_CREF
  CALL EIRENE_DEALLOC_CESTIM
  CALL EIRENE_DEALLOC_CADGEO
  CALL EIRENE_DEALLOC_CAI
  CALL EIRENE_DEALLOC_CGRPTL
  CALL EIRENE_DEALLOC_CPLOT
  CALL EIRENE_DEALLOC_CINIT
  CALL EIRENE_DEALLOC_CUPD
  IF (NCHORI > 0) CALL EIRENE_DEALLOC_COMSIG
  CALL EIRENE_DEALLOC_CPOLYG
  CALL EIRENE_DEALLOC_CGRID
  CALL EIRENE_DEALLOC_CSPEZ
  CALL EIRENE_DEALLOC_CZT1
  CALL EIRENE_DEALLOC_CTRCEI
  IF (NMODE .NE. 0) CALL EIRENE_DEALLOC_CCOUPL
  CALL EIRENE_DEALLOC_CGEOM
  CALL EIRENE_DEALLOC_CSDVI
  CALL EIRENE_DEALLOC_CSDVI_BGK
  CALL EIRENE_DEALLOC_CSDVI_COP
  CALL EIRENE_DEALLOC_CTETRA
  CALL EIRENE_DEALLOC_COMPRT
  CALL EIRENE_DEALLOC_CPES
  CALL EIRENE_DEALLOC_COMNNL
  CALL EIRENE_DEALLOC_COMSOU
  CALL EIRENE_DEALLOC_CSTEP
  CALL EIRENE_DEALLOC_COMSPL
  CALL EIRENE_DEALLOC_CTEXT
  CALL EIRENE_DEALLOC_CLGIN
  CALL EIRENE_DEALLOC_COUTAU
  CALL EIRENE_DEALLOC_COMXS
  CALL EIRENE_DEALLOC_CSPEI
  CALL EIRENE_DEALLOC_CLAST
  call EIRENE_dealloc_cfplk
  CALL EIRENE_LOCAT2            ! DEALLOCATE LOCAL ARRAYS IN LOCATE
  CALL EIRENE_SAMSF2            ! DEALLOCATE LOCAL ARRAYS IN SAMSRF
  CALL EIRENE_STATS3            ! DEALLOCATE LOCAL ARRAYS IN STATIS

! yannick
  call eirene_dealloc_ctrig

  write(*,*) 'done.'

! this is now done in styx2D
!
!         IF (MPI_INITIALIZE) CALL MPI_FINALIZE(IER)
 
  IF (MY_PE > 0) THEN
    CLOSE (UNIT=IUNOUT)
  END IF

end subroutine styx_deallocate_eirene_modules
