subroutine styx_broadcast_eirene_variables
  use all_variables, only : global_parameters, interp_data2, global_variables, reference_parameters
  use eirmod_parmmod
  use eirmod_cpes
  use eirmod_cestim
  use eirmod_comusr
  use eirmod_cstep
  use eirmod_clgin
  use eirmod_comnnl
  use eirmod_cspei
  use eirmod_csdvi
  use eirmod_czt1
  use eirmod_comsou
  use eirmod_coutau
  use eirmod_cupd
  use eirmod_ccona
  use eirmod_comxs
  use styx2eirene
  implicit none
  integer :: ier

  include 'mpif.h'

  ! current time step (may evolve during the run), used in EIRENE only
  if (timedep .and. my_pe == 0) then
    dt_eirene=global_variables%dt*reference_parameters%fields%tau0*float(n_short_cycles+1)
    dtimv_styx=dt_eirene
    write(*,*) 'current EIRENE time horizon (s) = ',dt_eirene
  endif

  call mpi_bcast(dt_eirene,1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  
  !fluxes
  CALL MPI_BCAST (FLUX,NSTRA,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  ! plasma parameters
  CALL MPI_BCAST (TEIN,NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (TIIN,NPLSTI*NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (DEIN,NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (DIIN,NPLS*NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (VXIN,NPLSV*NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (VYIN,NPLSV*NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (VZIN,NPLSV*NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  ! derived data
  CALL MPI_BCAST (TEINL,NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (TIINL,NPLSTI*NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (EDRIFT,NPLS*NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (DEINL,NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (DIINL,NPLS*NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (BVIN,NPLSV*NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (PARMOM,NPLS*NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (LGVAC,NRAD*(NPLS+2),MPI_LOGICAL,0,MPI_COMM_WORLD,ier)
  ! used for sampling velocities
  CALL MPI_BCAST (ZT1,NPLS*NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (ZRG,NPLS*NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)

  ! rates
  CALL MPI_BCAST (TABDS1,NRDS*NSTORDR,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (TABRC1,NREC*NSTORDR,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (TABPI3,NRPI*NSTORDR*NSTORDT,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (TABCX3,NRCX*NSTORDR*NSTORDT,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (TABEL3,NREL*NSTORDR*NSTORDT,MPI_REAL8,0,MPI_COMM_WORLD,ier)

  ! energy rates
  CALL MPI_BCAST (EELDS1,NRDS*NSTORDR,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (EHVDS1,NRDS*NSTORDR,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (EELRC1,NREC*NSTORDR,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (EELPI1,NRPI*NSTORDR,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (EHVPI3,NRPI*NSTORDR*NSTORDT,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (EPLPI3,NRPI*NSTORDR*NSTORDT,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (EPLCX3,NRCX*NSTORDR*NSTORDT,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (EPLEL3,NREL*NSTORDR*NSTORDT,MPI_REAL8,0,MPI_COMM_WORLD,ier)

  ! step functions (fluxes, plasma parameters at the wall)
  CALL MPI_BCAST (FLSTEP,NSTPP1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (ELSTEP,NSTPP1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (FLTOT,(NSPZ+1)*NSTEP,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (VF,NSTPP1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (QUOT,NSTPP1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (ADD,NSTPP1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (QUOTI,NSTPP1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (ADDIV,NSTPP1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (TESTEP,NSTPP2,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (TISTEP,NPLSTI*NSTEP*NGITT,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (RRSTEP,NSTPP2,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (VXSTEP,NPLSV*NSTEP*NGITT,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (VYSTEP,NPLSV*NSTEP*NGITT,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (VZSTEP,NPLSV*NSTEP*NGITT,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (DISTEP,NSTPP3,MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (IRSTEP,NSTPP2,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (IPSTEP,NSTPP2,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (ITSTEP,NSTPP2,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (IASTEP,NSTPP2,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (IBSTEP,NSTPP2,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (IGSTEP,NSTPP2,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (ISTUF,NSTEP,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (NSMAX,NSTEP,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (NSPSTI,NSTEP,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (NSPSTE,NSTEP,MPI_INTEGER,0,MPI_COMM_WORLD,ier)

  ! data modified here

  CALL MPI_BCAST (RECYCT,NSPZ*(NLIMPS+1),MPI_REAL8,0,MPI_COMM_WORLD,ier)
  CALL MPI_BCAST (EWALL,NLIMPS+1,MPI_REAL8,0,MPI_COMM_WORLD,ier) 


  call mpi_bcast(curiter,1,mpi_integer,0,mpi_comm_world,ier)
  call mpi_bcast(numiter,1,mpi_integer,0,mpi_comm_world,ier)

  ! turn on additionnal diagnostics for last call 
  if (curiter == numiter) then
     call styx_setup_last_eirene_call
     CALL MPI_BCAST (ISDVI,MSDVI,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
     CALL MPI_BCAST (IIHC,2*NCV,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
     CALL MPI_BCAST (IGHC,2*NCV,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
  endif

!!!!!! some of the variables for noise estimation should be broadcasted here !!!!!

  ! time0 is defined in module comnl

  if (my_pe == 0 .and. timedep) then
     icalleir=icalleir+1
     time0=time0+dfloat(icalleir-1)*dtimv_styx
     ! reinitialize and broadcast counter
     IPRNLI=0
  endif

  if (timedep) then 
    call MPI_BCAST (SORWGT,NSRFS*NSTRA,MPI_REAL8,0,MPI_COMM_WORLD,ier)
    call MPI_BCAST (NSRFSI,NSTRA,MPI_REAL8,0,MPI_COMM_WORLD,ier)
    CALL MPI_BCAST (ISPEZI,6*NSPZ,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
    CALL MPI_BCAST (DTIMV,1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (DTIMVI,1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (DTIMVN,1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (TIME0,1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (RPART,NPRNL*NPARTT,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (RPARTC,NPRNL*NPARTT,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (RPARTW,NPRNL+1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NPRNLI,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IPRNLI,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IPRNLS,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IPRNL ,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NPTST ,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NTMSTP,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ITMSTP,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IPART,NPRNL*MPARTT,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IPARTC,NPRNL*MPARTT,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NPRNLS,NSTRA,MPI_INTEGER,0,MPI_COMM_WORLD,ier)

  endif
 
  CALL MPI_BCAST (IPRNLI,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
  



end subroutine styx_broadcast_eirene_variables
