'T  ' 'Set of X(m) VS(eV) data values for Sputt. Opt. 8'
'T   Number of rows of X,VS(x) Y<0,VS(x) Y>0: '  0
'T   STEP limiter shape coords. for Edge 6: XST1 Y<0(m)'     0.0
'T                                  Y<0   : YST1 Y<0(m)'     0.0
'T                                          XST2 Y<0(m)'     0.0
'T                                          YST2 Y<0(m)'     0.0
'T                                          XST3 Y<0(m)'     0.0
'T                                          YST3 Y<0(m)'     0.0
'T                                  Y>0   : XST1 Y>0(m)'     0.0
'T                                          YST1 Y>0(m)'     0.0
'T                                          XST2 Y>0(m)'     0.0
'T                                          YST2 Y>0(m)'     0.0
'T                                          XST3 Y>0(m)'     0.0
'T                                          YST3 Y>0(m)'     0.0
'T   Coord for Dperpi/Dperpo changeover  +/-(1..MAXQXS)'      0
