'T131 Radial Position of camera observation           (m)   '     0.0
'T131 Angular Position   (0.0 = from limiter tip)  (degrees)'     0.0     
'    R BINS (m).' 'Values must be in range 0 > R > A-AW.  Define radial'
'    bins.                Number of R positions :- '   0
'    Theta BINS (degress).' 'Give values for 0 < T < 180. Define       '
'    angular bins. Max 49. Number of Y positions :- '   0
