'T31   ION TEMPERATURE outb.base Y < 0 TBiout<(eV)   '   40.0
'      ION outboard exp. decay Y < 0   LTiout<(m)    '    0.022
'      ION outboard base value Y > 0   TBiout>(eV)   '   40.0
'      ION outboard exp. decay Y > 0   LTiout>(m)    '    0.022
'      ION inboard base value          TBiin  (eV)   '   40.0
'      0 < X < ATiin exp. decay        LTiin1 (m)    '    0.0                   
'      0 < X < ATiin linear decay      GTiin1 (eV/m) '  4800.0
'      ION inboard crossover point     ATiin  (m)    '    0.7                   
'      ATiin < X < A exp. decay        LTiin2 (m)    '    0.0                   
'      ATiin < X < A linear decay      GTiin2 (eV/m) '    0.0                   
'T31' 'Set of inboard paired values (X,Tbi) to interpolate'                    
'T31   Number of rows of (X,Tbi) data :-'     0                                
