C
C
!  6.12.05  bugfix: avoid calculation of B-field in dead cells
!                   because geometrical parameters may not be known there.
!  6.8. 06  bugfix of bugfix: avoid calculation of B-field in dead cells, but
!                             still make sure to set B-field in 1D cases.
!  15.12.06 bug fix: index error corrected in call to prousr when called for ADIN 
!                    
      SUBROUTINE PLASMA

      USE PRECISION
      USE PARMMOD
      USE COMUSR
      USE CCONA
      USE CLOGAU
      USE CINIT
      USE CPOLYG
      USE CGRID
      USE CGEOM
      USE CTEXT
      USE COMPRT

      IMPLICIT NONE

      REAL(DP), ALLOCATABLE :: HELP(:)
      REAL(DP) :: PUX, PUY, EL, EP, PN, BD, B, BVAC, FACT
      INTEGER :: IB, IAIN, K, JJ, ITALI, ICELL, IND, ISTREAM,
     .           IP, IT, IA, J, IR, IPLSTI, IPLSV
C
C  INDPRO=9 MEANS: THESE ARRAYS ARE ALREADY SET IN COUPLE_... (SUBR. INFCOP)
      IF (INDPRO(1) /= 9) TEIN = 0.D0
      IF (INDPRO(2) /= 9) TIIN = 0.D0
      DEIN = 0.D0
      IF (INDPRO(3) /= 9) DIIN = 0.D0
      IF (INDPRO(4) /= 9) VXIN = 0.D0
      IF (INDPRO(4) /= 9) VYIN = 0.D0
      IF (INDPRO(4) /= 9) VZIN = 0.D0
      IF (INDPRO(5) /= 9) BXIN = 0.D0
      IF (INDPRO(5) /= 9) BYIN = 0.D0
      IF (INDPRO(5) /= 9) BZIN = 0.D0
      IF (INDPRO(5) /= 9) BFIN = 0.D0
      IF (INDPRO(6) /= 9) ADIN = 0.D0

      ALLOCATE (HELP(NRAD))
      HELP=0.
C
C  SET EIRENE VACUUM MODEL DATA. I.E. IF ALL TEMPERATURES ARE
C  LESS THAN TVAC OR THE BACKGROUND DENSITY IS LESS THAN DVAC,
C  THEN THIS ZONE IS CONSIDERED TO BE AN "EIRENE VACUUM ZONE",
C  PARTICLE MEAN FREE PATHES IN SUCH ZONES ARE
C  EQUAL TO 1.D10 (CM) AND REACTION RATES ARE ZERO
      TVAC=0.02
      DVAC=1.D2
      VVAC=0.
      BVAC=1.
C
C     SET DENSITY, TEMPERATURE AND MACH NUMBER PROFILES
C     ON MESH "RHOZNE(J)"
C
C
C
C  ELECTRON TEMPERATURE
      IND=INDPRO(1)
      GOTO (101,102,103,104,105,106,107,110,110),IND
101     CALL PROFN (TEIN,TE0,TE1,TE2,TE3,TE4,TE5,TVAC)
        GOTO 110
102     CALL PROFE (TEIN,TE0,TE1,TE2,TE4,TE5,TVAC)
        GOTO 110
103     CALL PROFS (TEIN,TE0,TE1,TE5,TVAC)
        GOTO 110
104     CONTINUE
        ISTREAM=TE0
        ITALI=1
        CALL READTL(TXTPLS(1,ITALI),TXTPSP(1,ITALI),
     .              TXTPUN(1,ITALI),
     .              TEIN,NR1ST,NP2ND,NT3RD,NBMLT,NSBOX,
     .              3,ISTREAM)
        GOTO 110
105     CALL PROUSR (TEIN,0,TE0,TE1,TE2,TE3,TE4,TE5,TVAC,NSURF)
        GOTO 110
106     CALL PROFR (TEIN,0,1,1,NSURF)
        GOTO 110
107     CALL PROFR (TEIN,0,1,1,NSBOX)
        GOTO 110
110   CONTINUE



C  ION TEMPERATURE
      IND=INDPRO(2)
      DO 120 IPLS=1,NPLSTI
        GOTO (111,112,113,114,115,116,117,120,120),IND
111     CALL PROFN (HELP,TI0(IPLS),TI1(IPLS),TI2(IPLS),
     .                   TI3(IPLS),TI4(IPLS),TI5(IPLS),TVAC)
        TIIN(IPLS,1:NR1ST)=HELP(1:NR1ST)
        GOTO 120
112     CALL PROFE (HELP,TI0(IPLS),TI1(IPLS),TI2(IPLS),
     .                   TI4(IPLS),TI5(IPLS),TVAC)
        TIIN(IPLS,1:NR1ST)=HELP(1:NR1ST)
        GOTO 120
113     CALL PROFS (HELP,TI0(IPLS),TI1(IPLS),TI5(IPLS),TVAC)
        TIIN(IPLS,1:NR1ST)=HELP(1:NR1ST)
        GOTO 120
c  INDPRO=4:  read from stream TIO(IPLS)
114     CONTINUE
        ISTREAM=TI0(IPLS)
        ITALI=2
        CALL READTL(TXTPLS(IPLS,ITALI),TXTPSP(IPLS,ITALI),
     .              TXTPUN(IPLS,ITALI),
     .              HELP,NR1ST,NP2ND,NT3RD,NBMLT,NSBOX,
     .              3,ISTREAM)
        TIIN(IPLS,1:NSBOX)=HELP(1:NSBOX)
        GOTO 120
115     CALL PROUSR (HELP,1+0*NPLS,TI0(IPLS),TI1(IPLS),TI2(IPLS),
     .                      TI3(IPLS),TI4(IPLS),TI5(IPLS),TVAC,NSURF)
        TIIN(IPLS,1:NSURF)=HELP(1:NSURF)
        GOTO 120
120     CONTINUE
        GOTO 1120
116     CALL PROFR (TIIN,1+0*NPLS,NPLSTI,NPLSTI,NSURF)
        GOTO 1120
117     CALL PROFR (TIIN,1+0*NPLS,NPLSTI,NPLSTI,NSBOX)
        GOTO 1120
1120  CONTINUE



C  ION DENSITY
      IND=INDPRO(3)
      DO 130 IPLS=1,NPLSI
        IF (LEN_TRIM(CDENMODEL(IPLS)) > 0) CYCLE
        GOTO (121,122,123,124,125,126,127,130,130),IND
121     CALL PROFN (HELP,DI0(IPLS),DI1(IPLS),DI2(IPLS),
     .                   DI3(IPLS),DI4(IPLS),DI5(IPLS),DVAC)
        DIIN(IPLS,1:NR1ST)=HELP(1:NR1ST)
        GOTO 130
122     CALL PROFE (HELP,DI0(IPLS),DI1(IPLS),DI2(IPLS),
     .                   DI4(IPLS),DI5(IPLS),DVAC)
        DIIN(IPLS,1:NR1ST)=HELP(1:NR1ST)
        GOTO 130
123     CALL PROFS (HELP,DI0(IPLS),DI1(IPLS),DI5(IPLS),DVAC)
        DIIN(IPLS,1:NR1ST)=HELP(1:NR1ST)
        GOTO 130
c  INDPRO=4:  read from stream DIO(IPLS)
124     CONTINUE
        ISTREAM=DI0(IPLS)
        ITALI=4
        CALL READTL(TXTPLS(IPLS,ITALI),TXTPSP(IPLS,ITALI),
     .              TXTPUN(IPLS,ITALI),
     .              HELP,NR1ST,NP2ND,NT3RD,NBMLT,NSBOX,
     .              3,ISTREAM)
        DIIN(IPLS,1:NSBOX)=HELP(1:NSBOX)
        GOTO 130
125     CALL PROUSR (HELP,1+1*NPLS,DI0(IPLS),DI1(IPLS),DI2(IPLS),
     .                    DI3(IPLS),DI4(IPLS),DI5(IPLS),DVAC,NSURF)
        DIIN(IPLS,1:NSURF)=HELP(1:NSURF)
        GOTO 130
130     CONTINUE
        GOTO 1130
126     CALL PROFR (DIIN,1+0*NPLS+NPLSTI,NPLSI,NPLS,NSURF)
        GOTO 1130
127     CALL PROFR (DIIN,1+0*NPLS+NPLSTI,NPLSI,NPLS,NSBOX)
        GOTO 1130
1130  CONTINUE



C  DRIFT VELOCITY
      IND=INDPRO(4)
      DO 140 IPLS=1,NPLSV
        GOTO (131,132,133,134,135,136,137,140,140),IND
131     CALL PROFN (HELP,VX0(IPLS),VX1(IPLS),VX2(IPLS),
     .                   VX3(IPLS),VX4(IPLS),VX5(IPLS),VVAC)
        VXIN(IPLS,1:NR1ST)=HELP(1:NR1ST)
        CALL PROFN (HELP,VY0(IPLS),VY1(IPLS),VY2(IPLS),
     .                   VY3(IPLS),VY4(IPLS),VY5(IPLS),VVAC)
        VYIN(IPLS,1:NR1ST)=HELP(1:NR1ST)
        CALL PROFN (HELP,VZ0(IPLS),VZ1(IPLS),VZ2(IPLS),
     .                   VZ3(IPLS),VZ4(IPLS),VZ5(IPLS),VVAC)
        VZIN(IPLS,1:NR1ST)=HELP(1:NR1ST)
        GOTO 140
132     CALL PROFE (HELP,VX0(IPLS),VX1(IPLS),VX2(IPLS),
     .                   VX4(IPLS),VX5(IPLS),VVAC)
        VXIN(IPLS,1:NR1ST)=HELP(1:NR1ST)
        CALL PROFE (HELP,VY0(IPLS),VY1(IPLS),VY2(IPLS),
     .                   VY4(IPLS),VY5(IPLS),VVAC)
        VYIN(IPLS,1:NR1ST)=HELP(1:NR1ST)
        CALL PROFE (HELP,VZ0(IPLS),VZ1(IPLS),VZ2(IPLS),
     .                   VZ4(IPLS),VZ5(IPLS),VVAC)
        VZIN(IPLS,1:NR1ST)=HELP(1:NR1ST)
        GOTO 140
133     CALL PROFS (HELP,VX0(IPLS),VX1(IPLS),VX5(IPLS),VVAC)
        VXIN(IPLS,1:NR1ST)=HELP(1:NR1ST)
        CALL PROFS (HELP,VY0(IPLS),VY1(IPLS),VY5(IPLS),VVAC)
        VYIN(IPLS,1:NR1ST)=HELP(1:NR1ST)
        CALL PROFS (HELP,VZ0(IPLS),VZ1(IPLS),VZ5(IPLS),VVAC)
        VZIN(IPLS,1:NR1ST)=HELP(1:NR1ST)
        GOTO 140
C  INDPRO=4 NOT IN USE
134     CONTINUE
        GOTO 140
135     CALL PROUSR (HELP,1+2*NPLS,VX0(IPLS),VX1(IPLS),VX2(IPLS),
     .                        VX3(IPLS),VX4(IPLS),VX5(IPLS),VVAC,NSURF)
        VXIN(IPLS,1:NSURF)=HELP(1:NSURF)
        CALL PROUSR (HELP,1+3*NPLS,VY0(IPLS),VY1(IPLS),VY2(IPLS),
     .                        VY3(IPLS),VY4(IPLS),VY5(IPLS),VVAC,NSURF)
        VYIN(IPLS,1:NSURF)=HELP(1:NSURF)
        CALL PROUSR (HELP,1+4*NPLS,VZ0(IPLS),VZ1(IPLS),VZ2(IPLS),
     .                        VZ3(IPLS),VZ4(IPLS),VZ5(IPLS),VVAC,NSURF)
        VZIN(IPLS,1:NSURF)=HELP(1:NSURF)
        GOTO 140
140   CONTINUE
C  SCALE FROM MACH NUMBER PROFILE TO CM/SEC PROFILE?
      IF (NLMACH) THEN
        DO 1141 IPLS=1,NPLSI
          IPLSTI=MPLSTI(IPLS)
          IPLSV=MPLSV(IPLS)
          DO 1142 ICELL=1,NSURF
            FACT=CVEL2A*SQRT((TIIN(IPLSTI,ICELL)+
     .                        TEIN(ICELL))/RMASSP(IPLS))
            VXIN(IPLSV,ICELL)=VXIN(IPLSV,ICELL)*FACT
            VYIN(IPLSV,ICELL)=VYIN(IPLSV,ICELL)*FACT
            VZIN(IPLSV,ICELL)=VZIN(IPLSV,ICELL)*FACT
1142      CONTINUE
1141    CONTINUE
      ENDIF
      GOTO 1140
136   CALL PROFR (VXIN,1+1*NPLS+NPLSTI+0*NPLSV,NPLSV,NPLSV,NSURF)
      CALL PROFR (VYIN,1+1*NPLS+NPLSTI+1*NPLSV,NPLSV,NPLSV,NSURF)
      CALL PROFR (VZIN,1+1*NPLS+NPLSTI+2*NPLSV,NPLSV,NPLSV,NSURF)
      GOTO 1140
137   CALL PROFR (VXIN,1+1*NPLS+NPLSTI+0*NPLSV,NPLSV,NPLSV,NSBOX)
      CALL PROFR (VYIN,1+1*NPLS+NPLSTI+1*NPLSV,NPLSV,NPLSV,NSBOX)
      CALL PROFR (VZIN,1+1*NPLS+NPLSTI+2*NPLSV,NPLSV,NPLSV,NSBOX)
      GOTO 1140
1140  CONTINUE
C
C
C  MAGNETIC FIELD UNIT VECTOR
C  FOR IND=5,6,7 OR 9: ALSO THE ABSOLUTE B-FIELD STRENGTH BF CAN BE SET
      IND=INDPRO(5)
C  DEFAULT: BFIELD IN Z-DIRECTION, IE., PITCH=0
      IF (IND /= 9) THEN
      DO J=1,NSBOX
        BXIN(J)=0.
        BYIN(J)=0.
        BZIN(J)=1.
      END DO
      END IF
      GOTO (141,142,143,144,145,146,147,150,150),IND
C  HELP IS FIELD LINE PITCH ANGLE: B_POL/B_TOT
141     CALL PROFN (HELP,B0,B1,B2,B3,B4,B5,BVAC)
        GOTO 1400
142     CALL PROFE (HELP,B0,B1,B2,B4,B5,BVAC)
        GOTO 1400
143     CALL PROFS (HELP,B0,B1,B5,BVAC)
        GOTO 1400
C  INDPRO=4: read from stream B0:  NOT IN USE
144     CONTINUE
        GOTO 150
C  CONVERT PITCH ANGLE INTO B-FIELD UNIT VECTOR
1400    CONTINUE
        IF (LEVGEO.EQ.1) THEN
          DO 1401 J=1,NSURF
            CALL NCELLN(J,IR,IP,IT,IA,IB,
     .                  NR1ST,NP2ND,NT3RD,NBMLT,NLRAD,NLPOL,NLTOR)
            IF (IR.GE.NR1ST) GOTO 1401
            IF ((NP2ND.GT.1).AND.(IP.GE.NP2ND)) GOTO 1401
            BXIN(J)=0.0
            BYIN(J)=HELP(IR)
            BZIN(J)=SQRT(1.-HELP(IR)*HELP(IR))
1401      CONTINUE
        ELSEIF (LEVGEO.EQ.2.AND.NLPOL) THEN
          DO 1402 J=1,NSURF
            CALL NCELLN(J,IR,IP,IT,IA,IB,
     .                  NR1ST,NP2ND,NT3RD,NBMLT,NLRAD,NLPOL,NLTOR)
            IF (IR.GE.NR1ST) GOTO 1402
            IF ((NP2ND.GT.1).AND.(IP.GE.NP2ND)) GOTO 1402
            EP=0.5*(EP1(IR)+EP1(IR+1))
            EL=0.5*(ELL(IR)+ELL(IR+1))
            JJ=IR+(IP-1)*NR1ST
            PUY= XCOM(JJ)-EP
            PUX=-YCOM(JJ)/EL/EL
            PN=SQRT(PUX*PUX+PUY*PUY+EPS60)
            BXIN(J)=HELP(IR)*PUX/PN
            BYIN(J)=HELP(IR)*PUY/PN
            BZIN(J)=SQRT(1.-HELP(IR)*HELP(IR))
1402      CONTINUE
        ELSEIF (LEVGEO.EQ.3.AND.NLPOL) THEN
          DO 1403 J=1,NSURF
            CALL NCELLN(J,IR,IP,IT,IA,IB,
     .                  NR1ST,NP2ND,NT3RD,NBMLT,NLRAD,NLPOL,NLTOR)
            IF (IR.GE.NR1ST) GOTO 1403
            IF ((NP2ND.GT.1).AND.(IP.GE.NP2ND)) GOTO 1403
            PUX=VPLX(IR,IP)+VPLX(IR+1,IP)
            PUY=VPLY(IR,IP)+VPLY(IR+1,IP)
            PN=SQRT(PUX*PUX+PUY*PUY+EPS60)
            BXIN(J)=HELP(IR)*PUX/PN
            BYIN(J)=HELP(IR)*PUY/PN
            BZIN(J)=SQRT(1.-HELP(IR)*HELP(IR))
1403      CONTINUE
        ELSE
          CALL LEER(1)
          WRITE (iunout,*) 
     .      'DEFAULT MAGNETIC FIELD (IN Z-DIRECTION) IS USED '
          CALL LEER(1)
        ENDIF
        GOTO 150
c  INDPRO=5:  call prousr
145     CONTINUE
        CALL PROUSR (BXIN,1+5*NPLS,B0,B1,B2,B3,B4,B5,0._DP,NSURF)
        CALL PROUSR (BYIN,2+5*NPLS,B0,B1,B2,B3,B4,B5,0._DP,NSURF)
        CALL PROUSR (BZIN,3+5*NPLS,B0,B1,B2,B3,B4,B5,1._DP,NSURF)
        CALL PROUSR (BFIN,4+5*NPLS,B0,B1,B2,B3,B4,B5,1._DP,NSURF)
        GOTO 150
c  INDPRO=6:  call profr (information comes from interfacing code)
c             default (vaccum) parameters in additional cells
146     CALL PROFR (BXIN,1+1*NPLS+NPLSTI+3*NPLSV,1,1,NSURF)
        CALL PROFR (BYIN,2+1*NPLS+NPLSTI+3*NPLSV,1,1,NSURF)
        CALL PROFR (BZIN,3+1*NPLS+NPLSTI+3*NPLSV,1,1,NSURF)
        CALL PROFR (BFIN,4+1*NPLS+NPLSTI+3*NPLSV,1,1,NSURF)
        GOTO 150
c  INDPRO=7:  call profr (information comes from interfacing code)
c             include also additional cells
147     CALL PROFR (BXIN,1+1*NPLS+NPLSTI+3*NPLSV,1,1,NSBOX)
        CALL PROFR (BYIN,2+1*NPLS+NPLSTI+3*NPLSV,1,1,NSBOX)
        CALL PROFR (BZIN,3+1*NPLS+NPLSTI+3*NPLSV,1,1,NSBOX)
        CALL PROFR (BFIN,4+1*NPLS+NPLSTI+3*NPLSV,1,1,NSBOX)
        GOTO 150
150   CONTINUE
C
C  CHECK FOR ZERO MAGNETIC FIELD IN ANY CELL (INCL. ADD. CELL REGION)
      DO 153 JJ=1,NSBOX
        IF (BXIN(JJ)**2+BYIN(JJ)**2+BZIN(JJ)**2.LE.EPS30) THEN
          WRITE (iunout,*) 'ZERO B-FIELD IN STANDARD CELL JJ= ',JJ
          CALL EXIT_OWN(1)
        ENDIF
        B=SQRT(BXIN(JJ)**2+BYIN(JJ)**2+BZIN(JJ)**2)
        IF (ABS(B-1.D0).GT.EPS12) THEN
          WRITE (iunout,*) 'B-FIELD IN STANDARD CELL JJ= ',JJ,B
          CALL EXIT_OWN(1)
        ENDIF
153   CONTINUE
C
C  ADDITIONAL INPUT TALLIES
      IND=INDPRO(6)
      DO 160 K=1,NAINI
        GOTO (151,151,151,151,155,156,157,160,160),IND
C  DEFAULT: ZERO
151     CONTINUE
        DO 1151 J=1,NR1ST
          ADIN(K,J)=0.
1151    CONTINUE
        GOTO 160
155     CALL PROUSR (HELP,6+1*NPLS+NPLSTI+3*NPLSV,
     .               BD,BD,BD,BD,BD,BD,0._DP,NSURF)
!pb        CALL RESETP (ADIN,HELP,K,1,NAIN,NSURF)
        ADIN(K,1:NSURF)=HELP(1:NSURF)
        GOTO 160
160   CONTINUE
      GOTO 1160
156   CALL PROFR (ADIN,6+1*NPLS+NPLSTI+3*NPLSV,NAINI,NAIN,NSURF)
      GOTO 1160
157   CALL PROFR (ADIN,6+1*NPLS+NPLSTI+3*NPLSV,NAINI,NAIN,NSBOX)
      GOTO 1160
1160  CONTINUE
C
C
C   SET VACUUM DATA IN ADDITIONAL REGIONS OUTSIDE THE
C   THE STANDARD MESH
C
      IF (INDPRO(1).LE.6 .OR. INDPRO(1).EQ.9) THEN
        DO J=NSURF+1,NSURF+NRADD
          TEIN(J)=TVAC
        ENDDO
      ENDIF
      IF (INDPRO(2).LE.6 .OR. INDPRO(2).EQ.9) THEN
        DO J=NSURF+1,NSURF+NRADD
          DO 17 IPLS=1,NPLSI
            IPLSTI=MPLSTI(IPLS)
            TIIN(IPLSTI,J)=TVAC
17        CONTINUE
        ENDDO
      ENDIF
      IF (INDPRO(3).LE.6 .OR. INDPRO(3).EQ.9) THEN
        DO J=NSURF+1,NSURF+NRADD
          DO 18 IPLS=1,NPLSI
            DIIN(IPLS,J)=DVAC
18        CONTINUE
        ENDDO
      ENDIF
      IF (INDPRO(4).LE.6 .OR. INDPRO(4).EQ.9) THEN
        DO J=NSURF+1,NSURF+NRADD
          DO 19 IPLS=1,NPLSI
            IPLSV=MPLSV(IPLS)
            VXIN(IPLSV,J)=VVAC
            VYIN(IPLSV,J)=VVAC
            VZIN(IPLSV,J)=VVAC
19        CONTINUE
        ENDDO
      ENDIF
      IF (INDPRO(5).LE.6 .OR. INDPRO(5).EQ.9) THEN
        DO J=NSURF+1,NSURF+NRADD
          BXIN(J)=0.
          BYIN(J)=0.
          BZIN(J)=1.
        ENDDO
      ENDIF
      IF (INDPRO(6).LE.6 .OR. INDPRO(6).EQ.9) THEN
        DO J=NSURF+1,NSURF+NRADD
          DO 20 IAIN=1,NAINI
            ADIN(IAIN,J)=0.
20        CONTINUE
        ENDDO
      ENDIF

      DEALLOCATE(HELP)
C
      RETURN
      END
