#!/bin/ksh
if [ $# -lt 2 ]
then 
   echo "usage: $0 <input driver> <output driver>"
   exit 1
fi
echo
echo Running full 3D version
echo
#
# Set environment variables for ADAS
#
#export XLFRTEOPTS=namelist=old
export ADASCENT=/u/adas/adas
export DIVDIR=/u/progs/div4
export DIVEXEDIR=/u/progs/div4
export EQUDIR=/u/progs/div4/shots
#
cd /u/progs/lim
mkdir $1
cd $1
/u/progs/lim/limsrc/lim3O < /u/progs/lim/data/$1.dli > /u/progs/lim/results/$1.lim
echo Done LIM
mv fort.7 $1.dat 
mv fort.78 $1.dbg
mv fort.79 ../results/$1.ddl
mv $1.dbg ../results
cp $1.dat /u/progs/lim/results
#a2ps -nn $1.dat > $1.ps 
cp $1.ps /u/progs/lim/results
cp fort.9 /u/progs/lim/results/$1.inp
#
# slmod
#
cp fort.63 $1.pro
cp $1.pro ../results
cp fort.64 $1.slv
cp $1.slv ../results
cp fort.59 $1.rpr
cp $1.rpr ../results
cp $1.dbg ../results
echo Results moved
#
# slmod end
#
#/u/progs/lim/outsrc3D/out3O < /u/progs/lim/limout/$2.dlo > $1.out
#cp fort.7 /u/progs/lim/results/$1.dag
#cp fort.9 /u/progs/lim/results/$1.ing
#cp $1.out /u/progs/lim/results/$1.out
#
# To convert back to gnuplot - comment out the following line 
# and uncomment the rest.
#
#mv POSTSCPT.LIS /u/progs/lim/results/$1.psg
mv fort.8 /u/progs/lim/results/$1.raw
compress -f -v /u/progs/lim/results/$1.raw
cd /u/progs/lim
rm -r $1
#lp $1.ps
#lp $1.psi
#lp $1.psg
cd /u/progs/lim



