C
      SUBROUTINE TORCOL(*)

C  PARTICLE ON TOROIDAL PERIODICITY SURFACE MTSURF, FLIGHT INTO CELL NNTCLL
C  RETURN 1:  NO SURFACE TALLIES, FLIGHT CONTINUES

      USE PRECISION
      USE PARMMOD
      USE CCONA
      USE CLOGAU
      USE CUPD
      USE CGRID
      USE COMPRT
      USE CLGIN
      USE CFPLK

      IMPLICIT NONE

      REAL(DP) :: VELX_OLD, SINROT,COSROT
      INTEGER :: LEARC1, ISTS, NN, IPERID_OLD
C
      TIME=TIME+ZT/VEL
C
      IF (NINCZ.EQ.0) THEN
        WRITE (iunout,*) 'ERROR IN TORCOL, NINCZ ?  '
        WRITE (iunout,*) 'NINCZ ',NINCZ
        CALL EXIT_OWN(1)
      ENDIF
C
C
      IF (ITYP.LE.2) THEN
C  ANGLE FOR ROTATION IS 2*ALPHA
        COSROT=COSAL
        SINROT=SINAL*FLOAT(NINCZ)
        VELX_OLD=VELX
        VELX= VELX_OLD*COSROT +VELZ*SINROT
        VELZ=-VELX_OLD*SINROT +VELZ*COSROT
      ENDIF
C  ADVANCE TO NEXT TOROIDAL CELL
      X0=X01-RMTOR
      Y0=Y0+ZT*VELY
      Z01=-Z01
      Z0=Z01
C
      NLSRFX=.FALSE.
      NLSRFZ=.FALSE.
      NLSRFZ=.TRUE.
      IPERID=NNTCLL
C
      IF (LEVGEO.EQ.3.OR.(LEVGEO.EQ.2.AND.NLPOL)) THEN
        IF (NRCELL.GT.0)
     .  NN=LEARC1(X0,Y0,Z0,IPOLG,NRCELL,NRCELL,.FALSE.,.FALSE.,
     .                           NPANU,'TORCOL 1')
      ENDIF
C
      IF (NLTRC) CALL CHCTRC(X0,Y0,Z0,16,11)
C
      IF (.NOT.NLTOR) THEN
C
        MSURF=0
        colflag = .true.
        RETURN 1
      ELSE
C
C  NLTOR=TRUE:
C
        MSURF=0
        IF (NRCELL.GT.0) NTCELL=NNTCLL
        ISTS=INMP3I(IRCELL,IPCELL,MTSURF)
        IF (ISTS.EQ.0) RETURN 1
        ZT=0.
        RETURN
      ENDIF
C
997   CONTINUE
      END
