 
 
 
      SUBROUTINE EIRENE_ELLIPSOID
     .  (X0,Y0,Z0,CX,CY,CZ,XLIMS1,YLIMS1,ZLIMS1,
     .                      XLIMS2,YLIMS2,ZLIMS2,RLB,ILCOL,NX,NY,NZ)
 
      USE EIRMOD_PRECISION
      USE EIRMOD_CCONA
 
      IMPLICIT NONE
 
      REAL(DP), INTENT(IN) :: X0, Y0, Z0, CX, CY, CZ, XLIMS1, YLIMS1,
     .                      ZLIMS1, XLIMS2, YLIMS2, ZLIMS2, RLB
      INTEGER, INTENT(IN) :: ILCOL, NX, NY, NZ
 
      RETURN
      END
