      SUBROUTINE BROADCAST
      IMPLICIT NONE
      RETURN
      END

!      SUBROUTINE BROAD_USR
!      IMPLICIT NONE
!      RETURN
!      END

      SUBROUTINE BROAD_IESTR(IESTR)
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: IESTR
      RETURN
      END

      SUBROUTINE BROADREF
      IMPLICIT NONE
      RETURN
      END

      SUBROUTINE CALSTR
      IMPLICIT NONE
      RETURN
      END

      SUBROUTINE COLSUM
      IMPLICIT NONE
      RETURN
      END

      SUBROUTINE MPI_BARRIER (MPI_COM,IER)
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: MPI_COM
      INTEGER, INTENT(OUT) :: IER
      IER=0
      RETURN
      END

      SUBROUTINE MPI_COMM_RANK (MPI_COM,MY_PE,IER)
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: MPI_COM
      INTEGER, INTENT(OUT) :: MY_PE, IER
      MY_PE=0
      IER=0
      RETURN
      END

      SUBROUTINE MPI_COMM_SIZE (MPI_COM,NPRS,IER)
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: MPI_COM
      INTEGER, INTENT(OUT) :: NPRS, IER
      NPRS=1
      IER=0
      RETURN
      END

      SUBROUTINE MPI_FINALIZE (IER)
      IMPLICIT NONE
      INTEGER, INTENT(OUT) :: IER
      IER=0
      RETURN
      END

      SUBROUTINE MPI_INIT (IER)
      IMPLICIT NONE
      INTEGER, INTENT(OUT) :: IER
      IER=0
      RETURN
      END
