C
C
      SUBROUTINE XSECTP_PARAM

      USE PRECISION
      USE PARMMOD
      USE COMUSR
      USE CCONA
      USE CGRID
      USE CZT1
      USE CTRCEI
      USE CTEXT
      USE COMXS
      USE CSPEI

      IMPLICIT NONE

      INTEGER :: NRC, IATM, IPLS, KK
C
C
C   RECOMBINATION
C
      DO 1000 IPLS=1,NPLSI
C
        IF (NRCP(IPLS).EQ.0) THEN
C
          IF (NCHARP(IPLS).EQ.1.AND.NCHRGP(IPLS).EQ.1) THEN
C
C  DEFAULT HYDROGENIC RECOMBINATION MODEL
C  HYDR. RECOMBINATION RATE-COEFFICIENT (1/S/CCM) E + H+ --> H + RAD.
C  GORDEEV ET. AL., PIS'MA ZH. EHKSP. TEOR. FIZ. 25 (1977) 223.
C
            DO 52 IATM=1,NATMI
              IF (NMASSP(IPLS).EQ.NMASSA(IATM).AND.
     .                            NCHRGP(IPLS).EQ.1) THEN
C
                NREC=NREC+1
              ENDIF
52          CONTINUE
C
          ENDIF
C
C  NON DEFAULT MODEL:  240--
C
        ELSEIF (NRCP(IPLS).GT.0) THEN
          DO 82 NRC=1,NRCP(IPLS)
            KK=IREACP(IPLS,NRC)
            IF ((ISWR(KK).NE.6) .AND. (ISWR(KK).NE.7)) GOTO 82
C
C  RECOMBINATION MODEL FOR BULK IONS
            NREC=NREC+1
C
82        CONTINUE
C
C  NO MODEL DEFINED
        ELSE
        ENDIF
C
C
1000  CONTINUE
C
      RETURN
C
      END
