C
      SUBROUTINE REFANG (COSP,COSM,CRTXR,CRTYR,CRTZR,NMODEL,SNORM)
C
C   ANGLE OF REFLECTION, GAUSSIAN, COSINE LIKE, SPECULAR OR MIXED
C   THIS ROUTINE IS USED FOR SPECIAL ANGULAR SOURCE DISTRIBUTIONS
C   FOR PRIMARY SOURCE PARTICLES (CALLED FROM SUBR. LOCATE)
C   INPUT : VELX,VELY,VELZ VIA COMPRT
C           CRTX,CRTY,CRTZ VIA COMPRT
C           COSP:
C           COSM:
C           CRTXR,CRTYR,CRTZR: MODIFIED SURFACE NORMAL VECTOR
C   OUTPUT: VELX,VELY,VELZ VIA COMPRT, AND VELX_MEAN,....,VELZ_MEAN
C
      USE PRECISION
      USE PARMMOD
      USE CCONA
      USE CRAND
      USE COMPRT

      IMPLICIT NONE

      REAL(DP), INTENT(IN) :: COSP, COSM, CRTXR, CRTYR, CRTZR, SNORM
      INTEGER, INTENT(IN) :: NMODEL
      REAL(DP) :: A, ZCPHI, ZCTHET, ZSTHET, VX, VY, VZ, ZPHI,
     .            ZTHET, CRTXL, CRTYL, CRTZL, COSIN, ZSPHI
      REAL(DP), EXTERNAL :: RANF_EIRENE
      INTEGER :: ICOUNT

      CRTXL=CRTXR
      CRTYL=CRTYR
      CRTZL=CRTZR
      IF (SNORM.GE.EPS10) THEN
        COSIN=CRTXL*VELX+CRTYL*VELY+CRTZL*VELZ
      ELSE
        COSIN=CRTX*VELX+CRTY*VELY+CRTZ*VELZ
        CRTXL=CRTX
        CRTYL=CRTY
        CRTZL=CRTZ
      ENDIF
C   AZIMUTAL ANGLE: EQUIDISTRIBUTION
      ZTHET=PI2A*RANF_EIRENE( )
      ZSTHET=SIN(ZTHET)
      ZCTHET=COS(ZTHET)
C
      IF (NMODEL.EQ.1) THEN
C   POLAR ANGLE: MODIFIED COSINE WITH CUT OFF COSM
        A=RANF_EIRENE( )
        ZCPHI=(1.-A*COSM)**COSP
      ELSE
C   POLAR ANGLE: FROM GAUSSIAN WITH CUT OFF COSM
        ICOUNT=0
410     IF (INIV2.EQ.0) CALL FGAUSS
        ZPHI=COSP*FG1(INIV2)
        INIV2=INIV2-1
        ICOUNT=ICOUNT+1
C   CUT OFF ANGLE: COSM (RADIANS)
        IF (ICOUNT.GT.1000) THEN
          WRITE (iunout,*) 'WARNING FROM REFANG: ICOUNT=1000 '
          GOTO 420
        ENDIF
        IF (ABS(ZPHI).GT.COSM) GOTO 410
420     ZCPHI=COS(ZPHI)
      ENDIF
C
      ZSPHI=SQRT(1.-ZCPHI*ZCPHI)
C
C  NO SPECULAR CONTRIBUTION IN MODIFIED COSINE
      VX=-ZCPHI
      VY=ZSPHI*ZCTHET
      VZ=ZSPHI*ZSTHET
C
      IF (ABS(COSIN).LT.EPS10) THEN
C  NO SPECIFIED DIRECTION, EG. POINT ISOTROPIC SOURCE
        VELX=VX
        VELY=VY
        VELZ=VZ
      ELSE
C  ROTATE, TO ACCOUNT FOR SURFACE NORMAL VECTOR CRTXL,CRTYL,CRTZL
        CALL ROTATF (VELX,VELY,VELZ,VX,VY,VZ,CRTXL,CRTYL,CRTZL)
      ENDIF
C
      VELX_MEAN=VELX
      VELY_MEAN=VELY
      VELZ_MEAN=VELZ
C
      RETURN
      END
