      MODULE CSPEI

      USE PRECISION
      USE PARMMOD

      IMPLICIT NONE

      PRIVATE

      PUBLIC :: ALLOC_CSPEI, DEALLOC_CSPEI, INIT_CSPEI,
     P          ALLOC_BCKGRND, DEALLOC_BCKGRND, INIT_BCKGRND

      REAL(DP), PUBLIC, TARGET, ALLOCATABLE, SAVE ::
     R  SMESTV(:,:), SMESTS(:,:)

      REAL(DP), PUBLIC, ALLOCATABLE, SAVE ::
     R  STV(:,:), STVW(:,:), STVC(:,:,:),
     R  STVS(:),  STVWS(:),  STVCS(:,:)

      REAL(DP), PUBLIC, ALLOCATABLE, SAVE ::
     R  EE(:,:),    FF(:,:),
     R  EES(:),     FFS(:),
     R  SDVIA(:,:), SDVIAW(:,:), SDVIAC(:,:,:)

      REAL(DP), PUBLIC, TARGET, ALLOCATABLE, SAVE ::
     R  PLASMA_BCKGRND(:,:)

      REAL(DP), PUBLIC, POINTER, SAVE ::
     .  TEINTF(:),   TIINTF(:,:), DIINTF(:,:),
     .  VXINTF(:,:), VYINTF(:,:), VZINTF(:,:),
     .  BXINTF(:),   BYINTF(:),   BZINTF(:),   BFINTF(:),
     .  VLINTF(:),   ADINTF(:,:)

      INTEGER, PUBLIC, SAVE :: IESTR

      INTEGER, PUBLIC, SAVE ::
     I  NIDC, NIDV, NIDS


      CONTAINS


      SUBROUTINE ALLOC_CSPEI

      IF (ALLOCATED(SMESTV)) RETURN

      IF (NSMSTRA > 0) THEN
        NIDV=NVOLTL
        NIDS=NSRFTL
      ELSE
        NIDV=1
        NIDS=1
      END IF

      ALLOCATE (SMESTV(NIDV,NRTAL))
      ALLOCATE (SMESTS(NIDS,NLMPGS))

      ALLOCATE (STV(NSD,NRTAL))
      ALLOCATE (STVW(NSDW,NLIMPS))
      ALLOCATE (STVC(0:2,NCV,NRTAL))
      ALLOCATE (STVS(NSD))
      ALLOCATE (STVWS(NSDW))
      ALLOCATE (STVCS(0:2,NCV))
      ALLOCATE (EE(NSD,NRTAL))
      ALLOCATE (FF(NSDW,NLIMPS))
      ALLOCATE (EES(NSD))
      ALLOCATE (FFS(NSDW))
      ALLOCATE (SDVIA(NSD,NRTAL))
      ALLOCATE (SDVIAW(NSDW,NLIMPS))
      ALLOCATE (SDVIAC(2,NCV,NRTAL))

      WRITE (55,'(A,T25,I15)')
     .       ' CSPEI ',(NIDV*NRTAL+(3*NSD+5*NCV)*NRTAL +
     .                  NIDS*NLMPGS + 3*NSDW*NLIMPS + 2*NSD +
     .                  2*NSDW + 3*NCV)*8

      CALL INIT_CSPEI

      RETURN
      END SUBROUTINE ALLOC_CSPEI


      SUBROUTINE DEALLOC_CSPEI

      IF (.NOT.ALLOCATED(SMESTV)) RETURN

      DEALLOCATE (SMESTV)
      DEALLOCATE (SMESTS)

      DEALLOCATE (STV)
      DEALLOCATE (STVW)
      DEALLOCATE (STVC)
      DEALLOCATE (STVS)
      DEALLOCATE (STVWS)
      DEALLOCATE (STVCS)
      DEALLOCATE (EE)
      DEALLOCATE (FF)
      DEALLOCATE (EES)
      DEALLOCATE (FFS)
      DEALLOCATE (SDVIA)
      DEALLOCATE (SDVIAW)
      DEALLOCATE (SDVIAC)

      RETURN
      END SUBROUTINE DEALLOC_CSPEI


      SUBROUTINE INIT_CSPEI

      SMESTV = 0._DP
      SMESTS = 0._DP

      STV    = 0._DP
      STVW   = 0._DP
      STVC   = 0._DP
      STVS   = 0._DP
      STVWS  = 0._DP
      STVCS  = 0._DP
      EE     = 0._DP
      FF     = 0._DP
      EES    = 0._DP
      FFS    = 0._DP
      SDVIA  = 0._DP
      SDVIAW = 0._DP
      SDVIAC = 0._DP

      RETURN
      END SUBROUTINE INIT_CSPEI


      SUBROUTINE ALLOC_BCKGRND

c      NIDC=1*NPLS+NAIN+6+NPLSTI+3*NPLSV ! bug, SL, 31.12.2018
      NIDC=1*NPLS+NAIN+6+NPLSTI+4*NPLSV

      IF (.NOT.ALLOCATED(PLASMA_BCKGRND)) THEN

        ALLOCATE(PLASMA_BCKGRND(NIDC,NRAD))

        TEINTF => PLASMA_BCKGRND(1+0+0*NPLS             , :)
        TIINTF => PLASMA_BCKGRND(1+1+0*NPLS        :
     .                           1+0+0*NPLS+NPLSTI, :)
        DIINTF => PLASMA_BCKGRND(1+1+0*NPLS+NPLSTI :
     .                           1+0+1*NPLS+NPLSTI, :)
        VXINTF => PLASMA_BCKGRND(1+1+1*NPLS+NPLSTI+0*NPLSV :
     .                           1+0+1*NPLS+NPLSTI+1*NPLSV, :)
        VYINTF => PLASMA_BCKGRND(1+1+1*NPLS+NPLSTI+1*NPLSV :
     .                           1+0+1*NPLS+NPLSTI+2*NPLSV, :)
        VZINTF => PLASMA_BCKGRND(1+1+1*NPLS+NPLSTI+2*NPLSV :
     .                           1+0+1*NPLS+NPLSTI+3*NPLSV, :)
        BXINTF => PLASMA_BCKGRND(1+1+1*NPLS+NPLSTI+3*NPLSV, :)
        BYINTF => PLASMA_BCKGRND(1+2+1*NPLS+NPLSTI+3*NPLSV, :)
        BZINTF => PLASMA_BCKGRND(1+3+1*NPLS+NPLSTI+3*NPLSV, :)
        BFINTF => PLASMA_BCKGRND(1+4+1*NPLS+NPLSTI+3*NPLSV, :)
        VLINTF => PLASMA_BCKGRND(1+5+1*NPLS+NPLSTI+3*NPLSV, :)
        ADINTF => PLASMA_BCKGRND(1+6+1*NPLS+NPLSTI+3*NPLSV :
     .                             6+1*NPLS+NPLSTI+4*NPLSV+NAIN, :)

        CALL INIT_BCKGRND

      END IF

      RETURN
      END SUBROUTINE ALLOC_BCKGRND


      SUBROUTINE DEALLOC_BCKGRND

      IF (ALLOCATED(PLASMA_BCKGRND)) DEALLOCATE(PLASMA_BCKGRND)

      NULLIFY(TEINTF)
      NULLIFY(TIINTF)
      NULLIFY(DIINTF)
      NULLIFY(VXINTF)
      NULLIFY(VYINTF)
      NULLIFY(VZINTF)
      NULLIFY(BXINTF)
      NULLIFY(BYINTF)
      NULLIFY(BZINTF)
      NULLIFY(BFINTF)
      NULLIFY(VLINTF)
      NULLIFY(ADINTF)

      RETURN
      END SUBROUTINE DEALLOC_BCKGRND


      SUBROUTINE INIT_BCKGRND

      PLASMA_BCKGRND = 0._DP

      RETURN
      END SUBROUTINE INIT_BCKGRND

      END MODULE CSPEI


