C
C
      SUBROUTINE SIGCX(IFIRST,JJJ,ZDS,PEN,PSIG,TIMAX,ARGST)
C
C  INPUT:
C          IFIRST: FLAG FOR INITIALISATION
C          NCELL:  INDEX IN TALLY ARRAYS FOR CURRENT ZONE
C          JJJ:    INDEX OF SEGMENT ALONG CHORD
C          ZDS:    LENGTH OF SEGMENT NO. JJJ
C          PEN:    ENERGY (EV) AT WHICH CX FLUXES ARE TO BE EVALUATED
C  OUTPUT: CONTRIB. FROM CELL NCELL AND CHORD SEGMENT JJJ TO:
C          THE CX FLUX PSIG(IATM),IATM=0,NATMI OF ENERGY PEN (EV)
C          THE MAX. ION TEMP. TIMAX ALONG LINE OF SIGHT
C          THE INTEGRANT ARGST SUCH THAT INTEGR.(ARGST*DL) = PSIG
C
      USE PRECISION
      USE PARMMOD
      USE COMUSR
      USE CESTIM
      USE CADGEO
      USE CCONA
      USE CLOGAU
      USE CUPD
      USE COMSIG
      USE CGRID
      USE CZT1
      USE CTRCEI
      USE CGEOM
      USE COMPRT
      USE CLGIN
      USE COMXS
      USE CSPEI

      IMPLICIT NONE

      INTEGER, INTENT(IN) :: IFIRST, JJJ
      REAL(DP), INTENT(IN) :: ZDS, PEN
      REAL(DP), INTENT(IN OUT) :: PSIG(0:NSPZ+2), TIMAX
      REAL(DP), INTENT(OUT) :: ARGST(0:NSPZ+2,NRAD)
      REAL(DP), ALLOCATABLE, SAVE :: ZARG2(:), ZARG3(:)
      REAL(DP) :: ZLAMB(0:NATM), 
     .          SIGTTT(0:NATM,NPLS), CFLAG(7,3)
      REAL(DP) :: ELAB, CXS, CXRATE, CROSS, PVELQ0, ZNI, HEB, VREL, 
     .          VRELQ, ZEXP2, ATTENU, ZEXP3, SIGADD, ARGU, ZEXP1, 
     .          ZMAX, VXS, VYS, VZS, ZTII, ZARG1, ZTI32, FPATHA, ZTI, 
     .          TTARG
      INTEGER :: IREAC, IAT, NCELC, ICELL, IRCX, IACX, IPLSTI
C
!pb      SAVE
      DATA ZMAX/40./

      IF (IFIRST.EQ.0) THEN
        ALLOCATE (ZARG2(0:NATM))
        ALLOCATE (ZARG3(0:NATM))
        TIMAX=0.
        DO 100 IATM=0,NATMI
          PSIG(IATM)=0.
          ZARG2(IATM)=0.
          ZARG3(IATM)=0.
          DO 101 ICELL=1,NSBOX
            ARGST(IATM,ICELL)=0.
101       CONTINUE
100     CONTINUE
      ELSE
C
C  MEAN FREE PATH LENGTH FOR ATTENUATION FACTOR
C  IONS IPLS WITH  (SHIFTED, VXIN,VYIN,VZIN) MAXWELLIAN
C  AT KT=TIIN(IPLS,NCELL),
C  ALL SPECIES IN PLASMA
C  ELECTRONS WITH  MAXWELLIAN AT KT=TEIN(NCELL),
C  MONOENERGETIC NEUTRAL BEAM, VELOCITY VEL (CM/SEC), SPECIES IATM
C  WITH SPEED UNIT VECTOR (-VELX,-VELY,-VELZ)
C
        ncelc=ncltal(ncell)

        DO 200 IATM=1,NATMI
          VEL=SQRT(PEN/RMASSA(IATM))*CVELAA
          VXS=VELX
          VYS=VELY
          VZS=VELZ
          VELX=-VELX
          VELY=-VELY
          VELZ=-VELZ
          ZLAMB(IATM)=FPATHA(NCELL,CFLAG)
          VELX=VXS
          VELY=VYS
          VELZ=VZS
200     CONTINUE
C
C  CX-COLLISION FREQUENCY (1/SEC)
C  MONOENERGETIC ION BEAM, ENERGY PEN (EV), SPEED UNIT VECTOR:
C  -(VELX,VELY,VELZ) AND SPECIES IPLS=1,NPLSI
C  NEUTRALS WITH MAXWELLIAN KT=2/3*EDENA/PDENA, SPECIES IATM=1,NATMI
C
        DO 300 IATM=0,NATMI
          DO 300 IPLS=1,NPLSI
            SIGTTT(IATM,IPLS)=0.
300     CONTINUE
C
        DO 311 IATM=1,NATMI
          IF (LGACX(IATM,0,0).EQ.0) GOTO 311
          IF (LGVAC(NCELL,0).OR.PDENA(IATM,NCELC).LE.0.) GOTO 311
C  DRIFTEN HIER NOCH NICHT DRIN, DAZU MITTLERE NEUTRAL DRIFTEN NOETIG
          TTARG=2./3.*EDENA(IATM,NCELC)/PDENA(IATM,NCELC)
          ZTI=TTARG*8./PIA*CVEL2A*CVEL2A
          DO 310 IACX=1,NACXI(IATM)
            IRCX=LGACX(IATM,IACX,0)
            IPLS=LGACX(IATM,IACX,1)
C
C  LOCAL ION TEMPERATURE
C
            IPLSTI = MPLSTI(IPLS)
            ZTII=TIIN(IPLSTI,NCELL)
            TIMAX=MAX(TIMAX,ZTII)
C
            ZTI32=1.0/(ZTII*SQRT(ZTII))
            ZARG1=PEN/ZTII
            ZEXP1=0.
            IF(ZARG1.LE.ZMAX) ZEXP1=EXP(-ZARG1)
            ZNI=(ZEXP1*ZTI32)
C
            VEL=SQRT(PEN/RMASSP(IPLS))*CVELAA
            PVELQ0=VEL*VEL
            HEB=LOG10(PVELQ0*CVELI2)
C
            VRELQ=ZTI/RMASSA(IATM)+PVELQ0
            VREL=SQRT(VRELQ)
C  STRICTLY: A BEAM (ION) MAXWELLIAN (NEUTRAL) RATE SHOULD BE COMPUTED
C  USE APPROXIMATION: <SIGMA V> APPROX SIGMA(V_EFF)*V_EFF
C  IS CX CROSS SECTION AVAILABLE ?
            IREAC=MODCOL(3,1,NSPH+IATM,IPLS)
            IF (IREAC.EQ.-1.OR.IREAC.GT.0) THEN
              ELAB=LOG(VRELQ)+DEFCX(IRCX)
              CXS=CROSS(ELAB,IREAC,IRCX,'SIGCX ')
              CXRATE=CXS*VREL
C
              SIGTTT(IATM,IPLS)=CXRATE*PDENA(IATM,NCELC)
            ELSE
              WRITE (6,*) 'CROSS SECTION NOT AVAILABLE IN SIGCX  '
            ENDIF
310       CONTINUE
C
311     CONTINUE
C
C  UP TO THIS POINT, IATM IS THE SPECIES INDEX OF THE ATOM GOING INTO
C  CX WITH BULK ION IPLS, AND SIGTTT(IATM,IPLS) IS THE CORRESPONDING RATE.
C  FOR THE SPECTRUM, NOW, THE ATOM SPECIES AFTER CX MATTERS (E.G.: H + D+ --> D + H+)
C  THEN, UP TO NOW, IATM WAS H, AND FROM NOW ON IT STANDS FOR D.
C
C  ATTENUATION FACTOR:
C  FOR ALL ATOMS WITH SPECIES INDEX IATM
        DO 400 IATM=1,NATMI
          ZARG3(IATM)=ZARG3(IATM)+ZARG2(IATM)
          ZARG2(IATM)=ZDS/ZLAMB(IATM)
          ZEXP2=0.0
          ZEXP3=0.0
          IF(ZARG2(IATM).LT.ZMAX) ZEXP2=EXP(-ZARG2(IATM))
          IF(ZARG3(IATM).LT.ZMAX) ZEXP3=EXP(-ZARG3(IATM))
          ATTENU=ZLAMB(IATM)*ZEXP3*(1-ZEXP2)
C
C  SOURCE-TERM FOR ATOMS IATM
C
C  1.) WEGEN CX  VON IONEN DER SPECIES IPLS MIT ATOMEN IAT=1,NATMI
C  2.) DIREKT  VON PRIMAERER QUELLE (Z.B.RECADD: REKOMBINATION)
C  3.) DIREKT  VON SEKUNDAERER QUELLE (Z.B. DURCH WANDREKOMBINATION
C                                           HIERHER GESTREUT)
C
          SIGADD=0.
CVL       SIGADD=RECADD(IATM,NCELL)
          DO 410 IPLS=1,NPLSI
C  IAT IS THAT ATOM SPECIES, WHICH RESULTS IN IATM AFTER CX WITH IPLS
C  FIND PRE-COLLISION ATOM INDEX IAT:
C           IAT=.....
C  THIS NEXT STATEMENT IS NOT CORRECT.
            IAT=IATM
            SIGADD=SIGTTT(IAT,IPLS)*DIIN(IPLS,NCELL)+SIGADD
410       CONTINUE
          ARGU=ZNI*SIGADD
          PSIG(IATM)=PSIG(IATM)+ARGU*ATTENU
          ARGST(IATM,JJJ)=ARGU*ZEXP3*SQRT(ZEXP2*PEN)/11.137
400     CONTINUE
C
      ENDIF
      RETURN
      END
