!pb  03.06.09  NCHORI --> NCHOR in if-condition as NCHORI is not yet broadcasted 
 
      SUBROUTINE EIRENE_ALLOCATE_MODULES
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      USE EIRMOD_CESTIM
      USE EIRMOD_CREFMOD
      USE EIRMOD_COMUSR
      USE EIRMOD_CADGEO
      USE EIRMOD_CAI
      USE EIRMOD_CCONA
      USE EIRMOD_CLOGAU
      USE EIRMOD_CINIT
      USE EIRMOD_COMSIG
      USE EIRMOD_CPOLYG
      USE EIRMOD_CGRID
      USE EIRMOD_CZT1
      USE EIRMOD_CTRCEI
      USE EIRMOD_CCOUPL
      USE EIRMOD_CGEOM
      USE EIRMOD_CSDVI
      USE EIRMOD_CSDVI_BGK
      USE EIRMOD_CSDVI_COP
      USE EIRMOD_CTETRA
      USE EIRMOD_COMPRT
      USE EIRMOD_CPES
      USE EIRMOD_COMNNL
      USE EIRMOD_COMSOU
      USE EIRMOD_CSTEP
      USE EIRMOD_COMSPL
      USE EIRMOD_CTEXT
      USE EIRMOD_CLGIN
      USE EIRMOD_COUTAU
      USE EIRMOD_COMXS
      USE EIRMOD_CTRIG
      USE EIRMOD_BRAEIR
      USE EIRMOD_EIRBRA
      USE EIRMOD_CLAST
      USE EIRMOD_CPLOT
      USE EIRMOD_CREF
      USE EIRMOD_CSPEI
      USE EIRMOD_CSPEZ
      USE EIRMOD_CUPD
      IMPLICIT NONE
 
      CALL EIRENE_ALLOC_CESTIM(1)
!pb      CALL ALLOC_CESTIM(2)
      CALL EIRENE_ALLOC_CREFMOD
      CALL EIRENE_ALLOC_COMUSR(1)
      CALL EIRENE_ALLOC_COMUSR(2)
      CALL EIRENE_ALLOC_COMUSR(3)
      CALL EIRENE_ALLOC_CADGEO
      CALL EIRENE_ALLOC_CAI
      CALL EIRENE_ALLOC_CCONA
      CALL EIRENE_ALLOC_CLOGAU
      CALL EIRENE_ALLOC_CINIT
!pb      IF (NCHORI > 0) CALL EIRENE_ALLOC_COMSIG
      IF (NCHOR > 0) CALL EIRENE_ALLOC_COMSIG
      CALL EIRENE_ALLOC_CPOLYG
      CALL EIRENE_ALLOC_CGRID
      CALL EIRENE_ALLOC_CZT1(1)
      CALL EIRENE_ALLOC_CZT1(2)
      CALL EIRENE_ALLOC_CTRCEI
      IF (NMODE .NE. 0) CALL EIRENE_ALLOC_CCOUPL(1)
      CALL EIRENE_ALLOC_CCOUPL(2)
      CALL EIRENE_ALLOC_CGEOM(1)
      CALL EIRENE_ALLOC_CGEOM(2)
      CALL EIRENE_ALLOC_CSDVI(1)
      CALL EIRENE_ALLOC_CSDVI(2)
      CALL EIRENE_ALLOC_CSDVI_BGK
      CALL EIRENE_ALLOC_CSDVI_COP
      CALL EIRENE_ALLOC_CTETRA
      CALL EIRENE_ALLOC_COMPRT
      CALL EIRENE_ALLOC_CPES
      CALL EIRENE_ALLOC_COMNNL
      CALL EIRENE_ALLOC_COMSOU(1)
      CALL EIRENE_ALLOC_COMSOU(2)
      CALL EIRENE_ALLOC_CSTEP
      CALL EIRENE_ALLOC_COMSPL
      CALL EIRENE_ALLOC_CTEXT(1)
      CALL EIRENE_ALLOC_CTEXT(2)
      CALL EIRENE_ALLOC_CLGIN
      CALL EIRENE_ALLOC_COUTAU
      CALL EIRENE_ALLOC_COMXS(1)
      CALL EIRENE_ALLOC_COMXS(2)
      CALL EIRENE_ALLOC_CTRIG
 
      CALL EIRENE_ALLOC_BRAEIR (NDX,NDY,NFL)
      CALL EIRENE_ALLOC_EIRBRA (NDX,NDY,NFL,NSTRA)
      CALL EIRENE_ALLOC_CLAST
      CALL EIRENE_ALLOC_CPLOT
      CALL EIRENE_ALLOC_CREF
      CALL EIRENE_ALLOC_CSPEI
      CALL EIRENE_ALLOC_CSPEZ
      CALL EIRENE_ALLOC_CUPD
 
!  allocate and initialize storage for trajectories
      IF (.NOT.ALLOCATED(TRAJ)) THEN
        ALLOCATE (TRAJ(NCHOR+NTRJ))
 
        DO ITRJ = 1, NCHOR+NTRJ
          ALLOCATE(TRAJ(ITRJ)%TRJ)
          TRAJ(ITRJ)%TRJ%NCOU_CELL = 0
          NULLIFY(TRAJ(ITRJ)%TRJ%CELLS)
        END DO
      END IF
 
      RETURN
      END SUBROUTINE EIRENE_ALLOCATE_MODULES
