 
 
      SUBROUTINE EIRENE_BROADSPUT(ES,M2M1,ETF,ETH,Q,N1,N2)
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      IMPLICIT NONE
 
      INCLUDE 'mpif.h'
      INTEGER, INTENT(IN):: N1, N2
      REAL(DP), INTENT(IN OUT) :: ES(N1), M2M1(N1,N2), ETF(N1,N2),
     .                            ETH(N1,N2), Q(N1,N2)
      INTEGER :: IER
 
      CALL MPI_BARRIER(MPI_COMM_WORLD,ier)
 
      CALL MPI_BCAST (ES,N1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (M2M1,N1*N2,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ETF,N1*N2,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ETH,N1*N2,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (Q,N1*N2,MPI_REAL8,0,MPI_COMM_WORLD,ier)
 
      CALL MPI_BARRIER(MPI_COMM_WORLD,ier)
 
      RETURN
      END SUBROUTINE EIRENE_BROADSPUT
