#!/bin/ksh
#
#
# Script file intended to set up a new account for a user of DIVIMP
#
# 

DIVSRC=/u/jde/divimp

DIVDIR=$HOME/divimp
DIVRES=$DIVDIR/results
DIVDAT=$DIVDIR/data
DIVSHOTS=$DIVDIR/shots

#
# Create directory tree if it does not exist
#

if [[ ! ( -d $DIVDIR ) ]] then
   mkdir $DIVDIR
fi

if [[ ! ( -d $DIVRES ) ]] then
   mkdir $DIVRES
fi

if [[ ! ( -d $DIVDAT ) ]] then
   mkdir $DIVDAT
fi

if [[ ! ( -d $DIVSHOTS ) ]] then
   mkdir $DIVSHOTS
fi

#
# Copy USER run scripts set up to get the executable from /u/jde/divimp
#
# If users want to build and modify the code these scripts would need to be 
# replaced with the standard ones. 
#

cp $DIVSRC/rundiv.user $DIVDIR/rundiv
cp $DIVSRC/runout.user $DIVDIR/runout
cp $DIVSRC/runeire99   $DIVDIR/runeire99
cp $DIVSRC/runpin      $DIVDIR/runpin

#
# Copy catalog management commands 
#

cp $DIVSRC/div_catalog   $DIVDIR/div_catalog
cp $DIVSRC/div_retrieve  $DIVDIR/div_retrieve

#
# Copy 2 simple testcase input files
#

cp $DIVSRC/data/testcase06.d6i $DIVDAT
cp $DIVSRC/data/testcase06-prob.d6o $DIVDAT

cp $DIVSRC/data/testcase08.d6i $DIVDAT
cp $DIVSRC/data/testcase08-bg.d6o $DIVDAT






