      MODULE CSDVI_BGK

      USE PRECISION
      USE PARMMOD

      IMPLICIT NONE

      PRIVATE

      PUBLIC :: ALLOC_CSDVI_BGK, DEALLOC_CSDVI_BGK, INIT_CSDVI_BGK

      REAL(DP), PUBLIC, ALLOCATABLE, SAVE ::
     R  SIGMA_BGK(:,:), SGMS_BGK(:),
     R  STV_BGK(:,:),   STVS_BGK(:),
     R  SDVIA_BGK(:,:), EE_BGK(:,:), EES_BGK(:)

      INTEGER, PUBLIC, SAVE ::
     I  NBGV_STAT, NSBGK, NBGVI_STAT


      CONTAINS


      SUBROUTINE ALLOC_CSDVI_BGK

      IF (ALLOCATED(SIGMA_BGK)) RETURN

      NBGV_STAT=(NBGV+2*(NATM+NMOL))*NSWIT+1
      NSBGK=NBGV_STAT*NRTALS

      ALLOCATE (SIGMA_BGK(NBGV_STAT,NRTALS))
      ALLOCATE (SGMS_BGK(NBGV_STAT))
      ALLOCATE (STV_BGK(NBGV_STAT,NRTALS))
      ALLOCATE (STVS_BGK(NBGV_STAT))
      ALLOCATE (SDVIA_BGK(NBGV_STAT,NRTALS))
      ALLOCATE (EE_BGK(NBGV_STAT,NRTALS))
      ALLOCATE (EES_BGK(NBGV_STAT))

      WRITE (55,*) ' CSDVI_BGK ',(4*NRTALS+3)*NBGV_STAT*8

      CALL INIT_CSDVI_BGK

      RETURN
      END SUBROUTINE ALLOC_CSDVI_BGK


      SUBROUTINE DEALLOC_CSDVI_BGK

      IF (.NOT.ALLOCATED(SIGMA_BGK)) RETURN

      DEALLOCATE (SIGMA_BGK)
      DEALLOCATE (SGMS_BGK)
      DEALLOCATE (STV_BGK)
      DEALLOCATE (STVS_BGK)
      DEALLOCATE (SDVIA_BGK)
      DEALLOCATE (EE_BGK)
      DEALLOCATE (EES_BGK)

      RETURN
      END SUBROUTINE DEALLOC_CSDVI_BGK


      SUBROUTINE INIT_CSDVI_BGK

      SIGMA_BGK = 0._DP
      SGMS_BGK  = 0._DP
      STV_BGK   = 0._DP
      STVS_BGK  = 0._DP
      SDVIA_BGK = 0._DP
      EE_BGK    = 0._DP
      EES_BGK   = 0._DP

      RETURN
      END SUBROUTINE INIT_CSDVI_BGK

      END MODULE CSDVI_BGK
