      MODULE EIRBRA

C  NEUTRAL SOURCE TERMS: SNI,SMO,SEE,SEI (EIRENE ---> BRAAMS)

      USE PRECISION
!pb      USE PARMMOD

      IMPLICIT NONE

      PRIVATE

      PUBLIC :: ALLOC_EIRBRA, DEALLOC_EIRBRA, INIT_EIRBRA

      REAL(DP), PUBLIC, ALLOCATABLE, SAVE ::
     R SNI(:,:,:,:), SMO(:,:,:,:),
     R SEE(:,:,:),   SEI(:,:,:)

      REAL(DP), PUBLIC, ALLOCATABLE, SAVE ::
     R VOLSUMN(:), VOLSUMM(:), VOLSUMEI(:), VOLSUMEE(:)
      
      INTEGER, SAVE :: NDXD, NDYD, NFLD, NSTRAD


      CONTAINS


      SUBROUTINE ALLOC_EIRBRA(NDXP, NDYP, NFL, NSTRA)
      
      INTEGER, INTENT(IN) :: NDXP, NDYP, NFL, NSTRA

      IF (ALLOCATED(SNI)) RETURN

      NDXD = NDXP+1
      NDYD = NDYP+1
      NFLD = NFL
      NSTRAD = NSTRA
      
      ALLOCATE (SNI(0:NDXD,0:NDYD,NFLD,NSTRAD))
      ALLOCATE (SMO(0:NDXD,0:NDYD,NFLD,NSTRAD))
      ALLOCATE (SEE(0:NDXD,0:NDYD,NSTRAD))
      ALLOCATE (SEI(0:NDXD,0:NDYD,NSTRAD))

      ALLOCATE (VOLSUMN(NSTRA))
      ALLOCATE (VOLSUMM(NSTRA))
      ALLOCATE (VOLSUMEI(NSTRA))
      ALLOCATE (VOLSUMEE(NSTRA))

      WRITE (55,'(A,T25,I15)')
     .             ' EIRBRA ',((NDXD+1)*(NDYD+1)*NSTRAD*2*NFLD+
     .                        4*NSTRA)*8

      CALL INIT_EIRBRA

      RETURN 
      END SUBROUTINE ALLOC_EIRBRA


      SUBROUTINE DEALLOC_EIRBRA

      IF (.NOT.ALLOCATED(SNI)) RETURN

      DEALLOCATE (SNI)
      DEALLOCATE (SMO)
      DEALLOCATE (SEE)
      DEALLOCATE (SEI)

      DEALLOCATE (VOLSUMN)
      DEALLOCATE (VOLSUMM)
      DEALLOCATE (VOLSUMEI)
      DEALLOCATE (VOLSUMEE)

      RETURN 
      END SUBROUTINE DEALLOC_EIRBRA


      SUBROUTINE INIT_EIRBRA

      SNI = 0._DP
      SMO = 0._DP
      SEE = 0._DP
      SEI = 0._DP

      VOLSUMN  = 0._DP
      VOLSUMM  = 0._DP
      VOLSUMEI = 0._DP
      VOLSUMEE = 0._DP

      RETURN 
      END SUBROUTINE INIT_EIRBRA

      END MODULE EIRBRA


