C
C
C*DK MASJ6
      SUBROUTINE MASJ6 (A,I,J,K,L,M,N)
      IMPLICIT NONE
      CHARACTER(48), INTENT(IN) :: A
      INTEGER, INTENT(IN) :: I, J, K, L, M, N
      WRITE (6,60) A,I,J,K,L,M,N
60    FORMAT (1X,A48/1X,6(I6,3X))
      RETURN
      END
