C
C*DK MASJR2
      SUBROUTINE MASJR2 (A,I,B,C)
      USE PRECISION
      IMPLICIT NONE
      CHARACTER(24), INTENT(IN) :: A
      REAL(DP), INTENT(IN) :: B, C
      INTEGER, INTENT(IN) :: I
      WRITE (6,60) A,I,B,C
60    FORMAT (1X,A24,3X,I6,3X,2(1PE12.4,3X))
      RETURN
      END
