C
C
C*DK MASJ5
      SUBROUTINE MASJ5 (A,I,J,K,L,M)
      IMPLICIT NONE
      CHARACTER(40), INTENT(IN) :: A
      INTEGER, INTENT(IN) :: I, J, K, L, M
      WRITE (6,60) A,I,J,K,L,M
60    FORMAT (1X,A40/1X,5(I6,3X))
      RETURN
      END
