C
C
      SUBROUTINE NCELLN(NCELL,NR,NP,NT,NA,NB,NR1,NP2,NT3,NBL,LR,LP,LT)
C  FIND STANDARD MESH CELL NUMBERS FROM NCELL
C
C     LR : NLRAD
C     LP : NLPOL
C     LT : NLTOR
C     NR1: NR1ST
C     NP2: NP2ND
C     NT3: NT3RD
C     NBL: NBMLT
C
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: NCELL, NR1, NP2, NT3, NBL
      INTEGER, INTENT(OUT) :: NR, NP, NT, NA, NB
      LOGICAL, INTENT(IN) :: LR,LP,LT
      INTEGER :: NCELL0, NBLCKA, NP2T3, NSTRD, NR1P2, N12, NCELL1, 
     .           NCELL2, NCELL3, N23

      NSTRD=NR1*NP2*NT3
      IF (NCELL.GT.NSTRD*NBL) THEN
        NA=NCELL-NSTRD*NBL
        NB=NBL+1
        NR=0
        NP=1
        NT=1
        RETURN
      ELSEIF (NCELL.EQ.0) THEN
        NA=0
        NB=1
        NR=0
        NP=1
        NT=1
        RETURN
      ENDIF
C
C  AT THIS POINT: 1 <= NCELL <= NSURF, HENCE: NA=0
C
      NR1P2=0
      IF (LP.OR.LT) NR1P2=NR1
      NP2T3=0
      IF (LT) NP2T3=NP2
C
      NCELL0=NCELL
      NA=0
      NB=(NCELL0-1)/NSTRD+1
      NBLCKA=NSTRD*(NB-1)+NA
C
      NCELL1=NCELL0-NBLCKA
      IF (LT) THEN
        N23=(NCELL1-1)/NR1P2+1
        NT=(N23-1)/NP2T3+1
      ELSE
        NT=1
      ENDIF
C
      NCELL2=NCELL1-(NT-1)*NP2T3*NR1P2
      IF (LP) THEN
        N12=NCELL2
        NP=(N12-1)/NR1P2+1
      ELSE
        NP=1
      ENDIF
C
      NCELL3=NCELL2-(NP-1)*NR1P2
      NR=NCELL3
      RETURN
      END
