C
      SUBROUTINE SUMOSTRA (ISTRA)
C
C  SUM UP TALLIES FOR SUM OVER STRATA
C
      USE PRECISION
      USE PARMMOD
      USE COMUSR
      USE COUTAU

      IMPLICIT NONE

      INTEGER, INTENT(IN) :: ISTRA
      INTEGER :: IMOL, IATM, IION, IPHOT, IPLS
      INTEGER :: IADV, ICLV, ISNV, ICPV, IBGV

C
C  UPDATE TALLIES FOR  "SUM OVER STRATA"
C
      DO 1101 IMOL=0,NMOLI
        PPMLI (IMOL,0)=PPMLI (IMOL,0)+PPMLI (IMOL,ISTRA)
        WTOTM (IMOL,0)=WTOTM (IMOL,0)+WTOTM (IMOL,ISTRA)
        PDENMI(IMOL,0)=PDENMI(IMOL,0)+PDENMI(IMOL,ISTRA)
        EDENMI(IMOL,0)=EDENMI(IMOL,0)+EDENMI(IMOL,ISTRA)
        PAMLI (IMOL,0)=PAMLI (IMOL,0)+PAMLI (IMOL,ISTRA)
        PMMLI (IMOL,0)=PMMLI (IMOL,0)+PMMLI (IMOL,ISTRA)
        PIMLI (IMOL,0)=PIMLI (IMOL,0)+PIMLI (IMOL,ISTRA)
        PPHMLI(IMOL,0)=PPHMLI(IMOL,0)+PPHMLI(IMOL,ISTRA)
        POTMLI(IMOL,0)=POTMLI(IMOL,0)+POTMLI(IMOL,ISTRA)
        PRFAMI(IMOL,0)=PRFAMI(IMOL,0)+PRFAMI(IMOL,ISTRA)
        PRFMMI(IMOL,0)=PRFMMI(IMOL,0)+PRFMMI(IMOL,ISTRA)
        PRFIMI(IMOL,0)=PRFIMI(IMOL,0)+PRFIMI(IMOL,ISTRA)
        PRFPHMI(IMOL,0)=PRFPHMI(IMOL,0)+PRFPHMI(IMOL,ISTRA)
        PRFPMI(IMOL,0)=PRFPMI(IMOL,0)+PRFPMI(IMOL,ISTRA)
        EOTMLI(IMOL,0)=EOTMLI(IMOL,0)+EOTMLI(IMOL,ISTRA)
        ERFAMI(IMOL,0)=ERFAMI(IMOL,0)+ERFAMI(IMOL,ISTRA)
        ERFMMI(IMOL,0)=ERFMMI(IMOL,0)+ERFMMI(IMOL,ISTRA)
        ERFIMI(IMOL,0)=ERFIMI(IMOL,0)+ERFIMI(IMOL,ISTRA)
        ERFPHMI(IMOL,0)=ERFPHMI(IMOL,0)+ERFPHMI(IMOL,ISTRA)
        ERFPMI(IMOL,0)=ERFPMI(IMOL,0)+ERFPMI(IMOL,ISTRA)
        SPTMLI(IMOL,0)=SPTMLI(IMOL,0)+SPTMLI(IMOL,ISTRA)
        PGENMI(IMOL,0)=PGENMI(IMOL,0)+PGENMI(IMOL,ISTRA)
        EGENMI(IMOL,0)=EGENMI(IMOL,0)+EGENMI(IMOL,ISTRA)
        VGENMI(IMOL,0)=VGENMI(IMOL,0)+VGENMI(IMOL,ISTRA)
1101  CONTINUE
      DO 1102 IATM=0,NATMI
        PPATI (IATM,0)=PPATI (IATM,0)+PPATI (IATM,ISTRA)
        WTOTA (IATM,0)=WTOTA (IATM,0)+WTOTA (IATM,ISTRA)
        PDENAI(IATM,0)=PDENAI(IATM,0)+PDENAI(IATM,ISTRA)
        EDENAI(IATM,0)=EDENAI(IATM,0)+EDENAI(IATM,ISTRA)
        PAATI (IATM,0)=PAATI (IATM,0)+PAATI (IATM,ISTRA)
        PMATI (IATM,0)=PMATI (IATM,0)+PMATI (IATM,ISTRA)
        PIATI (IATM,0)=PIATI (IATM,0)+PIATI (IATM,ISTRA)
        PPHATI(IATM,0)=PPHATI(IATM,0)+PPHATI(IATM,ISTRA)
        POTATI(IATM,0)=POTATI(IATM,0)+POTATI(IATM,ISTRA)
        PRFAAI(IATM,0)=PRFAAI(IATM,0)+PRFAAI(IATM,ISTRA)
        PRFMAI(IATM,0)=PRFMAI(IATM,0)+PRFMAI(IATM,ISTRA)
        PRFIAI(IATM,0)=PRFIAI(IATM,0)+PRFIAI(IATM,ISTRA)
        PRFPHAI(IATM,0)=PRFPHAI(IATM,0)+PRFPHAI(IATM,ISTRA)
        PRFPAI(IATM,0)=PRFPAI(IATM,0)+PRFPAI(IATM,ISTRA)
        EOTATI(IATM,0)=EOTATI(IATM,0)+EOTATI(IATM,ISTRA)
        ERFAAI(IATM,0)=ERFAAI(IATM,0)+ERFAAI(IATM,ISTRA)
        ERFMAI(IATM,0)=ERFMAI(IATM,0)+ERFMAI(IATM,ISTRA)
        ERFIAI(IATM,0)=ERFIAI(IATM,0)+ERFIAI(IATM,ISTRA)
        ERFPHAI(IATM,0)=ERFPHAI(IATM,0)+ERFPHAI(IATM,ISTRA)
        ERFPAI(IATM,0)=ERFPAI(IATM,0)+ERFPAI(IATM,ISTRA)
        SPTATI(IATM,0)=SPTATI(IATM,0)+SPTATI(IATM,ISTRA)
        PGENAI(IATM,0)=PGENAI(IATM,0)+PGENAI(IATM,ISTRA)
        EGENAI(IATM,0)=EGENAI(IATM,0)+EGENAI(IATM,ISTRA)
        VGENAI(IATM,0)=VGENAI(IATM,0)+VGENAI(IATM,ISTRA)
1102  CONTINUE
      DO 1103 IION=0,NIONI
        PPIOI (IION,0)=PPIOI (IION,0)+PPIOI (IION,ISTRA)
        EELFI (IION,0)=EELFI (IION,0)+EELFI (IION,ISTRA)
        WTOTI (IION,0)=WTOTI (IION,0)+WTOTI (IION,ISTRA)
        PDENII(IION,0)=PDENII(IION,0)+PDENII(IION,ISTRA)
        EDENII(IION,0)=EDENII(IION,0)+EDENII(IION,ISTRA)
        PAIOI (IION,0)=PAIOI (IION,0)+PAIOI (IION,ISTRA)
        PMIOI (IION,0)=PMIOI (IION,0)+PMIOI (IION,ISTRA)
        PIIOI (IION,0)=PIIOI (IION,0)+PIIOI (IION,ISTRA)
        PPHIOI(IION,0)=PPHIOI(IION,0)+PPHIOI(IION,ISTRA)
        POTIOI(IION,0)=POTIOI(IION,0)+POTIOI(IION,ISTRA)
        PRFAII(IION,0)=PRFAII(IION,0)+PRFAII(IION,ISTRA)
        PRFMII(IION,0)=PRFMII(IION,0)+PRFMII(IION,ISTRA)
        PRFIII(IION,0)=PRFIII(IION,0)+PRFIII(IION,ISTRA)
        PRFPHII(IION,0)=PRFPHII(IION,0)+PRFPHII(IION,ISTRA)
        PRFPII(IION,0)=PRFPII(IION,0)+PRFPII(IION,ISTRA)
        EOTIOI(IION,0)=EOTIOI(IION,0)+EOTIOI(IION,ISTRA)
        ERFAII(IION,0)=ERFAII(IION,0)+ERFAII(IION,ISTRA)
        ERFMII(IION,0)=ERFMII(IION,0)+ERFMII(IION,ISTRA)
        ERFIII(IION,0)=ERFIII(IION,0)+ERFIII(IION,ISTRA)
        ERFPHII(IION,0)=ERFPHII(IION,0)+ERFPHII(IION,ISTRA)
        ERFPII(IION,0)=ERFPII(IION,0)+ERFPII(IION,ISTRA)
        SPTIOI(IION,0)=SPTIOI(IION,0)+SPTIOI(IION,ISTRA)
        PGENII(IION,0)=PGENII(IION,0)+PGENII(IION,ISTRA)
        EGENII(IION,0)=EGENII(IION,0)+EGENII(IION,ISTRA)
        VGENII(IION,0)=VGENII(IION,0)+VGENII(IION,ISTRA)
1103  CONTINUE
      DO IPHOT=0,NPHOTI
        PPPHTI  (IPHOT,0)=PPPHTI  (IPHOT,0)+PPPHTI  (IPHOT,ISTRA)
        WTOTPH  (IPHOT,0)=WTOTPH  (IPHOT,0)+WTOTPH  (IPHOT,ISTRA)
        PDENPHI (IPHOT,0)=PDENPHI (IPHOT,0)+PDENPHI (IPHOT,ISTRA)
        EDENPHI (IPHOT,0)=EDENPHI (IPHOT,0)+EDENPHI (IPHOT,ISTRA)
        PAPHTI  (IPHOT,0)=PAPHTI  (IPHOT,0)+PAPHTI  (IPHOT,ISTRA)
        PMPHTI  (IPHOT,0)=PMPHTI  (IPHOT,0)+PMPHTI  (IPHOT,ISTRA)
        PIPHTI  (IPHOT,0)=PIPHTI  (IPHOT,0)+PIPHTI  (IPHOT,ISTRA)
        PPHPHTI (IPHOT,0)=PPHPHTI (IPHOT,0)+PPHPHTI (IPHOT,ISTRA)
        POTPHTI (IPHOT,0)=POTPHTI (IPHOT,0)+POTPHTI (IPHOT,ISTRA)
        PRFAPHTI(IPHOT,0)=PRFAPHTI(IPHOT,0)+PRFAPHTI(IPHOT,ISTRA)
        PRFMPHTI(IPHOT,0)=PRFMPHTI(IPHOT,0)+PRFMPHTI(IPHOT,ISTRA)
        PRFIPHTI(IPHOT,0)=PRFIPHTI(IPHOT,0)+PRFIPHTI(IPHOT,ISTRA)
        PRFPHPHTI(IPHOT,0)=PRFPHPHTI(IPHOT,0)+PRFPHPHTI(IPHOT,ISTRA)
        PRFPPHTI(IPHOT,0)=PRFPPHTI(IPHOT,0)+PRFPPHTI(IPHOT,ISTRA)
        EOTPHTI (IPHOT,0)=EOTPHTI (IPHOT,0)+EOTPHTI (IPHOT,ISTRA)
        ERFAPHTI(IPHOT,0)=ERFAPHTI(IPHOT,0)+ERFAPHTI(IPHOT,ISTRA)
        ERFMPHTI(IPHOT,0)=ERFMPHTI(IPHOT,0)+ERFMPHTI(IPHOT,ISTRA)
        ERFIPHTI(IPHOT,0)=ERFIPHTI(IPHOT,0)+ERFIPHTI(IPHOT,ISTRA)
        ERFPHPHTI(IPHOT,0)=ERFPHPHTI(IPHOT,0)+ERFPHPHTI(IPHOT,ISTRA)
        ERFPPHTI(IPHOT,0)=ERFPPHTI(IPHOT,0)+ERFPPHTI(IPHOT,ISTRA)
        SPTPHTI (IPHOT,0)=SPTPHTI (IPHOT,0)+SPTPHTI (IPHOT,ISTRA)
        PGENPHI (IPHOT,0)=PGENPHI (IPHOT,0)+PGENPHI (IPHOT,ISTRA)
        EGENPHI (IPHOT,0)=EGENPHI (IPHOT,0)+EGENPHI (IPHOT,ISTRA)
        VGENPHI (IPHOT,0)=VGENPHI (IPHOT,0)+VGENPHI (IPHOT,ISTRA)
      END DO
      DO 1104 IPLS=0,NPLSI
        PPPLI (IPLS,0)=PPPLI (IPLS,0)+PPPLI (IPLS,ISTRA)
        WTOTP (IPLS,0)=WTOTP (IPLS,0)+WTOTP (IPLS,ISTRA)
        PAPLI (IPLS,0)=PAPLI (IPLS,0)+PAPLI (IPLS,ISTRA)
        PMPLI (IPLS,0)=PMPLI (IPLS,0)+PMPLI (IPLS,ISTRA)
        PIPLI (IPLS,0)=PIPLI (IPLS,0)+PIPLI (IPLS,ISTRA)
        PPHPLI(IPLS,0)=PPHPLI(IPLS,0)+PPHPLI(IPLS,ISTRA)
        POTPLI(IPLS,0)=POTPLI(IPLS,0)+POTPLI(IPLS,ISTRA)
        EOTPLI(IPLS,0)=EOTPLI(IPLS,0)+EOTPLI(IPLS,ISTRA)
        SPTPLI(IPLS,0)=SPTPLI(IPLS,0)+SPTPLI(IPLS,ISTRA)
1104  CONTINUE
      WTOTE(0)=WTOTE(0)+WTOTE(ISTRA)
      DO 1105 IADV=0,NADVI
        ADDVI(IADV,0)=ADDVI(IADV,0)+ADDVI(IADV,ISTRA)
1105  CONTINUE
      DO 1106 ICLV=0,NCLVI
        COLVI(ICLV,0)=COLVI(ICLV,0)+COLVI(ICLV,ISTRA)
1106  CONTINUE
      DO 1107 ISNV=0,NSNVI
        SNAPVI(ISNV,0)=SNAPVI(ISNV,0)+SNAPVI(ISNV,ISTRA)
1107  CONTINUE
      DO 1108 ICPV=0,NCPVI
        COPVI(ICPV,0)=COPVI(ICPV,0)+COPVI(ICPV,ISTRA)
1108  CONTINUE
      DO 1109 IBGV=0,NBGVI
        BGKVI(IBGV,0)=BGKVI(IBGV,0)+BGKVI(IBGV,ISTRA)
1109  CONTINUE
      PAELI (0)=PAELI (0)+PAELI (ISTRA)
      PMELI (0)=PMELI (0)+PMELI (ISTRA)
      PIELI (0)=PIELI (0)+PIELI (ISTRA)
      PPHELI(0)=PPHELI(0)+PPHELI(ISTRA)
C
      EAELI (0)=EAELI (0)+EAELI (ISTRA)
      EAATI (0)=EAATI (0)+EAATI (ISTRA)
      EAMLI (0)=EAMLI (0)+EAMLI (ISTRA)
      EAIOI (0)=EAIOI (0)+EAIOI (ISTRA)
      EAPHTI(0)=EAPHTI(0)+EAPHTI(ISTRA)
      EAPLI (0)=EAPLI (0)+EAPLI (ISTRA)
C
      EMELI (0)=EMELI (0)+EMELI (ISTRA)
      EMATI (0)=EMATI (0)+EMATI (ISTRA)
      EMMLI (0)=EMMLI (0)+EMMLI (ISTRA)
      EMIOI (0)=EMIOI (0)+EMIOI (ISTRA)
      EMPHTI(0)=EMPHTI(0)+EMPHTI(ISTRA)
      EMPLI (0)=EMPLI (0)+EMPLI (ISTRA)
C
      EIELI (0)=EIELI (0)+EIELI (ISTRA)
      EIATI (0)=EIATI (0)+EIATI (ISTRA)
      EIMLI (0)=EIMLI (0)+EIMLI (ISTRA)
      EIIOI (0)=EIIOI (0)+EIIOI (ISTRA)
      EIPHTI(0)=EIPHTI(0)+EIPHTI(ISTRA)
      EIPLI (0)=EIPLI (0)+EIPLI (ISTRA)
C
      EPHELI (0)=EPHELI (0)+EPHELI (ISTRA)
      EPHATI (0)=EPHATI (0)+EPHATI (ISTRA)
      EPHMLI (0)=EPHMLI (0)+EPHMLI (ISTRA)
      EPHIOI (0)=EPHIOI (0)+EPHIOI (ISTRA)
      EPHPHTI(0)=EPHPHTI(0)+EPHPHTI(ISTRA)
      EPHPLI (0)=EPHPLI (0)+EPHPLI (ISTRA)
C
      EPATI (0)=EPATI (0)+EPATI (ISTRA)
      EPMLI (0)=EPMLI (0)+EPMLI (ISTRA)
      EPIOI (0)=EPIOI (0)+EPIOI (ISTRA)
      EPPHTI(0)=EPPHTI(0)+EPPHTI(ISTRA)
      EPPLI (0)=EPPLI (0)+EPPLI (ISTRA)
C
C
      FLUXT(0)=FLUXT(0)+FLUXT(ISTRA)
      XMCP(0)=XMCP(0)+XMCP(ISTRA)
      PTRASH(0)=PTRASH(0)+PTRASH(ISTRA)
      ETRASH(0)=ETRASH(0)+ETRASH(ISTRA)
      ETOTA(0)=ETOTA(0)+ETOTA(ISTRA)
      ETOTM(0)=ETOTM(0)+ETOTM(ISTRA)
      ETOTI(0)=ETOTI(0)+ETOTI(ISTRA)
      ETOTP(0)=ETOTP(0)+ETOTP(ISTRA)
      ETOTPH(0)=ETOTPH(0)+ETOTPH(ISTRA)
C
      RETURN
      END
