#!/bin/ksh

if [ $# -lt 1 ]
then 
   echo usage: 'go [2d,3d,3ds] [all](optional)'
   exit 1
fi

if [ $# -eq 2 ]
then
  if [ $2 = "all" ]
  then
    rm *.o
  fi
fi
  
rm *.f

if [ $1 = "2d" ]
then  

  echo
  echo Standard LIM version
  echo  

  make -f make2d
  exit 1
fi

if [ $1 = "3d" ]
then  

  echo
  echo Building 3D LIM version
  echo  

  cp ../limcom/SLCOM ../limcom/sl_limcom3d/SLCOM
  make -f make3d
  exit 1
fi

if [ $1 = "3ds" ]
then  

  echo
  echo Building 3D LIM version with only a few X cells
  echo

  cp ../limcom/SLCOM ../limcom/sl_limcom3ds/SLCOM
  make -f make3ds
  exit 1
fi  

echo
echo Error - unrecognized option: $1
echo

exit 1


