!pb  31.10.06:  definition of RSPLST, ISPLST changed
!               RSPLST(15,NPARTC) --> RSPLST(NPARTC,15)
!    20.06.07:  MAXLEVEL=15 defined, used in dimensioning of RSPLST and ISPLST 

      MODULE COMSPL

      USE PRECISION
      USE PARMMOD
!pb      USE COMPRT , ONLY : NPARTC, MPARTC

      IMPLICIT NONE

      PRIVATE

      PUBLIC :: ALLOC_COMSPL, DEALLOC_COMSPL, INIT_COMSPL

      REAL(DP), PUBLIC, TARGET, ALLOCATABLE, SAVE :: RCMSPL(:)

      REAL(DP), PUBLIC, POINTER, SAVE ::
     R WMINV,    WMINS,     WMINC,     WMINL,     SPLPAR,
     R RNUMB(:), PRMSPL(:)

      REAL(DP), PUBLIC, ALLOCATABLE, SAVE ::
     R RSPLST(:,:)

      INTEGER, PUBLIC, PARAMETER :: MAXLEVEL=15

      INTEGER, PUBLIC, TARGET, ALLOCATABLE, SAVE :: ICMSPL(:)

      INTEGER, PUBLIC, POINTER, SAVE ::
     I MAXLEV, NLEVEL,
     I MAXRAD, MAXPOL, MAXTOR, MAXADD,
     I NODES(:), NSSPL(:)

      INTEGER, PUBLIC, ALLOCATABLE, SAVE ::
     I ISPLST(:,:)

      LOGICAL, PUBLIC, TARGET, ALLOCATABLE, SAVE :: LCMSPL(:)

      LOGICAL, PUBLIC, POINTER, SAVE ::
     L NLSPLT(:),
     L NLPRCA(:), NLPRCM(:), NLPRCI(:), NLPRCPH(:)

      LOGICAL, PUBLIC, ALLOCATABLE, SAVE ::
     L NLPRCS(:)

      INTEGER, PUBLIC, SAVE ::
     I NCMSPL, MCMSPL, KCMSPL


      CONTAINS


      SUBROUTINE ALLOC_COMSPL

      IF (ALLOCATED(RCMSPL)) RETURN

      NCMSPL=2*(N1ST+N2ND+N3RD+NLIM)+5
      MCMSPL=N1ST+N2ND+N3RD+NLIM+21
      KCMSPL=N1ST+N2ND+N3RD+NLIM+NATM+NMOL+NION+NPHOT

      ALLOCATE (RCMSPL(NCMSPL))
      ALLOCATE (ICMSPL(MCMSPL))
      ALLOCATE (LCMSPL(KCMSPL))

      ALLOCATE (RSPLST(NPARTC,MAXLEVEL))
      ALLOCATE (ISPLST(MPARTC,MAXLEVEL))
      ALLOCATE (NLPRCS(0:NLIMPS))

      WRITE (55,'(A,T25,I15)')
     .       ' COMSPL ',(NCMSPL+MAXLEVEL*NPARTC)*8 +
     .                  (MCMSPL+MAXLEVEL*MPARTC)*4 + (KCMSPL+NLIMPS+1)*4

      WMINV  => RCMSPL(1)
      WMINS  => RCMSPL(2)
      WMINC  => RCMSPL(3)
      WMINL  => RCMSPL(4)
      SPLPAR => RCMSPL(5)
      RNUMB  => RCMSPL(6:5+N1ST+N2ND+N3RD+NLIM)
      PRMSPL => RCMSPL(6+N1ST+N2ND+N3RD+NLIM : NCMSPL)

      MAXLEV => ICMSPL(1)
      NLEVEL => ICMSPL(2)
      MAXRAD => ICMSPL(3)
      MAXPOL => ICMSPL(4)
      MAXTOR => ICMSPL(5)
      MAXADD => ICMSPL(6)
      NODES  => ICMSPL(7:21)
      NSSPL  => ICMSPL(22:MCMSPL)

      NLPRCA => LCMSPL(1:NATM)
      NLPRCM => LCMSPL(1+NATM:NATM+NMOL)
      NLPRCI => LCMSPL(1+NATM+NMOL:NATM+NMOL+NION)
      NLPRCPH=> LCMSPL(1+NATM+NMOL+NION:NATM+NMOL+NION+NPHOT)
      NLSPLT => LCMSPL(1+NATM+NMOL+NION+NPHOT:KCMSPL)

      CALL INIT_COMSPL

      RETURN
      END SUBROUTINE ALLOC_COMSPL


      SUBROUTINE DEALLOC_COMSPL

      IF (.NOT.ALLOCATED(RCMSPL)) RETURN

      DEALLOCATE (RCMSPL)
      DEALLOCATE (ICMSPL)
      DEALLOCATE (LCMSPL)

      DEALLOCATE (RSPLST)
      DEALLOCATE (ISPLST)
      DEALLOCATE (NLPRCS)

      RETURN
      END SUBROUTINE DEALLOC_COMSPL


      SUBROUTINE INIT_COMSPL

      RCMSPL = 0._DP
      ICMSPL = 0
      LCMSPL = .FALSE.

      RSPLST = 0._DP
      ISPLST = 0
      NLPRCS = .FALSE.

      RETURN
      END SUBROUTINE INIT_COMSPL

      END MODULE COMSPL
