CDK USER
C
C   USER SUPPLIED SUBROUTINES
C
C           ************
C           *  TEXTOR  *  (HELIUM INCLUDED)
C           ************
C
      SUBROUTINE PROUSR (PRO,INDX,P0,P1,P2,P3,P4,P5,PROVAC,N)
C
C     P0 : CENTRAL VALUE
C     P1 : STARTING RADIUS FOR POLYNOMIAL
C     P2 : SWITCH FOR PHASE 1: OH-PHASE
C                           2: NI-PHASE
C     P3 : FACTOR FOR TI: TI=K*TE
C
      USE PRECISION
      USE PARMMOD
      USE COMUSR
      USE CGRID
      USE CGEOM
      IMPLICIT NONE
      REAL(DP), INTENT(IN) :: P0, P1, P2, P3, P4, P5, PROVAC
      REAL(DP), INTENT(OUT) :: PRO(*)
      INTEGER, INTENT(IN) :: INDX, N

      RETURN
      END
