C
C
C
C
      SUBROUTINE PROFE(PRO,PRO0,RINP,A1,E,SEP,PROVAC)
C
C  EXPONENTIAL PROFILE, PLUS EXPONENTIAL DECAY BEYOND RHOSEP
C
      USE PRECISION
      USE PARMMOD
      USE CCONA
      USE CGRID
      USE COMPRT, ONLY: IUNOUT

      IMPLICIT NONE

      REAL(DP), INTENT(IN) :: PRO0, RINP, A1, E, SEP, PROVAC
      REAL(DP), INTENT(OUT) :: PRO(*)
      REAL(DP) :: EP1R, ELLR, YR, AREAA, ARCA, RHOINP, ZR,
     .          AR, DIST, PROS, RHO
      INTEGER :: J, JM1, LEARCA, NLOCAL

      RHO=SEP
      RHOINP=RINP
      IF (LEVGEO.LE.2) THEN
        IF (RRA.GT.RAA) THEN
          NLOCAL=NR1STM
          PRO(NR1STM)=PROVAC
        ELSE
          NLOCAL=NR1ST
        ENDIF
C
C FIND RADIAL SURFACE LABELING CO-ORDINATE AT "SEP"
C
        IF (LEVGEO.EQ.2) THEN
          JM1=LEARCA(SEP,RSURF,1,NLOCAL,1,'PROFE       ')
          AR=AREAA (SEP,JM1,ARCA,YR,EP1R,ELLR)
          RHO=SQRT(AR*PIAI)
          JM1=LEARCA(RINP,RSURF,1,NLOCAL,1,'PROFE       ')
          AR=AREAA (RINP,JM1,ARCA,YR,EP1R,ELLR)
          RHOINP=SQRT(AR*PIAI)
        ENDIF
      ELSE
        WRITE (iunout,*) 'WARNING: PROFE CALLED WITH LEVGEO.GT.2 '
        WRITE (iunout,*) 'NO PLASMA PARAMETERS RETURNED'
        RETURN
      ENDIF
C
      DO 20 J=1,NLOCAL-1
        IF (RHOZNE(J).LE.RHO) THEN
          ZR=RHOZNE(J)-RHOINP
          PRO(J)=PRO0*EXP(-ZR/A1)
        ELSE
          DIST=RHO-RHOINP
          PROS=PRO0*EXP(-DIST/A1)
          PRO(J)=PROS*EXP((RHO-RHOZNE(J))/E)
        ENDIF
20    CONTINUE
      PRO(NR1ST)=0.
      RETURN
      END
