!pb  22.11.06: flag for shift of first parameter to rate_coeff introduced


      FUNCTION FEPLCX3 (IRCX,K)

      USE PRECISION
      USE PARMMOD
      USE COMUSR
      USE CCONA
      USE COMPRT
      USE COMXS

      IMPLICIT NONE

      INTEGER, INTENT(IN) :: IRCX, K
      REAL(DP) :: PLS, ADD, EPCX, FEPLCX3, RATE_COEFF
      INTEGER :: II, KK, IPLSTI

      FEPLCX3=0.D0
      KK=NELRCX(IRCX)
      IPLSTI=MPLSTI(IPLS)
      IF (KK < 0) THEN
        SELECT CASE (KK)
        CASE (-1)
C  DEFAULT CX MODEL
            FEPLCX3=1.5*TIIN(IPLSTI,K)+EDRIFT(IPLS,K)
        CASE (-2)
C  MEAN ENERGY FROM DRIFTING MONOENERGETIC
            FEPLCX3=EPLCX3(IRCX,1,1)+EDRIFT(IPLS,K)
        CASE (-3)
C  MEAN ENERGY FROM DRIFTING MAXWELLIAN
            FEPLCX3=1.5*TIIN(IPLSTI,K)+EDRIFT(IPLS,K)
        END SELECT
      ELSE
C  MEAN ENERGY FROM SINGLE PARAMETER FIT KK
        PLS=TIINL(IPLSTI,K)+ADDCX(IRCX,IPLS)
        EPCX = RATE_COEFF(KK,PLS,0._DP,.FALSE.,0)
        ADD=EPLCX3(IRCX,1,1)
        FEPLCX3=EPCX*DIIN(IPLS,K)*ADD
      END IF

      RETURN
      END
