      MODULE CPES

      USE PRECISION
      USE PARMMOD

      IMPLICIT NONE

      PRIVATE

      PUBLIC :: ALLOC_CPES, DEALLOC_CPES, INIT_CPES

      INTEGER, PUBLIC, ALLOCATABLE, SAVE ::
     I         NPESTR(:), NPESTA(:),
     I         NSTRPE(:)

      INTEGER, PUBLIC, SAVE :: 
     I         NSTEFF, nprs, my_pe

      LOGICAL, PUBLIC, SAVE :: LIDENT


      CONTAINS


      SUBROUTINE ALLOC_CPES

      IF (ALLOCATED(NPESTR)) RETURN

      ALLOCATE (NPESTR(0:NSTRA))
      ALLOCATE (NPESTA(0:NSTRA))
      ALLOCATE (NSTRPE(0:NRPES-1))

      WRITE (55,*) ' CPES ',(2*(NSTRA+1)+NRPES)*4

      CALL INIT_CPES

      RETURN
      END SUBROUTINE ALLOC_CPES


      SUBROUTINE DEALLOC_CPES

      IF (.NOT.ALLOCATED(NPESTR)) RETURN

      DEALLOCATE (NPESTR)
      DEALLOCATE (NPESTA)
      DEALLOCATE (NSTRPE)

      RETURN
      END SUBROUTINE DEALLOC_CPES


      SUBROUTINE INIT_CPES

      NPESTR = 0
      NPESTA = 0
      NSTRPE = 0

      RETURN
      END SUBROUTINE INIT_CPES

      END MODULE CPES
