      SUBROUTINE SCAL_VOLAV_TALLIES (ISTR, ZWW, ZW,
     .                               ZVOLIN, ZVOLIW, SCLTAL, N1DIM)

      USE PRECISION
      USE PARMMOD
      USE COMSOU
      USE COMUSR
      USE COMPRT, ONLY: IUNOUT
      USE CGRID
      USE COUTAU
      USE CESTIM
      USE CCONA
      USE CGEOM
      USE CSPEZ
      USE COMNNL

      IMPLICIT NONE

      INTEGER, INTENT(IN) :: ISTR, N1DIM
      REAL(DP), INTENT(IN) :: ZWW, ZW
      REAL(DP), INTENT(INOUT) :: SCLTAL(N1DIM,*)
      REAL(DP), INTENT(IN) :: ZVOLIN(*), ZVOLIW(*)

      REAL(DP) :: ZFAC
      INTEGER :: IATM, J, IMOL, IION, IPHOT, IPLS, IADV, ICLV,
     .           ISNV, ICPV, IBGV, ISPC, ICL
C
C
C*****VOLUME AVERAGED TALLIES  220 - 239
C
C  ATOMIC PARTICLE SPECIES LOOP FOR THE STRATUM ISTRA
C
      DO 220 IATM=1,NATMI
         IF (LOGATM(IATM,ISTR)) THEN
          DO 221 J=1,NSBOX_TAL
            IF (LPDENA) PDENA(IATM,J)=PDENA(IATM,J)*ZVOLIN(J)
            IF (LEDENA) EDENA(IATM,J)=EDENA(IATM,J)*ZVOLIN(J)
            IF (LPAAT)  PAAT(IATM,J) =PAAT(IATM,J) *ZVOLIW(J)
            IF (LPMAT)  PMAT(IATM,J) =PMAT(IATM,J) *ZVOLIW(J)
            IF (LPIAT)  PIAT(IATM,J) =PIAT(IATM,J) *ZVOLIW(J)
            IF (LPPHAT) PPHAT(IATM,J)=PPHAT(IATM,J)*ZVOLIW(J)
            IF (LPGENA) PGENA(IATM,J)=PGENA(IATM,J)*ZVOLIW(J)
            IF (LEGENA) EGENA(IATM,J)=EGENA(IATM,J)*ZVOLIW(J)
            IF (LVGENA) VGENA(IATM,J)=VGENA(IATM,J)*ZVOLIW(J)
            IF (LPPAT)  PPAT(IATM,J) =PPAT(IATM,J) *ZVOLIW(J)
            IF (LVXDENA) VXDENA(IATM,J)=VXDENA(IATM,J)*ZVOLIN(J)
            IF (LVYDENA) VYDENA(IATM,J)=VYDENA(IATM,J)*ZVOLIN(J)
            IF (LVZDENA) VZDENA(IATM,J)=VZDENA(IATM,J)*ZVOLIN(J)
221       CONTINUE
        ENDIF
        SCLTAL(IATM,1)=1
        SCLTAL(IATM,5)=1
        SCLTAL(IATM,10)=3
        SCLTAL(IATM,16)=3
        SCLTAL(IATM,22)=3
        SCLTAL(IATM,28)=3
        SCLTAL(IATM,63)=3
        SCLTAL(IATM,67)=3
        SCLTAL(IATM,71)=3
        SCLTAL(IATM,75)=3
        SCLTAL(IATM,85)=1
        SCLTAL(IATM,89)=1
        SCLTAL(IATM,93)=1
220   CONTINUE
C
C  MOLECULAR PARTICLE SPECIES LOOP FOR THE STRATUM ISTRA
C
      DO 222 IMOL=1,NMOLI
        IF (LOGMOL(IMOL,ISTR)) THEN
          DO 223 J=1,NSBOX_TAL
            IF (LPDENM) PDENM(IMOL,J)=PDENM(IMOL,J)*ZVOLIN(J)
            IF (LEDENM) EDENM(IMOL,J)=EDENM(IMOL,J)*ZVOLIN(J)
            IF (LPAML)  PAML(IMOL,J) =PAML(IMOL,J) *ZVOLIW(J)
            IF (LPMML)  PMML(IMOL,J) =PMML(IMOL,J) *ZVOLIW(J)
            IF (LPIML)  PIML(IMOL,J) =PIML(IMOL,J) *ZVOLIW(J)
            IF (LPPHML) PPHML(IMOL,J)=PPHML(IMOL,J)*ZVOLIW(J)
            IF (LPGENM) PGENM(IMOL,J)=PGENM(IMOL,J)*ZVOLIW(J)
            IF (LEGENM) EGENM(IMOL,J)=EGENM(IMOL,J)*ZVOLIW(J)
            IF (LVGENM) VGENM(IMOL,J)=VGENM(IMOL,J)*ZVOLIW(J)
            IF (LPPML)  PPML(IMOL,J) =PPML(IMOL,J) *ZVOLIW(J)
            IF (LVXDENM) VXDENM(IMOL,J)=VXDENM(IMOL,J)*ZVOLIN(J)
            IF (LVYDENM) VYDENM(IMOL,J)=VYDENM(IMOL,J)*ZVOLIN(J)
            IF (LVZDENM) VZDENM(IMOL,J)=VZDENM(IMOL,J)*ZVOLIN(J)
223       CONTINUE
        ENDIF
        SCLTAL(IMOL,2)=1
        SCLTAL(IMOL,6)=1
        SCLTAL(IMOL,11)=3
        SCLTAL(IMOL,17)=3
        SCLTAL(IMOL,23)=3
        SCLTAL(IMOL,29)=3
        SCLTAL(IMOL,64)=3
        SCLTAL(IMOL,68)=3
        SCLTAL(IMOL,72)=3
        SCLTAL(IMOL,76)=3
        SCLTAL(IMOL,86)=1
        SCLTAL(IMOL,90)=1
        SCLTAL(IMOL,94)=1
222   CONTINUE
C
C  TEST ION PARTICLE SPECIES LOOP FOR THE STRATUM ISTRA
C
      DO 225 IION=1,NIONI
        IF (LOGION(IION,ISTR)) THEN
          DO 226 J=1,NSBOX_TAL
            IF (LPDENI) PDENI(IION,J)=PDENI(IION,J)*ZVOLIN(J)
            IF (LEDENI) EDENI(IION,J)=EDENI(IION,J)*ZVOLIN(J)
            IF (LPAIO)  PAIO(IION,J) =PAIO(IION,J) *ZVOLIW(J)
            IF (LPMIO)  PMIO(IION,J) =PMIO(IION,J) *ZVOLIW(J)
            IF (LPIIO)  PIIO(IION,J) =PIIO(IION,J) *ZVOLIW(J)
            IF (LPPHIO) PPHIO(IION,J)=PPHIO(IION,J)*ZVOLIW(J)
            IF (LPGENI) PGENI(IION,J)=PGENI(IION,J)*ZVOLIW(J)
            IF (LEGENI) EGENI(IION,J)=EGENI(IION,J)*ZVOLIW(J)
            IF (LVGENI) VGENI(IION,J)=VGENI(IION,J)*ZVOLIW(J)
            IF (LPPIO)  PPIO(IION,J) =PPIO(IION,J) *ZVOLIW(J)
            IF (LVXDENI) VXDENI(IION,J)=VXDENI(IION,J)*ZVOLIN(J)
            IF (LVYDENI) VYDENI(IION,J)=VYDENI(IION,J)*ZVOLIN(J)
            IF (LVZDENI) VZDENI(IION,J)=VZDENI(IION,J)*ZVOLIN(J)
226       CONTINUE
        ENDIF
        SCLTAL(IION,3)=1
        SCLTAL(IION,7)=1
        SCLTAL(IION,12)=3
        SCLTAL(IION,18)=3
        SCLTAL(IION,24)=3
        SCLTAL(IION,30)=3
        SCLTAL(IION,65)=3
        SCLTAL(IION,69)=3
        SCLTAL(IION,73)=3
        SCLTAL(IION,77)=3
        SCLTAL(IION,87)=1
        SCLTAL(IION,91)=1
        SCLTAL(IION,95)=1
225   CONTINUE
C
C  PHOTON PARTICLE SPECIES LOOP FOR THE STRATUM ISTRA
C
      DO IPHOT=1,NPHOTI
        IF (LOGPHOT(IPHOT,ISTR)) THEN
          DO J=1,NSBOX_TAL
            IF (LPDENPH) PDENPH(IPHOT,J)=PDENPH(IPHOT,J)*ZVOLIN(J)
            IF (LEDENPH) EDENPH(IPHOT,J)=EDENPH(IPHOT,J)*ZVOLIN(J)
            IF (LPAPHT)  PAPHT(IPHOT,J) =PAPHT(IPHOT,J) *ZVOLIW(J)
            IF (LPMPHT)  PMPHT(IPHOT,J) =PMPHT(IPHOT,J) *ZVOLIW(J)
            IF (LPIPHT)  PIPHT(IPHOT,J) =PIPHT(IPHOT,J) *ZVOLIW(J)
            IF (LPPHPHT) PPHPHT(IPHOT,J)=PPHPHT(IPHOT,J)*ZVOLIW(J)
            IF (LPGENPH) PGENPH(IPHOT,J)=PGENPH(IPHOT,J)*ZVOLIW(J)
            IF (LEGENPH) EGENPH(IPHOT,J)=EGENPH(IPHOT,J)*ZVOLIW(J)
            IF (LVGENPH) VGENPH(IPHOT,J)=VGENPH(IPHOT,J)*ZVOLIW(J)
            IF (LPPPHT)  PPPHT(IPHOT,J) =PPPHT(IPHOT,J) *ZVOLIW(J)
            IF (LVXDENPH) VXDENPH(IPHOT,J)=VXDENPH(IPHOT,J)*ZVOLIN(J)
            IF (LVYDENPH) VYDENPH(IPHOT,J)=VYDENPH(IPHOT,J)*ZVOLIN(J)
            IF (LVZDENPH) VZDENPH(IPHOT,J)=VZDENPH(IPHOT,J)*ZVOLIN(J)
          END DO
        ENDIF
        SCLTAL(IPHOT,4)=1
        SCLTAL(IPHOT,8)=1
        SCLTAL(IPHOT,13)=3
        SCLTAL(IPHOT,19)=3
        SCLTAL(IPHOT,25)=3
        SCLTAL(IPHOT,31)=3
        SCLTAL(IPHOT,66)=3
        SCLTAL(IPHOT,70)=3
        SCLTAL(IPHOT,74)=3
        SCLTAL(IPHOT,78)=3
        SCLTAL(IPHOT,88)=1
        SCLTAL(IPHOT,92)=1
        SCLTAL(IPHOT,96)=1
      END DO
C
C  BULK ION PARTICLE SPECIES LOOP FOR THE STRATUM ISTRA
C
      DO 227 IPLS=1,NPLSI
        IF (LOGPLS(IPLS,ISTR)) THEN
          DO 228 J=1,NSBOX_TAL
            IF (LPAPL)  PAPL(IPLS,J) =PAPL(IPLS,J) *ZVOLIW(J)
            IF (LPMPL)  PMPL(IPLS,J) =PMPL(IPLS,J) *ZVOLIW(J)
            IF (LPIPL)  PIPL(IPLS,J) =PIPL(IPLS,J) *ZVOLIW(J)
            IF (LPPHPL) PPHPL(IPLS,J)=PPHPL(IPLS,J)*ZVOLIW(J)
            IF (LPPPL)  PPPL(IPLS,J) =PPPL(IPLS,J) *ZVOLIW(J)
            IF (LMAPL)  MAPL(IPLS,J) =MAPL(IPLS,J) *ZVOLIW(J)
            IF (LMMPL)  MMPL(IPLS,J) =MMPL(IPLS,J) *ZVOLIW(J)
            IF (LMIPL)  MIPL(IPLS,J) =MIPL(IPLS,J) *ZVOLIW(J)
            IF (LMPHPL) MPHPL(IPLS,J)=MPHPL(IPLS,J)*ZVOLIW(J)
228       CONTINUE
        SCLTAL(IPLS,14)=3
        SCLTAL(IPLS,20)=3
        SCLTAL(IPLS,26)=3
        SCLTAL(IPLS,32)=3
        SCLTAL(IPLS,32)=3
        SCLTAL(IPLS,79)=3
        SCLTAL(IPLS,97)=3
        SCLTAL(IPLS,98)=3
        SCLTAL(IPLS,99)=3
        SCLTAL(IPLS,100)=3
        ENDIF
227   CONTINUE
C
C  ADDITIONAL TRACKLENGTH ESTIMATED TALLIES FOR THE STRATUM ISTRA
C  TALLY NO. NTALA
C
      IF (LADDV) THEN
        DO 230 IADV=1,NADVI
          IF (IADVE(IADV).EQ.1) THEN
C  SCALE # PER VOLUME
            DO 231 J=1,NSBOX_TAL
              ADDV(IADV,J)=ADDV(IADV,J)*ZVOLIN(J)
231         CONTINUE
            SCLTAL(IADV,NTALA)=1
          ELSEIF (IADVE(IADV).EQ.2) THEN
C  SCALE # PER CELL
            DO 232 J=1,NSBOX_TAL
              ADDV(IADV,J)=ADDV(IADV,J)*ZW
232         CONTINUE
            SCLTAL(IADV,NTALA)=2
C  SCALE AMP/S PER VOLUME
          ELSEIF (IADVE(IADV).EQ.3) THEN
            DO 233 J=1,NSBOX_TAL
              ADDV(IADV,J)=ADDV(IADV,J)*ZVOLIW(J)
233         CONTINUE
            SCLTAL(IADV,NTALA)=3
C  SCALE AMP/S PER CELL
          ELSEIF (IADVE(IADV).EQ.4) THEN
            DO 234 J=1,NSBOX_TAL
              ADDV(IADV,J)=ADDV(IADV,J)*ZWW
234         CONTINUE
            SCLTAL(IADV,NTALA)=4
C         ELSE
C  DON'T SCALE AT ALL
            SCLTAL(IADV,NTALA)=0
          ENDIF
230     CONTINUE
      END IF
C
C  ADDITIONAL COLLISION ESTIMATED TALLIES FOR THE STRATUM ISTRA
C  TALLY NO. NTALC
C
      IF (LCOLV) THEN
        DO 235 ICLV=1,NCLVI
          IF (ICLVE(ICLV).EQ.1) THEN
C  SCALE # PER VOLUME
            DO 236 J=1,NSBOX_TAL
              COLV(ICLV,J)=COLV(ICLV,J)*ZVOLIN(J)
236         CONTINUE
            SCLTAL(ICLV,NTALC)=1
          ELSEIF (ICLVE(ICLV).EQ.2) THEN
C  SCALE # PER CELL
            DO 237 J=1,NSBOX_TAL
              COLV(ICLV,J)=COLV(ICLV,J)*ZW
237         CONTINUE
            SCLTAL(ICLV,NTALC)=2
          ELSEIF (ICLVE(ICLV).EQ.3) THEN
C  SCALE AMP/S PER VOLUME
            DO 238 J=1,NSBOX_TAL
              COLV(ICLV,J)=COLV(ICLV,J)*ZVOLIW(J)
238         CONTINUE
            SCLTAL(ICLV,NTALC)=3
          ELSEIF (ICLVE(ICLV).EQ.4) THEN
C  SCALE AMP/S PER CELL
            DO 239 J=1,NSBOX_TAL
              COLV(ICLV,J)=COLV(ICLV,J)*ZWW
239         CONTINUE
            SCLTAL(ICLV,NTALC)=4
C         ELSE
C  DON'T SCALE AT ALL
            SCLTAL(ICLV,NTALC)=0
          ENDIF
235     CONTINUE
      END IF
C
C  ADDITIONAL SNAPSHOT ESTIMATED TALLIES FOR THE STRATUM ISTRA
C  TALLY NO. NTALT, FIRST: SNAPV=SNAPV*DTIMV, THEN: SCALING
C
      IF (LSNAPV) THEN
        DO 245 ISNV=1,NSNVI
          IF (ISNVE(ISNV).EQ.1) THEN
C  SCALE # PER VOLUME
            DO 246 J=1,NSBOX_TAL
              SNAPV(ISNV,J)=SNAPV(ISNV,J)*DTIMV*ZVOLIN(J)
246         CONTINUE
            SCLTAL(ISNV,NTALT)=1
          ELSEIF (ISNVE(ISNV).EQ.2) THEN
C  SCALE # PER CELL
            DO 247 J=1,NSBOX_TAL
              SNAPV(ISNV,J)=SNAPV(ISNV,J)*DTIMV*ZW
247         CONTINUE
            SCLTAL(ISNV,NTALT)=2
          ELSEIF (ISNVE(ISNV).EQ.3) THEN
C  SCALE AMP/S PER VOLUME
            DO 248 J=1,NSBOX_TAL
              SNAPV(ISNV,J)=SNAPV(ISNV,J)*DTIMV*ZVOLIW(J)
248         CONTINUE
            SCLTAL(ISNV,NTALT)=3
          ELSEIF (ISNVE(ISNV).EQ.4) THEN
C  SCALE AMP/S PER CELL
            DO 249 J=1,NSBOX_TAL
              SNAPV(ISNV,J)=SNAPV(ISNV,J)*DTIMV*ZWW
249         CONTINUE
            SCLTAL(ISNV,NTALT)=4
C         ELSE
C  DON'T SCALE AT ALL
            DO J=1,NSBOX_TAL
              SNAPV(ISNV,J)=SNAPV(ISNV,J)*DTIMV
            ENDDO
            SCLTAL(ISNV,NTALT)=0
          ENDIF
245     CONTINUE
      END IF
C
C  TALLIES FOR FLUID CODE COUPLING FOR THE STRATUM ISTRA
C  TALLY NO. NTALM
C
      IF (LCOPV) THEN
        DO 255 ICPV=1,NCPVI
          IF (ICPVE(ICPV).EQ.1) THEN
C  SCALE # PER VOLUME
            DO 256 J=1,NSBOX_TAL
              COPV(ICPV,J)=COPV(ICPV,J)*ZVOLIN(J)
256         CONTINUE
            SCLTAL(ICPV,NTALM)=1
          ELSEIF (ICPVE(ICPV).EQ.2) THEN
C  SCALE # PER CELL
            DO 257 J=1,NSBOX_TAL
              COPV(ICPV,J)=COPV(ICPV,J)*ZW
257         CONTINUE
            SCLTAL(ICPV,NTALM)=2
          ELSEIF (ICPVE(ICPV).EQ.3) THEN
C  SCALE AMP/S PER VOLUME
            DO 258 J=1,NSBOX_TAL
              COPV(ICPV,J)=COPV(ICPV,J)*ZVOLIW(J)
258         CONTINUE
            SCLTAL(ICPV,NTALM)=3
          ELSEIF (ICPVE(ICPV).EQ.4) THEN
C  SCALE AMP/S PER CELL
            DO 259 J=1,NSBOX_TAL
              COPV(ICPV,J)=COPV(ICPV,J)*ZWW
259         CONTINUE
            SCLTAL(ICPV,NTALM)=4
C         ELSE
C  DON'T SCALE AT ALL
            SCLTAL(ICPV,NTALM)=0
          ENDIF
255     CONTINUE
      END IF
C
C  TALLIES FOR ITERATIVE MODE, E.G.: BGK OPTION. STRATUM ISTRA
C  TALLY NO. NTALB
C
      IF (LBGKV) THEN
        DO 265 IBGV=1,NBGVI
          IF (IBGVE(IBGV).EQ.1) THEN
C  SCALE # PER VOLUME
            DO 266 J=1,NSBOX_TAL
              BGKV(IBGV,J)=BGKV(IBGV,J)*ZVOLIN(J)
266         CONTINUE
            SCLTAL(IBGV,NTALB)=1
          ELSEIF (IBGVE(IBGV).EQ.2) THEN
C  SCALE # PER CELL
            DO 267 J=1,NSBOX_TAL
              BGKV(IBGV,J)=BGKV(IBGV,J)*ZW
267         CONTINUE
            SCLTAL(IBGV,NTALB)=2
          ELSEIF (IBGVE(IBGV).EQ.3) THEN
C  SCALE AMP/S PER VOLUME
            DO 268 J=1,NSBOX_TAL
              BGKV(IBGV,J)=BGKV(IBGV,J)*ZVOLIW(J)
268         CONTINUE
            SCLTAL(IBGV,NTALB)=3
          ELSEIF (IBGVE(IBGV).EQ.4) THEN
C  SCALE AMP/S PER CELL
            DO 269 J=1,NSBOX_TAL
              BGKV(IBGV,J)=BGKV(IBGV,J)*ZWW
269         CONTINUE
            SCLTAL(IBGV,NTALB)=4
C         ELSE
C  DON'T SCALE AT ALL
            SCLTAL(IBGV,NTALB)=0
          ENDIF
265     CONTINUE
      END IF
C
C  OTHER TALLIES ESTIMATED FROM HISTORIES
C
      DO 270 J=1,NSBOX_TAL
        IF (LPAEL)  PAEL(J) =PAEL(J) *ZVOLIW(J)
        IF (LEAEL)  EAEL(J) =EAEL(J) *ZVOLIW(J)
        IF (LEAAT)  EAAT(J) =EAAT(J) *ZVOLIW(J)
        IF (LEAML)  EAML(J) =EAML(J) *ZVOLIW(J)
        IF (LEAPL)  EAPL(J) =EAPL(J) *ZVOLIW(J)
        IF (LEAIO)  EAIO(J) =EAIO(J) *ZVOLIW(J)
        IF (LEAPHT) EAPHT(J)=EAPHT(J)*ZVOLIW(J)
C
        IF (LPMEL)  PMEL(J) =PMEL(J) *ZVOLIW(J)
        IF (LEMEL)  EMEL(J) =EMEL(J) *ZVOLIW(J)
        IF (LEMAT)  EMAT(J) =EMAT(J) *ZVOLIW(J)
        IF (LEMML)  EMML(J) =EMML(J) *ZVOLIW(J)
        IF (LEMIO)  EMIO(J) =EMIO(J) *ZVOLIW(J)
        IF (LEMPHT) EMPHT(J)=EMPHT(J)*ZVOLIW(J)
        IF (LEMPL)  EMPL(J) =EMPL(J) *ZVOLIW(J)
C
        IF (LPIEL)  PIEL(J) =PIEL(J) *ZVOLIW(J)
        IF (LEIEL)  EIEL(J) =EIEL(J) *ZVOLIW(J)
        IF (LEIAT)  EIAT(J) =EIAT(J) *ZVOLIW(J)
        IF (LEIML)  EIML(J) =EIML(J) *ZVOLIW(J)
        IF (LEIIO)  EIIO(J) =EIIO(J) *ZVOLIW(J)
        IF (LEIPHT) EIPHT(J)=EIPHT(J)*ZVOLIW(J)
        IF (LEIPL)  EIPL(J) =EIPL(J) *ZVOLIW(J)
C
        IF (LPPHEL)  PPHEL(J) =PPHEL(J) *ZVOLIW(J)
        IF (LEPHEL)  EPHEL(J) =EPHEL(J) *ZVOLIW(J)
        IF (LEPHAT)  EPHAT(J) =EPHAT(J) *ZVOLIW(J)
        IF (LEPHML)  EPHML(J) =EPHML(J) *ZVOLIW(J)
        IF (LEPHIO)  EPHIO(J) =EPHIO(J) *ZVOLIW(J)
        IF (LEPHPHT) EPHPHT(J)=EPHPHT(J)*ZVOLIW(J)
        IF (LEPHPL)  EPHPL(J) =EPHPL(J) *ZVOLIW(J)

        IF (LEPAT)  EPAT(J) =EPAT(J) *ZVOLIW(J)
        IF (LEPML)  EPML(J) =EPML(J) *ZVOLIW(J)
        IF (LEPIO)  EPIO(J) =EPIO(J) *ZVOLIW(J)
        IF (LEPPHT) EPPHT(J)=EPPHT(J)*ZVOLIW(J)
        IF (LEPPL)  EPPL(J) =EPPL(J) *ZVOLIW(J)
270   CONTINUE
      SCLTAL(1,9)=3
      SCLTAL(1,15)=3
      SCLTAL(1,21)=3
      SCLTAL(1,27)=3
      SCLTAL(1,33)=3
      SCLTAL(1,34)=3
      SCLTAL(1,35)=3
      SCLTAL(1,36)=3
      SCLTAL(1,37)=3
      SCLTAL(1,38)=3
      SCLTAL(1,39)=3
      SCLTAL(1,40)=3
      SCLTAL(1,41)=3
      SCLTAL(1,42)=3
      SCLTAL(1,43)=3
      SCLTAL(1,44)=3
      SCLTAL(1,45)=3
      SCLTAL(1,46)=3
      SCLTAL(1,47)=3
      SCLTAL(1,48)=3
      SCLTAL(1,49)=3
      SCLTAL(1,50)=3
      SCLTAL(1,51)=3
      SCLTAL(1,52)=3
      SCLTAL(1,53)=3
      SCLTAL(1,54)=3
      SCLTAL(1,55)=3
      SCLTAL(1,56)=3
      SCLTAL(1,80)=3
      SCLTAL(1,81)=3
      SCLTAL(1,82)=3
      SCLTAL(1,83)=3
      SCLTAL(1,84)=3


C   SCALE AND INTEGRATE SPECTRA

      DO ISPC=1,NADSPC
        IF (ESTIML(ISPC)%PSPC%ISRFCLL /= 0) THEN
          ICL = ESTIML(ISPC)%PSPC%ISPCSRF
          IF (ESTIML(ISPC)%PSPC%ISRFCLL == 1) THEN
!  scoring cell
            ZFAC = ZVOLIN(ICL)
          ELSE IF (ESTIML(ISPC)%PSPC%ISRFCLL == 2) THEN
!  geometry cell
            ZFAC = ZW / VOL(ICL)
          ELSE
            ZFAC = 1._DP
            WRITE (IUNOUT,*) ' NO SCALING PERFORMED FOR SPECTRUM NO. ',
     .                         ISPC
          END IF
          ESTIML(ISPC)%PSPC%SPC = ESTIML(ISPC)%PSPC%SPC * ZFAC *
     .                            ESTIML(ISPC)%PSPC%SPCDELI
          ESTIML(ISPC)%PSPC%SPCINT = SUM(ESTIML(ISPC)%PSPC%SPC*
     .                                   ESTIML(ISPC)%PSPC%SPCDEL)
        END IF  
      END DO


      RETURN

      END SUBROUTINE SCAL_VOLAV_TALLIES
