#!/bin/bash
echo "Starting d-solps-sas-like-a2 batch run (79 bins)"
echo "C-52 case"
date
rundiv_walldyn d-solps-sas-like-a2_C_52 d-sasv-lsn-plots carre_sas-like fort.31_sas-like-exbnor >& logfile.d-solps-sas-like-a2_C_52
echo "C-53 case"
date
rundiv_walldyn d-solps-sas-like-a2_C_53 d-sasv-lsn-plots carre_sas-like fort.31_sas-like-exbnor >& logfile.d-solps-sas-like-a2_C_53
echo "C-54 case"
date
rundiv_walldyn d-solps-sas-like-a2_C_54 d-sasv-lsn-plots carre_sas-like fort.31_sas-like-exbnor >& logfile.d-solps-sas-like-a2_C_54
echo "C-55 case"
date
rundiv_walldyn d-solps-sas-like-a2_C_55 d-sasv-lsn-plots carre_sas-like fort.31_sas-like-exbnor >& logfile.d-solps-sas-like-a2_C_55
echo "C-56 case"
date
rundiv_walldyn d-solps-sas-like-a2_C_56 d-sasv-lsn-plots carre_sas-like fort.31_sas-like-exbnor >& logfile.d-solps-sas-like-a2_C_56
echo "C-57 case"
date
rundiv_walldyn d-solps-sas-like-a2_C_57 d-sasv-lsn-plots carre_sas-like fort.31_sas-like-exbnor >& logfile.d-solps-sas-like-a2_C_57
echo "C-58 case"
date
rundiv_walldyn d-solps-sas-like-a2_C_58 d-sasv-lsn-plots carre_sas-like fort.31_sas-like-exbnor >& logfile.d-solps-sas-like-a2_C_58
echo "C-59 case"
date
rundiv_walldyn d-solps-sas-like-a2_C_59 d-sasv-lsn-plots carre_sas-like fort.31_sas-like-exbnor >& logfile.d-solps-sas-like-a2_C_59
echo "C-60 case"
date
rundiv_walldyn d-solps-sas-like-a2_C_60 d-sasv-lsn-plots carre_sas-like fort.31_sas-like-exbnor >& logfile.d-solps-sas-like-a2_C_60
echo "C-61 case"
date
rundiv_walldyn d-solps-sas-like-a2_C_61 d-sasv-lsn-plots carre_sas-like fort.31_sas-like-exbnor >& logfile.d-solps-sas-like-a2_C_61
echo "C-62 case"
date
rundiv_walldyn d-solps-sas-like-a2_C_62 d-sasv-lsn-plots carre_sas-like fort.31_sas-like-exbnor >& logfile.d-solps-sas-like-a2_C_62
echo "C-63 case"
date
rundiv_walldyn d-solps-sas-like-a2_C_63 d-sasv-lsn-plots carre_sas-like fort.31_sas-like-exbnor >& logfile.d-solps-sas-like-a2_C_63
echo "C-64 case"
date
rundiv_walldyn d-solps-sas-like-a2_C_64 d-sasv-lsn-plots carre_sas-like fort.31_sas-like-exbnor >& logfile.d-solps-sas-like-a2_C_64
echo "C-65 case"
date
rundiv_walldyn d-solps-sas-like-a2_C_65 d-sasv-lsn-plots carre_sas-like fort.31_sas-like-exbnor >& logfile.d-solps-sas-like-a2_C_65
echo "C-66 case"
date
rundiv_walldyn d-solps-sas-like-a2_C_66 d-sasv-lsn-plots carre_sas-like fort.31_sas-like-exbnor >& logfile.d-solps-sas-like-a2_C_66
echo "C-67 case"
date
rundiv_walldyn d-solps-sas-like-a2_C_67 d-sasv-lsn-plots carre_sas-like fort.31_sas-like-exbnor >& logfile.d-solps-sas-like-a2_C_67
echo "C-68 case"
date
rundiv_walldyn d-solps-sas-like-a2_C_68 d-sasv-lsn-plots carre_sas-like fort.31_sas-like-exbnor >& logfile.d-solps-sas-like-a2_C_68
echo "C-71 case"
date
rundiv_walldyn d-solps-sas-like-a2_C_71 d-sasv-lsn-plots carre_sas-like fort.31_sas-like-exbnor >& logfile.d-solps-sas-like-a2_C_71
echo "C-74 case"
date
rundiv_walldyn d-solps-sas-like-a2_C_74 d-sasv-lsn-plots carre_sas-like fort.31_sas-like-exbnor >& logfile.d-solps-sas-like-a2_C_74
echo "C-78 case"
date
rundiv_walldyn d-solps-sas-like-a2_C_78 d-sasv-lsn-plots carre_sas-like fort.31_sas-like-exbnor >& logfile.d-solps-sas-like-a2_C_78
echo "C-81 case"
date
rundiv_walldyn d-solps-sas-like-a2_C_81 d-sasv-lsn-plots carre_sas-like fort.31_sas-like-exbnor >& logfile.d-solps-sas-like-a2_C_81
echo "C-85 case"
date
rundiv_walldyn d-solps-sas-like-a2_C_85 d-sasv-lsn-plots carre_sas-like fort.31_sas-like-exbnor >& logfile.d-solps-sas-like-a2_C_85
echo "C-88 case"
date
rundiv_walldyn d-solps-sas-like-a2_C_88 d-sasv-lsn-plots carre_sas-like fort.31_sas-like-exbnor >& logfile.d-solps-sas-like-a2_C_88
echo "C-92 case"
date
rundiv_walldyn d-solps-sas-like-a2_C_92 d-sasv-lsn-plots carre_sas-like fort.31_sas-like-exbnor >& logfile.d-solps-sas-like-a2_C_92
echo "C-95 case"
date
rundiv_walldyn d-solps-sas-like-a2_C_95 d-sasv-lsn-plots carre_sas-like fort.31_sas-like-exbnor >& logfile.d-solps-sas-like-a2_C_95
echo "C-98 case"
date
rundiv_walldyn d-solps-sas-like-a2_C_98 d-sasv-lsn-plots carre_sas-like fort.31_sas-like-exbnor >& logfile.d-solps-sas-like-a2_C_98
echo "C-101 case"
date
rundiv_walldyn d-solps-sas-like-a2_C_101 d-sasv-lsn-plots carre_sas-like fort.31_sas-like-exbnor >& logfile.d-solps-sas-like-a2_C_101
