#!/bin/tcsh
#
  alias ls ls
#
# ======================================================================
# PROCESS INPUT FLAGS
# ======================================================================
#
source $DIVHOME/scripts/run_divimp_process_flags $1 $2 $3 $4 $5 $6 $7 $8 $9 $10 $11 $12 $13 $14 $15
#
#
# ======================================================================
# SET SHELL VARIABLES
# ======================================================================
#
# DIVIMP root directory:
#  setenv DIVHOME ~/divimp

  setenv ADASCENT $DIVHOME/adas/
  setenv EIRDIR   $DIVHOME/$EIRTEMP
  setenv RESDIRTOP $DIVHOME/results
  source $DIVHOME/scripts/results_resdir $CASENAME

# Location of graphics library used by EIRENE:
  setenv GLI_HOME $DIVHOME/libsrc

# Set local directories:
  set    RUNDIR = $DIVHOME
  set    BATDIR = $DIVHOME/scripts
  setenv EXEDIR $DIVHOME/cases/$CASENAME.$$
  set    EQUDIR = $DIVHOME/shots
  set    DATDIR = $DIVHOME/data
  set    OUTDIR = $DIVHOME/out6

  setenv DIVDATDIR $DATDIR  # for ribbon grid code
#
# ----------------------------------------------------------------------
# Set DIVIMP/OUT executables:
#
  set DIVDIR = $DIVHOME/div6
  set DIVEXE = divimp
  set OUTEXE = out
  set DIVEXT = d6i
  if ( $MYEXT != "default" ) set DIVDIR = $DIVDIR.$MYEXT
  if ( $X86_64             ) set DIVDIR = $DIVDIR.64
#
# ----------------------------------------------------------------------
# Create and enter execution directory:
#
#  cd $DIVHOME/cases
#  if ( -e $CASENAME ) rm -rf $CASENAME
#  mkdir $CASENAME
#  cd    $CASENAME
  if ( -e $EXEDIR ) rm -rf $EXEDIR
  mkdir $EXEDIR
  cd    $EXEDIR
#  echo $QSUB_ID > qsub_id.txt
#  if ( $QSUB_ID != "none" ) then
#    ll ../* > ../test.dump
#    rm ../$QSUB_ID*
#  endif
#
# ----------------------------------------------------------------------
# Case parameter summary to the screen:
#
                              echo 
                              echo  "  DIVIMP case         : $CASENAME"
                              echo  "  Run directory       : $EXEDIR"
                              echo  "  OUT input file      : $OUTNAME"
                              echo  "  Geometry file       : $GRIDNAME"
  if ( $SAVENAME != "")       echo  "  Saved plasma case   : $SAVENAME"
  if ( $DEVICE  != "unknown") echo  "  Device name         : $DEVICE "
  if ( $DEVICE  != "unknown") echo  "  Data directory      : $DEVDIR "
  if ( $OUTONLY == "no")      echo  "  EIRENE version      : $EIRTEMP"
  if ( $OUTONLY == "no")      echo  "         template     : $EIRFILE"
  if ( $EIRRAW  == "yes")     echo  "         fort.13      : $EIRRAW "
  if ( $EIR15 != ""    )      echo  "         fort.15      : $EIR15  "
  if ( $EIRPHOTONS == "yes") then
                              echo  "    Following photons..."
  endif
  if ( $OUTONLY == "yes")     echo  "  OUT execution only  : yes"
  if ( $X86_64 )              echo  "  64-bit operation    : yes     "

                              echo 
#
# ======================================================================
# COPY SETUP FILES
# ======================================================================
#
  source $DIVHOME/scripts/run_divimp_prepare_files
#
# ======================================================================
# EXECUTE
# ======================================================================
#
    if ( $OUTONLY == "no" ) then
#
#     --------------------------------------------------------------------
#     Execute DIVIMP:
#
      echo
      echo "  Executing DIVIMP version 6 :" $MYEXT
      echo 
#      $DIVEXE < fort.5 > divout1
      nice +2 $DIVEXE < fort.5 > divout1
#    Xpgdbg $DIVEXE < fort.5 > divout1

#     Process this output now, since these file units conflict with OUT:
      mvc POSTSCPT.LIS old.LIS
      mvc fort.50 $CASENAME.slm
      mvc fort.7  $CASENAME.dat
      mvc fort.22 $CASENAME.html
      mvc fort.88 $CASENAME.src
    endif
#
#   ----------------------------------------------------------------------
#   Execute OUT:
#
    if       ( $OUTNAME == "none" ) then
      echo "OUT not executed - by request"
    else if !( -e $DATDIR/$OUTNAME.d6o ) then
      echo "OUT not executed - input file $OUTNAME.d6o not found"
    else if !( -e fort.8 ) then
      echo "OUT not executed - RAW data file not found"
    else
      if ( $MYEXT != "default" ) set OUTDIR = $OUTDIR.$MYEXT
      if ( $X86_64             ) set OUTDIR = $OUTDIR.64
      cp $DATDIR/$OUTNAME.d6o fort.99
      if ( -e $DATDIR/$CASENAME.d6i ) then
        echo
        echo "  Executing OUT version 6 :" $MYEXT
        echo 
#      Xpgdbg $RUNDIR/out6/$OUTEXE < fort.99 > outout1
#        nice +2 $OUTDIR/$OUTEXE < fort.99 > outout1
        nice +2 $OUTEXE < outinput.dat > outout1
      endif
    endif
  endif
#
#
# ======================================================================
# PROCESS RESULTS
# ======================================================================
#
# ----------------------------------------------------------------------
# Rename DIVIMP/OUT files:
#

#  if ( -e POSTSCPT.LIS ) then
#    ps2pdf POSTSCPT.LIS $CASENAME.pdf
#  endif

  mvc fort.22 $CASENAME.html

#  mvc fort.99 $CASENAME.divdat
  mvc divout1 $CASENAME.lim
  mvc fort.17 $CASENAME.pin
  mvc fort.21 $CASENAME.sol
  mvc fort.62 $CASENAME.bgp
  mvc divimp_plasma.out $CASENAME.bgp

  mvc outout1      $CASENAME.out
  mvc POSTSCPT.LIS $CASENAME.ps
  mvc fort.49      $CASENAME.plt
  mvc outdata.dat  $CASENAME.anl

  if ( $OUTONLY == "yes" ) then
    echo 'NOT PROCESSING .RAW FILES (OUTONLY = YES)'
  else
    mvc fort.8           $CASENAME.raw
    mvc plasma.dat       $CASENAME.raw.pla
    mvc source.dat       $CASENAME.raw.src
    mvc geomty.dat       $CASENAME.raw.geo
    mvc triangles.raw    $CASENAME.raw.tri
    mvc fort.79          $CASENAME.raw.rel
    mvc vac-grid.dat     $CASENAME.raw.vac
    mvc jummap.dat       $CASENAME.raw.jum
    mvc osm.raw          $CASENAME.raw.osm
    mvc osm_geometry.raw $CASENAME.raw.ogd
    mvc osm_legacy.raw   $CASENAME.raw.old
#   Process tetrahedron files:
    rename ".raw" ".raw.tet" -- tetrahedrons*.raw
    rename ".raw" ".raw.fil" -- filaments*.raw
    rename "tetrahedrons" "$CASENAME" -- tetrahedrons*.raw.tet
    rename "filaments"    "$CASENAME" -- filaments*.raw.fil
  endif

  mvc fort.90 $CASENAME.osm.log
  mvc fort.85 $CASENAME.g1
  mvc fort.86 $CASENAME.g2
  mvc fort.87 $CASENAME.g3
  mvc fort.65 $CASENAME.e1
  mvc fort.66 $CASENAME.e2
  mvc fort.67 $CASENAME.e3
  mvc fort.25 $CASENAME.sonnet

  mvc dump.dat $CASENAME.dump

  mvc fort.52 $CASENAME.eig

  mvc line.dat   $CASENAME.dat.line
  mvc strata.dat $CASENAME.dat.strata
  mvc bgk.dat    $CASENAME.dat.bgk
#  mvc acd.dat    $CASENAME.dat.acd
  mvc rec.dat    $CASENAME.dat.rec

  mvc fort.9     $CASENAME.inp

  mvc addsur.dat    $CASENAME.addsur

  if ( $OUTONLY == "no" ) then
    mvc triangles.dat       $CASENAME.triangles
    mvc triangles.npco_char $CASENAME.triangles.npco_char
    mvc triangles.elemente  $CASENAME.triangles.elemente
    mvc triangles.neighbors $CASENAME.triangles.neighbors
    mvc triangles.plasma    $CASENAME.triangles.plasma
    mvc triangles.efield    $CASENAME.triangles.efield

    mvc quadrangles.geometry $CASENAME.quadrangles.geometry
    mvc quadrangles.plasma   $CASENAME.quadrangles.plasma
    mvc quadrangles.efield   $CASENAME.quadrangles.efield

    mvc objects.dat       $CASENAME.triangles
    mvc objects.npco_char $CASENAME.objects.npco_char
    mvc objects.elemente  $CASENAME.objects.elemente
    mvc objects.neighbors $CASENAME.objects.neighbors
    mvc objects.plasma    $CASENAME.objects.plasma
    mvc objects.centre    $CASENAME.objects.centre
    mvc objects.efield    $CASENAME.objects.efield
  endif

#  mvc    osm.idl $CASENAME.osm
  rename osm     $CASENAME         -- osm.idl.*
  rename divimp  $CASENAME         -- divimp.* 
  rename output  $CASENAME.out     -- output.*
  rename idl     $CASENAME.idl     -- idl.*
  rename profile $CASENAME.profile -- profile.*      # line-of-sight profiles from RAY

  mvc plasma-transfer.dat $CASENAME.rzplasma
  mvc cell.dat            $CASENAME.dat.cell
  rename ".transfer" ".eir"      -- eirene*.transfer
  rename ".input"    ".eirdat"   -- eirene*.input
  rename ".output"   ".eirprn"   -- eirene*.output
  rename "eirene"    "$CASENAME" -- eirene*.eir*
#  mvc eirene.transfer     $CASENAME.eir

  mvc eirene.spectra $CASENAME.eir.spectra

  cpc core_analysis.dat $CASENAME.dat.midplane
#  mvc core_analysis.dat ~/idl/lc/$CASENAME.dat
  

# Inversions:
#
# ----------------------------------------------------------------------
# Rename image inversion related files:
#
  foreach FILENAME (`ls *.ray.*`)
    mv $FILENAME $CASENAME.$FILENAME
  end
#  foreach FILENAME (`ls *.idl.*`)
#    mv $FILENAME $CASENAME.$FILENAME
#  end
#
# ----------------------------------------------------------------------
# Divertor data dump (temporary):
#
  foreach FILENAME (`ls div.*`)
    mv $FILENAME $CASENAME.$FILENAME
  end
#
# ----------------------------------------------------------------------
# MatLab files:
#
  foreach FILENAME (`ls mlb.*`)
    mv $FILENAME $CASENAME.$FILENAME
  end
#
# ----------------------------------------------------------------------
# Marie-Helene data files for reflection modelling:
#
  foreach FILENAME (`ls mhf.*`)
    mv $FILENAME $CASENAME.$FILENAME
  end
  foreach FILENAME (`ls akf.*`)
    mv $FILENAME $CASENAME.$FILENAME
  end
#
# ----------------------------------------------------------------------
# Martin O'Mullane files:
#
  mv mom $CASENAME.mom
#
# ----------------------------------------------------------------------
# Field line traces for ribbon grid:
#
  rm -f *.trace.*
  foreach FILENAME (`ls trace.*`)
    mv -f $FILENAME $CASENAME.$FILENAME
  end
#
  mv *image*.jpg $RESDIR
#
# ----------------------------------------------------------------------
# Rename some EIRENE files:
#
  if ($EIRPHOTONS == "yes") mvc eirene.13 $CASENAME.eir13
  mvc eirene.15   $CASENAME.eir15
  mvc eirene.d10  $CASENAME.eird10
  mvc eirene.d11  $CASENAME.eird11
  mvc eirtrac.dat $CASENAME.eirtrc
#  rm *.eirtim
#
# ----------------------------------------------------------------------
# Rename SOL23 files:
#
  mvc fort.71 $CASENAME.sol23
  mvc fort.73 $CASENAME.exl23
  mvc fort.75 $CASENAME.cfd
#
# ----------------------------------------------------------------------
# Compress large files:
#
  if ( $OUTONLY == "yes" ) then
    echo 'NOT PROCESSING .RAW FILES (OUTONLY = YES)'
  else
    zipc $CASENAME.raw
    zipc $CASENAME.raw.src
    zipc $CASENAME.raw.pla
    zipc $CASENAME.raw.geo
    zipc $CASENAME.raw.rel
    zipc $CASENAME.raw.vac
    zipc $CASENAME.raw.jum
    zipc $CASENAME.raw.tri
    foreach FILENAME (`ls *raw.tet`)
      zipc $FILENAME
    end
    foreach FILENAME (`ls *.eir`)
      zipc $FILENAME
    end
    zipc $CASENAME.raw.osm
    zipc $CASENAME.raw.ogd
    zipc $CASENAME.raw.old
  endif
#  zipc $CASENAME.eir
#  zipc $CASENAME.pin
#  zipc $CASENAME.eird10
#  zipc $CASENAME.eird11
#
# ----------------------------------------------------------------------
# Move files for upload to the web:
#
#  mvc $CASENAME.html $RESDIR/transfer
#  mvc $CASENAME.pdf  $RESDIR/transfer
#
# ----------------------------------------------------------------------
#
# Move all files to results directory, replacing any previous results:
#
  rm *.A
#  zipc *.A
  rm *.map

  if ($OUTONLY == "no") rm $RESDIR/$CASENAME.*

  mv -f $CASENAME.* $RESDIR
  chmod u+r $RESDIR/$CASENAME.*
#
# ----------------------------------------------------------------------
# Try to collect QSUB log files
#
#  if ( $QSUB_ID != "none" ) then
#echo here! trying! > ../message.1
#    echo QSUM_ID is:
#    echo $QSUB_ID
#    $DIVHOME/scripts/qsub_report $EXEDIR $QSUB_ID $RESDIR $CASENAME &
#    echo "$DIVHOME/scripts/qsub_report $EXEDIR $QSUB_ID $RESDIR $CASENAME" > ../message.2
#    sleep 10
#  endif 
#
# ----------------------------------------------------------------------
# Clean:
#
  if ( $CLEAN == "yes" ) then
#    cd $DIVHOME/cases
#    rm -r -f $CASENAME
    rm -r -f $EXEDIR
  else
    echo "  Not cleaning execution directory"
  endif
#
#
#





