C
C
      SUBROUTINE FMAXWL
C
C  SAMPLE IRNDVC RANDOM NUMBERS FROM A GAUSSIAN FLUX V*FMAX(V)
C  AND RETURN THEM THE ARRAY FM1
C  SAMPLE IRNDVC PAIRS OF RANDOM NUMBER FROM A GAUSSIAN
C  AND RETURN THEM IN THE ARRAYS FM2 AND FM3
C  THIS ROUTINE IS CALLED WHEN INIV1.EQ.0. IT RESETS INIV1=IRNDVC
C
      USE CRAND

      IMPLICIT NONE

      REAL(DP) :: PI2, ZCOS, ZSIN, ZT, AR, ZZ
      REAL(DP), EXTERNAL :: RANF_EIRENE
      INTEGER :: JJ

      DATA PI2/6.283185/
C
C  THIS FUNCTION SAMPLES FROM A GAUSSIAN OF THE
C  FORM EXP(-(X-ZA)**2/(2.*ZS**2))/(ZS*SQRT(2*PI))
C  ZA=0.
C  ZS=1.
C
C  IT IS THE BOX-MUELLER METHOD
C
C
      DO 1 JJ=1,IRNDVC
C   1. COMPUTE THE SINE AND COSINE OF 2*PI*RAN(1)
C
        ZZ=PI2*RANF_EIRENE( )
        ZSIN=SIN(ZZ)
        ZCOS=COS(ZZ)
C
        AR=LOG(RANF_EIRENE( ))
        ZT=SQRT(-(AR+AR))
        FM2(JJ)=ZT*ZSIN
        FM3(JJ)=ZT*ZCOS
1     CONTINUE
C
C  SAMPLE FROM MAXWELLIAN FLUX BY INVERSION RULE
C
      DO 2 JJ=1,IRNDVC
        AR=LOG(RANF_EIRENE( ))
        FM1(JJ)=SQRT(-(AR+AR))
2     CONTINUE
      INIV1=IRNDVC
      RETURN
      END
