C   THIS CODE SEGMENT CONTAINES VARIOUS SUBROUTINES NEEDED FOR
C   INTERFACING THE EIRENE CODE TO PLASMA FLUID CODES.
C   IT READS GEOMETRICAL DATA (MESHES) FROM FILE FT30
C   AND PRODUCES THE EIRENE INPUT DATA (BLOCK 2).
C   IT READS PLASMA BACKGROUND DATA FROM FILE (FT31) OR COMMON BLOCKS,
C   IT THEN PRODUCES INPUT DATA FOR EIRENE
C   INPUT BLOCK 5 (PLASMA DATA) AND BLOCK 7 (SURFACE RECYCLING SOURCES)
C
C
C   THIS PARTICULAR VERSION LINKS EIRENE TO THE B2   2D MULTIFLUID EDGE
C   PLASMA TRANSPORT CODE.
C
C   IT WAS WRITTEN BY D.REITER AND P.BOERNER, KFA-JUELICH
C   E-MAIL: D.REITER @ KFA-JUELICH.DE
C
C
C
C   MOST OF THE FORTRAN IN THIS CODE SEGMENT HAS BEEN DEVELOPED
C   UNDER KFA-NET CONTRACT NO. 428/90-8/FU-D
C
C   FINAL REPORT BY: D.REITER(1), P.BOERNER(1), B.KUEPPERS(1),
C                    M.BAELMANS(2) AND G.P.MADDISON(3)
C                    (1992)
C   1): KFA-JUELICH GMBH
C   2): UNIV. LEUVEN, ERM, KFA-JUELICH
C   3): AEA TECHNOLOGY, FUSION, CULHAM, UKAEA FUSION ASSOCIATION
C
*DK COUPLE
C
      SUBROUTINE INFCOP
C
C
C     THIS SUBROUTINE DEFINES THE PLASMA MODEL IN CASE OF A COUPLED
C     NEUTRAL-PLASMA CALCULATION
C
C     THE ENTRY "IF0COP" RECEIVES GEOMETRICAL INPUT DATA FROM AN
C     EXTERNAL FILE (E.G. OTHER PLASMA CODES)
C     AND PREPARES THEM FOR AN EIRENE RUN
C
C     THE ENTRY "IF1COP" RECEIVES PLASMA INPUT DATA FROM AN
C     EXTERNAL FILE (E.G. OTHER PLASMA CODES)
C     AND PREPARES THEM FOR AN EIRENE RUN
C
C     THE ENTRY "IF2COP" PREPARES THE SOURCE SAMPLING DISTRIBUTION
C     FROM THE EXTERNAL DATA, AND MAY OVERWRITE OTHER INPUT
C     DATA FROM BLOCKS 1 TO 13 AS WELL
C
C     THE ENTRIES "IF3COP, IF4COP" RETURN  RESULTS TO AN EXTERNAL FILE
C
C
C
      USE PRECISION
      USE PARMMOD
      USE BRASPOI
      USE COMUSR
      USE CESTIM
      USE CADGEO
      USE CCONA
      USE CLOGAU
      USE CPLOT
      USE CINIT
      USE CPOLYG
      USE CGRID
      USE CZT1
      USE CTRCEI
      USE CCOUPL
      USE CGEOM
      USE CSDVI
      USE CSDVI_BGK
      USE CSDVI_COP
      USE CTETRA
      USE COMPRT
      USE COMNNL
      USE COMSOU
      USE CSTEP
      USE CTEXT
      USE CLGIN
      USE COUTAU
      USE COMXS
      USE CSPEI
      USE CTRIG
      USE module_avltree

      IMPLICIT NONE

      TYPE(CELLSIM), POINTER :: CPSIM
      TYPE(CELLMUL), POINTER :: CPMUL
C
      REAL(DP) :: SCALN(0:NFL)
      REAL(DP) :: DI(NPLS), VP(NPLS)
C
      REAL(DP) :: PUX(NRAD),PUY(NRAD),PVX(NRAD),PVY(NRAD),
     R          TORL(NSTRA,NGITT),EFLX(NSTRA),
     R          DUMMY(0:NDXP,0:NDYP),
     R          ESHT(NSTEP,NGITT),ORI(NSTEP,NGITT),
     R          SFNIT(0:NSTEP),SFEIT(0:NSTEP),
     R          SFEET(0:NSTEP),SHEAE(0:NSTEP),SHEAI(0:NSTEP)
      INTEGER, ALLOCATABLE, SAVE :: NRWL(:)
C
      LOGICAL :: LSHORT, LSTOP, LSTP

      INTEGER :: NBRICK, NQUAD, NLINE
      COMMON /CINTFA/ NBRICK, NQUAD, NLINE

      INTEGER, ALLOCATABLE :: NODQUAD(:,:), NODLINE(:,:)

      INTEGER, ALLOCATABLE :: IHELP(:), NOSTS(:), NLNSTS(:), NOSPEC(:)
      REAL(DP) :: TIS(NPLS),DIS(NPLS),VXS(NPLS),VYS(NPLS),VZS(NPLS)
      REAL(SP) :: PARM(16)
      INTEGER :: ITSIDE(3,4)

      REAL(DP) :: EMAXW, ESUM, ETOT, EADD, PERWI, PARWI, FLX, FLXI, 
     .          VPX, VPY, GAMMA, SHEATH, VT, PN1, VTEST, VR, DRR,
     .          PERW, PARW, CS, CUR, X1, Y1, Z1, X2, Y2, Z2, PHI1, PHI2,
     .          STEP, THMAX, BXS, BYS, BZS, PM1, TE, VPZ,
     .          EEMAX, RP1, OR, EESHT, V, T, TES, VL, XCO, YCO, ZCO,
     .          DIST, DIST1, DIST2, DIST3, BVAC
      INTEGER :: IFIRST, NREC11, NDXY, NR1STQ, ISTRAI, IY, IRC, NFALSE,
     .           JC, J, NDXYM, NDYAM, NDXAM, N1, N2, N3IN, N3EN, ITFAL,
     .           IAOT, IAIN, IR, IP, IR1, IP1, K, MPER, N3, NT, IERROR,
     .           IPL, IMODE, IFRST, ITARG, INEW, IOLD,
     .           N1EN, N1IN, N2EN, N2IN, IPRT, NDZA, I, NTGPRI, IT, 
     .           IEPLS, I4, IIPLS, IG, NPES, ITRI, NTACT, IN, NTOLD, IS,
     .           ISTS, IC, IDU, I1, I2, I3, NOD, NTT, IEL, NLN, 
     .           NQU, IQ, IMATCH, JTRI, JS, IP2, JP1, JP2, ISP, JSP,
     .           MINIS, MAXIS, MINJS, MAXJS, ICO, ICOLUMN, IANF, NREAD
      INTEGER :: INDCO(9),INDF1(3),INDF2(3),INDF3(3),INDF4(3),INDF5(3),
     .           INDF6(3)
      INTEGER, INTENT(IN) :: ISTRAA, ISTRAE, NEW_ITER
      INTEGER, EXTERNAL :: IDEZ
      REAL, ALLOCATABLE :: TEF(:),DENF(:,:)
C
      CHARACTER(72) :: ZEILE, NAMENT, SPECNAME
      CHARACTER(10) :: CHR, FORM
      CHARACTER(6) :: CITARG
      CHARACTER(72), ALLOCATABLE :: ENTITY(:)
      CHARACTER(1000) :: LINE
      LOGICAL, ALLOCATABLE :: LUSED(:)
      TYPE(TRI_ELEM), POINTER :: CURR, CUR2
C
C
      DATA ITSIDE /1,2,3,
     .             1,4,2,
     .             2,4,3,
     .             3,4,1/
C
      SAVE
C
      ENTRY IF0COP
C
      LSHORT=.FALSE.
C
      GOTO 99990
C
C  TO INITALIZE THE SHORT CYCLING, THE GEOMETRY HAS TO BE
C  DEFINED ONCE (ENTRY: INTER0)
C
      ENTRY INTER0
      LSHORT=.TRUE.
99990 CONTINUE
C
      IERROR=0
C
      IMODE=IABS(NMODE)
C
      IF (.NOT.LSHORT.AND.ITIMV.LE.1) THEN
        WRITE (6,*) '        SUBROUTINE INFCOP IS CALLED  '
C  READ INPUT DATA OF BLOCK 14
C  SAVE INPUT DATA OF BLOCK 14 FOR SHORT CYCLE ON COMMON CCOUPL
        CALL LEER(1)
        CALL ALLOC_CCOUPL(1)
        READ (IUNIN,'(5L1)') LSYMET,LBALAN
        IF (TRCINT)
     .  WRITE (6,*) ' LSYMET,LBALAN = ',LSYMET,LBALAN
        DO 20 IPL=1,NPLSI
          READ (IUNIN,'(2I6,2E12.4)') I,IFLB(IPL),FCTE(IPL),BMASS(IPL)
          IF (TRCINT)
     .    WRITE (6,*) IPL,IFLB(IPL),FCTE(IPL),BMASS(IPL)
20      CONTINUE
C  NUMBER OF DIFFERENT ENTITIES: NTARGI
        READ (IUNIN,'(I6)') NTARGI
        WRITE (6,*) '        NTARGI= ',NTARGI
        CALL LEER(1)
        IF (NTARGI.GT.NSTEP) THEN
          CALL MASPRM ('NSTEP',5,NSTEP,'NTARGI',6,NTARGI,IERROR)
          WRITE (6,*) 'EXIT CALLED FROM SUBR. INFCOP '
          CALL EXIT
        ENDIF
        ALLOCATE (NOSTS(NTARGI))
        ALLOCATE (ENTITY(NTARGI))
        DO 30 IT=1,NTARGI
          READ (IUNIN,'(2I6,1X,A72)') I,NOSTS(IT),NAMENT
          ENTITY(IT)=ADJUSTL(TRIM(NAMENT))
          CALL UPPERCASE (ENTITY(IT))
          IF (TRCINT)
     .      WRITE (6,'(2I6,1X,A72)') IT,NOSTS(IT),ENTITY(IT)
          IF (TRCINT) CALL LEER(1)
30      CONTINUE
C  READ ADDITIONAL DATA TO BE TRANSFERRED FROM FIDAP INTO EIRENE
C  HERE: FIDAP VOLUME TALLIES
        READ (IUNIN,'(I6)') NAINB
        WRITE (6,*) '        NAINI = ',NAINB
        IF (NAINB.GT.NAIN) THEN
          CALL MASPRM ('NAIN',4,NAIN,'NAINB',5,NAINB,IERROR)
          WRITE (6,*) 'EXIT CALLED FROM SUBR. INFCOP '
          CALL EXIT
        ENDIF
        IF (TRCINT.AND.NAINB.GT.0)
     .      WRITE (6,*) 'I,NAINS(IAIN),NAINT(IAIN)'
        DO 40 IAIN=1,NAINB
          READ (IUNIN,'(6I6)') I,NAINS(IAIN),NAINT(IAIN)
          READ (IUNIN,'(A72)') TXTPLS(IAIN,12)
          READ (IUNIN,'(2A24)') TXTPSP(IAIN,12),TXTPUN(IAIN,12)
          IF (TRCINT) THEN
            WRITE (6,'(6I6)') I,NAINS(IAIN),NAINT(IAIN)
            WRITE (6,'(1X,A72)') TXTPLS(IAIN,12)
            WRITE (6,'(1X,2A24)') TXTPSP(IAIN,12),TXTPUN(IAIN,12)
          ENDIF
40      CONTINUE
C  READ ADDITIONAL DATA TO BE TRANSFERRED FROM EIRENE INTO FIDAP
C  HERE: EIRENE SURFACE TALLIES
        READ (IUNIN,'(I6)') NAOTB
        WRITE (6,*) '        NAOTI = ',NAOTB
        IF (NAOTB.GT.NLIMPS) THEN
          CALL MASPRM ('NLIMPS',6,NLIMPS,'NAOTB',5,NAOTB,IERROR)
          WRITE (6,*) 'EXIT CALLED FROM SUBR. INFCOP '
          CALL EXIT
        ENDIF
        IF (TRCINT.AND.NAOTB.GT.0)
     .      WRITE (6,*) 'I,NAOTS(IAOT),NAOTT(IAOT)'
        DO 50 IAOT=1,NAOTB
          READ (IUNIN,'(6I6)') I,NAOTS(IAOT),NAOTT(IAOT)
          IF (TRCINT) THEN
            WRITE (6,'(6I6)') I,NAOTS(IAOT),NAOTT(IAOT)
          ENDIF
50      CONTINUE
      ENDIF
C
C READING BLOCK 14 FROM FORMATTED INPUT FILE (IUNIN) FINISHED
C
C SAVE SOME MORE INPUT DATA FOR SHORT CYCLE ON COMMON CCOUPL
      LNLPLG=NLPLG
      LNLDRF=NLDRFT
      LTRCFL=TRCFLE
      NSTRI=NSTRAI
      DO 60 ISTRA=1,NSTRAI
        LNLVOL(ISTRA)=NLVOL(ISTRA)
60    CONTINUE
      NMODEI=NMODE
      NFILNN=NFILEN
C
C  DEFINE ADDITIONAL TALLIES FOR COUPLING (UPDATED IN SUBR. UPTCOP
C                                              AND IN SUBR. COLLIDE)
      NCPVI=NPLSI
      IF (NCPVI.GT.NCPV) THEN
        WRITE (6,*) 'FROM INTERFACING SUBROUTINE INFCOP: '
        CALL MASPRM('NCPV',4,NCPV,'NCPVI',5,NCPVI,IERROR)
        CALL EXIT
      ENDIF
      DO 70 IPLS=1,NPLSI
        ICPVE(IPLS)=1
        ICPRC(IPLS)=1
        TXTTAL(IPLS,NTALM)=
     .  'ENERGY WEIGHTED CX RATE OF ATOMS WITH IPLS                  '
        TXTSPC(IPLS,NTALM)=TEXTS(NSPAMI+IPLS)
        TXTUNT(IPLS,NTALM)='AMP                       '
C
        ICPVE(NPLSI+IPLS)=3
        ICPRC(NPLSI+IPLS)=1
        TXTTAL(NPLSI+IPLS,NTALM)=
     .  'PAR. MOM. SOURCE, FROM ATOMS, FOR IPLS             '
        TXTSPC(NPLSI+IPLS,NTALM)=TEXTS(NSPAMI+IPLS)
        TXTUNT(NPLSI+IPLS,NTALM)='G*CM/S* AMP * CM**-3       '
C
        ICPVE(2*NPLSI+IPLS)=3
        ICPRC(2*NPLSI+IPLS)=2
        TXTTAL(2*NPLSI+IPLS,NTALM)=
     .  'PAR. MOM. SOURCE, FROM MOLECULES, FOR IPLS         '
        TXTSPC(2*NPLSI+IPLS,NTALM)=TEXTS(NSPAMI+IPLS)
        TXTUNT(2*NPLSI+IPLS,NTALM)='G*CM/S* AMP * CM**-3       '
C
        ICPVE(3*NPLSI+IPLS)=3
        ICPRC(3*NPLSI+IPLS)=3
        TXTTAL(3*NPLSI+IPLS,NTALM)=
     .  'PAR. MOM. SOURCE, FROM TEST IONS, FOR IPLS         '
        TXTSPC(3*NPLSI+IPLS,NTALM)=TEXTS(NSPAMI+IPLS)
        TXTUNT(3*NPLSI+IPLS,NTALM)='G*CM/S* AMP * CM**-3       '
C
70    CONTINUE
C
      OPEN (UNIT=29,ACCESS='SEQUENTIAL',FORM='FORMATTED')
      REWIND 29
C
      OPEN (UNIT=30,ACCESS='SEQUENTIAL',FORM='FORMATTED')
      REWIND 30
C
C  READ IN DATA TO SET UP GEOMETRY FOR NEUTRAL GAS TRANSPORT CODE
C  STATEMENT NUMBER 1000 ---> 1999
C
C  AT PRESENT THE DATA COME FROM THE FILE FT30
C  THIS PART WILL HAVE TO BE MODIFIED AS SOON AS BRAAMS PROVIDES
C  CELL VERTICES AND CUT DESCRIBTION
C
1000  CONTINUE
C
      INMTI=0
      NTRII = 0
      NRKNOT = 0
      NECKE = 0
      NSEITE = 0
      NCHBAR = 0
      ncltet = 0
      ALLOCATE (COORTRI(NKNOT))
      DO I=1,NKNOT
        NULLIFY(COORTRI(I)%PTRI)
      END DO

      nr1p2 = nr1st
      np2t3 = np2nd
      nr1ori = nr1st
      np2ori = np2nd
      nt3ori = nt3rd

      CALL ALLOC_CSTEP

      RRSTEP(1:NTARGI,1) = 0.D0

      READ (30,'(A72)') ZEILE
      DO WHILE (INDEX(ZEILE,'NODAL COORDINATES') == 0)
         READ (30,'(A72)') ZEILE
      END DO

      DO IC=1,NKNOT
         READ (30,*) IDU,XTRIAN(IC),YTRIAN(IC)
      END DO
      NRKNOT=NKNOT

!  CONVERT TO CM 
      XTRIAN(1:NKNOT)=XTRIAN(1:NKNOT)*0.1_DP
      YTRIAN(1:NKNOT)=YTRIAN(1:NKNOT)*0.1_DP

      write (6,*) ' xmin = ',minval(xtrian(1:nrknot))
      write (6,*) ' xmax = ',maxval(xtrian(1:nrknot))
      write (6,*) ' ymin = ',minval(ytrian(1:nrknot))
      write (6,*) ' ymax = ',maxval(ytrian(1:nrknot))

      ALLOCATE (NODQUAD(9,NQUAD))
      ALLOCATE (NODLINE(3,NLINE))
      ALLOCATE (NLNSTS(NLINE))
      ALLOCATE (LUSED(NLINE))
      NODQUAD = 0
      NODLINE = 0
      NLNSTS = 0
      LUSED = .FALSE.

      NQU = 0
      NLN = 0

      READ (30,'(A72)') ZEILE
      DO WHILE (INDEX(ZEILE,'ELEMENT GROUPS') == 0)
         READ (30,'(A72)') ZEILE
      END DO

      DO
        READ (30,'(A72)',END=9) ZEILE
        I1 = INDEX(ZEILE,'ELEMENTS:')
        DO WHILE (I1 == 0)
          READ (30,'(A72)',END=9) ZEILE
          I1 = INDEX(ZEILE,'ELEMENTS:')
        END DO
        I2 = INDEX(ZEILE,'NODES:')
        I3 = INDEX(ZEILE,'GEOMETRY:')
        READ (ZEILE(I2+7:I3-1),*) NOD

        READ (ZEILE(I1+10:I2),*) NTT

        READ (30,'(A72)') ZEILE
        I1 = INDEX(ZEILE,'ENTITY NAME:')
        DO WHILE (I1 == 0)
          READ (30,'(A72)') ZEILE
          I1 = INDEX(ZEILE,'ENTITY NAME:')
        END DO
        
        NAMENT = ADJUSTL(TRIM(ZEILE(I1+12:)))
        CALL UPPERCASE(NAMENT)
        ISTS=0
        DO IT=1,NTARGI
          IF (ENTITY(IT) == NAMENT) ISTS=NOSTS(IT)
        END DO
        
        IF (NOD == 9) THEN
! READ COORDINATE NUMBERS OF QUADRILATERALS
          DO IEL=1,NTT
            NQU = NQU + 1
            READ (30,*) IDU,(NODQUAD(J,NQU),J=1,NOD)
          END DO
        ELSE IF (NOD == 3) THEN
! READ COORDINATE NUMBERS OF BOUNDARY LINES
          DO IEL=1,NTT
            NLN = NLN + 1
            READ (30,*) IDU,(NODLINE(J,NLN),J=1,NOD)
            CALL BUBBLE (NODLINE(1:NOD,NLN),NOD)
            NLNSTS(NLN) = ISTS
          END DO
        ELSE
          EXIT
        END IF
         
      END DO

 9    CONTINUE
      NTACT=0
      DO I=1,NQUAD
        INDCO = NODQUAD(:,I)
C  SET UP TRIANGLES
        CALL MAKE_TRIAS (INDCO)
        
        ncell=NCELL+1
        ncltAL(ntact+1:ntrii) = ncell
        
        INDF1 = (/ INDCO(1), INDCO(2), INDCO(3) /)
        CALL BUBBLE (INDF1,3)
        INDF2 = (/ INDCO(3),  INDCO(4),  INDCO(5) /)
        CALL BUBBLE (INDF2,3)
        INDF3 = (/ INDCO(5),  INDCO(6),  INDCO(7) /)
        CALL BUBBLE (INDF3,3)
        INDF4 = (/ INDCO(7),  INDCO(8),  INDCO(1) /)
        CALL BUBBLE (INDF4,3)

        IMATCH=0
        DO IQ=1,NLINE
          IF (INDF1(1) == NODLINE(1,IQ)) THEN
            IF (ALL(INDF1 == NODLINE(:,IQ))) THEN
              INMTI(1,NTACT+1) = NLNSTS(IQ)
              INMTI(1,NTACT+2) = NLNSTS(IQ)
              LUSED(IQ) = .TRUE.
              IMATCH = IMATCH + 1
            END IF
          END IF
          IF (INDF2(1) == NODLINE(1,IQ)) THEN
            IF (ALL(INDF2 == NODLINE(:,IQ))) THEN
              INMTI(1,NTACT+3) = NLNSTS(IQ)  
              INMTI(1,NTACT+4) = NLNSTS(IQ) 
              LUSED(IQ) = .TRUE.
              IMATCH = IMATCH + 1
            END IF
          END IF
          IF (INDF3(1) == NODLINE(1,IQ)) THEN
            IF (ALL(INDF3 == NODLINE(:,IQ))) THEN
              INMTI(1,NTACT+5) = NLNSTS(IQ)
              INMTI(1,NTACT+6) = NLNSTS(IQ)
              LUSED(IQ) = .TRUE.
              IMATCH = IMATCH + 1
            END IF
          END IF
          IF (INDF4(1) == NODLINE(1,IQ)) THEN
            IF (ALL(INDF4 == NODLINE(:,IQ))) THEN
              INMTI(1,NTACT+7) = NLNSTS(IQ) 
              INMTI(1,NTACT+8) = NLNSTS(IQ) 
              LUSED(IQ) = .TRUE.
              IMATCH = IMATCH + 1
            END IF
          END IF
          IF (IMATCH == 4) EXIT
        END DO 

        ntact=ntrii

      END DO

      IF (.NOT.ALL(LUSED)) THEN
        WRITE (6,*) ' SURFACES WITHOUT MATCHING LINE FOUND IN IF0COP '
        DO IQ=1,NLINE
          IF (.NOT.LUSED(IQ)) WRITE (6,*) IQ
        END DO
        CALL EXIT
      END IF

      DO ITRI=1,NTRII    ! FOR ALL TRIANGLES
        DO IS=1,3        ! AND FOR ALL SIDES OF EACH TRIANGLE    
          IF (NCHBAR(IS,ITRI) == 0) THEN  ! IF IT HAS NO NEIGHBOR JET
            ISP=IS+1
            IF (ISP == 4) ISP = 1
            IP1=NECKE(IS,ITRI)
            IP2=NECKE(ISP,ITRI)
            MINIS=MIN(IP1,IP2)
            MAXIS=MAX(IP1,IP2)
            CURR => COORTRI(IP1)%PTRI
            DO WHILE (ASSOCIATED(CURR))
              JTRI = CURR%NOTRI
              IF (JTRI /= ITRI) THEN  ! OMIT TRIANGLE ITRI
                DO JS =1,3            ! CHECK ALL SIDES
                  JSP=JS+1
                  IF (JSP == 4) JSP = 1
                  JP1=NECKE(JS,JTRI)
                  JP2=NECKE(JSP,JTRI)
                  MINJS=MIN(JP1,JP2)
                  MAXJS=MAX(JP1,JP2)
                  IF ((MINIS == MINJS) .AND. (MAXIS == MAXJS)) THEN
                    NCHBAR(IS,ITRI) = JTRI  ! NEIGHBOR FOUND
                    NSEITE(IS,ITRI) = JS
                    NCHBAR(JS,JTRI) = ITRI
                    NSEITE(JS,JTRI) = IS
                    EXIT
                  END IF
                END DO ! JS
              END IF
              CURR => CURR%NEXT_TRI
            END DO  ! WHILE
          END IF
        END DO
      END DO

      DO IC=1,NRKNOT
        CURR => COORTRI(IC)%PTRI
        DO WHILE (ASSOCIATED(CURR))
          CUR2 => CURR
          CURR => CURR%NEXT_TRI
          DEALLOCATE(CUR2)
        END DO
        NULLIFY(COORTRI(IC)%PTRI)
      END DO

      IMATCH = 0
      DO ITRI=1,NTRII
        DO IS=1,3
          IF ((NCHBAR(IS,ITRI) == 0) .AND. (INMTI(IS,ITRI) == 0)) THEN
            WRITE (6,*) ' NO NEIGHBOR AND NO BOUNDARY',
     .                  ' CONDITION ON ITRI = ',
     .                    ITRI,' SIDE ',IS
            IMATCH = IMATCH + 1
          END IF
        END DO
      END DO

      IF (IMATCH > 0) CALL EXIT

      DEALLOCATE (NODQUAD)
      DEALLOCATE (NODLINE)
      DEALLOCATE (NLNSTS)
      DEALLOCATE (LUSED)

C
C
C  TRANSFER FLAGS
C
      NAINI=NAINB
C
C
      NLPLG=.FALSE.
      NLFEM=.TRUE.
      LEVGEO=4
      NR1ST=NTRII+1
      NLPOL=.FALSE.
      NP2ND=1
      NLTOR=.FALSE.
      NT3RD=1
      NR1TAL=NCLTAL(NTRII)+1
      NP2TAL=NP2ND
      NT3TAL=NT3RD

      DO IN=NR1ST,NR1ST+NRADD
        NCLTAL(IN)=NCLTAL(NTRII)+IN-NTRII
      ENDDO

      CALL LEER(2)
      CALL HEADNG(' CASE REDEFINED IN COUPLE_TETRA: ',32)
      WRITE (6,*) 'NLPLG,NLFEM ',NLPLG,NLFEM
      WRITE (6,*) 'NLPOL       ',NLPOL
      WRITE (6,*) 'NR1ST,NP2ND ',NR1ST,NP2ND
      CALL LEER(2)
CTRIG E
C
      RETURN
C
C   GEOMETRY DEFINITION PART FINISHED
C
      ENTRY IF1COP
C
C   NOW READ THE PLASMA STATE GIVEN BY BRAAMS
C   AT PRESENT THE DATA COME FROM THE FILE FT31
C   FURTHERMORE: SCALING TO EIRENE UNITS AND INDEX MAPPING
C   STATEMENT NO. 2000 ---> 2999
C
C  IN CASE OF "SHORT CYCLE" THE PLASMA STATE IS TRANSFERRED VIA COMMON
C
      LSHORT=.FALSE.
      CALL LEER(1)
      WRITE (6,*) 'IF1COP CALLED '
      IF (NLPLAS) WRITE (6,*) 'PLASMA DATA EXPECTED ON BRAEIR'
      IF (.NOT.NLPLAS) WRITE (6,*) 'PLASMA DATA EXPECTED ON FORT.31'
C  SKIP READING PLASMA, IF NLPLAS
      IF(NLPLAS) GOTO 2100
C
      GOTO 99991
C
C  IN CASE OF "SHORT CYCLE" OR TIME DEP. MODE
C  THE PLASMA STATE IS TRANSFERRED VIA COMMON
C  ONLY SCALING TO EIRENE UNITS AND INDEX MAPPING NEEDS TO BE DONE HERE
C
      ENTRY INTER1
      LSHORT=.TRUE.
      GOTO 2100
C
99991 CONTINUE
C
C
C  TRANSFER PROFILES
C
      IF (.NOT.(INDPRO(1).EQ.6.OR.INDPRO(2).EQ.6.OR.INDPRO(3).EQ.6.OR.
     .          INDPRO(4).EQ.6)) RETURN
C
C
      IF (NFLA.GT.NFL) THEN
        WRITE (6,*) ' PARAMETER ERROR DETECTED IN INFCOP '
        WRITE (6,*) ' NFLA MUST BE <= NFL'
        WRITE (6,*) ' NFLA,NFL = ',NFLA,NFL
        CALL EXIT
      ENDIF

2100  CONTINUE
C
C  RESET 2D ARRAYS ONTO 1D EIRENE ARRAYS, RESCALE TO EIRENE UNITS
C  AND CONVERT BRAAMS VECTORS INTO CARTHESIAN EIRENE VECTORS
C
C  UNITS CONVERSION FACTORS
      T=1._DP/11600._DP
      V=1.
      VL=1.
CTRIG A
> C  VACCUM DATA NEEDED FOR REGION OUTSIDE B2-MESH
>       TVAC=0.02
>       DVAC=1.E2_DP
>       VVAC=0.
>       BVAC=1.
> CTRIG E
      DO 2105 IPLS=1,NPLSI
        D(IPLS)=FCTE(IPLS)*1.E-6_DP
        FL(IPLS)=FCTE(IPLS)
2105  CONTINUE
C
      ALLOCATE (TEF(NKNOT))
      ALLOCATE (DENF(0:NPLSI,NKNOT))
      ALLOCATE (NOSPEC(NPLSI))
      ALLOCATE (LUSED(NPLSI))

      OPEN (UNIT=31,ACCESS='SEQUENTIAL',FORM='FORMATTED')
      REWIND 31
      READ (31,'(A1000)') LINE

      ICOLUMN = 0
      IANF = 1
      NOSPEC = 0
      FORM='(A       )'
      LUSED=.FALSE.
      DO IPLS=1,NPLSI
        IF (LEN_TRIM(CDENMODEL(IPLS)) > 0) LUSED(IPLS)=.TRUE.
      END DO
      DO 
!  POSITION OF NEXT NON-BLANK CHARACTER
        I1 = VERIFY(LINE(IANF:),' ')
        IF (I1 == 0) EXIT
        I2 = INDEX(LINE(IANF+I1:),' ')
        ICOLUMN=ICOLUMN+1
        IF (ICOLUMN > 6) THEN
          IF (I2 < 10) THEN
            WRITE (FORM(3:3),'(I1)') I2
          ELSE
            WRITE (FORM(3:4),'(I2)') I2
          END IF
          SPECNAME=REPEAT(' ',72)
          READ(LINE(IANF+I1-1:IANF+I1+I2-2),FORM) SPECNAME(1:i2)
          SPECNAME=TRIM(SPECNAME)
          CALL UPPERCASE (SPECNAME)
          DO IPLS=1,NPLSI
            IF (SPECNAME == TEXTS(NSPAMI+IPLS)) THEN
              IF (NOSPEC(IPLS) == 0) THEN
                NOSPEC(IPLS) = ICOLUMN-6
                LUSED(IPLS)=.TRUE.
              ELSE
                WRITE (6,*) ' ERROR! SPECIES ',SPECNAME,' FOUND TWICE '
              END IF
              EXIT
            END IF
          END DO
        END IF
        IANF=IANF+I1+I2-1
      END DO
      
     IF (.NOT. ALL(LUSED)) THEN
        WRITE (6,*) ' ERROR DETECTED IN INFCOP! '
        WRITE (6,*) ' BULK PARTICLE DEFINITION IN EIRENE INPUT DOES NOT'
        WRITE (6,*) ' MATCH SPECIFICATIONS IN FIDAP PLASMA FILE '
        WRITE (6,*) ' CALCULATION ABANDONNED '
        CALL EXIT
      END IF

      NREAD=COUNT(NOSPEC>0)
      DO IC=1,NKNOT
        READ (31,'(A1000)') LINE
        READ (LINE,*) ICO,XCO,YCO,ZCO,TEF(IC),
     .                (DENF(IPLS,IC),IPLS=0,NREAD)
      END DO

      TEINTF=TVAC
      TIINTF=TVAC
      DIINTF=DVAC
      DO ITRI=1,NTRII
        DIST1=1._DP/SQRT((XTRIAN(NECKE(1,ITRI))-XCOM(ITRI))**2+
     .                   (YTRIAN(NECKE(1,ITRI))-YCOM(ITRI))**2)
        DIST2=1._DP/SQRT((XTRIAN(NECKE(2,ITRI))-XCOM(ITRI))**2+
     .                   (YTRIAN(NECKE(2,ITRI))-YCOM(ITRI))**2)
        DIST3=1._DP/SQRT((XTRIAN(NECKE(3,ITRI))-XCOM(ITRI))**2+
     .                   (YTRIAN(NECKE(3,ITRI))-YCOM(ITRI))**2)
        DIST=DIST1+DIST2+DIST3
        TEINTF(ITRI) = T*(TEF(NECKE(1,ITRI))*DIST1 + 
     .                    TEF(NECKE(2,ITRI))*DIST2 +
     .                    TEF(NECKE(3,ITRI))*DIST3)/DIST
!  STORE ELECTRON DENSITY ONTO ADINTF(NAIN) FOR TRANSFER INTO SUBR. PLAUSR        
        ADINTF(NAIN,ITRI) = 1.E-6_DP*
     .                      (DENF(0,NECKE(1,ITRI))*DIST1 + 
     .                       DENF(0,NECKE(2,ITRI))*DIST2 +
     .                       DENF(0,NECKE(3,ITRI))*DIST3)/DIST
        DO IPLS=1,NPLSI
          IPL=NOSPEC(IPLS)
          IF (IPL == 0) CYCLE
          TIINTF(IPLS,ITRI) = TEINTF(ITRI)
          DIINTF(IPLS,ITRI) = D(IPLS)*
     .                       (DENF(IPL,NECKE(1,ITRI))*DIST1 + 
     .                        DENF(IPL,NECKE(2,ITRI))*DIST2 +
     .                        DENF(IPL,NECKE(3,ITRI))*DIST3)/DIST
        END DO
      END DO
      write (6,*) ' temax = ',maxval(teintf(1:ntrii))
      write (6,*) ' temin = ',minval(teintf(1:ntrii))

      DEALLOCATE (TEF)
      DEALLOCATE (DENF)
      DEALLOCATE (NOSPEC)
      DEALLOCATE (LUSED)
C
C
      RETURN
C
2999  CONTINUE
C
C  PLASMA PROFILES ARE NOW READ IN
C
      ENTRY IF2COP(ITARG)
      IF (ITARG.GT.NTARGI) THEN
        CALL LEER(1)
        WRITE (6,*) 'SOURCE DATA FOR STRATUM ISTRA= ',ITARG
        WRITE (6,*) 'CANNOT BE DEFINED IN IF2COP. CHANGE INDSRC(ISTRA)'
        CALL LEER(1)
        RETURN
      ENDIF
C
C  NEXT DEFINE FLUXES, TEMPERATURES AND VELOCITIES AT THE TARGETS
C  (FLUXES IN AMP/(CM ALONG TARGET), TEMPERATURES IN EV, VELOCITIES IN CM/SEC)
C   FNIXB*FL (FNIYB*FL) ARE GIVEN IN AMP
C  STATEMENT NO 3000 ---> 3999
C
3000  CONTINUE
C
      TESTEP(ITARG,:)=0.D0
      TISTEP(:,ITARG,:)=0.D0
      DISTEP(:,ITARG,:)=0.D0
      VXSTEP(:,ITARG,:)=0.D0
      VYSTEP(:,ITARG,:)=0.D0
      VZSTEP(:,ITARG,:)=0.D0
      FLSTEP(:,ITARG,:)=0.D0
      DO IG=1,NRWL(ITARG)
        IN=IRSTEP(ITARG,IG)
        TESTEP(ITARG,IG)=TEINTF(IN)
        TISTEP(1:NPLSI,ITARG,IG)=TIINTF(1:NPLSI,IN)
        DISTEP(1:NPLSI,ITARG,IG)=DIINTF(1:NPLSI,IN)
        VXSTEP(1:NPLSI,ITARG,IG)=VXINTF(1:NPLSI,IN)
        VYSTEP(1:NPLSI,ITARG,IG)=VYINTF(1:NPLSI,IN)
        VZSTEP(1:NPLSI,ITARG,IG)=VZINTF(1:NPLSI,IN)
        FLSTEP(1:NPLSI,ITARG,IG)=1.D0
      END DO
      nrwl(itarg)=nrwl(itarg)+1
C
      IF (TRCSOU) CALL LEER(2)
C
C  INITALIZE FUNCTION STEP (FOR RANDOM SAMPLING ALONG TARGET)
C  SET SOME SOURCE PARAMETERS EXPLICITLY TO ENFORCE INPUT CONSISTENCY
C
      IIPLS=1
      IEPLS=NPLSI
      FLUX(ITARG)=STEP(IIPLS,IEPLS,NRWL(ITARG),ITARG)
C
      NLPLS(ITARG)=.TRUE.
      NLATM(ITARG)=.FALSE.
      NLMOL(ITARG)=.FALSE.
      NLION(ITARG)=.FALSE.
C
      NLSRF(ITARG)=.TRUE.
      NLPNT(ITARG)=.FALSE.
      NLLNE(ITARG)=.FALSE.
      NLVOL(ITARG)=.FALSE.
      NLCNS(ITARG)=.FALSE.
C
      NSRFSI(ITARG)=1
      INDIM(1,ITARG)=4
      I4=IDEZ(INT(SORLIM(1,ITARG)),4,4)
      SORLIM(1,ITARG)=I4*1000+104
      SORIND(1,ITARG)=ITARG
C  IN CASE INDIM=4: INSOR,INDGRD... ARE REDUNDANT
      NRSOR(1,ITARG)=-1
      NPSOR(1,ITARG)=-1
      IF (INDSRC(ITARG).LT.6) THEN
        WRITE (6,*) 'MESSAGE FROM IF2COP: '
        WRITE (6,*) 'SOURCE STRENGTH AND SPATIAL DISTRIBUTION FOR '
        WRITE (6,*) 'STRATUM ',ISTRA,' MODIFIED.'
        CALL MASR1('FLUX=   ',FLUX(ISTRA))
        WRITE (6,*) 'USE STEP FUNCTION ISTEP= ',ITARG,' FROM BLOCK 14'
      ENDIF
C
      IF (INDSRC(ITARG).EQ.6) THEN
C  DEFINE SOURCE FOR TARGET RECYCLING STRATUM ITARG
C  ASSUME NOW: ITARG=ISTRA
C  DEFAULTS ARE ALREADY SET IN SUBR. INPUT.
C
        CALL FTCRI(ITARG,CITARG)
        TXTSOU(ITARG)= 'SURFACE RECYCLING SOURCE NO.'//CITARG
        NPTS(ITARG)=NPTC(ITARG,1)
        NINITL(ITARG)=ITARG*1001
        NSPEZ(ITARG)=-1
        SORIFL(1,ITARG)=NIFLG(ITARG,1)
        SORWGT(1,ITARG)=1.
        IF (NIXY(ITARG,1).EQ.1) THEN
C TARGET RECYCLING SOURCE AT POLOIDAL SURFACE NPES
          NEMODS(ITARG)=3
          NAMODS(ITARG)=1
          SORENI(ITARG)=3.
          SORENE(ITARG)=0.5
        ELSEIF (NIXY(ITARG,1).EQ.2) THEN
C WALL RECYCLING SOURCE AT RADIAL SURFACE NPES
          NEMODS(ITARG)=2
          NAMODS(ITARG)=1
          SORENI(ITARG)=2.
          SORENE(ITARG)=0.
        ENDIF
C
C  SORAD1,...: USE POLYGON MESH, IE. SORAD1,... ARE REDUNDANT.
C
C  VELOCITY SPACE DISTRIBUTION
        SORCOS(ITARG)=1.
        SORMAX(ITARG)=0.
C
C
C  DO 2028 LOOP FROM SUBR. INPUT
        THMAX=MAX(0.D0,MIN(PIHA,SORMAX(ITARG)*DEGRAD))
        IF (NAMODS(ITARG).EQ.1) THEN
          RP1=SORCOS(ITARG)+1.
          SORCOS(ITARG)=1./RP1
          IF (ABS(COS(THMAX)).LE.EPS10) THEN
            SORMAX(ITARG)=1.
          ELSE
            SORMAX(ITARG)=1.-COS(THMAX)**RP1
          ENDIF
        ELSEIF (NAMODS(ITARG).EQ.2) THEN
          SORCOS(ITARG)=SORCOS(ITARG)*DEGRAD
          SORMAX(ITARG)=THMAX
        ENDIF
        NLSYMT(0)=NLSYMT(0).AND.NLSYMT(ITARG)
        NLSYMP(0)=NLSYMP(0).AND.NLSYMP(ITARG)
C
      ENDIF
C
C  SOURCE DEFINITION FOR TARGET RECYCLING STRATUM ITARG COMPLETED
C
3999  CONTINUE
C
C  TARGET DATA ARE DEFINED NOW
C
      DO 5000 IG=1,NGITT
        ELSTEP(:,ITARG,IG)=0.
5000  CONTINUE
C
C  COMPUTE EXACT SURFACE ENERGY FLUXES FOR COMPARISON WITH SAMPLED
C  E-FLUX "ETOTP". THIS IS ONLY FOR DIAGNOSTICS PURPOSES
C  E.G. TO CHECK CONSISTENCY OF BOUNDARY CONDITIONS
C  STATEMENT NO. 6000 ---> 6500
C
      IF (.NOT.TRCSOU) GOTO 6500
C
      EEMAX=0.
      EESHT=0.
C
      DO 6011 IG=1,NRWL(ITARG)-1
        OR=ORI(ITARG,IG)
C  COMPUTE SHEATH POTENTIAL ESHT(ITARG,IG)
C  USE ALL NPLSI SPECIES, NOT JUST IFL=NSPZI,NSPZE
        ESHT(ITARG,IG)=0.D0
        IF (NEMODS(ITARG).EQ.3.OR.NEMODS(ITARG).EQ.5.OR.
     .      NEMODS(ITARG).EQ.7) THEN
          IF (IGSTEP(ITARG,IG).GT.200000) THEN
            ITRI=IRSTEP(ITARG,IG)
            NPES=IGSTEP(ITARG,IG)-200000
            DO 6005 IPL=1,NPLSI
              PM1=(PTRIX(NPES,ITRI)*VXSTEP(IPL,ITARG,IG)+
     .             PTRIY(NPES,ITRI)*VYSTEP(IPL,ITARG,IG))*OR
              VPZ=VZSTEP(IPL,ITARG,IG)
              VP(IPL)=SQRT(PM1**2+VPZ**2)
              DI(IPL)=DISTEP(IPL,ITARG,IG)
6005        CONTINUE
            TE=TESTEP(ITARG,IG)
            CUR=0.
            GAMMA=0.
            ESHT(ITARG,IG)=SHEATH(TE,DI,VP,NCHRGP,GAMMA,CUR,NPLSI,
     .                           -ITARG)
          ELSEIF (IGSTEP(ITARG,IG).LT.200000) THEN
            ITRI=IRSTEP(ITARG,IG)
            NPES=IGSTEP(ITARG,IG)-100000
            ESHT(ITARG,IG)= 0
          ENDIF
        ENDIF
C
        IF (IGSTEP(ITARG,IG).LT.200000) GOTO 6010
        ITRI=IRSTEP(ITARG,IG)
        NPES=IGSTEP(ITARG,IG)-200000
        DO 6009 IPLS=1,NPLSI
          IF (FLSTEP(IPLS,ITARG,IG).EQ.0.D0) GOTO 6009
          VT=SQRT(2.*TISTEP(IPLS,ITARG,IG)/BMASS(IPLS))*CVEL2A
C  VELOCITY COMPONENT NORMAL TO TARGET SURFACE
C  I.E., POLOIDAL COMPONENT V-POL
C  ASSUMING ORTHOGONAL TARGET
          PM1=(PTRIX(NPES,ITRI)*VXSTEP(IPLS,ITARG,IG)+
     .         PTRIY(NPES,ITRI)*VYSTEP(IPLS,ITARG,IG))*OR
C  VELOCITY COMPONENT PARALLEL TO TARGET SURFACE
C  I.E., RADIAL PLUS TOROIDAL COMPONENT, V-RAD + V-TOR
C  AGAIN: ASSUMING ORTHOGONAL TARGET
          VPX=VXSTEP(IPLS,ITARG,IG)-PM1*PPLNX(IY,NPES)*OR
          VPY=VYSTEP(IPLS,ITARG,IG)-PM1*PPLNY(IY,NPES)*OR
          VPZ=VZSTEP(IPLS,ITARG,IG)-0.
          PN1=SQRT(VPX**2+VPY**2+VPZ**2)
          PERW=0.
          PARW=0.
          IF (VT.GT.0.) THEN
            PERW=PM1/VT
            PARW=PN1/VT
          ENDIF
C
          CS=SQRT((1.*TISTEP(IPLS,ITARG,IG)+
     .                TESTEP(ITARG,IG))/BMASS(IPLS))*CVEL2A
C THE MACH NUMBER BOUNDARY CONDITION ONLY AFFECTS THE PARALLEL TO B
C MOMENTUM, I.E., NOT THE RADIAL VELOCITY
          VTEST=SQRT(PM1**2+VPZ**2)
          VTEST=VTEST/(CS+EPS60)
          VR=SQRT(VPX**2+VPY**2)
          WRITE (6,*) 'IPLS,ITARG,IG,MACH ',IPLS,ITARG,IG,VTEST
C         WRITE (6,*) 'POL., TOR., RAD. ',PM1,VPZ,VR
          CALL LEER(1)
C TARGET ENERGY FLUXES
          DRR=RRSTEP(ITARG,IG+1)-RRSTEP(ITARG,IG)
          IF (NEMODS(ITARG).EQ.1) THEN
            EADD=SORENI(ITARG)
          ELSEIF (NEMODS(ITARG).EQ.2.OR.NEMODS(ITARG).EQ.3) THEN
            EADD=SORENI(ITARG)*TISTEP(IPLS,ITARG,IG)+SORENE(ITARG)*
     .             TESTEP(ITARG,IG)
          ELSEIF (NEMODS(ITARG).GE.4) THEN
            PERWI=PERW/SQRT(BMASS(IPLS)/RMASSP(IPLS))
            PARWI=PARW/SQRT(BMASS(IPLS)/RMASSP(IPLS))
            EADD=EMAXW(TISTEP(IPLS,ITARG,IG),PERWI,PARWI)
          ENDIF
          ESUM=EADD*FLSTEP(IPLS,ITARG,IG)
          ELSTEP(IPLS,ITARG,IG)=ELSTEP(IPLS,ITARG,IG)+ESUM
          EEMAX=EEMAX+ESUM*DRR
C  ADD SHEATH ACCELERATION
          EADD=NCHRGP(IPLS)*ESHT(ITARG,IG)
          ESUM=EADD*FLSTEP(IPLS,ITARG,IG)
          EESHT=EESHT+ESUM*DRR
          ELSTEP(IPLS,ITARG,IG)=ELSTEP(IPLS,ITARG,IG)+ESUM
6009    CONTINUE
        GOTO 6011
6010    CONTINUE
C  TO BE WRITTEN
6011  CONTINUE
C
      CALL LEER(1)
      WRITE (6,*) 'TARGET DATA: TARGET NO. ITARG=ISTRA= ',ITARG
      WRITE (6,*) 'IG, ARC, P-FLUX, E-FLUX, TE, TI, SHEATH/TE'
      DO 6100 IG=1,NRWL(ITARG)-1
        WRITE (6,'(1X,I4,1P,6E11.3)')
     .             IG,RRSTEP(ITARG,IG),FLSTEP(0,ITARG,IG),
     .             ELSTEP(0,ITARG,IG),
     .             TESTEP(ITARG,IG),TISTEP(1,ITARG,IG),
     .             ESHT(ITARG,IG)/(TESTEP(ITARG,IG)+EPS60)
6100  CONTINUE
      WRITE (6,'(1X,I4,1P,1E11.3)') NRWL(ITARG),
     .                                 RRSTEP(ITARG,NRWL(ITARG))
      CALL MASR1 ('EEMAX    ',EEMAX)
      CALL MASR1 ('EESHT    ',EESHT)
C
      ETOT=EEMAX+EESHT
      EFLX(ITARG)=EEMAX+EESHT
      WRITE (6,*) 'PARTICLE FLUX(IPLS), IPLS=1,NPLSI '
      WRITE (6,'(1X,1P,6E12.4)') (FLTOT(ISPZ,ITARG),ISPZ=1,NPLSI)
      CALL LEER(1)
      WRITE (6,*) 'ENERGY FLUX '
      WRITE (6,'(1X,1P,1E12.4)') EFLX(ITARG)
      CALL LEER(2)
C
6300  CONTINUE
C
C
C  SET SOME OTHER DATA SPECIFIC FOR EIRENE CODE REQUIREMENTS
C  STATEMENT NO. 6500 ---> 6999
C
6500  CONTINUE
C
C
      RETURN
999   CONTINUE
      WRITE (6,*) 'ERROR IN IF2COP: NGITT TOO SMALL '
      CALL EXIT
      RETURN
C
C
      ENTRY IF3COP(ISTRAA,ISTRAE,NEW_ITER)
C
C
      WRITE (6,*) ' IF3COP IS CALLED, ISTRAA,ISTRAE '
      WRITE (6,*) ISTRAA,ISTRAE
      LSHORT=.FALSE.
      LSTOP=.TRUE.
      IFIRST=0
      NDXY=(NDXA-1)*NR1STQ+NDYA
      GOTO 99992
C
      ENTRY INTER3(LSTP,IFRST,ISTRAA,ISTRAE,NEW_ITER)
C
C  ENTRY FOR SHORT CYCLE FROM SUBR. EIRSRT
C
C  IFIRST=0: RESTORE DATA FROM A PREVIOUS EIRENE RUN, SET REFERENCE
C            DATA FOR "STOP-CRITERION" SNIS,SEES,SEIS
C  IFIRST>0: MODIFY SOURCE TERMS ACCORDING TO NEW PLASMA CONDITIONS,
C            COMPARE INTEGRALS WITH SNIS,...., AND DECIDE TO STOP OR
C            CONTINUE SHORT CYCLE (LSTOP)
C
      LSHORT=.TRUE.
      LSTOP=LSTP
      IFIRST=IFRST
      NDXY=(NDXA-1)*NR1STQ+NDYA
C
99992 CONTINUE
C
      DO 10000 ISTRAI=ISTRAA,ISTRAE
C
        IF (XMCP(ISTRAI).LE.1.) GOTO 10000
C
        IF (LSHORT) GOTO 7000
C
C  READ DATA FROM STRATUM NO. ISTRAI BACK INTO WORKING SPACE
C  IF REQUIRED
C
        IF (ISTRAI.EQ.IESTR) THEN
C  NOTHING TO BE DONE
        ELSEIF ((NFILEN.EQ.1.OR.NFILEN.EQ.2).AND.IESTR.NE.ISTRAI) THEN
          IESTR=ISTRAI
          CALL RSTRT(ISTRAI,NSTRAI,NESTM1,NESTM2,NADSPC,
     .               ESTIMV,ESTIMS,ESTIML,
     .               NSDVI1,SDVI1,NSDVI2,SDVI2,
     .               NSDVC1,SIGMAC,NSDVC2,SGMCS,
     .               NSBGK,SIGMA_BGK,NBGV_STAT,SGMS_BGK,
     .               NSCOP,SIGMA_COP,NCPV_STAT,SGMS_COP,
     .               NSIGI_SPC,TRCFLE)
        ELSE
          WRITE (6,*) 'ERROR IN INFCOP: STRATUM ISTRAI= ',ISTRAI
          WRITE (6,*) 'IS NOT AVAILABLE. EXIT CALLED'
          CALL EXIT
        ENDIF
C
C  DATA TRANSFER BACK FROM EIRENE TO EXTERNAL CODE
C  STATEMENT NO 7000 ---> 7999
C
7000    CONTINUE
C
C  SCALE SURFACE SOURCES PER UNIT FLUX, FOR OTHER SOURCES USE
C  EIRENE SCALINGS
        IF (ISTRAI.LE.NTARGI.AND.WTOTP(0,ISTRAI).NE.0.) THEN
C  FLUX FROM EIRENE TO PLASMA CODE: NEGATIVE
          FLX=-WTOTP(0,ISTRAI)
          FLXI=1./FLX
        ELSEIF (ISTRAI.LE.NTARGI.AND.WTOTP(0,ISTRAI).EQ.0.) THEN
          WRITE (6,*) 'NO FLUX FROM STRATUM NO. ISTRAI= ',ISTRAI
          WRITE (6,*) 'NO DATA RETURNED FOR THIS STRATUM'
          GOTO 7999
        ELSEIF (ISTRAI.GT.NTARGI) THEN
          FLXI=1.
        ENDIF
C
        IF (.NOT.LSHORT) GOTO 7400
C  SHORT LOOP CORRECTION FINISHED
C
7400    CONTINUE
C
C
C  ADD CONTRIBUTIONS FROM VOLUME RECOMBINATION SOURCE
C
C
        IF (.NOT.LSYMET) GOTO 7500
C
C  SECONDLY SYMMETRISE EIRENE ARRAYS ACCORDING TO SYMMETRY IN MODEL
C
C
C   THIRDLY WRITE EIRENE ARRAYS (1D) ONTO BRAAMS ARRAYS (2D)
C   AND RESCALE TO PROPER UNITS: #/CELL/STRATUM FLUX
C   # STANDS FOR PARTICLES (SNI), MOMENTUM (SMO)
C   AND ENERGY (SEE,SEI)
C
7500    CONTINUE
C
C   NEXT:
C   IF LSHORT: CRITERION TO STOP SHORT CYCLE,
C   IF NOT LSHORT: RESCALE SURFACE SOURCE STRATA
C                  UNITS: # PER UNIT TARGET PLATE FLUX
C
C
C
C   THIRDLY:
C   INDEX MAPPING BACK TO BRAAMS IMPLEMENTATION OF LINDA GEOMETRY
C
C
7700    CONTINUE
C
7999    CONTINUE
C
C  DATA TRANSFER BACK TO PLASMA CODE FINISHED FOR STRATUM NO. ISTRAI
C
10000 CONTINUE
C
      RETURN
C
      ENTRY IF4COP
C
      NREC11=NOUTAU
      OPEN (UNIT=11,ACCESS='DIRECT',FORM='UNFORMATTED',RECL=8*NREC11)
      IRC=3
      WRITE (11,REC=IRC) RCCPL
      IF (TRCINT.OR.TRCFLE)   WRITE (6,*) 'WRITE 11  IRC= ',IRC
      ALLOCATE (IHELP(NOUTAU))
      JC=0
      DO K=1,NPTRGT
        DO J=1,10*NSTEP
          JC=JC+1
          IHELP(JC)=ICCPL1(J,K)
          IF (JC == NOUTAU) THEN
            IRC=IRC+1
            WRITE (11,REC=IRC) IHELP
            IF (TRCINT.OR.TRCFLE)   WRITE (6,*) 'WRITE 11  IRC= ',IRC
            JC=0
          END IF
        END DO
      END DO
      IF (JC > 0) THEN
        IRC=IRC+1
        WRITE (11,REC=IRC) IHELP
        IF (TRCINT.OR.TRCFLE)   WRITE (6,*) 'WRITE 11  IRC= ',IRC
      END IF
      DEALLOCATE (IHELP)
      IRC=IRC+1
      WRITE (11,REC=IRC) ICCPL2
      IRC=IRC+1
      WRITE (11,REC=IRC) LCCPL
      IF (TRCINT.OR.TRCFLE)   WRITE (6,*) 'WRITE 11  IRC= ',IRC
C
      IF (LSHORT) LSTOP=LSTP
C
      IF (.NOT.LSTOP) RETURN
C
      IF (.NOT.(LBALAN)) GOTO 11000
C
C  BALANCES, SHOULD BE DONE ONLY AT THE END OF BRAAMS RUN
C  AT THE END OF AN EIRENE RUN THE BALANCES MAY BE OFF AT LEAST AT
C  THE BEGINNING OF THE CYCLING PROCEDURE, BECAUSE THE PLASMA STILL
C  HAS TO ADJUST TO THE NEW SOURCES
C
C
C
11000 CONTINUE
C
      RETURN
C
      END
