C
C
C*DK SLOPE
      FUNCTION EIRENE_SLOPE(KN,JCH,NN,EN,BU,N,M)
C
C     CALCULATE SLOPE OF STRAIGHT LINE
C
      USE EIRMOD_PRECISION
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: KN, JCH, NN, N, M
      REAL(DP), INTENT(IN) :: EN(M), BU(N,M)
      REAL(DP) :: ZSUM1, ZSUM2, ZSUM3, ZSUM4, ZX, ZY, FKN, EIRENE_SLOPE
      INTEGER :: J
C
      ZSUM1=0.0
      ZSUM2=0.0
      ZSUM3=0.0
      ZSUM4=0.0
C
      FKN=KN
      DO 101 J=1,KN
        ZX=EN(NN+J-1)
        ZY=BU(JCH,NN+J-1)
C
        ZSUM1=ZSUM1+ZX*ZY
        ZSUM2=ZSUM2+ZX
        ZSUM3=ZSUM3+ZY
        ZSUM4=ZSUM4+ZX*ZX
101   CONTINUE
C
      EIRENE_SLOPE=(FKN*ZSUM1-ZSUM2*ZSUM3)/(FKN*ZSUM4-ZSUM2*ZSUM2)
C
      RETURN
      END
