
      SUBROUTINE BROADSPUT(ES,M2M1,ETF,ETH,Q,N1,N2)
      USE PRECISION
      USE PARMMOD
      IMPLICIT NONE
      INTEGER, INTENT(IN):: N1, N2
      REAL(DP), INTENT(IN OUT) :: ES(N1), M2M1(N1,N2), ETF(N1,N2),
     .                            ETH(N1,N2), Q(N1,N2)
      RETURN
      END
