#!/bin/tcsh -x
#
  alias ls ls
#
# ======================================================================
# PROCESS INPUT FLAGS
# ======================================================================
#
# Select non-default DIVIMP/OUT executable:
# ----------------------------------------------------------------------
#
  setenv X86_64 0
  if ( "$1" == "-64") then
    shift
    setenv X86_64 1
  endif

  setenv MYEXT "default"
  setenv ITER  no
  if ( "$1" == "-iter" ) then
    shift 
    setenv ITER  yes
    setenv MYEXT iter
  endif

  setenv MASTU no
  if ( "$1" == "-mastu" || "$1" == "-mu" ) then
    shift 
    setenv MASTU yes
    setenv MYEXT mastu
  endif
#
# ----------------------------------------------------------------------
# Decide which version of EIRENE to run, and if photon transport is 
# included:
# 
  setenv EIRTEMP eirene99
  setenv EIRFILE eirene99.dat
  setenv EIR13  
  setenv EIR15  
  setenv EIRPHOTONS 
  if      ( "$1" == "-eirene04" || "$1" == "-04" ) then
    shift 
    setenv EIRTEMP eirene04
    setenv EIRFILE eirene04.dat
    if      ( "$1" == "-template" || "$1" == "-t" ) then
      shift 
      setenv EIRFILE eirene04.dat.$1
      shift
    endif
    if      ( "$1" == "-photons" ) then
      shift 
      setenv EIRPHOTONS yes
      setenv EIRFILE    eirene04.dat.photons
    endif
    if      ( "$1" == "-photons.cont" ) then
      shift 
      setenv EIRPHOTONS  yes
      setenv EIRFILE     eirene04.dat.photons.cont
    endif
    if      ( "$1" == "-photons.bgk" ) then
      shift 
      setenv EIRPHOTONS  yes
      setenv EIRFILE  eirene04.dat.photons.bgk
    endif
    if      ( "$1" == "-puff" ) then
      shift 
      setenv EIRFILE     eirene04.dat.puff
    endif
    if      ( "$1" == "-13" ) then
      shift 
      setenv EIR13  $1
      shift 
    endif
  endif

  setenv EIRRAW  "no"
  if      ( "$1" == "-eirene06" || "$1" == "-06" ) then
    shift 
    setenv EIRTEMP  eirene06
    setenv EIRFILE  eirene06.dat
    if      ( "$1" == "-cr" ) then
      shift 
      setenv EIRRAW  "yes"
    endif
    if      ( "$1" == "-template" || "$1" == "-t" ) then
      shift 
      setenv EIRFILE  eirene06.dat.$1
      shift
    endif
    if      ( "$1" == "-photons" ) then
      shift 
      setenv EIRPHOTONS  yes
      setenv EIRFILE     eirene06.dat.photons
    endif
  endif

  if      ( "$1" == "-eirene07" || "$1" == "-07" ) then
    shift 
    setenv EIRTEMP  eirene07
    setenv EIRFILE  eirene07.dat
    if      ( "$1" == "-cr" ) then
      shift 
      setenv EIRRAW  "yes"
    endif
    if      ( "$1" == "-template" || "$1" == "-t" ) then
      shift 
      setenv EIRFILE  eirene07.dat.$1
      shift
    endif
    if      ( "$1" == "-photons" ) then
      shift 
      setenv EIRPHOTONS  yes
      setenv EIRFILE     eirene07.dat.photons
    endif
    if      ( "$1" == "-13" ) then
      shift 
      setenv EIR13  $1
      shift 
    endif
    if      ( "$1" == "-15" ) then
      shift 
      setenv EIR15  $1
      shift 
    endif
  endif
#
# ----------------------------------------------------------------------
# Just run OUT, the post-processing and graphics package:
# 
  setenv OUTONLY no
  if ( "$1" == "-out" || "$1" == "-o" ) then
    shift 
    setenv OUTONLY yes
  endif
#
# ----------------------------------------------------------------------
# Don't delete case directory when the run is completed, for debugging:
# 
  setenv CLEAN yes
  if ( "$1" == "-noclean" || "$1" == "-nc" ) then
    shift 
    setenv CLEAN no
  endif
#
# ----------------------------------------------------------------------
# Just run OUT, the post-processing and graphics package:
# 
  setenv DEVICE unknown
  setenv DEVDIR unknown
  if ( "$1" == "-device" || "$1" == "-d" ) then
    shift
    setenv DEVICE $1
    shift 
    setenv DEVDIR $1
    shift
  endif
#
# ----------------------------------------------------------------------
# Validate input (weak):
#
  if ( $1 == "" || $2 == "" || ($3 == "" && $OUTONLY == "no" ))  then
    echo "Parameter error"
    exit
  endif
#
# ----------------------------------------------------------------------
# Set case variables from what's left:
  setenv CASENAME $1
  setenv OUTNAME  $2
  setenv GRIDNAME $3
  setenv SAVENAME $4
  if ( $OUTONLY == "yes" ) setenv SAVENAME $CASENAME

  exit(0)
