#!/bin/tcsh

  if ( $CASENAME == "" ) then
    echo 'ERROR: No Case name specified - script exiting'
    exit
  endif

  set RUNDIR = $DIVHOME
  set XEIDIR = $DIVHOME/cases/$CASENAME.eirene
  set EXEDIR = $DIVHOME/cases/$CASENAME
  set LEIDIR = $DIVHOME/eirene06
  set DATDIR = $DIVHOME/data
# EIRENE plots
#  setenv GLI_HOME /usr/local/lib
  setenv GLI_HOME .
  setenv GRSOFT_DEVICE 62

# Establish execution directories
  cd $DIVHOME/cases
  if ( -e $XEIDIR ) then
    rm -rf $XEIDIR
  endif
  mkdir $XEIDIR
  cd    $XEIDIR

# Find EIRENE input file
  if      ( -e $DATDIR/$CASENAME.eirdat ) then
    #   Take the EIRENE input file from the EIRENE directory
    #   if there is one there:
    cp $DATDIR/$CASENAME.eirdat fort.1
    echo Found file in data directory
  else if ( -e $EXEDIR/$CASENAME.eirdat ) then
    #   File in DIVIMP execution directory:
    cp $EXEDIR/$CASENAME.eirdat fort.1
    echo Found file in execution directory
  else if ( -e $EXEDIR/eirene.input ) then
    #   Take newly written file:
    cp $EXEDIR/eirene.input fort.1
  else if ( -e $EXEDIR/eirene.template ) then
    #   Take template file in special cases:
    cp $EXEDIR/eirene.template fort.1
  else if ( -e $EXEDIR/fort.81 ) then
    #   Take newly written file - old:
    cp $EXEDIR/fort.81 fort.1
  else
    echo EIRENE input file not found
    exit 1
  endif

# Copy DIVIMP transfer files
#  cp $EXEDIR/triangles.points cmod.npco_char
#  cp $EXEDIR/triangles.sides  cmod.elemente
#  cp $EXEDIR/triangles.map    cmod.neighbors
  cp $EXEDIR/objects.npco_char cmod.npco_char
  cp $EXEDIR/objects.elemente  cmod.elemente
  cp $EXEDIR/objects.neighbors cmod.neighbors
  cp $EXEDIR/objects.plasma    cmod.plasma

  if (-e $EXEDIR/eirene.13) cp $EXEDIR/eirene.13 fort.13

# Copy (local) collision rate data 
  cp $EXEDIR/HYDHEL  .
  cp $EXEDIR/SPUTER  .
  cp $EXEDIR/AMJUEL  .
  cp $EXEDIR/METHANE .
  cp $EXEDIR/H2VIBR  .
  mkdir TRIM
  cp -r $EXEDIR/TRIM/* TRIM
  mv TRIM/trim.dat fort.21

  cp $LEIDIR/case/PHOTON .
  cp $LEIDIR/case/POLARI .
  cp $LEIDIR/case/graphite_ext.dat .
  cp $LEIDIR/case/mo_ext.dat .

  cp $EXEDIR/gksfont.dat .

# Execute EIRENE
  cp $EXEDIR/eirene06 ./eirene

#exit
 
# Xpgdbg ./eirene > asdex.out
#exit
  eirene > eirene.out
#/usr/totalview/bin/totalview ./eirene > eirene.out

# Process results
  mvc eirene.transfer $EXEDIR
  mvc eirene.out      $EXEDIR/$CASENAME.eirprn
  mvc gli.eps         $EXEDIR/$CASENAME.eps
#  mvc fort.1          $EXEDIR/$CASENAME.eirdat
  mvc fort.13         $EXEDIR/eirene.13
  cpc fort.90         $EXEDIR/eirtrac.dat


#  exit

# Clean
  cd $DIVHOME/cases
  rm -r -f $CASENAME.eirene
  cd $EXEDIR










