      SUBROUTINE BROADCAST_NEUTRAL 
      USE PARALLEL 
      USE GEOMETRY_PL
      USE PHYSICAL_CELL
      USE NEUTRAL_TRANSPORT 

C1. surface
      ENTRY BROADCAST_SF_N0()

      CALL BROADCAST_INTE_S(NONTRT_N0)
      IF(NONTRT_N0 > 0) THEN
        IF(MYPE > 0) ALLOCATE(
     I    IR0NR_N0(NONTRT_N0),IZONR_N0(NONTRT_N0),INDINR_N0(NONTRT_N0)
     I,   IP1NR_N0(NONTRT_N0),IP2NR_N0(NONTRT_N0)
     I,   IT1NR_N0(NONTRT_N0),IT2NR_N0(NONTRT_N0)
     &                            )

          CALL BROADCAST_INTE( IR0NR_N0,NONTRT_N0)
          CALL BROADCAST_INTE( IZONR_N0,NONTRT_N0)
          CALL BROADCAST_INTE(INDINR_N0,NONTRT_N0)
          CALL BROADCAST_INTE( IP1NR_N0,NONTRT_N0)
          CALL BROADCAST_INTE( IP2NR_N0,NONTRT_N0)
          CALL BROADCAST_INTE( IT1NR_N0,NONTRT_N0)
          CALL BROADCAST_INTE( IT2NR_N0,NONTRT_N0)
      ENDIF 
   
      CALL BROADCAST_INTE_S(NONTPT_N0)
      IF(NONTPT_N0 > 0) THEN
        IF(MYPE > 0) ALLOCATE(
     I    IP0NP_N0(NONTPT_N0),IZONP_N0(NONTPT_N0),INDINP_N0(NONTPT_N0)
     I,   IR1NP_N0(NONTPT_N0),IR2NP_N0(NONTPT_N0)
     I,   IT1NP_N0(NONTPT_N0),IT2NP_N0(NONTPT_N0)
     &                            )

          CALL BROADCAST_INTE( IP0NP_N0,NONTPT_N0)
          CALL BROADCAST_INTE( IZONP_N0,NONTPT_N0)
          CALL BROADCAST_INTE(INDINP_N0,NONTPT_N0)
          CALL BROADCAST_INTE( IR1NP_N0,NONTPT_N0)
          CALL BROADCAST_INTE( IR2NP_N0,NONTPT_N0)
          CALL BROADCAST_INTE( IT1NP_N0,NONTPT_N0)
          CALL BROADCAST_INTE( IT2NP_N0,NONTPT_N0)
      ENDIF 

      CALL BROADCAST_INTE_S(NONTTT_N0)
      IF(NONTTT_N0 > 0) THEN
        IF(MYPE > 0) ALLOCATE(
     I    IT0NT_N0(NONTTT_N0),IZONT_N0(NONTTT_N0),INDINT_N0(NONTTT_N0)
     I,   IR1NT_N0(NONTTT_N0),IR2NT_N0(NONTTT_N0)
     I,   IP1NT_N0(NONTTT_N0),IP2NT_N0(NONTTT_N0)
     &                            )

          CALL BROADCAST_INTE( IT0NT_N0,NONTTT_N0)
          CALL BROADCAST_INTE( IZONT_N0,NONTTT_N0)
          CALL BROADCAST_INTE(INDINT_N0,NONTTT_N0)
          CALL BROADCAST_INTE( IR1NT_N0,NONTTT_N0)
          CALL BROADCAST_INTE( IR2NT_N0,NONTTT_N0)
          CALL BROADCAST_INTE( IP1NT_N0,NONTTT_N0)
          CALL BROADCAST_INTE( IP2NT_N0,NONTTT_N0)
      ENDIF 
      RETURN

C2. Cell nr.
      ENTRY BROADCAST_CELL_NR_N0()

      CALL BROADCAST_INTE_S(NCTYPE_DEF)
      CALL BROADCAST_INTE_S(NCELL_N1  )
      CALL BROADCAST_INTE_S(NCELL_N2  )
    
      IF( NCTYPE_DEF > 0) THEN
        IF(MYPE > 0) ALLOCATE(
     I           NCELL_AB       (0:NCTYPE_DEF)
     R,          PLASMA_ADD_CELL(4,NCTYPE_DEF) )

        CALL BROADCAST_INTE(NCELL_AB,NCTYPE_DEF+1)
        CALL BROADCAST_REAL(PLASMA_ADD_CELL,4*NCTYPE_DEF)
      ENDIF 
      CALL BROADCAST_INTE(IDCELL,MESH_P_OS(NZONET))
      RETURN

C3. Source distribution
      ENTRY BROADCAST_SOURCE_N0()

      CALL BROADCAST_INTE_S(N0S_DEF )
      CALL BROADCAST_INTE_S(NS_PLACE)
      CALL BROADCAST_INTE_S(NSSIDE  ) 
      CALL BROADCAST_INTE_S(NSSTOR  ) 

      IF    (N0S_DEF  > 0) THEN
      ELSEIF(N0S_DEF == 0) THEN
         IF(MYPE > 0) ALLOCATE (
     .            IJK_N0(NSSTOR)
     .,           ISD_N0(NSSTOR)
     .,           IZO_N0(NSSTOR)
     .,           IR0_N0(NSSTOR)
     .,           IP0_N0(NSSTOR)
     .,           IT0_N0(NSSTOR)
     .,           GEWICH(NSSTOR)
     .           )

         CALL BROADCAST_INTE(IJK_N0,NSSTOR)
         CALL BROADCAST_INTE(ISD_N0,NSSTOR)
         CALL BROADCAST_INTE(IZO_N0,NSSTOR)
         CALL BROADCAST_INTE(IR0_N0,NSSTOR)
         CALL BROADCAST_INTE(IP0_N0,NSSTOR)
         CALL BROADCAST_INTE(IT0_N0,NSSTOR)
         CALL BROADCAST_REAL(GEWICH,NSSTOR)
      ELSE
         IF(MYPE > 0) ALLOCATE (
     .            NADDSF(NSSTOR)
     .,           XSOURP(NSSTOR)
     .,           YSOURP(NSSTOR)
     .,           ZSOURP(NSSTOR)
     .,           GEWICH(NSSTOR)
     .           )

         CALL BROADCAST_INTE(NADDSF,NSSTOR)
         CALL BROADCAST_REAL(XSOURP,NSSTOR)
         CALL BROADCAST_REAL(YSOURP,NSSTOR)
         CALL BROADCAST_REAL(ZSOURP,NSSTOR)
         CALL BROADCAST_REAL(GEWICH,NSSTOR)
      ENDIF 
      RETURN 

C4. Additional surfaces
      ENTRY BROADCAST_ADD_SF_N0()

      CALL BROADCAST_INTE_S(NPLATE  )
      CALL BROADCAST_INTE_S(NTRIANG )

      IF(NPLATE  >  0) THEN
         IF(MYPE > 0) ALLOCATE (
     .          ISR_TYPE(NPLATE   )
     .,         NSTUCK  (NPLATE,2 )
     .,         X_TRIA  (3,NTRIANG)
     .,         Y_TRIA  (3,NTRIANG)
     .,         Z_TRIA  (3,NTRIANG)
     .         )
         
         CALL BROADCAST_INTE(ISR_TYPE, NPLATE )
         CALL BROADCAST_INTE(NSTUCK ,2*NPLATE )
         CALL BROADCAST_REAL(X_TRIA ,3*NTRIANG)
         CALL BROADCAST_REAL(Y_TRIA ,3*NTRIANG)
         CALL BROADCAST_REAL(Z_TRIA ,3*NTRIANG)
      ENDIF 
      RETURN 

      END SUBROUTINE BROADCAST_NEUTRAL

