#!/bin/bash

export FILE_LIST=`ls $1 2>/dev/null`

if [ ! -z "$FILE_LIST" ]
then
  for FILENAME in $FILE_LIST
  do
#    echo batch_mv: mv $FILENAME $CASENAME.$FILENAME
    mv $FILENAME $CASENAME.$FILENAME   
  done
fi


