#!/bin/tcsh
#
# ======================================================================
# STOP THE PRESSES, AND RELAUNCH ON THE CLUSTER AS qsub PROCESS
# ======================================================================
#
  if ( "$1" == "-qsub" ) then
    shift
    set qsub_id = $1
    shift
    cd $DIVHOME/cases
    echo cd $HOME/divimp/scripts > run_qsub_1
    echo $HOME/divimp/scripts/run $1 $2 $3 $4 $5 $6 $7 $8 $9 $10 $11 > run_qsub_2
    set script_name = $qsub_id
    cat run_qsub_1 run_qsub_2 > $script_name
    chmod u+x $script_name
    rm run_qsub_1 run_qsub_2
    qsub $script_name
#    qstat -f | grep -i exec_host
    exit
  endif
#
# ======================================================================
# PROCESS INPUT FLAGS
# ======================================================================
#
  set DIR_SCRIPT = $DIVHOME/scripts

  if      ( "$1" == "-uls" ) then
    shift
    source $DIR_SCRIPT/run_osm uls $1 $2 $3 $4 $5 $6 $7 $8 $9 $10 $11
  else if ( "$1" == "-osm" ) then
    shift
#    set DEVICE = $1 
#    if      ( $DEVICE == "iter" || $DEVICE == "mast" ) then
#      shift
      source $DIR_SCRIPT/run_osm $1 $2 $3 $4 $5 $6 $7 $8 $9 $10 $11
#    else
#      echo ERROR: unknown device specification: $DEVICE
#      exit
#    endif
  else if ( "$1" == "-ray" ) then
    shift
    source $DIR_SCRIPT/run_ray mast $1 $2 $3 $4 $5 $6 $7 $8 $9 $10 $11
  else
    source $DIR_SCRIPT/run_divimp $1 $2 $3 $4 $5 $6 $7 $8 $9 $10 $11
  endif

#
# ======================================================================
# SET SHELL VARIABLES
# ======================================================================
#


#
# ======================================================================
# CREATE CASE DIRECTORY
# ======================================================================
#




#
# ======================================================================
# SETUP REMOTE EXECUTION
# ======================================================================
#


#
# ======================================================================
# SETUP LOCAL EXECUTION
# ======================================================================
#



#
# ======================================================================
# POST PROCESSING WITH OUT
# ======================================================================
#


#
# ======================================================================
# STORE OUTPUT FILES
# ======================================================================
#


#
# ======================================================================
# CLEAN UP RUN DIRECTORY
# ======================================================================
#
