#!/bin/tcsh
#
if (! $?DIVIMP_PROGDIR) then
   set progdir = divimp
else
   set progdir = $DIVIMP_PROGDIR
endif 

echo 'DIVIMP directory:' $HOME/$progdir

echo 'SETTING UP Testcases'
#
set scriptdir = $HOME/$progdir/scripts

source $scriptdir/init_testcases

#
# Check to see if testcase directory already exists
#
if ( !(-e $testdir) ) then 
#
#  Run testcases 
#
   source $scriptdir/run_testcases
#
#  Change to results directory - create testcase directory and copy in results
#
   cd $resultdir
#
   mkdir $testdir
#

#
#  Copy the new testcases from the results director to the testcase directory
#

   foreach ext ( $extlist ) 

#
#     Loop through list of testcases 
#
      foreach testcase ( $testcaselist )
#        
#        Copy all the new testcases to the testcases directory
#
         if ($ext == '.lim') then  

	    echo "---- Copying" $testcase$ext.$zext "file to" $testdir 
            cp $resultdir/$testcase$ext.$zext $testdir

         else if ($ext == '.out') then    

	    echo "---- Copying" $testcase$ext.$zext "file to" $testdir 
	    cp $resultdir/$testcase$ext.$zext $testdir

         else

	    echo "---- Copying" $testcase$ext "file to" $testdir 
	    cp $resultdir/$testcase$ext $testdir

	 endif   
      end
   end

#   cp $resultdir/testcases_out.txt $testdir 
#   cp $resultdir/testcase0$testlist.dat $testdir
#   cp $resultdir/testcase0$testlist.lim.Z $testdir
#   cp $resultdir/testcase0$testlist.eirprn $testdir 
#   cp $resultdir/testcase0$testlist.out.Z $testdir
#
#  Return to main directory
#
   cd $divmain
else
   echo "ERROR: Test cases have already been set up."
   echo "       Please run update_testcases to update the default testcases."
endif

