#!/bin/tcsh
#
set progdir=divimp-gf

echo 'SETTING UP Testcases'
#
set scriptdir = $HOME/$progdir/scripts

source $scriptdir/init_testcases

#
# Check to see if testcase directory already exists
#
if ( !(-e $testdir) ) then 
#
#  Run testcases 
#
   source $scriptdir/run_testcases
#
#  Change to results directory - create testcase directory and copy in results
#
   cd $resultdir
#
   mkdir $testdir
#
   cp $resultdir/testcases_out.txt $testdir 
   cp $resultdir/testcase0$testlist.dat $testdir
   cp $resultdir/testcase0$testlist.lim.Z $testdir
   cp $resultdir/testcase0$testlist.eirprn $testdir 
   cp $resultdir/testcase0$testlist.out.Z $testdir
#
#  Return to main directory
#
   cd $divmain
else
   echo "ERROR: Test cases have already been set up."
   echo "       Please run update_testcases to update the default testcases."
endif

