C
C  *************************
C  *                       *
C  * INITIALIZATION PHASE  *
C  *                       *
C  *************************
C
C      SUBROUTINE SETPRM
C      SUBROUTINE SETCON
C      SUBROUTINE SETTXT
C      SUBROUTINE INPUT
C      SUBROUTINE GRID
C      SUBROUTINE VOLUME
C      SUBROUTINE PLASMA
C      SUBROUTINE PLASMA_DERIV
C      SUBROUTINE PROFN(PRO,PRO0,PROS,P,Q,E,SEP,PROVAC)
C      SUBROUTINE PROFE(PRO,PRO0,RINP,A1,E,SEP,PROVAC)
C      SUBROUTINE PROFS(PRO,PRO0,PROS,SEP,PROVAC)
C      SUBROUTINE PROFR(PRO,INDEX,NSPZI,NSPZ1,NDAT)
C
      SUBROUTINE SETPRM
      USE PRECISION
      USE PARMMOD
      USE COMUSR
      USE CESTIM
      USE CPOLYG
      USE CGRID
      USE CGEOM
      USE CSDVI
      USE CLGIN
      USE COUTAU
      USE COMXS
      USE CSPEI

      IMPLICIT NONE

      REAL(DP) :: RSAVE
      INTEGER :: ISAVE, NTESTP, J, NTEST, NTESTI
C
      IF (NRAD.LT.NLIMPS) THEN
        WRITE (6,*) 'POSSIBLE STORAGE CONFLICT. NRAD .LT. NLIMPS '
        WRITE (6,*) 'INCREASE PARAMETER NRAD. EXIT CALLED'
        CALL EXIT_OWN(1)
      ENDIF
C
      IF (NSTORDT.LT.1 .OR. NSTORDT.GT.9) THEN
        WRITE (6,*) 'POSSIBLE STORAGE CONFLICT. NSTORDT OUT OF RANGE '
        CALL EXIT_OWN(1)
      ENDIF
C
C   LEADING DIMENSIONS OF FIELDS IN COMMON BLOCK CESTIM AND COUTAU
C
      LIVTALV(1) = LIVTALV(1) .AND. NATM>0
      LIVTALV(2) = LIVTALV(2) .AND. NMOL>0
      LIVTALV(3) = LIVTALV(3) .AND. NION>0
      LIVTALV(4) = LIVTALV(4) .AND. NPHOT>0
      LIVTALV(5) = LIVTALV(5) .AND. NATM>0
      LIVTALV(6) = LIVTALV(6) .AND. NMOL>0
      LIVTALV(7) = LIVTALV(7) .AND. NION>0
      LIVTALV(8) = LIVTALV(8) .AND. NPHOT>0
      LIVTALV(9) = LIVTALV(9) .AND. NATM>0
      LIVTALV(10) = LIVTALV(10) .AND. NATM>0
      LIVTALV(11) = LIVTALV(11) .AND. NMOL>0
      LIVTALV(12) = LIVTALV(12) .AND. NION>0
      LIVTALV(13) = LIVTALV(13) .AND. NPHOT>0
      LIVTALV(14) = LIVTALV(14) .AND. NPLS>0
      LIVTALV(15) = LIVTALV(15) .AND. NMOL>0
      LIVTALV(16) = LIVTALV(16) .AND. NATM>0
      LIVTALV(17) = LIVTALV(17) .AND. NMOL>0
      LIVTALV(18) = LIVTALV(18) .AND. NION>0
      LIVTALV(19) = LIVTALV(19) .AND. NPHOT>0
      LIVTALV(20) = LIVTALV(20) .AND. NPLS>0
      LIVTALV(21) = LIVTALV(21) .AND. NION>0
      LIVTALV(22) = LIVTALV(22) .AND. NATM>0
      LIVTALV(23) = LIVTALV(23) .AND. NMOL>0
      LIVTALV(24) = LIVTALV(24) .AND. NION>0
      LIVTALV(25) = LIVTALV(25) .AND. NPHOT>0
      LIVTALV(26) = LIVTALV(26) .AND. NPLS>0
      LIVTALV(27) = LIVTALV(27) .AND. NPHOT>0
      LIVTALV(28) = LIVTALV(28) .AND. NATM>0
      LIVTALV(29) = LIVTALV(29) .AND. NMOL>0
      LIVTALV(30) = LIVTALV(30) .AND. NION>0
      LIVTALV(31) = LIVTALV(31) .AND. NPHOT>0
      LIVTALV(32) = LIVTALV(32) .AND. NPLS>0
      LIVTALV(33) = LIVTALV(33) .AND. NATM>0
      LIVTALV(34) = LIVTALV(34) .AND. NATM>0
      LIVTALV(35) = LIVTALV(35) .AND. NATM>0
      LIVTALV(36) = LIVTALV(36) .AND. NATM>0
      LIVTALV(37) = LIVTALV(37) .AND. NATM>0
      LIVTALV(38) = LIVTALV(38) .AND. NATM>0
      LIVTALV(39) = LIVTALV(39) .AND. NMOL>0
      LIVTALV(40) = LIVTALV(40) .AND. NMOL>0
      LIVTALV(41) = LIVTALV(41) .AND. NMOL>0
      LIVTALV(42) = LIVTALV(42) .AND. NMOL>0
      LIVTALV(43) = LIVTALV(43) .AND. NMOL>0
      LIVTALV(44) = LIVTALV(44) .AND. NMOL>0
      LIVTALV(45) = LIVTALV(45) .AND. NION>0
      LIVTALV(46) = LIVTALV(46) .AND. NION>0
      LIVTALV(47) = LIVTALV(47) .AND. NION>0
      LIVTALV(48) = LIVTALV(48) .AND. NION>0
      LIVTALV(49) = LIVTALV(49) .AND. NION>0
      LIVTALV(50) = LIVTALV(50) .AND. NION>0
      LIVTALV(51) = LIVTALV(51) .AND. NPHOT>0
      LIVTALV(52) = LIVTALV(52) .AND. NPHOT>0
      LIVTALV(53) = LIVTALV(53) .AND. NPHOT>0
      LIVTALV(54) = LIVTALV(54) .AND. NPHOT>0
      LIVTALV(55) = LIVTALV(55) .AND. NPHOT>0
      LIVTALV(56) = LIVTALV(56) .AND. NPHOT>0
      LIVTALV(NTALA) = LIVTALV(NTALA) .AND. NADV>0
      LIVTALV(NTALC) = LIVTALV(NTALC) .AND. NCLV>0
      LIVTALV(NTALT) = LIVTALV(NTALT) .AND. NSNV>0
      LIVTALV(NTALM) = LIVTALV(NTALM) .AND. NCPV>0
      LIVTALV(NTALB) = LIVTALV(NTALB) .AND. NBGV>0
      LIVTALV(NTALR) = LIVTALV(NTALR) .AND. NALV>0
C  GENERATION LIMIT TALLIES
      LIVTALV(NTALV-21) = LIVTALV(NTALV-21) .AND. NATM>0
      LIVTALV(NTALV-20) = LIVTALV(NTALV-20) .AND. NMOL>0
      LIVTALV(NTALV-19) = LIVTALV(NTALV-19) .AND. NION>0
      LIVTALV(NTALV-18) = LIVTALV(NTALV-18) .AND. NPHOT>0
      LIVTALV(NTALV-17) = LIVTALV(NTALV-17) .AND. NATM>0
      LIVTALV(NTALV-16) = LIVTALV(NTALV-16) .AND. NMOL>0
      LIVTALV(NTALV-15) = LIVTALV(NTALV-15) .AND. NION>0
      LIVTALV(NTALV-14) = LIVTALV(NTALV-14) .AND. NPHOT>0
      LIVTALV(NTALV-13) = LIVTALV(NTALV-13) .AND. NATM>0
      LIVTALV(NTALV-12) = LIVTALV(NTALV-12) .AND. NMOL>0
      LIVTALV(NTALV-11) = LIVTALV(NTALV-11) .AND. NION>0
      LIVTALV(NTALV-10) = LIVTALV(NTALV-10) .AND. NPHOT>0
      LIVTALV(NTALV-9) = LIVTALV(NTALV-9) .AND. NATM>0
      LIVTALV(NTALV-8) = LIVTALV(NTALV-8) .AND. NMOL>0
      LIVTALV(NTALV-7) = LIVTALV(NTALV-7) .AND. NION>0
      LIVTALV(NTALV-6) = LIVTALV(NTALV-6) .AND. NPHOT>0
      LIVTALV(NTALV-5) = LIVTALV(NTALV-5) .AND. NPLS>0
      LIVTALV(NTALV-4) = LIVTALV(NTALV-4) .AND. NATM>0
      LIVTALV(NTALV-3) = LIVTALV(NTALV-3) .AND. NMOL>0
      LIVTALV(NTALV-2) = LIVTALV(NTALV-2) .AND. NION>0
      LIVTALV(NTALV-1) = LIVTALV(NTALV-1) .AND. NPHOT>0
      LIVTALV(NTALV-0) = LIVTALV(NTALV-0) .AND. NPLS>0

      NFIRST(1)=NATM
      NFIRST(2)=NMOL
      NFIRST(3)=NION
      NFIRST(4)=NPHOT
      NFIRST(5)=NATM
      NFIRST(6)=NMOL
      NFIRST(7)=NION
      NFIRST(8)=NPHOT
      NFIRST(9)=0
      NFIRST(10)=NATM
      NFIRST(11)=NMOL
      NFIRST(12)=NION
      NFIRST(13)=NPHOT
      NFIRST(14)=NPLS
      NFIRST(15)=0
      NFIRST(16)=NATM
      NFIRST(17)=NMOL
      NFIRST(18)=NION
      NFIRST(19)=NPHOT
      NFIRST(20)=NPLS
      NFIRST(21)=0
      NFIRST(22)=NATM
      NFIRST(23)=NMOL
      NFIRST(24)=NION
      NFIRST(25)=NPHOT
      NFIRST(26)=NPLS
      NFIRST(27)=0
      NFIRST(28)=NATM
      NFIRST(29)=NMOL
      NFIRST(30)=NION
      NFIRST(31)=NPHOT
      NFIRST(32)=NPLS
      NFIRST(33)=0
      NFIRST(34)=0
      NFIRST(35)=0
      NFIRST(36)=0
      NFIRST(37)=0
      NFIRST(38)=0
      NFIRST(39)=0
      NFIRST(40)=0
      NFIRST(41)=0
      NFIRST(42)=0
      NFIRST(43)=0
      NFIRST(44)=0
      NFIRST(45)=0
      NFIRST(46)=0
      NFIRST(47)=0
      NFIRST(48)=0
      NFIRST(49)=0
      NFIRST(50)=0
      NFIRST(51)=0
      NFIRST(52)=0
      NFIRST(53)=0
      NFIRST(54)=0
      NFIRST(55)=0
      NFIRST(56)=0
      NFIRST(NTALA)=NADV
      NFIRST(NTALC)=NCLV
      NFIRST(NTALT)=NSNV
      NFIRST(NTALM)=NCPV
      NFIRST(NTALB)=NBGV
      NFIRST(NTALR)=NALV
C  GENERATION LIMIT TALLIES
      NFIRST(NTALV-21)=NATM
      NFIRST(NTALV-20)=NMOL
      NFIRST(NTALV-19)=NION
      NFIRST(NTALV-18)=NPHOT
      NFIRST(NTALV-17)=NATM
      NFIRST(NTALV-16)=NMOL
      NFIRST(NTALV-15)=NION
      NFIRST(NTALV-14)=NPHOT
      NFIRST(NTALV-13)=NATM
      NFIRST(NTALV-12)=NMOL
      NFIRST(NTALV-11)=NION
      NFIRST(NTALV-10)=NPHOT
      NFIRST(NTALV-9)=NATM
      NFIRST(NTALV-8)=NMOL
      NFIRST(NTALV-7)=NION
      NFIRST(NTALV-6)=NPHOT
      NFIRST(NTALV-5)=NPLS
      NFIRST(NTALV-4)=0
      NFIRST(NTALV-3)=0
      NFIRST(NTALV-2)=0
      NFIRST(NTALV-1)=0
      NFIRST(NTALV-0)=0
C
C  NTALV=82 ?
C
      DO 1 J=1,NTALV
!pb        IF (LIVTALV(J)) NFRSTI(J)=NFIRST(J)+1
        NFRSTI(J)=NFIRST(J)+1
        IF (LIVTALV(J)) NFIRST(J)=MAX0(1,NFIRST(J))
1     CONTINUE
C
      NADDI(1)=0
      NADDV(1)=0
      DO 2 J=2,NTALV
        NADDI(J)=NADDI(J-1)+NFRSTI(J-1)
2       NADDV(J)=NADDV(J-1)+NFIRST(J-1)
C
C  TOTAL NUMBER OF VOLUME AVERAGED TALLIES
      NVOLTL=NADDV(NTALV)+NFIRST(NTALV)  

      NTEST=NADDV(NTALV)+NFIRST(NTALV)
      NTESTI=NADDI(NTALV)+NFRSTI(NTALV)
      NTEST=NTEST*NRTAL
      NTESTI=NTESTI*NSTRAP
!pb      IF (NTEST.NE.NESTM1) THEN
!pb        WRITE (6,*) 'PARAMETER ERROR DETECTED IN SETPRM: NESTM1'
!pb        WRITE (6,*) 'NTEST, NESTM1 ',NTEST,NESTM1
!pb        CALL EXIT_OWN(1)
!pb      ENDIF
!pb      IF (NTESTI.NE.NOUTA1) THEN
!pb        WRITE (6,*) 'PARAMETER ERROR DETECTED IN SETPRM: NOUTA1'
!pb        WRITE (6,*) 'NTESTI, NOUTA1 ',NTESTI,NOUTA1
!pb        CALL EXIT_OWN(1)
!pb      ENDIF


      LIVTALS(1) = LIVTALS(1) .AND. NATM>0
      LIVTALS(2) = LIVTALS(2) .AND. NATM>0
      LIVTALS(3) = LIVTALS(3) .AND. NATM>0
      LIVTALS(4) = LIVTALS(4) .AND. NATM>0
      LIVTALS(5) = LIVTALS(5) .AND. NATM>0
      LIVTALS(6) = LIVTALS(6) .AND. NATM>0
      LIVTALS(7) = LIVTALS(7) .AND. NMOL>0
      LIVTALS(8) = LIVTALS(8) .AND. NMOL>0
      LIVTALS(9) = LIVTALS(9) .AND. NMOL>0
      LIVTALS(10) = LIVTALS(10) .AND. NMOL>0
      LIVTALS(11) = LIVTALS(11) .AND. NMOL>0
      LIVTALS(12) = LIVTALS(12) .AND. NMOL>0
      LIVTALS(13) = LIVTALS(13) .AND. NION>0
      LIVTALS(14) = LIVTALS(14) .AND. NION>0
      LIVTALS(15) = LIVTALS(15) .AND. NION>0
      LIVTALS(16) = LIVTALS(16) .AND. NION>0
      LIVTALS(17) = LIVTALS(17) .AND. NION>0
      LIVTALS(18) = LIVTALS(18) .AND. NION>0
      LIVTALS(19) = LIVTALS(19) .AND. NPHOT>0
      LIVTALS(20) = LIVTALS(20) .AND. NPHOT>0
      LIVTALS(21) = LIVTALS(21) .AND. NPHOT>0
      LIVTALS(22) = LIVTALS(22) .AND. NPHOT>0
      LIVTALS(23) = LIVTALS(23) .AND. NPHOT>0
      LIVTALS(24) = LIVTALS(24) .AND. NPHOT>0
      LIVTALS(25) = LIVTALS(25) .AND. NPLS>0

      LIVTALS(26) = LIVTALS(26) .AND. NATM>0
      LIVTALS(27) = LIVTALS(27) .AND. NATM>0
      LIVTALS(28) = LIVTALS(28) .AND. NATM>0
      LIVTALS(29) = LIVTALS(29) .AND. NATM>0
      LIVTALS(30) = LIVTALS(30) .AND. NATM>0
      LIVTALS(31) = LIVTALS(31) .AND. NATM>0
      LIVTALS(32) = LIVTALS(32) .AND. NMOL>0
      LIVTALS(33) = LIVTALS(33) .AND. NMOL>0
      LIVTALS(34) = LIVTALS(34) .AND. NMOL>0
      LIVTALS(35) = LIVTALS(35) .AND. NMOL>0
      LIVTALS(36) = LIVTALS(36) .AND. NMOL>0
      LIVTALS(37) = LIVTALS(37) .AND. NMOL>0
      LIVTALS(38) = LIVTALS(38) .AND. NION>0
      LIVTALS(39) = LIVTALS(39) .AND. NION>0
      LIVTALS(40) = LIVTALS(40) .AND. NION>0
      LIVTALS(41) = LIVTALS(41) .AND. NION>0
      LIVTALS(42) = LIVTALS(42) .AND. NION>0
      LIVTALS(43) = LIVTALS(43) .AND. NION>0
      LIVTALS(44) = LIVTALS(44) .AND. NPHOT>0
      LIVTALS(45) = LIVTALS(45) .AND. NPHOT>0
      LIVTALS(46) = LIVTALS(46) .AND. NPHOT>0
      LIVTALS(47) = LIVTALS(47) .AND. NPHOT>0
      LIVTALS(48) = LIVTALS(48) .AND. NPHOT>0
      LIVTALS(49) = LIVTALS(49) .AND. NPHOT>0
      LIVTALS(50) = LIVTALS(50) .AND. NPLS>0

      LIVTALS(51) = LIVTALS(51) .AND. NATM>0
      LIVTALS(52) = LIVTALS(52) .AND. NMOL>0
      LIVTALS(53) = LIVTALS(53) .AND. NION>0
      LIVTALS(54) = LIVTALS(54) .AND. NPHOT>0
      LIVTALS(55) = LIVTALS(55) .AND. NPLS>0
      LIVTALS(56) = LIVTALS(56) .AND. .TRUE.
      LIVTALS(NTLSA) = LIVTALS(NTLSA) .AND. NADS>0
      LIVTALS(NTLSR) = LIVTALS(NTLSR) .AND. NALS>0
      LIVTALS(59) = LIVTALS(59) .AND. NSPZ>0
C
      NFRSTW(1)=NATM
      NFRSTW(2)=NATM
      NFRSTW(3)=NATM
      NFRSTW(4)=NATM
      NFRSTW(5)=NATM
      NFRSTW(6)=NATM
      NFRSTW(7)=NMOL
      NFRSTW(8)=NMOL
      NFRSTW(9)=NMOL
      NFRSTW(10)=NMOL
      NFRSTW(11)=NMOL
      NFRSTW(12)=NMOL
      NFRSTW(13)=NION
      NFRSTW(14)=NION
      NFRSTW(15)=NION
      NFRSTW(16)=NION
      NFRSTW(17)=NION
      NFRSTW(18)=NION
      NFRSTW(19)=NPHOT
      NFRSTW(20)=NPHOT
      NFRSTW(21)=NPHOT
      NFRSTW(22)=NPHOT
      NFRSTW(23)=NPHOT
      NFRSTW(24)=NPHOT
      NFRSTW(25)=NPLS

      NFRSTW(26)=NATM
      NFRSTW(27)=NATM
      NFRSTW(28)=NATM
      NFRSTW(29)=NATM
      NFRSTW(30)=NATM
      NFRSTW(31)=NATM
      NFRSTW(32)=NMOL
      NFRSTW(33)=NMOL
      NFRSTW(34)=NMOL
      NFRSTW(35)=NMOL
      NFRSTW(36)=NMOL
      NFRSTW(37)=NMOL
      NFRSTW(38)=NION
      NFRSTW(39)=NION
      NFRSTW(40)=NION
      NFRSTW(41)=NION
      NFRSTW(42)=NION
      NFRSTW(43)=NION
      NFRSTW(44)=NPHOT
      NFRSTW(45)=NPHOT
      NFRSTW(46)=NPHOT
      NFRSTW(47)=NPHOT
      NFRSTW(48)=NPHOT
      NFRSTW(49)=NPHOT
      NFRSTW(50)=NPLS

      NFRSTW(51)=NATM
      NFRSTW(52)=NMOL
      NFRSTW(53)=NION
      NFRSTW(54)=NPHOT
      NFRSTW(55)=NPLS
      NFRSTW(56)=0
      NFRSTW(NTLSA)=NADS
      NFRSTW(NTLSR)=NALS
      NFRSTW(59)=NSPZ
C
C  NTALS=59 ?
C
      DO 4 J=1,NTALS
!pb        IF (LIVTALS(J)) NFRTWI(J)=NFRSTW(J)+1
        NFRTWI(J)=NFRSTW(J)+1
        IF (LIVTALS(J)) NFRSTW(J)=MAX0(1,NFRSTW(J))
4     CONTINUE
C
      NDDWI(1)=0
      NADDW(1)=0
      DO 3 J=2,NTALS
        NDDWI(J)=NDDWI(J-1)+NFRTWI(J-1)
3       NADDW(J)=NADDW(J-1)+NFRSTW(J-1)

C  TOTAL NUMBER OF SURFACE AVERAGED TALLIES
      NSRFTL=NADDW(NTALS)+NFRSTW(NTALS)

      NTEST=NADDW(NTALS)+NFRSTW(NTALS)
      NTESTI=NDDWI(NTALS)+NFRTWI(NTALS)
      NTEST=NTEST*NLMPGS
      NTESTI=NTESTI*NSTRAP
!pb      IF (NTEST.NE.NESTM2) THEN
!pb        WRITE (6,*) 'PARAMETER ERROR DETECTED IN SETPRM: NESTM2'
!pb        WRITE (6,*) 'NTEST, NESTM2 ',NTEST,NESTM2
!pb        CALL EXIT_OWN(1)
!pb      ENDIF
!pb      IF (NTESTI.NE.NOUTA2) THEN
!pb        WRITE (6,*) 'PARAMETER ERROR DETECTED IN SETPRM: NOUTA2'
!pb        WRITE (6,*) 'NTESTI, NOUTA2 ',NTESTI,NOUTA2
!pb        CALL EXIT_OWN(1)
!pb      ENDIF

      CALL ALLOC_CESTIM(2)
      CALL ASSOCIATE_CESTIM

C
C  CHECK LENGTH OF ARRAYS, WHICH ARE EQUIVALENZED TO OTHER ARRAYS
C
C
      IF (.FALSE.) THEN
      RSAVE=SGMS(NSD)
      SGMS(NSD)=1.234567
      IF (SDVI1(NSD,NRTAL+1).NE.1.234567) THEN
        WRITE (6,*) 'PARAMETER ERROR DETECTED IN SETPRM: NSDVI1?'
        CALL EXIT_OWN(1)
      ENDIF
      SGMS(NSD)=RSAVE
C
      RSAVE=SGMWS(NSDW)
      SGMWS(NSDW)=1.234567
      IF (SDVI2(NSDW,NLIMPS+1).NE.1.234567) THEN
        WRITE (6,*) 'PARAMETER ERROR DETECTED IN SETPRM: NSDVI2?'
        CALL EXIT_OWN(1)
      ENDIF
      SGMWS(NSDW)=RSAVE
C
      RSAVE=VGENPH(NPHOT,NRTAL)
      VGENPH(NPHOT,NRTAL)=1.234567
      IF (ESTIMV(NVOLTL,NRTAL).NE.1.234567) THEN
        WRITE (6,*) 'PARAMETER ERROR DETECTED IN SETPRM: NESTM1?'
        CALL EXIT_OWN(1)
      ENDIF
      VGENPH(NPHOT,NRTAL)=RSAVE
C
      RSAVE=SPUMP(NSPZ,NLMPGS)
      SPUMP(NSPZ,NLMPGS)=1.234567
      IF (ESTIMS(NSRFTL,NLMPGS).NE.1.234567) THEN
        WRITE (6,*) 'PARAMETER ERROR DETECTED IN SETPRM: NESTM2?'
        CALL EXIT_OWN(1)
      ENDIF
      SPUMP(NSPZ,NLMPGS)=RSAVE
C
C  NOW ATOMIC DATA ARRAYS: COMXS
C
      RSAVE=ZMFPI
      ZMFPI=1.234567
      IF (XSTORV(NSTORV).NE.1.234567) THEN
        WRITE (6,*) 'PARAMETER ERROR DETECTED IN SETPRM: NSTOR?'
        CALL EXIT_OWN(1)
      ENDIF
      ZMFPI=RSAVE
C
      RSAVE=VOLTOT
      VOLTOT=1.234567
      IF (RCGM1(NCGM1).NE.1.234567) THEN
        WRITE (6,*) 'PARAMETER ERROR DETECTED IN SETPRM: NCGM1?'
        CALL EXIT_OWN(1)
      ENDIF
      VOLTOT=RSAVE
C
      RSAVE=ZDF
      ZDF=1.234567
      IF (RCGRID(NCGRD).NE.1.234567) THEN
        WRITE (6,*) 'PARAMETER ERROR DETECTED IN SETPRM: NCGRD?'
        CALL EXIT_OWN(1)
      ENDIF
      ZDF=RSAVE
C
      ISAVE=NSBOX_TAL
      NSBOX_TAL=1234567
      IF (ICGRID(MCGRD).NE.1234567) THEN
        WRITE (6,*) 'PARAMETER ERROR DETECTED IN SETPRM: MCGRD?'
        CALL EXIT_OWN(1)
      ENDIF
      NSBOX_TAL=ISAVE
C
      ISAVE=NPPLG
      NPPLG=1234567
      IF (ICPLYG(MCPLYG).NE.1234567) THEN
        WRITE (6,*) 'PARAMETER ERROR DETECTED IN SETPRM: MCPLYG?'
        CALL EXIT_OWN(1)
      ENDIF
      NPPLG=ISAVE
      END IF
C
      NFRSTP(1)=0
      NFRSTP(2)=NPLSTI
      NFRSTP(3)=0
      NFRSTP(4)=NPLS
      NFRSTP(5)=NPLSV
      NFRSTP(6)=NPLSV
      NFRSTP(7)=NPLSV
      NFRSTP(8)=0
      NFRSTP(9)=0
      NFRSTP(10)=0
      NFRSTP(11)=0
      NFRSTP(12)=NAIN
      NFRSTP(13)=NPLS
      NFRSTP(14)=0
      NFRSTP(15)=NSPZMC
      NFRSTP(16)=0
      NFRSTP(17)=0
C
C  NTALI=17?
C
      DO 5 J=1,NTALI
        NFRSTP(J)=MAX0(1,NFRSTP(J))
5     CONTINUE
C
      NADDP(1)=0
      DO 6 J=2,NTALI
6       NADDP(J)=NADDP(J-1)+NFRSTP(J-1)
      NTESTP=NADDP(NTALI)+NFRSTP(NTALI)
      NTESTP=NTESTP*NRAD
      IF (NTESTP.NE.NPLPRM) THEN
        WRITE (6,*) 'PARAMETER ERROR DETECTED IN SETPRM: NPLPRM'
        WRITE (6,*) 'NTESTP, NPLPRM ',NTESTP,NPLPRM
        CALL EXIT_OWN(1)
      ENDIF
C
      RETURN
      END




