      MODULE CLAST

      USE PRECISION
      USE PARMMOD

      IMPLICIT NONE

      PRIVATE

      PUBLIC :: ALLOC_CLAST, DEALLOC_CLAST, INIT_CLAST

      REAL(DP), PUBLIC, ALLOCATABLE, SAVE ::
     R          XCMEAN(:), SGCVMX(:),
     R          XEMEAN(:), SGEVMX(:),
     R          XPMEAN(:), SGPVMX(:)

      INTEGER, PUBLIC, ALLOCATABLE, SAVE ::
     I         NCMEAN(:),IFLRCX(:),
     I         NEMEAN(:),IFLREL(:),
     I         NPMEAN(:),IFLRPI(:)


      CONTAINS


      SUBROUTINE ALLOC_CLAST

      IF (ALLOCATED(XCMEAN)) RETURN

      ALLOCATE (XCMEAN(NRCX))
      ALLOCATE (SGCVMX(NRCX))
      ALLOCATE (XEMEAN(NREL))
      ALLOCATE (SGEVMX(NREL))
      ALLOCATE (XPMEAN(NRPI))
      ALLOCATE (SGPVMX(NRPI))

      ALLOCATE (NCMEAN(NRCX))
      ALLOCATE (IFLRCX(NRCX))
      ALLOCATE (NEMEAN(NREL))
      ALLOCATE (IFLREL(NREL))
      ALLOCATE (NPMEAN(NRPI))
      ALLOCATE (IFLRPI(NRPI))

      WRITE (55,'(A,T25,I15)')
     .      ' CLAST ',(2*NRCX+2*NREL+2*NRPI)*(8+4)

      CALL INIT_CLAST

      RETURN
      END SUBROUTINE ALLOC_CLAST


      SUBROUTINE DEALLOC_CLAST

      IF (.NOT.ALLOCATED(XCMEAN)) RETURN

      DEALLOCATE (XCMEAN)
      DEALLOCATE (SGCVMX)
      DEALLOCATE (XEMEAN)
      DEALLOCATE (SGEVMX)
      DEALLOCATE (XPMEAN)
      DEALLOCATE (SGPVMX)

      DEALLOCATE (NCMEAN)
      DEALLOCATE (IFLRCX)
      DEALLOCATE (NEMEAN)
      DEALLOCATE (IFLREL)
      DEALLOCATE (NPMEAN)
      DEALLOCATE (IFLRPI)

      RETURN
      END SUBROUTINE DEALLOC_CLAST


      SUBROUTINE INIT_CLAST

      XCMEAN = 0._DP
      SGCVMX = 0._DP
      XEMEAN = 0._DP
      SGEVMX = 0._DP
      XPMEAN = 0._DP
      SGPVMX = 0._DP

      NCMEAN = 0
      IFLRCX = 0
      NEMEAN = 0
      IFLREL = 0
      NPMEAN = 0
      IFLRPI = 0

      RETURN
      END SUBROUTINE INIT_CLAST

      END MODULE CLAST
