C
C
C----------------------------------------------------------------------*
C SUBROUTINE PLTMSK                                                    *
C----------------------------------------------------------------------*
      SUBROUTINE PLTMSK(IERR)
C
C  PLOTPROGRAMM ZUR ERSTELLUNG EINES ZEICHENFELDES.
C  DIE EINGABEWERTE GEBEN AN WO SICH DAS FELD IM BILD BEFINDEN SOLL UND
C  WELCHE ART VON X- UND Y-ACHSE GEWUENSCHT WIRD.
C  DAS HEISST OB MIT LOGARITHMISCHER ODER LINEARER ACHSENEINTEILUNG,
C  MIT GITTERLINIEN ODER NUR MIT KURZEN MARKIERUNGEN VERSEHEN
C  ODER BESCHRIFTUNG VOM PROGRAMM ANGEPASST ODER SELBST VORGEGEBEN.
C
C  EINGABEDATEN:  COMMONBLOECKE ORIGIN,XAXES,YAXES
C
C
      USE CPLMSK

      IMPLICIT NONE
      INTEGER, INTENT(OUT) :: IERR
      REAL(DP) :: XMIN, XMAX, YMIN, YMAX
      INTEGER :: IAX
      CALL GRSCLC(REAL(X0PL,KIND(1.E0)),REAL(Y0PL,KIND(1.E0)),
     .            REAL(X0PL+LENX,KIND(1.E0)),
     .            REAL(Y0PL+LENY,KIND(1.E0)))
C  PLOT X AXIS
      IAX=1
      CALL PLTAXI(IERR,IAX)
C  PLOT Y AXIS
      IAX=2
      CALL PLTAXI(IERR,IAX)
      IF (IERR.GT.0) RETURN
C
      IF (LOGX) THEN
         XMIN=REAL(MINLX,KIND(1.E0))
         XMAX=REAL(MAXLX,KIND(1.E0))
      ELSE
         XMIN=MINX
         XMAX=MAXX
      ENDIF
C
      IF (LOGY) THEN
         YMIN=REAL(MINLY,KIND(1.E0))
         YMAX=REAL(MAXLY,KIND(1.E0))
      ELSE
         YMIN=MINY
         YMAX=MAXY
      ENDIF
C
      CALL GRSCLV(REAL(XMIN,KIND(1.E0)),REAL(YMIN,KIND(1.E0)),
     .            REAL(XMAX,KIND(1.E0)),REAL(YMAX,KIND(1.E0)))
C
      RETURN
      END
