

      SUBROUTINE IF0PRM(IUNIN)
C
      USE PRECISION
      USE PARMMOD
      USE COMUSR
      USE CINIT
      USE CTETRA

      IMPLICIT NONE

      INTEGER, INTENT(IN) :: IUNIN
      INTEGER :: NFLA, NCUTB, NCUTL, NDXA, NDYA, IPL, NTARGI, IT, IPRT,
     .           NAINB, IAIN, NAOTB, IAOT, NECKEN, NTRIAN, NRKNOT, 
     .           NTRII, NCOPI, N1, N2, N3, MPER
      INTEGER, ALLOCATABLE :: NTGPRT(:)
      CHARACTER(72) :: ZEILE
C
      READ (IUNIN,*)
      READ (IUNIN,'(3I6)') NFLA,NCUTB,NCUTL
      DO IPL=1,NPLS
        READ (IUNIN,*) 
      END DO
      READ (IUNIN,'(2I6)') NDXA,NDYA
C  NUMBER OF TARGET SOURCES ON B2 SURFACES: NTARGI
        READ (IUNIN,'(I6)') NTARGI
C  NUMBER OF PARTS PER TARGET SOURCE
      IF (NTARGI.GT.0) THEN
        ALLOCATE (NTGPRT(NTARGI))
        READ (IUNIN,'(12I6)') (NTGPRT(IT),IT=1,NTARGI)
        NPTRGT=SUM(NTGPRT)
        DO IT=1,NTARGI
          DO IPRT=1,NTGPRT(IT)
 331        READ (IUNIN,'(A72)') ZEILE
            IF (ZEILE(1:1).EQ.'*') THEN
              GOTO 331
            ENDIF
          END DO
        END DO
        DEALLOCATE (NTGPRT)
      END IF
      READ (IUNIN,*)
C  READ ADDITIONAL DATA TO BE TRANSFERRED FROM B2 INTO EIRENE
C  HERE: B2 VOLUME TALLIES
      READ (IUNIN,'(I6)') NAINB
      NAIN = MAX(NAIN,NAINB)
      DO IAIN=1,NAINB
        READ (IUNIN,*) 
        READ (IUNIN,*) 
        READ (IUNIN,*) 
      END DO
C  READ ADDITIONAL DATA TO BE TRANSFERRED FROM EIRENE INTO B2
C  HERE: EIRENE SURFACE TALLIES
      READ (IUNIN,'(I6)') NAOTB
      DO IAOT=1,NAOTB
        READ (IUNIN,*) 
      END DO
C
C READING BLOCK 14 FROM FORMATTED INPUT FILE (IUNIN) FINISHED
C
C
C  DEFINE ADDITIONAL TALLIES FOR COUPLING (UPDATED IN SUBR. UPTCOP
C                                              AND IN SUBR. COLLIDE)
      NCOPI=4
      NCPVI=NCOPI*NPLS
      NCOP = NCOPI
      NCPV = NCPVI
C
      OPEN (UNIT=30,ACCESS='SEQUENTIAL',FORM='FORMATTED')
      REWIND 30

      READ (30,*) N1,N2,N3
      READ (30,*) MPER
C
C SAVE SOME MORE INPUT DATA FOR SHORT CYCLE ON COMMON CCOUPL
      NDX = MAX(NDXA, N2)
      NDY = MAX(NDYA, N1)
      NFL = NFLA
      NDXP = NDX+1
      NDYP = NDY+1

      NTETRA=(N1-1)*(n2-1)*(N3-1)*6
      NCOORD=N1*N2*N3

      RETURN
      END
