#!/bin/tcsh
#
#
echo 'RUNNING and COMPARING Testcases'
#
set progdir=divimp-gf

set scriptdir = $HOME/$progdir/scripts

source $scriptdir/init_testcases

#
# Check to see if testcase directory already exists
#
#
if ( -e $testdir ) then 
#
#  Run testcases 
#
   source $scriptdir/run_testcases 
#
#  Compare testcases
#
   source $scriptdir/compare_testcases 
#
#  Return to main DIVIMP directory
#
   cd $divmain
#
else
   echo "ERROR: Test cases have not yet been set up on this machine."
   echo "       Please run setup_testcases."
endif



