C
C
      SUBROUTINE GRNXTB(K)
C
C  K=1 CALL VOR EINEM BILD AUS EIGENER GRSOFTWARE
C  K=2 CALL VOR EINEM BILD MIT GRBLD
C
      IMPLICIT NONE

      INTEGER, INTENT(IN) :: K
      INTEGER, SAVE :: IFIRST=0, IFRST2=0

      WRITE (6,*) 'GRNXTB K,IFIRST,IFRST2 ',K,IFIRST,IFRST2
      GOTO (1,2),K
1     IF (IFIRST.EQ.1) THEN
        CALL GRNXTF
        RETURN
      ELSE
        IFIRST=1
      ENDIF
      RETURN
C
2     IF (IFIRST.EQ.0) THEN
        CALL GRSCLC (0.,0.0,39.5,28.7)
        IFIRST=1
        IFRST2=1
      ELSE IF (IFRST2.EQ.0) THEN
        CALL GRNXTF
        CALL GRSCLC (0.,0.,39.5,28.7)
        IFRST2=1
      ELSE
        CALL GRSCLC (3.,3.5,39.5,28.7)
      ENDIF
      RETURN
      END
