

      FUNCTION FEHVPI3 (IRPI,K)

      USE PRECISION
      USE PARMMOD
      USE COMUSR
      USE CCONA
      USE COMXS

      IMPLICIT NONE

      INTEGER, INTENT(IN) :: IRPI, K
      REAL(DP) :: FEHVPI3, EHVPI, FTABPI3, RATE_COEFF, ERATE
      INTEGER :: II, KK

      FEHVPI3=0.D0
      KK=NRHVPI(IRPI)

      IF (KK == -1) THEN
! TAKE EHEAVY FROM INPUT FILE
         FEHVPI3=EHVPI3(IRPI,1,1)

      ELSE IF (KK > 0) THEN
        EHVPI = RATE_COEFF(KK,TEINL(K),0._DP,.FALSE.,0,ERATE)
        EHVPI=EXP(MAX(-100._DP,EHVPI+FACREA(KK,2)))
        FEHVPI3=EHVPI*DEIN(K)/(FTABPI3(IRPI,K)+EPS60)
      END IF

      RETURN
      END
