

      FUNCTION FTABPI3 (IRPI,K)

      USE PRECISION
      USE PARMMOD
      USE COMUSR
      USE COMPRT
      USE COMXS

      IMPLICIT NONE

      INTEGER, INTENT(IN) :: IRPI, K
      REAL(DP) :: TBPIC(9), FTABPI3, PLS, TBPI, RATE_COEFF, ERATE
      INTEGER :: J, I, II, KK, IPLSTI

      TBPI=0.D0
      KK = NREAPI(IRPI)

      IPLSTI=MPLSTI(IPLS)
      PLS=TIINL(IPLSTI,K)+ADDPI(IRPI,IPLS)

      TBPI = RATE_COEFF(KK,PLS,0._DP,.TRUE.,0,ERATE)*FACREA(KK,1)
      TBPI = TBPI*DIIN(IPLS,K)

      FTABPI3 = TBPI

      RETURN
      END

