C
C*DK MASR5
      SUBROUTINE MASR5 (A,B,C,D,E,F)
      USE PRECISION
      IMPLICIT NONE
      CHARACTER(40), INTENT(IN) :: A
      REAL(DP), INTENT(IN) :: B, C, D, E, F
      WRITE (6,60) A,B,C,D,E,F
60    FORMAT (1X,A40/1X,5(1PE12.4,3X))
      RETURN
      END
