CDR  APRIL 2006: IPHOT ADDED TO LOOP: DO 140
!pb  31.10.06:  definition of RPART, RPARTC, IPART, IPARTC changed
!               RPART(NPARTT,NPRNL) --> RPART(NPRNL,NPARTT)
C
      SUBROUTINE TMSTEP
C
C  THIS SUBROUTINE IS CALLED AFTER EACH TIME CYCLE. IT ALLOWS TO
C  MODIFY SOME PLASMA BACKGROUND AND PRIMARY SOURCE DATA (I.E., STRATA
C  ISTRA=1,NSTRAI-1) ACCORDING TO INPUT SPECIFICATIONS IN BLOCK 13.
C
C  IT THEN DEFINES THE STRATUM ISTRA=NSTRAI, I.E., THE SOURCE DUE TO
C  THE INITIAL CONDITION AT THE BEGINNING OF THE NEXT TIMESTEP.
C
      USE PRECISION
      USE PARMMOD
      USE COMUSR
      USE CCONA
      USE CLOGAU
      USE CPLOT
      USE CTRCEI
      USE COMPRT
      USE COMNNL
      USE COMSOU
      USE CTEXT
      USE CLGIN
      USE COUTAU

      IMPLICIT NONE

      REAL(DP) :: SGMTOT(NSTRA),FLX(NSTRA)
      REAL(DP) :: FLXQ, FCT, SGMREL, SGMTQN, ADDS, ADD, SGMTQ1
      INTEGER :: J, ISTRO, IPANO, ISTR, I, IPAN
C
C  STEP 1
C
C  REDUCE REDUNDANT PRINTOUT
      TRCPLT=.FALSE.
      TRCGRD=.FALSE.
      PLTSRC(NSTRAI)=.FALSE.
      DO 120 ISTR=1,NSTRAI-1
        PLTSRC(NSTRAI)=PLTSRC(NSTRAI).OR.PLTSRC(ISTR)
120   CONTINUE
C
C  SPEED UP GEOMETRY
C
C  STEP 2
C
C  MODIFY BACKGROUND DATA AS COMPARED TO PREVIOUS ITERATION
C  FOR TIME DEP. MODE
C
C  STARTING TIME FOR NEXT TIMESTEP
C
      TIME0=TIME0+DTIMV
C
C  CALL USER SUPPLIED ROUTINE TMSUSR
C  E.G.: FILL COMMON BRAEIR WITH NEW PLASMA, IF NMODE.NE.0
C  BE CAREFUL: NO INDEX MAPPING IS DONE, UNLESS
C  NCUTL.NE.NCUTB
      CALL TMSUSR(TIME0)
      NLPLAS=.TRUE.
C
C  STEP 3
C
C  SET SOURCE DUE TO INITIAL CONDITION FOR NEXT TIME CYCLE
C
C  SOURCE STRENGTH OF INITIAL DISTRIBUTION IN NEW TIME CYCLE
      IPRNL=IPRNLI
      IPRNLI=0
      IF (NPTST.EQ.0) THEN
        NPTS(NSTRAI)=IPRNL
        NLMOVIE=.FALSE.
      ELSEIF (NPTST.GT.0) THEN
        NPTS(NSTRAI)=NPTST
        NLMOVIE=.FALSE.
      ELSEIF (NPTST.LT.0) THEN
        NPTS(NSTRAI)=IPRNL
        NLMOVIE=.TRUE.
      ENDIF

      FLUX(NSTRAI)=0.
      RPARTW(0)=0.0
      DO 130 ISTR=1,NSTRAI
        SGMTOT(ISTR)=0.0
        FLX(ISTR)=0.0
130   CONTINUE
      SGMREL=0.0
C
      IF (IPRNL.EQ.0) GOTO 300
      IPANO=IPART(1,1)
      ISTRO=IPART(8,1)
      ADDS=0.
C
C  SET "ATOMIC" FLUXES ONTO CENSUS ARRAY
      DO 140  I=1,IPRNL
        IPAN=IPART(1,I)
        ISTR=IPART(8,I)
        ITYP=ISPEZI(IPART(9,I),-1)
        WEIGHT=RPART(9,I)
        IF (ITYP.EQ.0) THEN
          IPHOT=ISPEZI(IPART(I,9),0)
          RPART(9,I)=RPART(9,I)*FPHSCL(ISTR)
          ADD=WEIGHT*FLXFAC(ISTR)*NPRT(IPHOT)
        ELSEIF (ITYP.EQ.1) THEN
          IATM=ISPEZI(IPART(9,I),1)
          RPART(9,I)=RPART(9,I)*FASCL(ISTR)
          ADD=WEIGHT*FLXFAC(ISTR)*NPRT(NSPH+IATM)
        ELSEIF (ITYP.EQ.2) THEN
          IMOL=ISPEZI(IPART(9,I),2)
          RPART(9,I)=RPART(9,I)*FMSCL(ISTR)
          ADD=WEIGHT*FLXFAC(ISTR)*NPRT(NSPA+IMOL)
        ELSEIF (ITYP.EQ.3) THEN
          IION=ISPEZI(IPART(9,I),3)
          RPART(9,I)=RPART(9,I)*FISCL(ISTR)
          ADD=WEIGHT*FLXFAC(ISTR)*NPRT(NSPAM+IION)
        ENDIF
        RPARTW(I)=RPARTW(I-1)+WEIGHT*FLXFAC(ISTR)
C
C  ACCUMULATE CONTRIBUTION FROM TEST FLIGHT NO. IPANO
        IF (IPAN.EQ.IPANO) THEN
          ADDS=ADDS+ADD
        ENDIF
C  NEW PARTICLE ?
        IF (IPAN.NE.IPANO) THEN
          FLUX(NSTRAI)=FLUX(NSTRAI)+ADDS
          FLX(ISTRO)=FLX(ISTRO)+ADDS
          SGMTOT(ISTRO)=SGMTOT(ISTRO)+ADDS*ADDS
          IPANO=IPAN
          ISTRO=ISTR
          ADDS=ADD
        ENDIF
140   CONTINUE
C  CONTRIBUTION FROM LAST TEST FLIGHT
      FLUX(NSTRAI)=FLUX(NSTRAI)+ADDS
      FLX(ISTRO)=FLX(ISTRO)+ADDS
      SGMTOT(ISTRO)=SGMTOT(ISTRO)+ADDS*ADDS
C
C  VARIANCE OF CENSUS FLUX: ACCOUNT FOR SOURCE STRATIFICATION
C
      SGMTQ1=0.
      SGMREL=0.
      DO 150 ISTR=1,NSTRAI
        IF (XMCP(ISTR).GT.1.) THEN
          FCT=XMCP(ISTR)/(XMCP(ISTR)-1.)
          FLXQ=FLX(ISTR)*FLX(ISTR)
          SGMTQ1=SGMTQ1+(SGMTOT(ISTR)-FLXQ/XMCP(ISTR))*FCT
        ENDIF
150   CONTINUE
      IF (SGMTQ1.GT.0.D0) THEN
        SGMTQN=SQRT(SGMTQ1)
        SGMREL=SGMTQN/(FLUX(NSTRAI)+EPS60)
        SGMREL=MAX(0._DP,SGMREL-EPS10)*100.
      ENDIF
C
      IF (FLUX(NSTRAI).GT.0) THEN
        NSRFSI(NSTRAI)=1
        SORWGT(1,NSTRAI)=1.D0
      ENDIF
C
      DO I=1,IPRNL
        DO J=1,NPARTT
          RPARTC(J,I)=RPART(J,I)
        ENDDO
      ENDDO
      DO I=1,IPRNL
        DO J=1,MPARTT
          IPARTC(J,I)=IPART(J,I)
        ENDDO
      ENDDO
C
      DO I=1,IPRNL
        IPARTC(8,I)=NSTRAI
      ENDDO
C
C  CALL WRSNAP TO WRITE SNAPSHOT POPULATION
C  FOR NEXT RUN ON FT 15
C
      IF ((NFILEJ.EQ.1.OR.NFILEJ.EQ.3).AND.ITIMV.EQ.NTIME) THEN
        CALL WRSNAP
        WRITE (iunout,*) 'CENSUS ARRAY, FLUX AND TOTAL TIMESTEP STORED '
      ENDIF
C
300   CONTINUE
      CALL LEER(2)
      WRITE (iunout,*) 'TIME CYCLE COMPLETED, NEXT TIME CYCLE PREPARED '
      WRITE (iunout,*) 'NEXT TIME CYCLE RUNS FROM TIM1 TO TIM2:  '
      CALL MASR2('TIM1, TIM2      ',TIME0,TIME0+DTIMV)
      CALL MASJ1('IPRNL   ',IPRNL)
      WRITE (IUNOUT,*) '"ATOMIC" FLUX AT CENSUS (AMP):'
      CALL MASR1('FLUX    ',FLUX(NSTRAI))
      CALL MASR1('+-%     ',SGMREL)
C
      RETURN
      END
