C
C
      FUNCTION EIRENE_ELLU (X)
      USE EIRMOD_CLMSUR
      IMPLICIT NONE
      REAL(DP), INTENT(IN) :: X
      REAL(DP) :: EIRENE_ELLU
      EIRENE_ELLU=-BHALB*SQRT(MAX(0.D0,1.D0-X*X/(AHALB*AHALB)))
      RETURN
      END
