C
C
      FUNCTION EIRENE_PARA2U (XIN)
      USE EIRMOD_CLMSUR
      IMPLICIT NONE
      REAL(DP), INTENT(IN) :: XIN
      REAL(DP) :: RAD, Y, DH, EIRENE_PARA2U
      DH=-E/(2.*C)
      RAD=(E*E)/(4.*C*C)-(D*XIN+F)/C
      IF (RAD.GE.0.) GOTO 1
      EIRENE_PARA2U=1.D50
      RETURN
1     Y=-SQRT(RAD)
      EIRENE_PARA2U=Y-DH
      RETURN
      END
