#!/bin/bash

cp d-123417-$1.d6i d-123417-$2.d6i


arg1=s/$3/$4/g 
arg2=s/$5/$6/g
arg3=s/$7/$8/g

./replace_string -nq -nb -s "$arg1" -f d-123417-$2.d6i
./replace_string -nq -nb -s "$arg2" -f d-123417-$2.d6i
./replace_string -nq -nb -s "$arg3" -f d-123417-$2.d6i
