'SOL23  a_sm_s: P_SOL  limit [MW]                    '    1.0
'SOL23  a_sm_r: zhi(3) limit                         '    0.5
'SOL23  Relaxation parameter for PIN iterations      '    0.1
'SOL23  CFD convergence tolerance, max Residual      '    1.0E-3
'SOL23  CFD convergence tolerance, RMS Residual      '    1.0E-4
'SOL23  Qperp 0:const, 1:n, 2:sqrt(n), 3:Qiz, 4:d2ndr'    1
'SOL23  Power, Momentum loss limit (wrt.target)      '    1.0
