$
$   SOL 23 - Input parameters
$
'SOL23  Integration Type Option - 0=flat  1=linear   '     1
'SOL23  Boundary Condition Option - 0=std            '     0
'SOL23  SEED plasma type - 1=exp  2=s5gauss          '     1
'SOL23  Initial Ionization Source Length (*smax)     '    1.0
'SOL23  Initial Ionization Source Decay  (*smax)     '    0.10
'SOL23  Initial Ionization Source Offset (*smax)     '    0.10
'SOL23  Initial Momentum   Source Length (*smax)     '    0.10
'SOL23  a_sm_s: P_SOL  limit [MW]                    '    1.0
'SOL23  a_sm_r: zhi(3) limit                         '    0.5
'SOL23  Relaxation parameter for PIN iterations      '    0.1
'SOL23  CFD convergence tolerance, max Residual      '    1.0E-3
'SOL23  CFD convergence tolerance, RMS Residual      '    1.0E-4
'SOL23  Qperp 0:const, 1:n, 2:sqrt(n), 3:Qiz, 4:d2ndr'    1
'SOL23  Power, Momentum loss limit (wrt.target)      '    1.0


