      SUBROUTINE TALUSR(ICOUNT,VECTOR,TALTOT,TALAV,
     .                  TXTTL,TXTSP,TXTUN,ILAST,*)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C  USER SUPPLIED POST PROCESSED TALLY NO. ICOUNT, FOR STRATUM ISTRA,
C  STORED ON VECTOR. (ISTRA IS KNOWN FROM COMMON COMPRT)
C
C  RETURN 1:       DO NOT PRINTOUT VOLUME AVERAGED TALLY "VECTOR"
C                  VECTOR NEEDS NOT BE RETURNED. INSTEAD, THE POST-
C                  PROCESSED TALLY CAN ALSO BE PUT ONTO THE ADDITIONAL TALLY
C                  STORAGES (ADDV,COLV,...) IF STORAGE IS PROVIDED IN PARMUSR,
C                  AND IF THE PARAMETERS NADVI, NCLVI, ETC. IN BLOCK 10A, OR 10B,
C                  ARE PROPERLY SET.
C  RETURN  :       PRINTOUT VOLUME AVERAGED TALLY VECTOR(I), I=1,NRAD,
C                  AS SPECIFIED IN INPUT BLOCK 11 FOR PRINTOUT OF TALLY NO. 0
C  INPUT:  ICOUNT: COUNTS THE NUMBER OF CALL TO TALUSR FOR EACH STRATUM
C                  FIRST CALL FOR STRATUM ISTRA: ICOUNT=1
C  OUTPUT: ILAST:  IF ILAST.GT.ICOUNT, THEN TALSUR IS CALLED
C                  ONCE MORE WITH ICOUNT INCREASED BY ONE
C                  OTHERWISE: TALUSR IS NOT CALLED AGAIN FOR THE CURRENT TALLY
C          TXTTL,TXTSP,TXTUN: TEXT IN PRINTOUT FOR THIS TALLY: NAME, SPECIES, UNITS
C          TALTOT,TALAV: TOTAL AND AVERAGE VALUE, FOR PRINTOUT
C
      INCLUDE 'PARMMOD'
      INCLUDE 'CESTIM'
      INCLUDE 'COMPRT'
      DIMENSION VECTOR(NRAD)
      CHARACTER*24 TXTSP,TXTUN
      CHARACTER*72 TXTTL
C
C  COMPUTE 5 CONTRIBUTIONS TO H-ALPHA EMISSION PROFILE, AND TOTAL
c slmod begin - f90 - not tr
c...bug?
c I believe HALFA is meant to be called here.
      CALL HALFA(ISTRA,1,2,3,4,5,6)
c
c      CALL HALPHA(ISTRA,1,2,3,4,5,6)
c slmod end

      RETURN
      END
