C
C*DK MASR3
      SUBROUTINE MASR3 (A,B,C,D)
      USE PRECISION
      IMPLICIT NONE
      CHARACTER(24), INTENT(IN) :: A
      REAL(DP), INTENT(IN) :: B, C, D
      WRITE (6,60) A,B,C,D
60    FORMAT (1X,A24,1X,3(1PE12.4,3X))
      RETURN
      END
