#!/bin/tcsh 
#

set DIVHOME = ~/divimp

ln -sf $DIVHOME/comsrc/mod_geometry.f         src/mod_geometry.f
ln -sf $DIVHOME/comsrc/mod_sol28.f            src/mod_osm.f
ln -sf $DIVHOME/comsrc/mod_sol28_legacy.f     src/mod_legacy.f
ln -sf $DIVHOME/comsrc/mod_eirene06.f         src/mod_eirene06.f
ln -sf $DIVHOME/comsrc/mod_user.f             src/mod_user.f

ln -sf $DIVHOME/div6/src/sol28_dev.f          src/dev.f
ln -sf $DIVHOME/div6/src/sol28_main.f         src/main.f
ln -sf $DIVHOME/div6/src/sol28_grid.f         src/grid.f
ln -sf $DIVHOME/div6/src/sol28_input.f        src/input.f
ln -sf $DIVHOME/div6/src/sol28_prescription.f src/prescription.f
ln -sf $DIVHOME/div6/src/sol28_setup.f        src/setup.f
ln -sf $DIVHOME/div6/src/sol28_solver.f       src/solver.f
ln -sf $DIVHOME/div6/src/sol28_sources.f      src/sources.f
ln -sf $DIVHOME/div6/src/sol28_user.f         src/user.f

ln -sf $DIVHOME/comsrc/sol28_utility.f        src/utility.f
ln -sf $DIVHOME/comsrc/mod_interface.f        src/mod_interface.f

ln -sf $DIVHOME/div6/src/eirene06.f           src/eirene06.f
