C
C
      SUBROUTINE EIRENE_PROFR (PRO,IINDEX,NSPZI,NSPZ1,NDAT)
C
C  READ ENTIRE PROFILE FROM WORK ARRAY
C
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      USE EIRMOD_CSPEI
 
      IMPLICIT NONE
 
      INTEGER, INTENT(IN) :: IINDEX, NSPZI, NSPZ1, NDAT
      REAL(DP), INTENT(OUT) :: PRO(NSPZ1,*)
 
      PRO(1:NSPZI,1:NDAT) = PLASMA_BCKGRND(IINDEX+1:IINDEX+NSPZI,1:NDAT)
      RETURN
      END
