      MODULE CAI

      USE PRECISION
      USE PARMMOD

      IMPLICIT NONE

      PRIVATE

      PUBLIC :: ALLOC_CAI, DEALLOC_CAI, INIT_CAI

      REAL(DP), PUBLIC, ALLOCATABLE, SAVE :: RATIO(:)

      INTEGER, PUBLIC, ALLOCATABLE, SAVE :: NRECOM(:)

      CONTAINS


      SUBROUTINE ALLOC_CAI

      IF (ALLOCATED(RATIO)) RETURN

      ALLOCATE (RATIO(NSTRA))
      ALLOCATE (NRECOM(NSTRA))

      WRITE (55,'(A,T25,I15)')
     .      ' CAI ',NSTRA*(8+4)

      CALL INIT_CAI

      RETURN
      END SUBROUTINE ALLOC_CAI


      SUBROUTINE DEALLOC_CAI

      IF (.NOT.ALLOCATED(RATIO)) RETURN

      DEALLOCATE (RATIO)
      DEALLOCATE (NRECOM)

      RETURN
      END SUBROUTINE DEALLOC_CAI


      SUBROUTINE INIT_CAI

      RATIO  = 0.D0
      NRECOM = 0

      RETURN
      END SUBROUTINE INIT_CAI

      END MODULE CAI
