      MODULE COMXS
!  jan-05: natprc_2,..... introduced
      USE PRECISION
      USE PARMMOD

      IMPLICIT NONE

      PRIVATE
 
      PUBLIC :: ALLOC_COMXS, DEALLOC_COMXS, 
     .          INIT_CMDTA,  WRITE_CMDTA,   READ_CMDTA,
     .          WRITE_CMAMF, READ_CMAMF, REAC_PARAM, GET_REACTION,
     .          CMDTA_XDR, CMAMF_XDR 

      TYPE REAC_PARAM
        REAL(DP) :: E0, E1, AIK, G1, G2, C2, C3, C4, C6, B12, B21
        REAL(DP) :: C6A(12)
        INTEGER :: IGND, IRCART, IPROFILETYPE
        INTEGER :: IPLSC6(12)
      END TYPE REAC_PARAM

      TYPE(REAC_PARAM), PUBLIC, SAVE :: REACTION
      INTEGER, PUBLIC, SAVE :: IDREAC

      REAL(DP), PUBLIC, TARGET, ALLOCATABLE, SAVE ::
     R        XSTOR(:,:), XSTORV(:)

      REAL(DP), PUBLIC, POINTER, SAVE ::
     R SIGVCX(:),   SIGVPI(:),   SIGVEI(:),   SIGVEL(:),
     R ESIGCX(:,:), ESIGPI(:,:), ESIGEI(:,:), ESIGEL(:,:),
     R VSIGCX(:),   VSIGPI(:),   VSIGEL(:),
     R SIGCXT,      SIGPIT,      SIGEIT,      SIGELT,      SIGTOT,
     R SIGBGK,      ZMFPI

      REAL(DP), PUBLIC, SAVE :: ZMFPTHI, TDGTEMX

csw added OTHER (OT) reactions
      REAL(DP), PUBLIC, POINTER, SAVE :: SIGVOT(:),   ESIGOT(:,:),
     R SIGOTT

      REAL(DP), PUBLIC, ALLOCATABLE, SAVE ::
     R TABDS1(:,:),   TABRC1(:,:),
     R TABPI3(:,:,:), TABCX3(:,:,:), TABEL3(:,:,:),
     R FDLMPI(:),     FDLMCX(:),     FDLMEL(:),
     R ADDPI(:,:),    ADDCX(:,:),    ADDEL(:,:)

      REAL(DP), PUBLIC, ALLOCATABLE, SAVE ::
     R PELDS(:),  PATDS(:,:), PMLDS(:,:), PIODS(:,:), PPLDS(:,:),
     R PELPI(:),  PATPI(:,:), PMLPI(:,:), PIOPI(:,:), PPLPI(:,:),
     R P2ND(:,:), P2NP(:,:),  P2NDS(:),   P2NPI(:)

      REAL(DP), PUBLIC, ALLOCATABLE, SAVE ::
     R EELDS1(:,:),   EHVDS1(:,:),   EELRC1(:,:),
     R EPLPI3(:,:,:), EPLCX3(:,:,:), EPLEL3(:,:,:), EPLOT3(:,:,:)

      REAL(DP), PUBLIC, ALLOCATABLE, SAVE ::
     R EATDS(:,:,:), EMLDS(:,:,:), EIODS(:,:,:), EPLDS(:,:),
     R EATPI(:,:),   EMLPI(:,:),   EIOPI(:,:),   EPLPI(:,:)

      INTEGER, PUBLIC, ALLOCATABLE, SAVE ::
     I MODCOL(:,:,:,:),
     I IESTCX(:,:), IESTEL(:,:), IESTPI(:,:), IESTEI(:,:),
     I NAEII(:),    NMDSI(:),    NIDSI(:),
     I NACXI(:),    NMCXI(:),    NICXI(:),
     I NAELI(:),    NMELI(:),    NIELI(:),
     I NAPII(:),    NMPII(:),    NIPII(:),
     I NAEIIM(:),   NMDSIM(:),   NIDSIM(:),
     I NACXIM(:),   NMCXIM(:),   NICXIM(:),
     I NAELIM(:),   NMELIM(:),   NIELIM(:),
     I NAPIIM(:),   NMPIIM(:),   NIPIIM(:),
     I NPRCI(:),    NPRCIM(:),
     I NPBGKA(:),   NPBGKM(:),   NPBGKI(:), NPBGKP(:,:)

      INTEGER, PUBLIC, ALLOCATABLE, SAVE ::
     I NATPRC(:),  NMLPRC(:), NIOPRC(:), NPLPRC(:), NPHPRC(:),
     I NATPRC_2(:),  NMLPRC_2(:), NIOPRC_2(:), NPLPRC_2(:), NPHPRC_2(:),
     I N1STX(:,:), N2NDX(:,:)

      INTEGER, PUBLIC, ALLOCATABLE, SAVE ::
     I NSEACX(:,:,:), NSEMCX(:,:,:), NSEICX(:,:,:),
     I NSEAEL(:,:,:), NSEMEL(:,:,:), NSEIEL(:,:,:),
     I NSEPRC(:,:)

      INTEGER, PUBLIC, ALLOCATABLE, SAVE ::
     I NREACX(:),NREAPI(:),NREAEL(:),
     I NREAEI(:),JEREAEI(:),NREARC(:),JEREARC(:),
     I NELREI(:),JELREI(:),NREAHV(:),NELREL(:),
     I NELRRC(:),JELRRC(:),NELRPI(:),NELRCX(:),
     I NELROT(:),NREAOT(:),
     I IPATDS(:,:),IPMLDS(:,:),
     I IPIODS(:,:),IPPLDS(:,:),
     I IPATPI(:,:),IPMLPI(:,:),
     I IPIOPI(:,:),IPPLPI(:,:),
     I LGACX(:,:,:),LGMCX(:,:,:),
     I LGICX(:,:,:),
     I LGAEI(:,:),    LGMEI(:,:),
     I LGIEI(:,:),
     I LGAEL(:,:,:),LGMEL(:,:,:),
     I LGIEL(:,:,:),
     I LGPRC(:,:),
     I LGAPI(:,:,:),LGMPI(:,:,:),
     I LGIPI(:,:,:)

      INTEGER, PUBLIC, SAVE ::
     I NRPII, NREII, NRCXI, NRELI, NRRCI, NRBGI

      INTEGER, PUBLIC, SAVE ::
     I NSTOR1, NSTOR,  NSTORV, NTAB, NDAT, NMDTA, MMDTA, NAMF, MAMF,
     I MSTOR1, MSTOR2

      REAL(DP), PUBLIC, ALLOCATABLE, SAVE ::
     R CREAC(:,:,:),DELPOT(:),   FACREA(:),
     R RCMN(:,:),   RCMX(:,:),   FPARM(:,:,:),
     R FREACA(:,:), FREACM(:,:), FREACI(:,:), FREACP(:,:), FREACPH(:,:),
     R FLDLMA(:,:), FLDLMM(:,:), FLDLMI(:,:), FLDLMP(:,:), FLDLMPH(:,:),
     R EELECA(:,:), EELECM(:,:), EELECI(:,:), EELECP(:,:), EELECPH(:,:),
     R EBULKA(:,:), EBULKM(:,:), EBULKI(:,:), EBULKP(:,:), EBULKPH(:,:),
     R ESCD1A(:,:), ESCD1M(:,:), ESCD1I(:,:), ESCD1P(:,:), ESCD1PH(:,:),
     R ESCD2A(:,:), ESCD2M(:,:), ESCD2I(:,:), ESCD2P(:,:), ESCD2PH(:,:)

      INTEGER, PUBLIC, ALLOCATABLE, SAVE ::
     I ISWR(:),     MODCLF(:),   MASSP(:),    MASST(:),
     I IFEXMN(:,:), IFEXMX(:,:), IFTFLG(:,:),
     I NRCP(:),     NRCA(:),     NRCM(:),     NRCI(:),     NRCPH(:),
     I IREACA(:,:), IREACM(:,:), IREACI(:,:), IREACP(:,:), IREACPH(:,:),
     I IBULKA(:,:), IBULKM(:,:), IBULKI(:,:), IBULKP(:,:), IBULKPH(:,:),
     I ISCD1A(:,:), ISCD1M(:,:), ISCD1I(:,:), ISCD1P(:,:), ISCD1PH(:,:),
     I ISCD2A(:,:), ISCD2M(:,:), ISCD2I(:,:), ISCD2P(:,:), ISCD2PH(:,:),
     I ISCD3A(:,:), ISCD3M(:,:), ISCD3I(:,:), ISCD3P(:,:), ISCD3PH(:,:),
     I ISCDEA(:,:), ISCDEM(:,:), ISCDEI(:,:), ISCDEP(:,:), ISCDEPH(:,:),
     I IESTMA(:,:), IESTMM(:,:), IESTMI(:,:), IESTMPH(:,:),
     I IBGKA (:,:), IBGKM (:,:), IBGKI (:,:), IBGKPH (:,:)

      INTEGER, PUBLIC, SAVE ::
     I NREACI


      CONTAINS


      SUBROUTINE ALLOC_COMXS (ICAL)

      INTEGER, INTENT(IN) :: ICAL

      IF (ICAL == 1) THEN

        IF (ALLOCATED(XSTORV)) RETURN

        NSTORV = 8
C
        NAMF=9*11*11+11+
     P       NREAC*(9*11+18+ 6*NPHOT+ 6*NATM+ 6*NMOL+ 6*NION+ 6*NPLS)
        MAMF=NREAC*(     14+ 8*NPHOT+ 8*NATM+ 8*NMOL+ 8*NION+ 6*NPLS)+
     P               1*NATM+ 1*NMOL+ 1*NION+ 1*NPLS+1

        ALLOCATE (XSTORV(NSTORV))
  
        SIGCXT  => XSTORV(1)
        SIGPIT  => XSTORV(2)
        SIGEIT  => XSTORV(3)
        SIGELT  => XSTORV(4)
        SIGOTT  => XSTORV(5)
        SIGTOT  => XSTORV(6)
        SIGBGK  => XSTORV(7)
        ZMFPI   => XSTORV(8)

        ALLOCATE (NAEII(NATM))
        ALLOCATE (NMDSI(NMOL))
        ALLOCATE (NIDSI(NION))
        ALLOCATE (NACXI(NATM))
        ALLOCATE (NMCXI(NMOL))
        ALLOCATE (NICXI(NION))
        ALLOCATE (NAELI(NATM))
        ALLOCATE (NMELI(NMOL))
        ALLOCATE (NIELI(NION))
        ALLOCATE (NAPII(NATM))
        ALLOCATE (NMPII(NMOL))
        ALLOCATE (NIPII(NION))
        ALLOCATE (NPRCI(NPLS))
        ALLOCATE (NAEIIM(NATM)) 
        ALLOCATE (NMDSIM(NMOL))
        ALLOCATE (NIDSIM(NION))
        ALLOCATE (NACXIM(NATM))
        ALLOCATE (NMCXIM(NMOL))
        ALLOCATE (NICXIM(NION))
        ALLOCATE (NAELIM(NATM))
        ALLOCATE (NMELIM(NMOL))
        ALLOCATE (NIELIM(NION))
        ALLOCATE (NAPIIM(NATM))
        ALLOCATE (NMPIIM(NMOL))
        ALLOCATE (NIPIIM(NION))
        ALLOCATE (NPRCIM(NPLS))
        ALLOCATE (NPBGKA(NATM))
        ALLOCATE (NPBGKM(NMOL))
        ALLOCATE (NPBGKI(NION))
        ALLOCATE (NPBGKP(NPLS,2))

        ALLOCATE (NSEACX(NATM,NPLS,5))
        ALLOCATE (NSEMCX(NMOL,NPLS,5))
        ALLOCATE (NSEICX(NION,NPLS,5))
        ALLOCATE (NSEAEL(NATM,NPLS,5))
        ALLOCATE (NSEMEL(NMOL,NPLS,5))
        ALLOCATE (NSEIEL(NION,NPLS,5))

        ALLOCATE (CREAC(9,-1:9,-10:NREAC))
        ALLOCATE (DELPOT(NREAC))
        ALLOCATE (FACREA(-10:NREAC))
        ALLOCATE (RCMN(NREAC,2))
        ALLOCATE (RCMX(NREAC,2))
        ALLOCATE (FPARM(NREAC,6,2))
        ALLOCATE (FREACA(NATM,NREAC))
        ALLOCATE (FREACM(NMOL,NREAC))
        ALLOCATE (FREACI(NION,NREAC))
        ALLOCATE (FREACP(NPLS,NREAC))
        ALLOCATE (FREACPH(NPHOT,NREAC))
        ALLOCATE (FLDLMA(NATM,NREAC))
        ALLOCATE (FLDLMM(NMOL,NREAC))
        ALLOCATE (FLDLMI(NION,NREAC))
        ALLOCATE (FLDLMP(NPLS,NREAC))
        ALLOCATE (FLDLMPH(NPHOT,NREAC))
        ALLOCATE (EELECA(NATM,NREAC))
        ALLOCATE (EELECM(NMOL,NREAC))
        ALLOCATE (EELECI(NION,NREAC))
        ALLOCATE (EELECP(NPLS,NREAC))
        ALLOCATE (EELECPH(NPHOT,NREAC))
        ALLOCATE (EBULKA(NATM,NREAC))
        ALLOCATE (EBULKM(NMOL,NREAC))
        ALLOCATE (EBULKI(NION,NREAC))
        ALLOCATE (EBULKP(NPLS,NREAC))
        ALLOCATE (EBULKPH(NPHOT,NREAC))
        ALLOCATE (ESCD1A(NATM,NREAC))
        ALLOCATE (ESCD1M(NMOL,NREAC))
        ALLOCATE (ESCD1I(NION,NREAC))
        ALLOCATE (ESCD1P(NPLS,NREAC))
        ALLOCATE (ESCD1PH(NPHOT,NREAC))
        ALLOCATE (ESCD2A(NATM,NREAC))
        ALLOCATE (ESCD2M(NMOL,NREAC))
        ALLOCATE (ESCD2I(NION,NREAC))
        ALLOCATE (ESCD2P(NPLS,NREAC))
        ALLOCATE (ESCD2PH(NPHOT,NREAC))
  
        ALLOCATE (ISWR(NREAC))
        ALLOCATE (MODCLF(NREAC))
        ALLOCATE (MASSP(NREAC))
        ALLOCATE (MASST(NREAC))
        ALLOCATE (IFEXMN(NREAC,2))
        ALLOCATE (IFEXMX(NREAC,2))
        ALLOCATE (IFTFLG(NREAC,0:5))
        ALLOCATE (NRCP(NPLS))
        ALLOCATE (NRCA(NATM))
        ALLOCATE (NRCM(NMOL))
        ALLOCATE (NRCI(NION))
        ALLOCATE (NRCPH(NPHOT))
        ALLOCATE (IREACA(NATM,NREAC))
        ALLOCATE (IREACM(NMOL,NREAC))
        ALLOCATE (IREACI(NION,NREAC))
        ALLOCATE (IREACP(NPLS,NREAC))
        ALLOCATE (IREACPH(NPHOT,NREAC))
        ALLOCATE (IBULKA(NATM,NREAC))
        ALLOCATE (IBULKM(NMOL,NREAC))
        ALLOCATE (IBULKI(NION,NREAC))
        ALLOCATE (IBULKP(NPLS,NREAC))
        ALLOCATE (IBULKPH(NPHOT,NREAC))
        ALLOCATE (ISCD1A(NATM,NREAC))
        ALLOCATE (ISCD1M(NMOL,NREAC))
        ALLOCATE (ISCD1I(NION,NREAC))
        ALLOCATE (ISCD1P(NPLS,NREAC))
        ALLOCATE (ISCD1PH(NPHOT,NREAC))
        ALLOCATE (ISCD2A(NATM,NREAC))
        ALLOCATE (ISCD2M(NMOL,NREAC))
        ALLOCATE (ISCD2I(NION,NREAC))
        ALLOCATE (ISCD2P(NPLS,NREAC))
        ALLOCATE (ISCD2PH(NPHOT,NREAC))
        ALLOCATE (ISCD3A(NATM,NREAC))
        ALLOCATE (ISCD3M(NMOL,NREAC))
        ALLOCATE (ISCD3I(NION,NREAC))
        ALLOCATE (ISCD3P(NPLS,NREAC))
        ALLOCATE (ISCD3PH(NPHOT,NREAC))
        ALLOCATE (ISCDEA(NATM,NREAC))
        ALLOCATE (ISCDEM(NMOL,NREAC))
        ALLOCATE (ISCDEI(NION,NREAC))
        ALLOCATE (ISCDEP(NPLS,NREAC))
        ALLOCATE (ISCDEPH(NPHOT,NREAC))
        ALLOCATE (IESTMA(NATM,NREAC))
        ALLOCATE (IESTMM(NMOL,NREAC))
        ALLOCATE (IESTMI(NION,NREAC))
        ALLOCATE (IESTMPH(NPHOT,NREAC))
        ALLOCATE (IBGKA (NATM,NREAC))
        ALLOCATE (IBGKM (NMOL,NREAC))
        ALLOCATE (IBGKI (NION,NREAC))
        ALLOCATE (IBGKPH(NPHOT,NREAC))

        WRITE (55,'(A,T25,I15)')
     .        ' COMXS(1) ',(NSTORV+NAMF)*8 + (MAMF+
     .                      9*(NATM+NMOL+NION)+4*NPLS+
     .                      10*NPLS*(NATM+NMOL+NION))*4


      ELSE IF (ICAL == 2) THEN

        IF (ALLOCATED(XSTOR)) RETURN

        NSTOR1 = NREL+NRCX+NRPI+NRDS
        NSTOR  = NSTOR1+
     .           2*(NREL+NRCX+NRPI)+5*NRDS+
     .           NREL+NRCX+NRPI
C
        NTAB=NSTORDR*(NRDS+NREC)+
     P       NSTORDR*NSTORDT*(NRCX+NREL+NRPI)+
     P       (NPLS+1)*(NRPI+NRCX+NREL)
C
        NDAT=NSTORDR*(2*NRDS+NREC+
     P       NSTORDT*(NRCX+NREL+NRPI+NROT))+
     P      (NRDS+NRPI)*
     P      (NATMP+NMOLP+NIONP+NPLSP+1)+
     P      (NRPI+NRDS)*(NSPZP+1)+
     P       NRPI*  (NATMP+NMOLP+NIONP+NPLSP)+
     P       NRDS*2*(NATMP+NMOLP+NIONP+1)
C
        NMDTA=NTAB+NDAT
C
        MMDTA=7*4*NSPZ*(1+NCOLMC)+3*(NRCX+NREL+NRPI+NRDS)+6+
     P        9*(NATM+NMOL+NION)+4*NPLS+
     P        5*NREC+
     P        6*NRCX+
     P        10*NPLS*(NATM+NMOL+NION)+
     P        10*NREC+
     P        2*NRCX+2*NRPI+2*NREL+5*NRDS+4*NREC+
     P        (NRDS+NRPI)*
     P        (NATMP+NMOLP+NIONP+NPLSP)+
C  LG... ARRAYS
     P        (NATMP+NMOLP+NIONP      )*(NRDS+1)+
     P        2*(NATMP+NMOLP+NIONP      )*(NRCX+1)+
     P        2*(NATMP+NMOLP+NIONP      )*(NREL+1)+
     P          (                  NPLSP)*(NREC+1)+
     P        2*(NATMP+NMOLP+NIONP      )*(NRPI+1)


csw added NROT (photon.f)
        MSTOR1 = MAX(NRCX, NRPI, NRDS, NREL, NROT)
csw 18-->21
        MSTOR2 = 21
  
        ALLOCATE (XSTOR(MSTOR1,MSTOR2))
  
        SIGVCX => XSTOR(:,1)    
        SIGVPI => XSTOR(:,2)
        SIGVEI => XSTOR(:,3)
        SIGVEL => XSTOR(:,4)
        ESIGCX => XSTOR(:,5:6)
        ESIGPI => XSTOR(:,7:8)
        ESIGEI => XSTOR(:,9:13)
        ESIGEL => XSTOR(:,14:15)
        VSIGCX => XSTOR(:,16)
        VSIGPI => XSTOR(:,17)
        VSIGEL => XSTOR(:,18)
csw added n2lines
        SIGVOT => XSTOR(:,19)
        ESIGOT => XSTOR(:,20:21)


        ALLOCATE (TABDS1(NRDS,NSTORDR)) 
        ALLOCATE (TABRC1(NREC,NSTORDR)) 
        ALLOCATE (TABPI3(NRPI,NSTORDR,NSTORDT)) 
        ALLOCATE (TABCX3(NRCX,NSTORDR,NSTORDT)) 
        ALLOCATE (TABEL3(NREL,NSTORDR,NSTORDT)) 
        ALLOCATE (FDLMPI(NRPI)) 
        ALLOCATE (FDLMCX(NRCX)) 
        ALLOCATE (FDLMEL(NREL)) 
        ALLOCATE (ADDPI(NRPI,NPLS)) 
        ALLOCATE (ADDCX(NRCX,NPLS)) 
        ALLOCATE (ADDEL(NREL,NPLS)) 

        ALLOCATE (PELDS(NRDS)) 
        ALLOCATE (PATDS(NRDS,0:NATM)) 
        ALLOCATE (PMLDS(NRDS,0:NMOL)) 
        ALLOCATE (PIODS(NRDS,0:NION)) 
        ALLOCATE (PPLDS(NRDS,0:NPLS)) 
        ALLOCATE (PELPI(NRPI)) 
        ALLOCATE (PATPI(NRPI,0:NATM)) 
        ALLOCATE (PMLPI(NRPI,0:NMOL)) 
        ALLOCATE (PIOPI(NRPI,0:NION)) 
        ALLOCATE (PPLPI(NRPI,0:NPLS)) 
        ALLOCATE (P2ND(NRDS,0:NSPZ)) 
        ALLOCATE (P2NP(NRPI,0:NSPZ)) 
        ALLOCATE (P2NDS(NRDS)) 
        ALLOCATE (P2NPI(NRPI)) 

        ALLOCATE (EELDS1(NRDS,NSTORDR)) 
        ALLOCATE (EHVDS1(NRDS,NSTORDR)) 
        ALLOCATE (EELRC1(NREC,NSTORDR)) 
        ALLOCATE (EPLPI3(NRPI,NSTORDR,NSTORDT)) 
        ALLOCATE (EPLCX3(NRCX,NSTORDR,NSTORDT)) 
        ALLOCATE (EPLEL3(NREL,NSTORDR,NSTORDT)) 
        ALLOCATE (EPLOT3(NROT,NSTORDR,NSTORDT)) 
  
        ALLOCATE (EATPI(NRPI,0:NATM)) 
        ALLOCATE (EMLPI(NRPI,0:NMOL)) 
        ALLOCATE (EIOPI(NRPI,0:NION)) 
        ALLOCATE (EPLPI(NRPI,0:NPLS)) 
        ALLOCATE (EATDS(NRDS,0:NATM,2)) 
        ALLOCATE (EMLDS(NRDS,0:NMOL,2)) 
        ALLOCATE (EIODS(NRDS,0:NION,2)) 
        ALLOCATE (EPLDS(NRDS,2)) 

        ALLOCATE (MODCOL(7,0:4,NSPZ,0:NCOLMC))
        ALLOCATE (IESTCX(NRCX,3))
        ALLOCATE (IESTEL(NREL,3))
        ALLOCATE (IESTPI(NRPI,3))
        ALLOCATE (IESTEI(NRDS,3))

        ALLOCATE (NATPRC(NREC))
        ALLOCATE (NMLPRC(NREC))
        ALLOCATE (NIOPRC(NREC))
        ALLOCATE (NPLPRC(NREC))
        ALLOCATE (NPHPRC(NREC))
        ALLOCATE (NATPRC_2(NREC))
        ALLOCATE (NMLPRC_2(NREC))
        ALLOCATE (NIOPRC_2(NREC))
        ALLOCATE (NPLPRC_2(NREC))
        ALLOCATE (NPHPRC_2(NREC))
        ALLOCATE (N1STX(NRCX,3))
        ALLOCATE (N2NDX(NRCX,3))

        ALLOCATE (NSEPRC(NREC,5))

        ALLOCATE (NREACX(NRCX))
        ALLOCATE (NREAPI(NRPI))
        ALLOCATE (NREAEL(NREL))
        ALLOCATE (NREAEI(NRDS))
        ALLOCATE (JEREAEI(NRDS))
        ALLOCATE (NREARC(NREC))
        ALLOCATE (JEREARC(NREC))
        ALLOCATE (NELREI(NRDS))
        ALLOCATE (JELREI(NRDS))
        ALLOCATE (NREAHV(NRDS))
        ALLOCATE (NELREL(NREL))
        ALLOCATE (NELRRC(NREC))
        ALLOCATE (JELRRC(NREC))
        ALLOCATE (NELRPI(NRPI))
        ALLOCATE (NELRCX(NRCX))
        ALLOCATE (NELROT(NROT))
        ALLOCATE (NREAOT(NROT))
        ALLOCATE (IPATDS(NRDS,0:NATM))
        ALLOCATE (IPMLDS(NRDS,0:NMOL))
        ALLOCATE (IPIODS(NRDS,0:NION))
        ALLOCATE (IPPLDS(NRDS,0:NPLS))
        ALLOCATE (IPATPI(NRPI,0:NATM))
        ALLOCATE (IPMLPI(NRPI,0:NMOL))
        ALLOCATE (IPIOPI(NRPI,0:NION))
        ALLOCATE (IPPLPI(NRPI,0:NPLS))
        ALLOCATE (LGACX(0:NATM,0:NRCX,0:1))
        ALLOCATE (LGMCX(0:NMOL,0:NRCX,0:1))
        ALLOCATE (LGICX(0:NION,0:NRCX,0:1))
        ALLOCATE (LGAEI(0:NATM,0:NRDS))    
        ALLOCATE (LGMEI(0:NMOL,0:NRDS))
        ALLOCATE (LGIEI(0:NION,0:NRDS))
        ALLOCATE (LGAEL(0:NATM,0:NREL,0:1))
        ALLOCATE (LGMEL(0:NMOL,0:NREL,0:1))
        ALLOCATE (LGIEL(0:NION,0:NREL,0:1))
        ALLOCATE (LGPRC(0:NPLS,0:NREC))
        ALLOCATE (LGAPI(0:NATM,0:NRPI,0:1))
        ALLOCATE (LGMPI(0:NMOL,0:NRPI,0:1))
        ALLOCATE (LGIPI(0:NION,0:NRPI,0:1))

        WRITE (55,'(A,T25,I15)')
     .        ' COMXS(2) ',(MSTOR1*MSTOR2+NMDTA)*8 +
     .                     (MMDTA -
     .                      9*(NATM+NMOL+NION)-4*NPLS-
     .                      10*NPLS*(NATM+NMOL+NION))*4

      END IF

      CALL INIT_CMDTA (ICAL)

      RETURN
      END SUBROUTINE ALLOC_COMXS


      SUBROUTINE DEALLOC_COMXS

      IF (.NOT.ALLOCATED(XSTOR)) RETURN

      DEALLOCATE (XSTOR)  
      DEALLOCATE (XSTORV) 


      DEALLOCATE (TABDS1) 
      DEALLOCATE (TABRC1) 
      DEALLOCATE (TABPI3) 
      DEALLOCATE (TABCX3) 
      DEALLOCATE (TABEL3) 
      DEALLOCATE (FDLMPI) 
      DEALLOCATE (FDLMCX) 
      DEALLOCATE (FDLMEL) 
      DEALLOCATE (ADDPI)  
      DEALLOCATE (ADDCX)  
      DEALLOCATE (ADDEL)  

      DEALLOCATE (PELDS)  
      DEALLOCATE (PATDS)  
      DEALLOCATE (PMLDS)  
      DEALLOCATE (PIODS)  
      DEALLOCATE (PPLDS)  
      DEALLOCATE (PELPI)  
      DEALLOCATE (PATPI)  
      DEALLOCATE (PMLPI)  
      DEALLOCATE (PIOPI)  
      DEALLOCATE (PPLPI)  
      DEALLOCATE (P2ND)   
      DEALLOCATE (P2NP)   
      DEALLOCATE (P2NDS)  
      DEALLOCATE (P2NPI)  

      DEALLOCATE (EELDS1) 
      DEALLOCATE (EHVDS1) 
      DEALLOCATE (EELRC1) 
      DEALLOCATE (EPLPI3) 
      DEALLOCATE (EPLCX3) 
      DEALLOCATE (EPLEL3) 
      DEALLOCATE (EPLOT3) 

      DEALLOCATE (EATPI)  
      DEALLOCATE (EMLPI)  
      DEALLOCATE (EIOPI)  
      DEALLOCATE (EPLPI)  
      DEALLOCATE (EATDS)  
      DEALLOCATE (EMLDS)  
      DEALLOCATE (EIODS)  
      DEALLOCATE (EPLDS)  

      DEALLOCATE (MODCOL) 
      DEALLOCATE (IESTCX) 
      DEALLOCATE (IESTEL) 
      DEALLOCATE (IESTPI) 
      DEALLOCATE (IESTEI) 
      DEALLOCATE (NAEII)  
      DEALLOCATE (NMDSI)  
      DEALLOCATE (NIDSI)  
      DEALLOCATE (NACXI)  
      DEALLOCATE (NMCXI)  
      DEALLOCATE (NICXI)  
      DEALLOCATE (NAELI)  
      DEALLOCATE (NMELI)  
      DEALLOCATE (NIELI)  
      DEALLOCATE (NAPII)  
      DEALLOCATE (NMPII)  
      DEALLOCATE (NIPII)  
      DEALLOCATE (NPRCI)  
      DEALLOCATE (NAEIIM) 
      DEALLOCATE (NMDSIM) 
      DEALLOCATE (NIDSIM) 
      DEALLOCATE (NACXIM) 
      DEALLOCATE (NMCXIM) 
      DEALLOCATE (NICXIM) 
      DEALLOCATE (NAELIM) 
      DEALLOCATE (NMELIM) 
      DEALLOCATE (NIELIM) 
      DEALLOCATE (NAPIIM) 
      DEALLOCATE (NMPIIM) 
      DEALLOCATE (NIPIIM) 
      DEALLOCATE (NPRCIM) 
      DEALLOCATE (NPBGKA) 
      DEALLOCATE (NPBGKM) 
      DEALLOCATE (NPBGKI) 
      DEALLOCATE (NPBGKP) 

      DEALLOCATE (NATPRC_2)
      DEALLOCATE (NMLPRC_2)
      DEALLOCATE (NIOPRC_2)
      DEALLOCATE (NPLPRC_2)
      DEALLOCATE (NPHPRC_2)
      DEALLOCATE (NATPRC)
      DEALLOCATE (NMLPRC) 
      DEALLOCATE (NIOPRC) 
      DEALLOCATE (NPLPRC) 
      DEALLOCATE (NPHPRC) 
      DEALLOCATE (N1STX)  
      DEALLOCATE (N2NDX)  

      DEALLOCATE (NSEACX) 
      DEALLOCATE (NSEMCX) 
      DEALLOCATE (NSEICX) 
      DEALLOCATE (NSEAEL) 
      DEALLOCATE (NSEMEL) 
      DEALLOCATE (NSEIEL) 
      DEALLOCATE (NSEPRC) 

      DEALLOCATE (NREACX) 
      DEALLOCATE (NREAPI) 
      DEALLOCATE (NREAEL) 
      DEALLOCATE (NREAEI) 
      DEALLOCATE (JEREAEI)
      DEALLOCATE (NREARC) 
      DEALLOCATE (JEREARC)
      DEALLOCATE (NELREI) 
      DEALLOCATE (JELREI) 
      DEALLOCATE (NREAHV) 
      DEALLOCATE (NELREL) 
      DEALLOCATE (NELRRC) 
      DEALLOCATE (JELRRC) 
      DEALLOCATE (NELRPI) 
      DEALLOCATE (NELRCX) 
      DEALLOCATE (NELROT) 
      DEALLOCATE (NREAOT) 
      DEALLOCATE (IPATDS) 
      DEALLOCATE (IPMLDS) 
      DEALLOCATE (IPIODS) 
      DEALLOCATE (IPPLDS) 
      DEALLOCATE (IPATPI) 
      DEALLOCATE (IPMLPI) 
      DEALLOCATE (IPIOPI) 
      DEALLOCATE (IPPLPI) 
      DEALLOCATE (LGACX)  
      DEALLOCATE (LGMCX)  
      DEALLOCATE (LGICX)  
      DEALLOCATE (LGAEI)  
      DEALLOCATE (LGMEI)  
      DEALLOCATE (LGIEI)  
      DEALLOCATE (LGAEL)  
      DEALLOCATE (LGMEL)  
      DEALLOCATE (LGIEL)  
      DEALLOCATE (LGPRC)  
      DEALLOCATE (LGAPI)  
      DEALLOCATE (LGMPI)  
      DEALLOCATE (LGIPI)  

      DEALLOCATE (CREAC)  
      DEALLOCATE (DELPOT) 
      DEALLOCATE (FACREA) 
      DEALLOCATE (RCMN)   
      DEALLOCATE (RCMX)   
      DEALLOCATE (FPARM)  
      DEALLOCATE (FREACA) 
      DEALLOCATE (FREACM) 
      DEALLOCATE (FREACI) 
      DEALLOCATE (FREACP) 
      DEALLOCATE (FREACPH) 
      DEALLOCATE (FLDLMA) 
      DEALLOCATE (FLDLMM) 
      DEALLOCATE (FLDLMI) 
      DEALLOCATE (FLDLMP) 
      DEALLOCATE (FLDLMPH) 
      DEALLOCATE (EELECA) 
      DEALLOCATE (EELECM) 
      DEALLOCATE (EELECI) 
      DEALLOCATE (EELECP) 
      DEALLOCATE (EELECPH) 
      DEALLOCATE (EBULKA) 
      DEALLOCATE (EBULKM) 
      DEALLOCATE (EBULKI) 
      DEALLOCATE (EBULKP) 
      DEALLOCATE (EBULKPH) 
      DEALLOCATE (ESCD1A) 
      DEALLOCATE (ESCD1M) 
      DEALLOCATE (ESCD1I) 
      DEALLOCATE (ESCD1P) 
      DEALLOCATE (ESCD1PH) 
      DEALLOCATE (ESCD2A) 
      DEALLOCATE (ESCD2M) 
      DEALLOCATE (ESCD2I) 
      DEALLOCATE (ESCD2P) 
      DEALLOCATE (ESCD2PH) 

      DEALLOCATE (ISWR)   
      DEALLOCATE (MODCLF) 
      DEALLOCATE (MASSP)  
      DEALLOCATE (MASST)  
      DEALLOCATE (IFEXMN) 
      DEALLOCATE (IFEXMX) 
      DEALLOCATE (IFTFLG) 
      DEALLOCATE (NRCP)   
      DEALLOCATE (NRCA)   
      DEALLOCATE (NRCM)   
      DEALLOCATE (NRCI)   
      DEALLOCATE (NRCPH)   
      DEALLOCATE (IREACA) 
      DEALLOCATE (IREACM) 
      DEALLOCATE (IREACI) 
      DEALLOCATE (IREACP) 
      DEALLOCATE (IREACPH) 
      DEALLOCATE (IBULKA) 
      DEALLOCATE (IBULKM) 
      DEALLOCATE (IBULKI) 
      DEALLOCATE (IBULKP) 
      DEALLOCATE (IBULKPH) 
      DEALLOCATE (ISCD1A) 
      DEALLOCATE (ISCD1M) 
      DEALLOCATE (ISCD1I) 
      DEALLOCATE (ISCD1P) 
      DEALLOCATE (ISCD1PH) 
      DEALLOCATE (ISCD2A) 
      DEALLOCATE (ISCD2M) 
      DEALLOCATE (ISCD2I) 
      DEALLOCATE (ISCD2P) 
      DEALLOCATE (ISCD2PH) 
      DEALLOCATE (ISCD3A) 
      DEALLOCATE (ISCD3M) 
      DEALLOCATE (ISCD3I) 
      DEALLOCATE (ISCD3P) 
      DEALLOCATE (ISCD3PH) 
      DEALLOCATE (ISCDEA) 
      DEALLOCATE (ISCDEM) 
      DEALLOCATE (ISCDEI) 
      DEALLOCATE (ISCDEP) 
      DEALLOCATE (ISCDEPH) 
      DEALLOCATE (IESTMA) 
      DEALLOCATE (IESTMM) 
      DEALLOCATE (IESTMI) 
      DEALLOCATE (IESTMPH) 
      DEALLOCATE (IBGKA ) 
      DEALLOCATE (IBGKM ) 
      DEALLOCATE (IBGKI ) 
      DEALLOCATE (IBGKPH) 
      RETURN
      END SUBROUTINE DEALLOC_COMXS


      SUBROUTINE INIT_CMDTA (ICAL)

      INTEGER, INTENT(IN) :: ICAL

      IF (ICAL == 1) THEN
        NAEII   = 0
        NMDSI   = 0
        NIDSI   = 0
        NACXI   = 0
        NMCXI   = 0
        NICXI   = 0
        NAELI   = 0
        NMELI   = 0
        NIELI   = 0
        NAPII   = 0
        NMPII   = 0
        NIPII   = 0
        NPRCI   = 0
        NAEIIM  = 0
        NMDSIM  = 0
        NIDSIM  = 0
        NACXIM  = 0
        NMCXIM  = 0
        NICXIM  = 0
        NAELIM  = 0
        NMELIM  = 0
        NIELIM  = 0
        NAPIIM  = 0
        NMPIIM  = 0
        NIPIIM  = 0
        NPRCIM  = 0
        NPBGKA  = 0
        NPBGKM  = 0
        NPBGKI  = 0
        NPBGKP  = 0
  
        NSEACX  = 0
        NSEMCX  = 0
        NSEICX  = 0
        NSEAEL  = 0
        NSEMEL  = 0
        NSEIEL  = 0

        CREAC   = 0._DP
        DELPOT  = 0._DP
        FACREA  = 0._DP
        RCMN    = 0._DP
        RCMX    = 0._DP
        FPARM   = 0._DP
        FREACA  = 0._DP
        FREACM  = 0._DP
        FREACI  = 0._DP
        FREACP  = 0._DP
        FREACPH = 0._DP
        FLDLMA  = 0._DP
        FLDLMM  = 0._DP
        FLDLMI  = 0._DP
        FLDLMP  = 0._DP
        FLDLMPH = 0._DP
        EELECA  = 0._DP
        EELECM  = 0._DP
        EELECI  = 0._DP
        EELECP  = 0._DP
        EELECPH = 0._DP
        EBULKA  = 0._DP
        EBULKM  = 0._DP
        EBULKI  = 0._DP
        EBULKP  = 0._DP
        EBULKPH = 0._DP
        ESCD1A  = 0._DP
        ESCD1M  = 0._DP
        ESCD1I  = 0._DP
        ESCD1P  = 0._DP
        ESCD1PH = 0._DP
        ESCD2A  = 0._DP
        ESCD2M  = 0._DP
        ESCD2I  = 0._DP
        ESCD2P  = 0._DP
        ESCD2PH = 0._DP

        ZMFPTHI = 0._DP
        TDGTEMX = 1.E-30_DP
  
        ISWR    = 0
        MODCLF  = 0
        MASSP   = 0
        MASST   = 0
        IFEXMN  = 0
        IFEXMX  = 0
        IFTFLG  = 0
        NRCP    = 0
        NRCA    = 0
        NRCM    = 0
        NRCI    = 0
        NRCPH   = 0
        IREACA  = 0
        IREACM  = 0
        IREACI  = 0
        IREACP  = 0
        IREACPH = 0
        IBULKA  = 0
        IBULKM  = 0
        IBULKI  = 0
        IBULKP  = 0
        IBULKPH = 0
        ISCD1A  = 0
        ISCD1M  = 0
        ISCD1I  = 0
        ISCD1P  = 0
        ISCD1PH = 0
        ISCD2A  = 0
        ISCD2M  = 0
        ISCD2I  = 0
        ISCD2P  = 0
        ISCD2PH = 0
        ISCD3A  = 0
        ISCD3M  = 0
        ISCD3I  = 0
        ISCD3P  = 0
        ISCD3PH = 0
        ISCDEA  = 0
        ISCDEM  = 0
        ISCDEI  = 0
        ISCDEP  = 0
        ISCDEPH = 0
        IESTMA  = 0
        IESTMM  = 0
        IESTMI  = 0
        IESTMPH = 0
        IBGKA   = 0
        IBGKM   = 0
        IBGKI   = 0
        IBGKPH  = 0

        idreac  = 0

      ELSE IF (ICAL == 2) THEN

        XSTORV  = 0._DP 

        TABDS1  = 0._DP
        TABRC1  = 0._DP
        TABPI3  = 0._DP
        TABCX3  = 0._DP
        TABEL3  = 0._DP
        FDLMPI  = 0._DP
        FDLMCX  = 0._DP
        FDLMEL  = 0._DP
        ADDPI   = 0._DP
        ADDCX   = 0._DP
        ADDEL   = 0._DP
  
        PELDS   = 0._DP
        PATDS   = 0._DP
        PMLDS   = 0._DP
        PIODS   = 0._DP
        PPLDS   = 0._DP
        PELPI   = 0._DP
        PATPI   = 0._DP
        PMLPI   = 0._DP
        PIOPI   = 0._DP
        PPLPI   = 0._DP
        P2ND    = 0._DP
        P2NP    = 0._DP
        P2NDS   = 0._DP
        P2NPI   = 0._DP
  
        EELDS1  = 0._DP
        EHVDS1  = 0._DP
        EELRC1  = 0._DP
        EPLPI3  = 0._DP
        EPLCX3  = 0._DP
        EPLEL3  = 0._DP
        EPLOT3  = 0._DP
  
        EATPI   = 0._DP
        EMLPI   = 0._DP
        EIOPI   = 0._DP
        EPLPI   = 0._DP
        EATDS   = 0._DP
        EMLDS   = 0._DP
        EIODS   = 0._DP
        EPLDS   = 0._DP
  
        MODCOL  = 0
        IESTCX  = 0
        IESTEL  = 0
        IESTPI  = 0
        IESTEI  = 0
  
        NATPRC  = 0
        NMLPRC  = 0
        NIOPRC  = 0
        NPLPRC  = 0
        NPHPRC  = 0
        NATPRC_2= 0
        NMLPRC_2= 0
        NIOPRC_2= 0
        NPLPRC_2= 0
        NPHPRC_2= 0
        N1STX   = 0
        N2NDX   = 0
  
        NRPII   = 0
        NREII   = 0
        NRCXI   = 0
        NRELI   = 0
        NRRCI   = 0
        NRBGI   = 0
        NSEPRC  = 0
  
        NREACX  = 0
        NREAPI  = 0
        NREAEL  = 0
        NREAEI  = 0
        JEREAEI = 0
        NREARC  = 0
        JEREARC = 0
        NELREI  = 0
        JELREI  = 0
        NREAHV  = 0
        NELREL  = 0
        NELRRC  = 0
        JELRRC  = 0
        NELRPI  = 0
        NELRCX  = 0
        NELROT  = 0
        NREAOT  = 0
        IPATDS  = 0
        IPMLDS  = 0
        IPIODS  = 0
        IPPLDS  = 0
        IPATPI  = 0
        IPMLPI  = 0
        IPIOPI  = 0
        IPPLPI  = 0
        LGACX   = 0
        LGMCX   = 0
        LGICX   = 0
        LGAEI   = 0
        LGMEI   = 0
        LGIEI   = 0
        LGAEL   = 0
        LGMEL   = 0
        LGIEL   = 0
        LGPRC   = 0
        LGAPI   = 0
        LGMPI   = 0
        LGIPI   = 0

      END IF

      RETURN
      END SUBROUTINE INIT_CMDTA


      SUBROUTINE WRITE_CMDTA

      WRITE (13)
     . TABDS1 ,TABRC1 ,TABPI3 ,TABCX3 ,TABEL3 ,
     . FDLMPI ,FDLMCX ,FDLMEL ,
     . ADDPI  ,ADDCX  ,ADDEL  ,

     . PELDS  ,PATDS  ,PMLDS  ,PIODS  ,PPLDS  ,
     . PELPI  ,PATPI  ,PMLPI  ,PIOPI  ,PPLPI  ,
     . P2ND   ,P2NP   ,P2NDS  ,P2NPI  ,

     . EELDS1 ,EHVDS1 ,EELRC1 ,EPLPI3 ,EPLCX3 ,EPLEL3 ,EPLOT3 ,

     . EATPI  ,EMLPI  ,EIOPI  ,EPLPI  ,
     . EATDS  ,EMLDS  ,EIODS  ,EPLDS  

      WRITE (13)
     . MODCOL ,IESTCX ,IESTEL ,IESTPI ,IESTEI ,
     . NAEII  ,NMDSI  ,NIDSI  ,NACXI  ,NMCXI  ,NICXI  ,
     . NAELI  ,NMELI  ,NIELI  ,NAPII  ,NMPII  ,NIPII  ,NPRCI  ,
     . NAEIIM ,NMDSIM ,NIDSIM ,NACXIM ,NMCXIM ,NICXIM ,
     . NAELIM ,NMELIM ,NIELIM ,NAPIIM ,NMPIIM ,NIPIIM ,NPRCIM ,
     . NPBGKA ,NPBGKM ,NPBGKI ,NPBGKP ,
     . NATPRC ,NMLPRC ,NIOPRC ,NPLPRC ,NPHPRC ,
     . NATPRC_2 ,NMLPRC_2 ,NIOPRC_2 ,NPLPRC_2 ,NPHPRC_2 ,
     . N1STX  ,N2NDX  ,

     . NRPII  ,NREII  ,NRCXI  ,NRELI  ,NRRCI  ,NRBGI  ,

     . NSEACX ,NSEMCX ,NSEICX ,NSEAEL ,NSEMEL ,NSEIEL ,NSEPRC ,
     . NREACX ,NREAPI ,NREAEL ,NREAEI ,JEREAEI,NREARC ,JEREARC,
     . NELREI ,JELREI ,NREAHV ,NELREL ,NELRRC ,JELRRC ,NELRPI ,NELRCX ,
     . NELROT ,NREAOT ,
     . IPATDS ,IPMLDS ,IPIODS ,IPPLDS ,IPATPI ,IPMLPI ,IPIOPI ,IPPLPI ,
     . LGACX  ,LGMCX  ,LGICX  ,LGAEI  ,LGMEI  ,LGIEI  ,
     . LGAEL  ,LGMEL  ,LGIEL  ,LGPRC  ,LGAPI  ,LGMPI  ,LGIPI

      RETURN
      END SUBROUTINE WRITE_CMDTA


      SUBROUTINE READ_CMDTA

      READ (13)
     . TABDS1 ,TABRC1 ,TABPI3 ,TABCX3 ,TABEL3 ,
     . FDLMPI ,FDLMCX ,FDLMEL ,
     . ADDPI  ,ADDCX  ,ADDEL  ,

     . PELDS  ,PATDS  ,PMLDS  ,PIODS  ,PPLDS  ,
     . PELPI  ,PATPI  ,PMLPI  ,PIOPI  ,PPLPI  ,
     . P2ND   ,P2NP   ,P2NDS  ,P2NPI  ,

     . EELDS1 ,EHVDS1 ,EELRC1 ,EPLPI3 ,EPLCX3 ,EPLEL3 ,EPLOT3 ,

     . EATPI  ,EMLPI  ,EIOPI  ,EPLPI  ,
     . EATDS  ,EMLDS  ,EIODS  ,EPLDS  

      READ (13)
     . MODCOL ,IESTCX ,IESTEL ,IESTPI ,IESTEI ,
     . NAEII  ,NMDSI  ,NIDSI  ,NACXI  ,NMCXI  ,NICXI  ,
     . NAELI  ,NMELI  ,NIELI  ,NAPII  ,NMPII  ,NIPII  ,NPRCI  ,
     . NAEIIM ,NMDSIM ,NIDSIM ,NACXIM ,NMCXIM ,NICXIM ,
     . NAELIM ,NMELIM ,NIELIM ,NAPIIM ,NMPIIM ,NIPIIM ,NPRCIM ,
     . NPBGKA ,NPBGKM ,NPBGKI ,NPBGKP ,
     . NATPRC ,NMLPRC ,NIOPRC ,NPLPRC ,NPHPRC ,
     . NATPRC_2 ,NMLPRC_2 ,NIOPRC_2 ,NPLPRC_2 ,NPHPRC_2 ,
     . N1STX  ,N2NDX  ,

     . NRPII  ,NREII  ,NRCXI  ,NRELI  ,NRRCI  ,NRBGI  ,

     . NSEACX ,NSEMCX ,NSEICX ,NSEAEL ,NSEMEL ,NSEIEL ,NSEPRC ,
     . NREACX ,NREAPI ,NREAEL ,NREAEI ,JEREAEI,NREARC ,JEREARC,
     . NELREI ,JELREI ,NREAHV ,NELREL ,NELRRC ,JELRRC ,NELRPI ,NELRCX ,
     . NELROT ,NREAOT ,
     . IPATDS ,IPMLDS ,IPIODS ,IPPLDS ,IPATPI ,IPMLPI ,IPIOPI ,IPPLPI ,
     . LGACX  ,LGMCX  ,LGICX  ,LGAEI  ,LGMEI  ,LGIEI  ,
     . LGAEL  ,LGMEL  ,LGIEL  ,LGPRC  ,LGAPI  ,LGMPI  ,LGIPI

      RETURN
      END SUBROUTINE READ_CMDTA


      SUBROUTINE CMDTA_XDR (IUN)
      
      INTEGER, INTENT(IN) :: IUN
c
c      CALL FXDRDBL (IUN,TABDS1,NRDS*NSTORDR)
c      CALL FXDRDBL (IUN,TABRC1,NREC*NSTORDR)
c      CALL FXDRDBL (IUN,TABPI3,NRPI*NSTORDR*NSTORDT)
c      CALL FXDRDBL (IUN,TABCX3,NRCX*NSTORDR*NSTORDT)
c      CALL FXDRDBL (IUN,TABEL3,NREL*NSTORDR*NSTORDT)
c      CALL FXDRDBL (IUN,FDLMPI,NRPI)
c      CALL FXDRDBL (IUN,FDLMCX,NRCX)
c      CALL FXDRDBL (IUN,FDLMEL,NREL)
c      CALL FXDRDBL (IUN,ADDPI,NRPI*NPLS)
c      CALL FXDRDBL (IUN,ADDCX,NRCX*NPLS)
c      CALL FXDRDBL (IUN,ADDEL,NREL*NPLS)
c
c      CALL FXDRDBL (IUN,PELDS,NRDS)
c      CALL FXDRDBL (IUN,PATDS,NRDS*(NATM+1))
c      CALL FXDRDBL (IUN,PMLDS,NRDS*(NMOL+1))
c      CALL FXDRDBL (IUN,PIODS,NRDS*(NION+1))
c      CALL FXDRDBL (IUN,PPLDS,NRDS*(NPLS+1))
c      CALL FXDRDBL (IUN,PELPI,NRPI)
c      CALL FXDRDBL (IUN,PATPI,NRPI*(NATM+1))
c      CALL FXDRDBL (IUN,PMLPI,NRPI*(NMOL+1))
c      CALL FXDRDBL (IUN,PIOPI,NRPI*(NION+1))
c      CALL FXDRDBL (IUN,PPLPI,NRPI*(NPLS+1))
c      CALL FXDRDBL (IUN,P2ND,NRDS*(NSPZ+1))
c      CALL FXDRDBL (IUN,P2NP,NRPI*(NSPZ+1))
c      CALL FXDRDBL (IUN,P2NDS,NRDS)
c      CALL FXDRDBL (IUN,P2NPI,NRPI)
c
c      CALL FXDRDBL (IUN,EELDS1,NRDS*NSTORDR)
c      CALL FXDRDBL (IUN,EHVDS1,NRDS*NSTORDR)
c      CALL FXDRDBL (IUN,EELRC1,NREC*NSTORDR)
c      CALL FXDRDBL (IUN,EPLPI3,NRPI*NSTORDR*NSTORDT)
c      CALL FXDRDBL (IUN,EPLCX3,NRCX*NSTORDR*NSTORDT)
c      CALL FXDRDBL (IUN,EPLEL3,NREL*NSTORDR*NSTORDT)
c      CALL FXDRDBL (IUN,EPLOT3,NROT*NSTORDR*NSTORDT)
c      CALL FXDRDBL (IUN,EATPI,NRPI*(NATM+1))
c      CALL FXDRDBL (IUN,EMLPI,NRPI*(NMOL+1))
c      CALL FXDRDBL (IUN,EIOPI,NRPI*(NION+1))
c      CALL FXDRDBL (IUN,EPLPI,NRPI*(NPLS+1))
c      CALL FXDRDBL (IUN,EATDS,NRDS*(NATM+1)*2)
c      CALL FXDRDBL (IUN,EMLDS,NRDS*(NMOL+1)*2)
c      CALL FXDRDBL (IUN,EIODS,NRDS*(NION+1)*2)
c      CALL FXDRDBL (IUN,EPLDS,NRDS*2)
c
c
c      CALL FXDRINT (IUN,MODCOL ,7*5*NSPZ*(NCOLMC+1))
c      CALL FXDRINT (IUN,IESTCX ,3*NRCX)
c      CALL FXDRINT (IUN,IESTEL ,3*NREL)
c      CALL FXDRINT (IUN,IESTPI ,3*NRPI)
c      CALL FXDRINT (IUN,IESTEI ,3*NRDS)
c      CALL FXDRINT (IUN,NAEII  ,NATM)
c      CALL FXDRINT (IUN,NMDSI  ,NMOL)
c      CALL FXDRINT (IUN,NIDSI  ,NION)
c      CALL FXDRINT (IUN,NACXI  ,NATM)
c      CALL FXDRINT (IUN,NMCXI  ,NMOL)
c      CALL FXDRINT (IUN,NICXI  ,NION)
c      CALL FXDRINT (IUN,NAELI  ,NATM)
c      CALL FXDRINT (IUN,NMELI  ,NMOL)
c      CALL FXDRINT (IUN,NIELI  ,NION)
c      CALL FXDRINT (IUN,NAPII  ,NATM)
c      CALL FXDRINT (IUN,NMPII  ,NMOL)
c      CALL FXDRINT (IUN,NIPII  ,NION)
c      CALL FXDRINT (IUN,NPRCI  ,NPLS)
c      CALL FXDRINT (IUN,NAEIIM ,NATM)
c      CALL FXDRINT (IUN,NMDSIM ,NMOL)
c      CALL FXDRINT (IUN,NIDSIM ,NION)
c      CALL FXDRINT (IUN,NACXIM ,NATM)
c      CALL FXDRINT (IUN,NMCXIM ,NMOL)
c      CALL FXDRINT (IUN,NICXIM ,NION)
c      CALL FXDRINT (IUN,NAELIM ,NATM)
c      CALL FXDRINT (IUN,NMELIM ,NMOL)
c      CALL FXDRINT (IUN,NIELIM ,NION)
c      CALL FXDRINT (IUN,NAPIIM ,NATM)
c      CALL FXDRINT (IUN,NMPIIM ,NMOL)
c      CALL FXDRINT (IUN,NIPIIM ,NION)
c      CALL FXDRINT (IUN,NPRCIM ,NPLS)
c      CALL FXDRINT (IUN,NPBGKA ,NATM)
c      CALL FXDRINT (IUN,NPBGKM ,NMOL)
c      CALL FXDRINT (IUN,NPBGKI ,NION)
c      CALL FXDRINT (IUN,NPBGKP ,2*NPLS)
c      CALL FXDRINT (IUN,NATPRC ,NREC)
c      CALL FXDRINT (IUN,NMLPRC ,NREC)
c      CALL FXDRINT (IUN,NIOPRC ,NREC)
c      CALL FXDRINT (IUN,NPLPRC ,NREC)
c      CALL FXDRINT (IUN,NPHPRC ,NREC)
c      CALL FXDRINT (IUN,NATPRC_2 ,NREC)
c      CALL FXDRINT (IUN,NMLPRC_2 ,NREC)
c      CALL FXDRINT (IUN,NIOPRC_2 ,NREC)
c      CALL FXDRINT (IUN,NPLPRC_2 ,NREC)
c      CALL FXDRINT (IUN,NPHPRC_2 ,NREC)
c      CALL FXDRINT (IUN,N1STX  ,3*NRCX)
c      CALL FXDRINT (IUN,N2NDX  ,3*NRCX)
c
c      CALL FXDRINT (IUN,NRPII  ,1)
c      CALL FXDRINT (IUN,NREII  ,1)
c      CALL FXDRINT (IUN,NRCXI  ,1)
c      CALL FXDRINT (IUN,NRELI  ,1)
c      CALL FXDRINT (IUN,NRRCI  ,1)
c      CALL FXDRINT (IUN,NRBGI  ,1)
c
c      CALL FXDRINT (IUN,NSEACX ,5*NATM*NPLS)
c      CALL FXDRINT (IUN,NSEMCX ,5*NMOL*NPLS)
c      CALL FXDRINT (IUN,NSEICX ,5*NION*NPLS)
c      CALL FXDRINT (IUN,NSEAEL ,5*NATM*NPLS)
c      CALL FXDRINT (IUN,NSEMEL ,5*NMOL*NPLS)
c      CALL FXDRINT (IUN,NSEIEL ,5*NION*NPLS)
c      CALL FXDRINT (IUN,NSEPRC ,5*NREC)
c      CALL FXDRINT (IUN,NREACX ,NRCX)
c      CALL FXDRINT (IUN,NREAPI ,NRPI)
c      CALL FXDRINT (IUN,NREAEL ,NREL)
c      CALL FXDRINT (IUN,NREAEI ,NRDS)
c      CALL FXDRINT (IUN,JEREAEI,NRDS)
c      CALL FXDRINT (IUN,NREARC ,NREC)
c      CALL FXDRINT (IUN,JEREARC,NREC)
c      CALL FXDRINT (IUN,NELREI ,NRDS)
c      CALL FXDRINT (IUN,JELREI ,NRDS)
c      CALL FXDRINT (IUN,NREAHV ,NRDS)
c      CALL FXDRINT (IUN,NELREL ,NREL)
c      CALL FXDRINT (IUN,NELRRC ,NREC)
c      CALL FXDRINT (IUN,JELRRC ,NREC)
c      CALL FXDRINT (IUN,NELRPI ,NRPI)
c      CALL FXDRINT (IUN,NELRCX ,NRCX)
c      CALL FXDRINT (IUN,NELROT ,NROT)
c      CALL FXDRINT (IUN,NREAOT ,NROT)
c      CALL FXDRINT (IUN,IPATDS ,NRDS*(NATM+1))
c      CALL FXDRINT (IUN,IPMLDS ,NRDS*(NMOL+1))
c      CALL FXDRINT (IUN,IPIODS ,NRDS*(NION+1))
c      CALL FXDRINT (IUN,IPPLDS ,NRDS*(NPLS+1))
c      CALL FXDRINT (IUN,IPATPI ,NRPI*(NATM+1))
c      CALL FXDRINT (IUN,IPMLPI ,NRPI*(NMOL+1))
c      CALL FXDRINT (IUN,IPIOPI ,NRPI*(NION+1))
c      CALL FXDRINT (IUN,IPPLPI ,NRPI*(NPLS+1))
c
c      CALL FXDRINT (IUN,LGACX  ,2*(NATM+1)*(NRCX+1))
c      CALL FXDRINT (IUN,LGMCX  ,2*(NMOL+1)*(NRCX+1))
c      CALL FXDRINT (IUN,LGICX  ,2*(NION+1)*(NRCX+1))
c      CALL FXDRINT (IUN,LGAEI  ,(NATM+1)*(NRDS+1))
c      CALL FXDRINT (IUN,LGMEI  ,(NMOL+1)*(NRDS+1))
c      CALL FXDRINT (IUN,LGIEI  ,(NION+1)*(NRDS+1))
c      CALL FXDRINT (IUN,LGAEL  ,2*(NATM+1)*(NREL+1))
c      CALL FXDRINT (IUN,LGMEL  ,2*(NMOL+1)*(NREL+1))
c      CALL FXDRINT (IUN,LGIEL  ,2*(NION+1)*(NREL+1))
c      CALL FXDRINT (IUN,LGPRC  ,(NPLS+1)*(NREC+1))
c      CALL FXDRINT (IUN,LGAPI  ,2*(NATM+1)*(NRPI+1))
c      CALL FXDRINT (IUN,LGMPI  ,2*(NMOL+1)*(NRPI+1))
c      CALL FXDRINT (IUN,LGIPI  ,2*(NION+1)*(NRPI+1))

      RETURN
      END SUBROUTINE CMDTA_XDR


      SUBROUTINE WRITE_CMAMF

      WRITE (13)
     . CREAC,  DELPOT, FACREA, RCMN,   RCMX,   FPARM,
     . FREACA, FREACM, FREACI, FREACP, FREACPH,
     . FLDLMA, FLDLMM, FLDLMI, FLDLMP, FLDLMPH,
     . EELECA, EELECM, EELECI, EELECP, EELECPH,
     . EBULKA, EBULKM, EBULKI, EBULKP, EBULKPH,
     . ESCD1A, ESCD1M, ESCD1I, ESCD1P, ESCD1PH,
     . ESCD2A, ESCD2M, ESCD2I, ESCD2P, ESCD2PH,

     . NREACI, ISWR,   MODCLF, MASSP,  MASST,  IFTFLG,
     . IFEXMN, IFEXMX, NRCP,   NRCA,   NRCM,   NRCI, NRCPH,
     . IREACA, IREACM, IREACI, IREACP, IREACPH,
     . IBULKA, IBULKM, IBULKI, IBULKP, IBULKPH,
     . ISCD1A, ISCD1M, ISCD1I, ISCD1P, ISCD1PH,
     . ISCD2A, ISCD2M, ISCD2I, ISCD2P, ISCD2PH,
     . ISCD3A, ISCD3M, ISCD3I, ISCD3P, ISCD3PH,
     . ISCDEA, ISCDEM, ISCDEI, ISCDEP, ISCDEPH,
     . IESTMA, IESTMM, IESTMI, IESTMPH, IBGKA , IBGKM , IBGKI, IBGKPH

      RETURN
      END SUBROUTINE WRITE_CMAMF


      SUBROUTINE READ_CMAMF

      READ (13)
     . CREAC,  DELPOT, FACREA, RCMN,   RCMX,   FPARM,
     . FREACA, FREACM, FREACI, FREACP, FREACPH,
     . FLDLMA, FLDLMM, FLDLMI, FLDLMP, FLDLMPH,
     . EELECA, EELECM, EELECI, EELECP, EELECPH,
     . EBULKA, EBULKM, EBULKI, EBULKP, EBULKPH,
     . ESCD1A, ESCD1M, ESCD1I, ESCD1P, ESCD1PH,
     . ESCD2A, ESCD2M, ESCD2I, ESCD2P, ESCD2PH,

     . NREACI, ISWR,   MODCLF, MASSP,  MASST,  IFTFLG,
     . IFEXMN, IFEXMX, NRCP,   NRCA,   NRCM,   NRCI, NRCPH,
     . IREACA, IREACM, IREACI, IREACP, IREACPH,
     . IBULKA, IBULKM, IBULKI, IBULKP, IBULKPH,
     . ISCD1A, ISCD1M, ISCD1I, ISCD1P, ISCD1PH,
     . ISCD2A, ISCD2M, ISCD2I, ISCD2P, ISCD2PH,
     . ISCD3A, ISCD3M, ISCD3I, ISCD3P, ISCD3PH,
     . ISCDEA, ISCDEM, ISCDEI, ISCDEP, ISCDEPH,
     . IESTMA, IESTMM, IESTMI, IESTMPH, IBGKA , IBGKM , IBGKI, IBGKPH

      RETURN
      END SUBROUTINE READ_CMAMF


      SUBROUTINE CMAMF_XDR (IUN)
      
      INTEGER, INTENT(IN) :: IUN

c      CALL FXDRDBL (IUN,CREAC,9*11*(NREAC+11))
c      CALL FXDRDBL (IUN,DELPOT,NREAC) 
c      CALL FXDRDBL (IUN,FACREA,NREAC+11)
c      CALL FXDRDBL (IUN,RCMN,2*NREAC) 
c      CALL FXDRDBL (IUN,RCMX,2*NREAC)   
c      CALL FXDRDBL (IUN,FPARM,12*NREAC)
c      CALL FXDRDBL (IUN,FREACA,NATM*NREAC) 
c      CALL FXDRDBL (IUN,FREACM,NMOL*NREAC) 
c      CALL FXDRDBL (IUN,FREACI,NION*NREAC) 
c      CALL FXDRDBL (IUN,FREACP,NPLS*NREAC) 
c      CALL FXDRDBL (IUN,FREACPH,NPHOT*NREAC)
c      CALL FXDRDBL (IUN,FLDLMA,NATM*NREAC) 
c      CALL FXDRDBL (IUN,FLDLMM,NMOL*NREAC) 
c      CALL FXDRDBL (IUN,FLDLMI,NION*NREAC) 
c      CALL FXDRDBL (IUN,FLDLMP,NPLS*NREAC) 
c      CALL FXDRDBL (IUN,FLDLMPH,NPHOT*NREAC)
c      CALL FXDRDBL (IUN,EELECA,NATM*NREAC) 
c      CALL FXDRDBL (IUN,EELECM,NMOL*NREAC) 
c      CALL FXDRDBL (IUN,EELECI,NION*NREAC) 
c      CALL FXDRDBL (IUN,EELECP,NPLS*NREAC)
c      CALL FXDRDBL (IUN,EELECPH,NPHOT*NREAC)
c      CALL FXDRDBL (IUN,EBULKA,NATM*NREAC) 
c      CALL FXDRDBL (IUN,EBULKM,NMOL*NREAC) 
c      CALL FXDRDBL (IUN,EBULKI,NION*NREAC) 
c      CALL FXDRDBL (IUN,EBULKP,NPLS*NREAC) 
c      CALL FXDRDBL (IUN,EBULKPH,NPHOT*NREAC)
c      CALL FXDRDBL (IUN,ESCD1A,NATM*NREAC) 
c      CALL FXDRDBL (IUN,ESCD1M,NMOL*NREAC) 
c      CALL FXDRDBL (IUN,ESCD1I,NION*NREAC) 
c      CALL FXDRDBL (IUN,ESCD1P,NPLS*NREAC) 
c      CALL FXDRDBL (IUN,ESCD1PH,NPHOT*NREAC)
c      CALL FXDRDBL (IUN,ESCD2A,NATM*NREAC) 
c      CALL FXDRDBL (IUN,ESCD2M,NMOL*NREAC) 
c      CALL FXDRDBL (IUN,ESCD2I,NION*NREAC) 
c      CALL FXDRDBL (IUN,ESCD2P,NPLS*NREAC) 
c      CALL FXDRDBL (IUN,ESCD2PH,NPHOT*NREAC)

c      CALL FXDRINT (IUN,NREACI,1)
c      CALL FXDRINT (IUN,ISWR,NREAC)   
c      CALL FXDRINT (IUN,MODCLF,NREAC) 
c      CALL FXDRINT (IUN,MASSP,NREAC)  
c      CALL FXDRINT (IUN,MASST,NREAC)  
c      CALL FXDRINT (IUN,IFTFLG,6*NREAC)
c      CALL FXDRINT (IUN,IFEXMN,2*NREAC) 
c      CALL FXDRINT (IUN,IFEXMX,2*NREAC) 
c      CALL FXDRINT (IUN,NRCP,NPLS)   
c      CALL FXDRINT (IUN,NRCA,NATM)   
c      CALL FXDRINT (IUN,NRCM,NMOL)   
c      CALL FXDRINT (IUN,NRCI,NION) 
c      CALL FXDRINT (IUN,NRCPH,NPHOT)
c      CALL FXDRINT (IUN,IREACA,NATM*NREAC)
c      CALL FXDRINT (IUN,IREACM,NMOL*NREAC) 
c      CALL FXDRINT (IUN,IREACI,NION*NREAC) 
c      CALL FXDRINT (IUN,IREACP,NPLS*NREAC)  
c      CALL FXDRINT (IUN,IREACPH,NPHOT*NREAC) 
c      CALL FXDRINT (IUN,IBULKA,NATM*NREAC) 
c      CALL FXDRINT (IUN,IBULKM,NMOL*NREAC) 
c      CALL FXDRINT (IUN,IBULKI,NION*NREAC) 
c      CALL FXDRINT (IUN,IBULKP,NPLS*NREAC)  
c      CALL FXDRINT (IUN,IBULKPH,NPHOT*NREAC) 
c      CALL FXDRINT (IUN,ISCD1A,NATM*NREAC) 
c      CALL FXDRINT (IUN,ISCD1M,NMOL*NREAC) 
c      CALL FXDRINT (IUN,ISCD1I,NION*NREAC) 
c      CALL FXDRINT (IUN,ISCD1P,NPLS*NREAC)  
c      CALL FXDRINT (IUN,ISCD1PH,NPHOT*NREAC) 
c      CALL FXDRINT (IUN,ISCD2A,NATM*NREAC) 
c      CALL FXDRINT (IUN,ISCD2M,NMOL*NREAC) 
c      CALL FXDRINT (IUN,ISCD2I,NION*NREAC) 
c      CALL FXDRINT (IUN,ISCD2P,NPLS*NREAC)  
c      CALL FXDRINT (IUN,ISCD2PH,NPHOT*NREAC) 
c      CALL FXDRINT (IUN,ISCD3A,NATM*NREAC) 
c      CALL FXDRINT (IUN,ISCD3M,NMOL*NREAC) 
c      CALL FXDRINT (IUN,ISCD3I,NION*NREAC) 
c      CALL FXDRINT (IUN,ISCD3P,NPLS*NREAC)  
c      CALL FXDRINT (IUN,ISCD3PH,NPHOT*NREAC) 
c      CALL FXDRINT (IUN,ISCDEA,NATM*NREAC) 
c      CALL FXDRINT (IUN,ISCDEM,NMOL*NREAC) 
c      CALL FXDRINT (IUN,ISCDEI,NION*NREAC) 
c      CALL FXDRINT (IUN,ISCDEP,NPLS*NREAC)  
c      CALL FXDRINT (IUN,ISCDEPH,NPHOT*NREAC) 
c      CALL FXDRINT (IUN,IESTMA,NATM*NREAC) 
c      CALL FXDRINT (IUN,IESTMM,NMOL*NREAC) 
c      CALL FXDRINT (IUN,IESTMI,NION*NREAC) 
c      CALL FXDRINT (IUN,IESTMPH,NPHOT*NREAC) 
c      CALL FXDRINT (IUN,IBGKA ,NATM*NREAC) 
c      CALL FXDRINT (IUN,IBGKM ,NMOL*NREAC)  
c      CALL FXDRINT (IUN,IBGKI, NION*NREAC)
c      CALL FXDRINT (IUN,IBGKPH,NPHOT*NREAC) 

      RETURN
      END SUBROUTINE CMAMF_XDR


      SUBROUTINE GET_REACTION (IR)
      
      INTEGER, INTENT(IN) :: IR

      REACTION%AIK = CREAC(1,1,IR)
      REACTION%E0 = CREAC(2,1,IR)
      REACTION%G1 = CREAC(3,1,IR)
      REACTION%G2 = CREAC(4,1,IR)
      REACTION%E1 = CREAC(5,1,IR)
      REACTION%C2 = CREAC(6,1,IR)
      REACTION%C3 = CREAC(7,1,IR)
      REACTION%C4 = CREAC(8,1,IR)
      REACTION%C6 = CREAC(1,2,IR)
      REACTION%IRCART = CREAC(9,1,IR)
      
      REACTION%C6A(1:9)     = CREAC(1:9,2,IR)
      REACTION%C6A(10:12)   = CREAC(1:3,3,IR)
      REACTION%IPLSC6(1:6)  = CREAC(4:9,3,IR)
      REACTION%IPLSC6(7:12) = CREAC(1:6,4,IR)

      REACTION%IGND = CREAC(7,4,IR)
      REACTION%IPROFILETYPE = CREAC(8,4,IR)
      REACTION%B21 = CREAC(9,4,IR)
      REACTION%B12 = CREAC(1,5,IR)

      IDREAC = IR
      
      RETURN
      END SUBROUTINE GET_REACTION

      END MODULE COMXS

